vlib work
vmap work work
project new . simulation work modelsim.ini 0
project open simulation
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_mux_11.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/bisection.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_buffer_4.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_mulf_2.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_mulf_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_subf_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_fork_3.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_constant_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_buffer_15.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_fork_15.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_buffer_9.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_fork_12.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_constant_5.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_passer_9.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_absf_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_extsi_2.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_buffer_6.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_sink_4.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_sink_2.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_mulf_3.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_addf_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_buffer_19.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_passer_2.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/types.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_trunci_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_extsi_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_buffer_11.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_passer_12.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_mux_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_constant_3.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_cmpf_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_fork_13.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_mux_2.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_source_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_buffer_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_passer_8.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_buffer_23.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/single_argument.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_buffer_17.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_mux_7.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_buffer_10.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_addf_2.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_fork_9.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_mux_6.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_mux_5.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_cond_br_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/two_port_RAM.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_passer_14.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_init_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_passer_13.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_cmpf_2.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_buffer_8.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_buffer_21.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_passer_3.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_fork_17.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_fork_2.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_cond_br_2.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_addf_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_constant_2.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_cmpi_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_buffer_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_buffer_3.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_sink_6.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_passer_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_mux_3.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_cond_br_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_passer_10.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_mulf_4.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_andi_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_constant_7.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_mulf_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_fork_11.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_sink_3.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_buffer_2.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/bisection_wrapper.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_addi_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_fork_7.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_buffer_13.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_buffer_24.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_cmpf_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_fork_5.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_buffer_20.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_mux_8.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_fork_8.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_constant_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_passer_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_passer_5.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_sink_5.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_passer_6.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/flopoco_ip_cores.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_buffer_22.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_passer_11.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_mux_10.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_fork_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_mux_9.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_mux_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_buffer_12.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/tb_bisection.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_buffer_7.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/tb_join.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_fork_4.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_fork_6.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_cond_br_6.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_buffer_5.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_buffer_16.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_cond_br_3.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_buffer_14.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_sink_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_fork_14.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_mux_4.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_constant_6.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_constant_4.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_control_merge_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_buffer_18.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_fork_10.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_cond_br_4.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/simpackage.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_cond_br_5.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_fork_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_control_merge_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_extsi_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_passer_4.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_not_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_passer_7.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_sink_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/bisection/out_0/sim/HDL_SRC/handshake_fork_16.vhd
project calculateorder
project compileall
eval vsim tb
log -r *
run 100000ns -all
exit
