module {
  hw.module @iterative_sqrt(in %n : !handshake.channel<i32>, in %start : !handshake.control<>, in %clk : i1, in %rst : i1, out out0 : !handshake.channel<i32>, out end : !handshake.control<>) {
    %fork0.outs_0, %fork0.outs_1 = hw.instance "fork0" @handshake_fork_0(ins: %start: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.control<>, outs_1: !handshake.control<>)
    %fork1.outs_0, %fork1.outs_1 = hw.instance "fork1" @handshake_fork_1(ins: %n: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>)
    %source0.outs = hw.instance "source0" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant2.outs = hw.instance "constant2" @handshake_constant_0(ctrl: %source0.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %extsi0.outs = hw.instance "extsi0" @handshake_extsi_0(ins: %constant2.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %source1.outs = hw.instance "source1" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant3.outs = hw.instance "constant3" @handshake_constant_1(ctrl: %source1.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %fork2.outs_0, %fork2.outs_1 = hw.instance "fork2" @handshake_fork_2(ins: %constant3.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>)
    %buffer8.outs = hw.instance "buffer8" @handshake_buffer_0(ins: %mux5.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer9.outs = hw.instance "buffer9" @handshake_buffer_1(ins: %buffer8.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %cond_br35.trueOut, %cond_br35.falseOut = hw.instance "cond_br35" @handshake_cond_br_0(condition: %fork7.outs_5: !handshake.channel<i1>, data: %buffer9.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    hw.instance "sink0" @handshake_sink_0(ins: %cond_br35.falseOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> ()
    %buffer4.outs = hw.instance "buffer4" @handshake_buffer_0(ins: %mux3.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer5.outs = hw.instance "buffer5" @handshake_buffer_1(ins: %buffer4.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %cond_br36.trueOut, %cond_br36.falseOut = hw.instance "cond_br36" @handshake_cond_br_0(condition: %fork7.outs_6: !handshake.channel<i1>, data: %buffer5.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    hw.instance "sink1" @handshake_sink_0(ins: %cond_br36.falseOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> ()
    %constant1.outs = hw.instance "constant1" @handshake_constant_0(ctrl: %fork0.outs_1: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %fork3.outs_0, %fork3.outs_1 = hw.instance "fork3" @handshake_fork_2(ins: %constant1.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>)
    %extsi1.outs = hw.instance "extsi1" @handshake_extsi_0(ins: %fork3.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %merge0.outs = hw.instance "merge0" @handshake_merge_0(ins_0: %fork3.outs_0: !handshake.channel<i1>, ins_1: %fork7.outs_7: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer0.outs = hw.instance "buffer0" @handshake_buffer_2(ins: %merge0.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer1.outs = hw.instance "buffer1" @handshake_buffer_3(ins: %buffer0.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %fork4.outs_0, %fork4.outs_1, %fork4.outs_2, %fork4.outs_3, %fork4.outs_4, %fork4.outs_5 = hw.instance "fork4" @handshake_fork_3(ins: %buffer1.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>, outs_3: !handshake.channel<i1>, outs_4: !handshake.channel<i1>, outs_5: !handshake.channel<i1>)
    %mux0.outs = hw.instance "mux0" @handshake_mux_0(index: %fork4.outs_5: !handshake.channel<i1>, ins_0: %fork1.outs_1: !handshake.channel<i32>, ins_1: %fork8.outs_3: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer6.outs = hw.instance "buffer6" @handshake_buffer_0(ins: %mux4.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer7.outs = hw.instance "buffer7" @handshake_buffer_1(ins: %buffer6.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %mux3.outs = hw.instance "mux3" @handshake_mux_0(index: %fork11.outs_1: !handshake.channel<i1>, ins_0: %fork5.outs_2: !handshake.channel<i32>, ins_1: %buffer7.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %mux4.outs = hw.instance "mux4" @handshake_mux_0(index: %fork12.outs_1: !handshake.channel<i1>, ins_0: %fork5.outs_3: !handshake.channel<i32>, ins_1: %addi1.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer10.outs = hw.instance "buffer10" @handshake_buffer_0(ins: %mux6.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer11.outs = hw.instance "buffer11" @handshake_buffer_1(ins: %buffer10.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %mux5.outs = hw.instance "mux5" @handshake_mux_0(index: %fork11.outs_2: !handshake.channel<i1>, ins_0: %fork6.outs_2: !handshake.channel<i32>, ins_1: %buffer11.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %mux6.outs = hw.instance "mux6" @handshake_mux_0(index: %fork12.outs_2: !handshake.channel<i1>, ins_0: %addi2.result: !handshake.channel<i32>, ins_1: %fork6.outs_3: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %mux7.outs = hw.instance "mux7" @handshake_mux_1(index: %fork4.outs_4: !handshake.channel<i1>, ins_0: %fork2.outs_1: !handshake.channel<i1>, ins_1: %fork11.outs_3: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %mux8.outs = hw.instance "mux8" @handshake_mux_0(index: %fork4.outs_3: !handshake.channel<i1>, ins_0: %extsi1.outs: !handshake.channel<i32>, ins_1: %select0.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %mux9.outs = hw.instance "mux9" @handshake_mux_1(index: %fork4.outs_2: !handshake.channel<i1>, ins_0: %fork2.outs_0: !handshake.channel<i1>, ins_1: %andi1.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %mux10.outs = hw.instance "mux10" @handshake_mux_0(index: %fork4.outs_1: !handshake.channel<i1>, ins_0: %extsi0.outs: !handshake.channel<i32>, ins_1: %cond_br36.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer18.outs = hw.instance "buffer18" @handshake_buffer_0(ins: %mux10.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer19.outs = hw.instance "buffer19" @handshake_buffer_1(ins: %buffer18.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %fork5.outs_0, %fork5.outs_1, %fork5.outs_2, %fork5.outs_3 = hw.instance "fork5" @handshake_fork_4(ins: %buffer19.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>, outs_2: !handshake.channel<i32>, outs_3: !handshake.channel<i32>)
    %mux11.outs = hw.instance "mux11" @handshake_mux_0(index: %fork4.outs_0: !handshake.channel<i1>, ins_0: %fork1.outs_0: !handshake.channel<i32>, ins_1: %cond_br35.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer20.outs = hw.instance "buffer20" @handshake_buffer_0(ins: %mux11.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer21.outs = hw.instance "buffer21" @handshake_buffer_1(ins: %buffer20.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %fork6.outs_0, %fork6.outs_1, %fork6.outs_2, %fork6.outs_3 = hw.instance "fork6" @handshake_fork_4(ins: %buffer21.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>, outs_2: !handshake.channel<i32>, outs_3: !handshake.channel<i32>)
    %cmpi0.result = hw.instance "cmpi0" @handshake_cmpi_0(lhs: %fork5.outs_1: !handshake.channel<i32>, rhs: %fork6.outs_1: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %buffer12.outs = hw.instance "buffer12" @handshake_buffer_2(ins: %mux7.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer13.outs = hw.instance "buffer13" @handshake_buffer_3(ins: %buffer12.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %andi0.result = hw.instance "andi0" @handshake_andi_0(lhs: %cmpi0.result: !handshake.channel<i1>, rhs: %buffer13.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %fork7.outs_0, %fork7.outs_1, %fork7.outs_2, %fork7.outs_3, %fork7.outs_4, %fork7.outs_5, %fork7.outs_6, %fork7.outs_7 = hw.instance "fork7" @handshake_fork_5(ins: %andi0.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>, outs_3: !handshake.channel<i1>, outs_4: !handshake.channel<i1>, outs_5: !handshake.channel<i1>, outs_6: !handshake.channel<i1>, outs_7: !handshake.channel<i1>)
    %buffer14.outs = hw.instance "buffer14" @handshake_buffer_0(ins: %mux8.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer15.outs = hw.instance "buffer15" @handshake_buffer_1(ins: %buffer14.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %cond_br37.trueOut, %cond_br37.falseOut = hw.instance "cond_br37" @handshake_cond_br_0(condition: %fork7.outs_4: !handshake.channel<i1>, data: %buffer15.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    %buffer16.outs = hw.instance "buffer16" @handshake_buffer_2(ins: %mux9.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer17.outs = hw.instance "buffer17" @handshake_buffer_3(ins: %buffer16.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %cond_br38.trueOut, %cond_br38.falseOut = hw.instance "cond_br38" @handshake_cond_br_1(condition: %fork7.outs_3: !handshake.channel<i1>, data: %buffer17.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i1>, falseOut: !handshake.channel<i1>)
    %buffer2.outs = hw.instance "buffer2" @handshake_buffer_0(ins: %mux0.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer3.outs = hw.instance "buffer3" @handshake_buffer_1(ins: %buffer2.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %cond_br39.trueOut, %cond_br39.falseOut = hw.instance "cond_br39" @handshake_cond_br_0(condition: %fork7.outs_2: !handshake.channel<i1>, data: %buffer3.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    hw.instance "sink2" @handshake_sink_0(ins: %cond_br39.falseOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> ()
    %fork8.outs_0, %fork8.outs_1, %fork8.outs_2, %fork8.outs_3 = hw.instance "fork8" @handshake_fork_4(ins: %cond_br39.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>, outs_2: !handshake.channel<i32>, outs_3: !handshake.channel<i32>)
    %cond_br40.trueOut, %cond_br40.falseOut = hw.instance "cond_br40" @handshake_cond_br_0(condition: %fork7.outs_1: !handshake.channel<i1>, data: %fork6.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    %cond_br41.trueOut, %cond_br41.falseOut = hw.instance "cond_br41" @handshake_cond_br_0(condition: %fork7.outs_0: !handshake.channel<i1>, data: %fork5.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    hw.instance "sink3" @handshake_sink_0(ins: %cond_br41.falseOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> ()
    %source6.outs = hw.instance "source6" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant7.outs = hw.instance "constant7" @handshake_constant_2(ctrl: %source6.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i2>)
    %extsi2.outs = hw.instance "extsi2" @handshake_extsi_1(ins: %constant7.outs: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %addi0.result = hw.instance "addi0" @handshake_addi_0(lhs: %cond_br41.trueOut: !handshake.channel<i32>, rhs: %cond_br40.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %shrsi0.result = hw.instance "shrsi0" @handshake_shrsi_0(lhs: %addi0.result: !handshake.channel<i32>, rhs: %extsi2.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %fork9.outs_0, %fork9.outs_1, %fork9.outs_2, %fork9.outs_3 = hw.instance "fork9" @handshake_fork_4(ins: %shrsi0.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>, outs_2: !handshake.channel<i32>, outs_3: !handshake.channel<i32>)
    %muli0.result = hw.instance "muli0" @handshake_muli_0(lhs: %fork9.outs_2: !handshake.channel<i32>, rhs: %fork9.outs_3: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %fork10.outs_0, %fork10.outs_1, %fork10.outs_2 = hw.instance "fork10" @handshake_fork_6(ins: %muli0.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>, outs_2: !handshake.channel<i32>)
    %cmpi1.result = hw.instance "cmpi1" @handshake_cmpi_1(lhs: %fork10.outs_2: !handshake.channel<i32>, rhs: %fork8.outs_2: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %cmpi2.result = hw.instance "cmpi2" @handshake_cmpi_2(lhs: %fork10.outs_1: !handshake.channel<i32>, rhs: %fork8.outs_1: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %fork11.outs_0, %fork11.outs_1, %fork11.outs_2, %fork11.outs_3 = hw.instance "fork11" @handshake_fork_7(ins: %cmpi2.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>, outs_3: !handshake.channel<i1>)
    %andi1.result = hw.instance "andi1" @handshake_andi_0(lhs: %fork11.outs_0: !handshake.channel<i1>, rhs: %cond_br38.trueOut: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %select0.result = hw.instance "select0" @handshake_select_0(condition: %cmpi1.result: !handshake.channel<i1>, trueValue: %fork9.outs_1: !handshake.channel<i32>, falseValue: %cond_br37.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %cmpi3.result = hw.instance "cmpi3" @handshake_cmpi_3(lhs: %fork10.outs_0: !handshake.channel<i32>, rhs: %fork8.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %fork12.outs_0, %fork12.outs_1, %fork12.outs_2 = hw.instance "fork12" @handshake_fork_8(ins: %cmpi3.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>)
    %cond_br42.trueOut, %cond_br42.falseOut = hw.instance "cond_br42" @handshake_cond_br_0(condition: %fork12.outs_0: !handshake.channel<i1>, data: %fork9.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    %source7.outs = hw.instance "source7" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant8.outs = hw.instance "constant8" @handshake_constant_2(ctrl: %source7.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i2>)
    %extsi3.outs = hw.instance "extsi3" @handshake_extsi_1(ins: %constant8.outs: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %addi1.result = hw.instance "addi1" @handshake_addi_0(lhs: %cond_br42.trueOut: !handshake.channel<i32>, rhs: %extsi3.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %source8.outs = hw.instance "source8" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant6.outs = hw.instance "constant6" @handshake_constant_3(ctrl: %source8.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %addi2.result = hw.instance "addi2" @handshake_addi_0(lhs: %cond_br42.falseOut: !handshake.channel<i32>, rhs: %constant6.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %select1.result = hw.instance "select1" @handshake_select_0(condition: %cond_br38.falseOut: !handshake.channel<i1>, trueValue: %cond_br40.falseOut: !handshake.channel<i32>, falseValue: %cond_br37.falseOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    hw.output %select1.result, %fork0.outs_0 : !handshake.channel<i32>, !handshake.control<>
  }
  hw.module.extern @handshake_fork_0(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.control<>, out outs_1 : !handshake.control<>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.control<>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_fork_1(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_source_0(in %clk : i1, in %rst : i1, out outs : !handshake.control<>) attributes {hw.name = "handshake.source", hw.parameters = {}}
  hw.module.extern @handshake_constant_0(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 1 : ui32, VALUE = "0"}}
  hw.module.extern @handshake_extsi_0(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i1>, OUTPUT_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_constant_1(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 1 : ui32, VALUE = "1"}}
  hw.module.extern @handshake_fork_2(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_0(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<i32>, NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 1, V: 1, R: 0}>}}
  hw.module.extern @handshake_buffer_1(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.channel<i32>, NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 0, V: 0, R: 1}>}}
  hw.module.extern @handshake_cond_br_0(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i32>, out falseOut : !handshake.channel<i32>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_sink_0(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_merge_0(in %ins_0 : !handshake.channel<i1>, in %ins_1 : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.merge", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_2(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<i1>, NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 1, V: 1, R: 0}>}}
  hw.module.extern @handshake_buffer_3(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.channel<i1>, NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 0, V: 0, R: 1}>}}
  hw.module.extern @handshake_fork_3(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>, out outs_2 : !handshake.channel<i1>, out outs_3 : !handshake.channel<i1>, out outs_4 : !handshake.channel<i1>, out outs_5 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 6 : ui32}}
  hw.module.extern @handshake_mux_0(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.channel<i32>, in %ins_1 : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_mux_1(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.channel<i1>, in %ins_1 : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_fork_4(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>, out outs_2 : !handshake.channel<i32>, out outs_3 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, SIZE = 4 : ui32}}
  hw.module.extern @handshake_cmpi_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.cmpi", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, PREDICATE = "sle"}}
  hw.module.extern @handshake_andi_0(in %lhs : !handshake.channel<i1>, in %rhs : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.andi", hw.parameters = {DATA_TYPE = !handshake.channel<i1>}}
  hw.module.extern @handshake_fork_5(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>, out outs_2 : !handshake.channel<i1>, out outs_3 : !handshake.channel<i1>, out outs_4 : !handshake.channel<i1>, out outs_5 : !handshake.channel<i1>, out outs_6 : !handshake.channel<i1>, out outs_7 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 8 : ui32}}
  hw.module.extern @handshake_cond_br_1(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i1>, out falseOut : !handshake.channel<i1>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<i1>}}
  hw.module.extern @handshake_constant_2(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i2>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 2 : ui32, VALUE = "01"}}
  hw.module.extern @handshake_extsi_1(in %ins : !handshake.channel<i2>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i2>, OUTPUT_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_addi_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.addi", hw.parameters = {DATA_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_shrsi_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.shrsi", hw.parameters = {DATA_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_muli_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.muli", hw.parameters = {DATA_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_fork_6(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>, out outs_2 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, SIZE = 3 : ui32}}
  hw.module.extern @handshake_cmpi_1(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.cmpi", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, PREDICATE = "eq"}}
  hw.module.extern @handshake_cmpi_2(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.cmpi", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, PREDICATE = "ne"}}
  hw.module.extern @handshake_fork_7(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>, out outs_2 : !handshake.channel<i1>, out outs_3 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 4 : ui32}}
  hw.module.extern @handshake_select_0(in %condition : !handshake.channel<i1>, in %trueValue : !handshake.channel<i32>, in %falseValue : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.select", hw.parameters = {DATA_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_cmpi_3(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.cmpi", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, PREDICATE = "slt"}}
  hw.module.extern @handshake_fork_8(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>, out outs_2 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 3 : ui32}}
  hw.module.extern @handshake_constant_3(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 32 : ui32, VALUE = "11111111111111111111111111111111"}}
  hw.module @iterative_sqrt_wrapper(in %n : !handshake.channel<i32>, in %start : !handshake.control<>, in %clk : i1, in %rst : i1, out out0 : !handshake.channel<i32>, out end : !handshake.control<>) {
    %iterative_sqrt_wrapped.out0, %iterative_sqrt_wrapped.end = hw.instance "iterative_sqrt_wrapped" @iterative_sqrt(n: %n: !handshake.channel<i32>, start: %start: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (out0: !handshake.channel<i32>, end: !handshake.control<>)
    hw.output %iterative_sqrt_wrapped.out0, %iterative_sqrt_wrapped.end : !handshake.channel<i32>, !handshake.control<>
  }
}

