vlib work
vmap work work
project new . simulation work modelsim.ini 0
project open simulation
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_mem_controller_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_buffer_4.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_fork_3.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_constant_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_muli_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_store_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_buffer_9.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_constant_5.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_extsi_2.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_buffer_6.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_passer_2.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_addi_2.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/types.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_trunci_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_extsi_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_buffer_11.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_trunci_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_mux_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_extsi_5.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_constant_3.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_mux_2.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_source_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_buffer_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/single_argument.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_merge_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_buffer_10.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_fork_9.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_cond_br_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/two_port_RAM.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_init_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_buffer_8.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_extsi_3.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_passer_3.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_fork_2.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_muli_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_constant_2.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_cmpi_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_buffer_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_buffer_3.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_passer_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_mem_controller_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_extsi_6.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_mux_3.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_cond_br_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_andi_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/nested_loop.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_cmpi_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_buffer_2.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_addi_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_fork_7.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_buffer_13.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_spec_v2_resolver_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_fork_5.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_fork_8.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_constant_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_passer_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_passer_5.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_fork_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_mux_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_buffer_12.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_addi_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_trunci_2.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_buffer_7.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/nested_loop_wrapper.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/tb_nested_loop.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/tb_join.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_fork_4.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_fork_6.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_buffer_5.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_mem_controller_2.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_constant_4.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_control_merge_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_load_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_fork_10.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/simpackage.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_extsi_4.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_fork_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_extsi_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/mem_to_bram_32_10.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_passer_4.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_not_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/nested_loop/out/sim/HDL_SRC/handshake_sink_0.vhd
project calculateorder
project compileall
eval vsim tb
log -r *
run 20000ns -all
exit
