handshakes calles replaceMergto gsa

Operation null is feeding %0:4 = "handshake.lsq"(%arg0, %arg2, %26#1, %32#0, %35#1, %39#0, %43#1, %50#0, %52#0, %52#1, %55#0) {groupSizes = [1 : i32, 1 : i32, 2 : i32], handshake.name = "lsq1"} : (memref<10xi32>, !handshake.control<>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>) -> (!handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>)
Operation null is feeding %0:4 = "handshake.lsq"(%arg0, %arg2, %26#1, %32#0, %35#1, %39#0, %43#1, %50#0, %52#0, %52#1, %55#0) {groupSizes = [1 : i32, 1 : i32, 2 : i32], handshake.name = "lsq1"} : (memref<10xi32>, !handshake.control<>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>) -> (!handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>)
Operation %26:2 = "handshake.lazy_fork"(%9) : (!handshake.control<>) -> (!handshake.control<>, !handshake.control<>) is feeding %0:4 = "handshake.lsq"(%arg0, %arg2, %26#1, %32#0, %35#1, %39#0, %43#1, %50#0, %52#0, %52#1, %55#0) {groupSizes = [1 : i32, 1 : i32, 2 : i32], handshake.name = "lsq1"} : (memref<10xi32>, !handshake.control<>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>) -> (!handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>)
Operation %32:2 = "handshake.load"(%44#0, %0#0) {handshake.bb = 2 : ui32, handshake.deps = #handshake<deps[<"store1" (0)>]>, handshake.mem_interface = #handshake.mem_interface<LSQ: 0>, handshake.name = "load3"} : (!handshake.channel<i32>, !handshake.channel<i32>) -> (!handshake.channel<i32>, !handshake.channel<i32>) is feeding %0:4 = "handshake.lsq"(%arg0, %arg2, %26#1, %32#0, %35#1, %39#0, %43#1, %50#0, %52#0, %52#1, %55#0) {groupSizes = [1 : i32, 1 : i32, 2 : i32], handshake.name = "lsq1"} : (memref<10xi32>, !handshake.control<>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>) -> (!handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>)
Operation %35:2 = "handshake.lazy_fork"(%6) : (!handshake.control<>) -> (!handshake.control<>, !handshake.control<>) is feeding %0:4 = "handshake.lsq"(%arg0, %arg2, %26#1, %32#0, %35#1, %39#0, %43#1, %50#0, %52#0, %52#1, %55#0) {groupSizes = [1 : i32, 1 : i32, 2 : i32], handshake.name = "lsq1"} : (memref<10xi32>, !handshake.control<>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>) -> (!handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>)
Operation %39:2 = "handshake.load"(%44#0, %0#1) {handshake.bb = 3 : ui32, handshake.deps = #handshake<deps[<"store1" (0)>]>, handshake.mem_interface = #handshake.mem_interface<LSQ: 1>, handshake.name = "load4"} : (!handshake.channel<i32>, !handshake.channel<i32>) -> (!handshake.channel<i32>, !handshake.channel<i32>) is feeding %0:4 = "handshake.lsq"(%arg0, %arg2, %26#1, %32#0, %35#1, %39#0, %43#1, %50#0, %52#0, %52#1, %55#0) {groupSizes = [1 : i32, 1 : i32, 2 : i32], handshake.name = "lsq1"} : (memref<10xi32>, !handshake.control<>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>) -> (!handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>)
    Operation %43:2 = "handshake.lazy_fork"(%42) : (!handshake.control<>) -> (!handshake.control<>, !handshake.control<>) is feeding %0:4 = "handshake.lsq"(%arg0, %arg2, %26#1, %32#0, %35#1, %39#0, %43#1, %50#0, %52#0, %52#1, %55#0) {groupSizes = [1 : i32, 1 : i32, 2 : i32], handshake.name = "lsq1"} : (memref<10xi32>, !handshake.control<>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>) -> (!handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>)
Operation %50:2 = "handshake.load"(%44#0, %0#2) {handshake.bb = 4 : ui32, handshake.deps = #handshake<deps[<"store1" (0)>]>, handshake.mem_interface = #handshake.mem_interface<LSQ: 2>, handshake.name = "load5"} : (!handshake.channel<i32>, !handshake.channel<i32>) -> (!handshake.channel<i32>, !handshake.channel<i32>) is feeding %0:4 = "handshake.lsq"(%arg0, %arg2, %26#1, %32#0, %35#1, %39#0, %43#1, %50#0, %52#0, %52#1, %55#0) {groupSizes = [1 : i32, 1 : i32, 2 : i32], handshake.name = "lsq1"} : (memref<10xi32>, !handshake.control<>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>) -> (!handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>)
Operation %52:2 = "handshake.store"(%44#0, %51) {handshake.bb = 4 : ui32, handshake.deps = #handshake<deps[<"load3" (0)>, <"load4" (0)>, <"load5" (0)>, <"store1" (0)>]>, handshake.mem_interface = #handshake.mem_interface<LSQ: 2>, handshake.name = "store1"} : (!handshake.channel<i32>, !handshake.channel<i32>) -> (!handshake.channel<i32>, !handshake.channel<i32>) is feeding %0:4 = "handshake.lsq"(%arg0, %arg2, %26#1, %32#0, %35#1, %39#0, %43#1, %50#0, %52#0, %52#1, %55#0) {groupSizes = [1 : i32, 1 : i32, 2 : i32], handshake.name = "lsq1"} : (memref<10xi32>, !handshake.control<>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>) -> (!handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>)
Operation %52:2 = "handshake.store"(%44#0, %51) {handshake.bb = 4 : ui32, handshake.deps = #handshake<deps[<"load3" (0)>, <"load4" (0)>, <"load5" (0)>, <"store1" (0)>]>, handshake.mem_interface = #handshake.mem_interface<LSQ: 2>, handshake.name = "store1"} : (!handshake.channel<i32>, !handshake.channel<i32>) -> (!handshake.channel<i32>, !handshake.channel<i32>) is feeding %0:4 = "handshake.lsq"(%arg0, %arg2, %26#1, %32#0, %35#1, %39#0, %43#1, %50#0, %52#0, %52#1, %55#0) {groupSizes = [1 : i32, 1 : i32, 2 : i32], handshake.name = "lsq1"} : (memref<10xi32>, !handshake.control<>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>) -> (!handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>)
Operation %55:2 = "handshake.control_merge"(%25#1) {handshake.bb = 5 : ui32, handshake.name = "control_merge4"} : (!handshake.control<>) -> (!handshake.control<>, !handshake.channel<i1>) is feeding %0:4 = "handshake.lsq"(%arg0, %arg2, %26#1, %32#0, %35#1, %39#0, %43#1, %50#0, %52#0, %52#1, %55#0) {groupSizes = [1 : i32, 1 : i32, 2 : i32], handshake.name = "lsq1"} : (memref<10xi32>, !handshake.control<>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>) -> (!handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>)
Operation %1 = "handshake.source"() {handshake.bb = 0 : ui32, handshake.name = "source0"} : () -> !handshake.control<> is feeding %2 = "handshake.constant"(%1) {handshake.bb = 0 : ui32, handshake.name = "constant0", value = 0 : i32} : (!handshake.control<>) -> !handshake.channel<i32>
Operation %3 = "handshake.source"() {handshake.bb = 0 : ui32, handshake.name = "source1"} : () -> !handshake.control<> is feeding %4 = "handshake.constant"(%3) {handshake.bb = 0 : ui32, handshake.name = "constant4", value = true} : (!handshake.control<>) -> !handshake.channel<i1>
Operation null is feeding %5 = "handshake.br"(%arg3) {handshake.bb = 0 : ui32, handshake.name = "br1"} : (!handshake.control<>) -> !handshake.control<>
    Operation %43:2 = "handshake.lazy_fork"(%42) : (!handshake.control<>) -> (!handshake.control<>, !handshake.control<>) is feeding %6 = "handshake.merge"(%43#0, %6, %6, %arg3) {nphi} : (!handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>) -> !handshake.control<>
  Operation %6 = "handshake.merge"(%43#0, %6, %6, %arg3) {nphi} : (!handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>) -> !handshake.control<> is feeding %6 = "handshake.merge"(%43#0, %6, %6, %arg3) {nphi} : (!handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>) -> !handshake.control<>
  Operation %6 = "handshake.merge"(%43#0, %6, %6, %arg3) {nphi} : (!handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>) -> !handshake.control<> is feeding %6 = "handshake.merge"(%43#0, %6, %6, %arg3) {nphi} : (!handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>) -> !handshake.control<>
Operation null is feeding %6 = "handshake.merge"(%43#0, %6, %6, %arg3) {nphi} : (!handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>) -> !handshake.control<>
Operation %35:2 = "handshake.lazy_fork"(%6) : (!handshake.control<>) -> (!handshake.control<>, !handshake.control<>) is feeding %7 = "handshake.merge"(%35#0, %35#0, %7, %arg3) {nphi} : (!handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>) -> !handshake.control<>
Operation %35:2 = "handshake.lazy_fork"(%6) : (!handshake.control<>) -> (!handshake.control<>, !handshake.control<>) is feeding %7 = "handshake.merge"(%35#0, %35#0, %7, %arg3) {nphi} : (!handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>) -> !handshake.control<>
Operation %7 = "handshake.merge"(%35#0, %35#0, %7, %arg3) {nphi} : (!handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>) -> !handshake.control<> is feeding %7 = "handshake.merge"(%35#0, %35#0, %7, %arg3) {nphi} : (!handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>) -> !handshake.control<>
Operation null is feeding %7 = "handshake.merge"(%35#0, %35#0, %7, %arg3) {nphi} : (!handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>) -> !handshake.control<>
Operation %26:2 = "handshake.lazy_fork"(%9) : (!handshake.control<>) -> (!handshake.control<>, !handshake.control<>) is feeding %8 = "handshake.merge"(%26#0, %26#0, %26#0, %arg3) {nphi} : (!handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>) -> !handshake.control<>
Operation %26:2 = "handshake.lazy_fork"(%9) : (!handshake.control<>) -> (!handshake.control<>, !handshake.control<>) is feeding %8 = "handshake.merge"(%26#0, %26#0, %26#0, %arg3) {nphi} : (!handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>) -> !handshake.control<>
Operation %26:2 = "handshake.lazy_fork"(%9) : (!handshake.control<>) -> (!handshake.control<>, !handshake.control<>) is feeding %8 = "handshake.merge"(%26#0, %26#0, %26#0, %arg3) {nphi} : (!handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>) -> !handshake.control<>
Operation null is feeding %8 = "handshake.merge"(%26#0, %26#0, %26#0, %arg3) {nphi} : (!handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>) -> !handshake.control<>
    Operation %43:2 = "handshake.lazy_fork"(%42) : (!handshake.control<>) -> (!handshake.control<>, !handshake.control<>) is feeding %9 = "handshake.merge"(%43#0, %9, %9, %arg3) {nphi} : (!handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>) -> !handshake.control<>
Operation %9 = "handshake.merge"(%43#0, %9, %9, %arg3) {nphi} : (!handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>) -> !handshake.control<> is feeding %9 = "handshake.merge"(%43#0, %9, %9, %arg3) {nphi} : (!handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>) -> !handshake.control<>
Operation %9 = "handshake.merge"(%43#0, %9, %9, %arg3) {nphi} : (!handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>) -> !handshake.control<> is feeding %9 = "handshake.merge"(%43#0, %9, %9, %arg3) {nphi} : (!handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>) -> !handshake.control<>
Operation null is feeding %9 = "handshake.merge"(%43#0, %9, %9, %arg3) {nphi} : (!handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>) -> !handshake.control<>
Operation %24 = "handshake.andi"(%23, %21) {handshake.bb = 1 : ui32, handshake.name = "andi0"} : (!handshake.channel<i1>, !handshake.channel<i1>) -> !handshake.channel<i1> is feeding %10:2 = "handshake.cond_br"(%24, %19) {handshake.bb = 1 : ui32, handshake.name = "cond_br14"} : (!handshake.channel<i1>, !handshake.channel<i32>) -> (!handshake.channel<i32>, !handshake.channel<i32>)
Operation %19 = "handshake.mux"(%33, %22, %20) {ftd.phi, handshake.bb = 1 : ui32, handshake.name = "mux3"} : (!handshake.channel<i1>, !handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i32> is feeding %10:2 = "handshake.cond_br"(%24, %19) {handshake.bb = 1 : ui32, handshake.name = "cond_br14"} : (!handshake.channel<i1>, !handshake.channel<i32>) -> (!handshake.channel<i32>, !handshake.channel<i32>)
Operation %24 = "handshake.andi"(%23, %21) {handshake.bb = 1 : ui32, handshake.name = "andi0"} : (!handshake.channel<i1>, !handshake.channel<i1>) -> !handshake.channel<i1> is feeding %11:2 = "handshake.cond_br"(%24, %17) {handshake.bb = 1 : ui32, handshake.name = "cond_br15"} : (!handshake.channel<i1>, !handshake.channel<i1>) -> (!handshake.channel<i1>, !handshake.channel<i1>)
Operation %17 = "handshake.mux"(%33, %29, %18) {ftd.phi, handshake.bb = 1 : ui32, handshake.name = "mux1"} : (!handshake.channel<i1>, !handshake.channel<i1>, !handshake.channel<i1>) -> !handshake.channel<i1> is feeding %11:2 = "handshake.cond_br"(%24, %17) {handshake.bb = 1 : ui32, handshake.name = "cond_br15"} : (!handshake.channel<i1>, !handshake.channel<i1>) -> (!handshake.channel<i1>, !handshake.channel<i1>)
Operation %24 = "handshake.andi"(%23, %21) {handshake.bb = 1 : ui32, handshake.name = "andi0"} : (!handshake.channel<i1>, !handshake.channel<i1>) -> !handshake.channel<i1> is feeding %12:2 = "handshake.cond_br"(%24, %15) {handshake.bb = 1 : ui32, handshake.name = "cond_br16"} : (!handshake.channel<i1>, !handshake.channel<i32>) -> (!handshake.channel<i32>, !handshake.channel<i32>)
Operation %15 = "handshake.mux"(%14, %arg1, %12#0) {ftd.regen, handshake.bb = 1 : ui32, handshake.name = "mux0"} : (!handshake.channel<i1>, !handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i32> is feeding %12:2 = "handshake.cond_br"(%24, %15) {handshake.bb = 1 : ui32, handshake.name = "cond_br16"} : (!handshake.channel<i1>, !handshake.channel<i32>) -> (!handshake.channel<i32>, !handshake.channel<i32>)
Operation null is feeding %13 = "handshake.constant"(%arg3) {ftd.imerge, handshake.bb = 1 : ui32, handshake.name = "constant1", value = false} : (!handshake.control<>) -> !handshake.channel<i1>
Operation %13 = "handshake.constant"(%arg3) {ftd.imerge, handshake.bb = 1 : ui32, handshake.name = "constant1", value = false} : (!handshake.control<>) -> !handshake.channel<i1> is feeding %14 = "handshake.merge"(%13, %24) {ftd.imerge, handshake.bb = 1 : ui32, handshake.name = "merge0"} : (!handshake.channel<i1>, !handshake.channel<i1>) -> !handshake.channel<i1>
Operation %24 = "handshake.andi"(%23, %21) {handshake.bb = 1 : ui32, handshake.name = "andi0"} : (!handshake.channel<i1>, !handshake.channel<i1>) -> !handshake.channel<i1> is feeding %14 = "handshake.merge"(%13, %24) {ftd.imerge, handshake.bb = 1 : ui32, handshake.name = "merge0"} : (!handshake.channel<i1>, !handshake.channel<i1>) -> !handshake.channel<i1>
Operation %14 = "handshake.merge"(%13, %24) {ftd.imerge, handshake.bb = 1 : ui32, handshake.name = "merge0"} : (!handshake.channel<i1>, !handshake.channel<i1>) -> !handshake.channel<i1> is feeding %15 = "handshake.mux"(%14, %arg1, %12#0) {ftd.regen, handshake.bb = 1 : ui32, handshake.name = "mux0"} : (!handshake.channel<i1>, !handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i32>
Operation null is feeding %15 = "handshake.mux"(%14, %arg1, %12#0) {ftd.regen, handshake.bb = 1 : ui32, handshake.name = "mux0"} : (!handshake.channel<i1>, !handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i32>
Operation %12:2 = "handshake.cond_br"(%24, %15) {handshake.bb = 1 : ui32, handshake.name = "cond_br16"} : (!handshake.channel<i1>, !handshake.channel<i32>) -> (!handshake.channel<i32>, !handshake.channel<i32>) is feeding %15 = "handshake.mux"(%14, %arg1, %12#0) {ftd.regen, handshake.bb = 1 : ui32, handshake.name = "mux0"} : (!handshake.channel<i1>, !handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i32>
Operation %5 = "handshake.br"(%arg3) {handshake.bb = 0 : ui32, handshake.name = "br1"} : (!handshake.control<>) -> !handshake.control<> is feeding %16:2 = "handshake.control_merge"(%5, %34#1, %41#1, %54) {handshake.bb = 1 : ui32, handshake.name = "control_merge0"} : (!handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>) -> (!handshake.control<>, !handshake.channel<i2>)
Operation %34:2 = "handshake.cond_br"(%33, %27#0) {handshake.bb = 2 : ui32, handshake.name = "cond_br11"} : (!handshake.channel<i1>, !handshake.control<>) -> (!handshake.control<>, !handshake.control<>) is feeding %16:2 = "handshake.control_merge"(%5, %34#1, %41#1, %54) {handshake.bb = 1 : ui32, handshake.name = "control_merge0"} : (!handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>) -> (!handshake.control<>, !handshake.channel<i2>)
Operation %41:2 = "handshake.cond_br"(%40, %36#0) {handshake.bb = 3 : ui32, handshake.name = "cond_br12"} : (!handshake.channel<i1>, !handshake.control<>) -> (!handshake.control<>, !handshake.control<>) is feeding %16:2 = "handshake.control_merge"(%5, %34#1, %41#1, %54) {handshake.bb = 1 : ui32, handshake.name = "control_merge0"} : (!handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>) -> (!handshake.control<>, !handshake.channel<i2>)
Operation %54 = "handshake.br"(%45#0) {handshake.bb = 4 : ui32, handshake.name = "br2"} : (!handshake.control<>) -> !handshake.control<> is feeding %16:2 = "handshake.control_merge"(%5, %34#1, %41#1, %54) {handshake.bb = 1 : ui32, handshake.name = "control_merge0"} : (!handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>) -> (!handshake.control<>, !handshake.channel<i2>)
Operation %33 = "handshake.cmpi"(%32#1, %31) {handshake.bb = 2 : ui32, handshake.name = "cmpi1", predicate = 1 : i64} : (!handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i1> is feeding %17 = "handshake.mux"(%33, %29, %18) {ftd.phi, handshake.bb = 1 : ui32, handshake.name = "mux1"} : (!handshake.channel<i1>, !handshake.channel<i1>, !handshake.channel<i1>) -> !handshake.channel<i1>
Operation %29 = "handshake.constant"(%28) {handshake.bb = 2 : ui32, handshake.name = "constant5", value = false} : (!handshake.control<>) -> !handshake.channel<i1> is feeding %17 = "handshake.mux"(%33, %29, %18) {ftd.phi, handshake.bb = 1 : ui32, handshake.name = "mux1"} : (!handshake.channel<i1>, !handshake.channel<i1>, !handshake.channel<i1>) -> !handshake.channel<i1>
Operation %18 = "handshake.mux"(%40, %40, %47) {ftd.phi, handshake.bb = 1 : ui32, handshake.name = "mux2"} : (!handshake.channel<i1>, !handshake.channel<i1>, !handshake.channel<i1>) -> !handshake.channel<i1> is feeding %17 = "handshake.mux"(%33, %29, %18) {ftd.phi, handshake.bb = 1 : ui32, handshake.name = "mux1"} : (!handshake.channel<i1>, !handshake.channel<i1>, !handshake.channel<i1>) -> !handshake.channel<i1>
Operation %40 = "handshake.cmpi"(%39#1, %38) {handshake.bb = 3 : ui32, handshake.name = "cmpi2", predicate = 1 : i64} : (!handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i1> is feeding %18 = "handshake.mux"(%40, %40, %47) {ftd.phi, handshake.bb = 1 : ui32, handshake.name = "mux2"} : (!handshake.channel<i1>, !handshake.channel<i1>, !handshake.channel<i1>) -> !handshake.channel<i1>
Operation %40 = "handshake.cmpi"(%39#1, %38) {handshake.bb = 3 : ui32, handshake.name = "cmpi2", predicate = 1 : i64} : (!handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i1> is feeding %18 = "handshake.mux"(%40, %40, %47) {ftd.phi, handshake.bb = 1 : ui32, handshake.name = "mux2"} : (!handshake.channel<i1>, !handshake.channel<i1>, !handshake.channel<i1>) -> !handshake.channel<i1>
Operation %47 = "handshake.constant"(%46) {handshake.bb = 4 : ui32, handshake.name = "constant8", value = true} : (!handshake.control<>) -> !handshake.channel<i1> is feeding %18 = "handshake.mux"(%40, %40, %47) {ftd.phi, handshake.bb = 1 : ui32, handshake.name = "mux2"} : (!handshake.channel<i1>, !handshake.channel<i1>, !handshake.channel<i1>) -> !handshake.channel<i1>
Operation %33 = "handshake.cmpi"(%32#1, %31) {handshake.bb = 2 : ui32, handshake.name = "cmpi1", predicate = 1 : i64} : (!handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i1> is feeding %19 = "handshake.mux"(%33, %22, %20) {ftd.phi, handshake.bb = 1 : ui32, handshake.name = "mux3"} : (!handshake.channel<i1>, !handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i32>
Operation %22 = "handshake.mux"(%14, %2, %10#0) {ftd.phi, handshake.bb = 1 : ui32, handshake.name = "mux6"} : (!handshake.channel<i1>, !handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i32> is feeding %19 = "handshake.mux"(%33, %22, %20) {ftd.phi, handshake.bb = 1 : ui32, handshake.name = "mux3"} : (!handshake.channel<i1>, !handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i32>
Operation %20 = "handshake.mux"(%40, %22, %53) {ftd.phi, handshake.bb = 1 : ui32, handshake.name = "mux4"} : (!handshake.channel<i1>, !handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i32> is feeding %19 = "handshake.mux"(%33, %22, %20) {ftd.phi, handshake.bb = 1 : ui32, handshake.name = "mux3"} : (!handshake.channel<i1>, !handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i32>
Operation %40 = "handshake.cmpi"(%39#1, %38) {handshake.bb = 3 : ui32, handshake.name = "cmpi2", predicate = 1 : i64} : (!handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i1> is feeding %20 = "handshake.mux"(%40, %22, %53) {ftd.phi, handshake.bb = 1 : ui32, handshake.name = "mux4"} : (!handshake.channel<i1>, !handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i32>
Operation %22 = "handshake.mux"(%14, %2, %10#0) {ftd.phi, handshake.bb = 1 : ui32, handshake.name = "mux6"} : (!handshake.channel<i1>, !handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i32> is feeding %20 = "handshake.mux"(%40, %22, %53) {ftd.phi, handshake.bb = 1 : ui32, handshake.name = "mux4"} : (!handshake.channel<i1>, !handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i32>
Operation %53 = "handshake.addi"(%44#0, %49) {handshake.bb = 4 : ui32, handshake.name = "addi1"} : (!handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i32> is feeding %20 = "handshake.mux"(%40, %22, %53) {ftd.phi, handshake.bb = 1 : ui32, handshake.name = "mux4"} : (!handshake.channel<i1>, !handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i32>
Operation %14 = "handshake.merge"(%13, %24) {ftd.imerge, handshake.bb = 1 : ui32, handshake.name = "merge0"} : (!handshake.channel<i1>, !handshake.channel<i1>) -> !handshake.channel<i1> is feeding %21 = "handshake.mux"(%14, %4, %11#0) {ftd.phi, handshake.bb = 1 : ui32, handshake.name = "mux5"} : (!handshake.channel<i1>, !handshake.channel<i1>, !handshake.channel<i1>) -> !handshake.channel<i1>
Operation %4 = "handshake.constant"(%3) {handshake.bb = 0 : ui32, handshake.name = "constant4", value = true} : (!handshake.control<>) -> !handshake.channel<i1> is feeding %21 = "handshake.mux"(%14, %4, %11#0) {ftd.phi, handshake.bb = 1 : ui32, handshake.name = "mux5"} : (!handshake.channel<i1>, !handshake.channel<i1>, !handshake.channel<i1>) -> !handshake.channel<i1>
Operation %11:2 = "handshake.cond_br"(%24, %17) {handshake.bb = 1 : ui32, handshake.name = "cond_br15"} : (!handshake.channel<i1>, !handshake.channel<i1>) -> (!handshake.channel<i1>, !handshake.channel<i1>) is feeding %21 = "handshake.mux"(%14, %4, %11#0) {ftd.phi, handshake.bb = 1 : ui32, handshake.name = "mux5"} : (!handshake.channel<i1>, !handshake.channel<i1>, !handshake.channel<i1>) -> !handshake.channel<i1>
Operation %14 = "handshake.merge"(%13, %24) {ftd.imerge, handshake.bb = 1 : ui32, handshake.name = "merge0"} : (!handshake.channel<i1>, !handshake.channel<i1>) -> !handshake.channel<i1> is feeding %22 = "handshake.mux"(%14, %2, %10#0) {ftd.phi, handshake.bb = 1 : ui32, handshake.name = "mux6"} : (!handshake.channel<i1>, !handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i32>
Operation %2 = "handshake.constant"(%1) {handshake.bb = 0 : ui32, handshake.name = "constant0", value = 0 : i32} : (!handshake.control<>) -> !handshake.channel<i32> is feeding %22 = "handshake.mux"(%14, %2, %10#0) {ftd.phi, handshake.bb = 1 : ui32, handshake.name = "mux6"} : (!handshake.channel<i1>, !handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i32>
Operation %10:2 = "handshake.cond_br"(%24, %19) {handshake.bb = 1 : ui32, handshake.name = "cond_br14"} : (!handshake.channel<i1>, !handshake.channel<i32>) -> (!handshake.channel<i32>, !handshake.channel<i32>) is feeding %22 = "handshake.mux"(%14, %2, %10#0) {ftd.phi, handshake.bb = 1 : ui32, handshake.name = "mux6"} : (!handshake.channel<i1>, !handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i32>
Operation %22 = "handshake.mux"(%14, %2, %10#0) {ftd.phi, handshake.bb = 1 : ui32, handshake.name = "mux6"} : (!handshake.channel<i1>, !handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i32> is feeding %23 = "handshake.cmpi"(%22, %15) {handshake.bb = 1 : ui32, handshake.name = "cmpi0", predicate = 2 : i64} : (!handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i1>
Operation %15 = "handshake.mux"(%14, %arg1, %12#0) {ftd.regen, handshake.bb = 1 : ui32, handshake.name = "mux0"} : (!handshake.channel<i1>, !handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i32> is feeding %23 = "handshake.cmpi"(%22, %15) {handshake.bb = 1 : ui32, handshake.name = "cmpi0", predicate = 2 : i64} : (!handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i1>
Operation %23 = "handshake.cmpi"(%22, %15) {handshake.bb = 1 : ui32, handshake.name = "cmpi0", predicate = 2 : i64} : (!handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i1> is feeding %24 = "handshake.andi"(%23, %21) {handshake.bb = 1 : ui32, handshake.name = "andi0"} : (!handshake.channel<i1>, !handshake.channel<i1>) -> !handshake.channel<i1>
Operation %21 = "handshake.mux"(%14, %4, %11#0) {ftd.phi, handshake.bb = 1 : ui32, handshake.name = "mux5"} : (!handshake.channel<i1>, !handshake.channel<i1>, !handshake.channel<i1>) -> !handshake.channel<i1> is feeding %24 = "handshake.andi"(%23, %21) {handshake.bb = 1 : ui32, handshake.name = "andi0"} : (!handshake.channel<i1>, !handshake.channel<i1>) -> !handshake.channel<i1>
Operation %24 = "handshake.andi"(%23, %21) {handshake.bb = 1 : ui32, handshake.name = "andi0"} : (!handshake.channel<i1>, !handshake.channel<i1>) -> !handshake.channel<i1> is feeding %25:2 = "handshake.cond_br"(%24, %16#0) {handshake.bb = 1 : ui32, handshake.name = "cond_br6"} : (!handshake.channel<i1>, !handshake.control<>) -> (!handshake.control<>, !handshake.control<>)
Operation %16:2 = "handshake.control_merge"(%5, %34#1, %41#1, %54) {handshake.bb = 1 : ui32, handshake.name = "control_merge0"} : (!handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>) -> (!handshake.control<>, !handshake.channel<i2>) is feeding %25:2 = "handshake.cond_br"(%24, %16#0) {handshake.bb = 1 : ui32, handshake.name = "cond_br6"} : (!handshake.channel<i1>, !handshake.control<>) -> (!handshake.control<>, !handshake.control<>)
Operation %24 = "handshake.andi"(%23, %21) {handshake.bb = 1 : ui32, handshake.name = "andi0"} : (!handshake.channel<i1>, !handshake.channel<i1>) -> !handshake.channel<i1> is feeding "cf.cond_br"(%24)[^bb2, ^bb5] <{operandSegmentSizes = array<i32: 1, 0, 0>}> : (!handshake.channel<i1>) -> ()
Operation %9 = "handshake.merge"(%43#0, %9, %9, %arg3) {nphi} : (!handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>) -> !handshake.control<> is feeding %26:2 = "handshake.lazy_fork"(%9) : (!handshake.control<>) -> (!handshake.control<>, !handshake.control<>)
Operation %25:2 = "handshake.cond_br"(%24, %16#0) {handshake.bb = 1 : ui32, handshake.name = "cond_br6"} : (!handshake.channel<i1>, !handshake.control<>) -> (!handshake.control<>, !handshake.control<>) is feeding %27:2 = "handshake.control_merge"(%25#0) {handshake.bb = 2 : ui32, handshake.name = "control_merge1"} : (!handshake.control<>) -> (!handshake.control<>, !handshake.channel<i1>)
Operation %28 = "handshake.source"() {handshake.bb = 2 : ui32, handshake.name = "source3"} : () -> !handshake.control<> is feeding %29 = "handshake.constant"(%28) {handshake.bb = 2 : ui32, handshake.name = "constant5", value = false} : (!handshake.control<>) -> !handshake.channel<i1>
Operation %30 = "handshake.source"() {handshake.bb = 2 : ui32, handshake.name = "source4"} : () -> !handshake.control<> is feeding %31 = "handshake.constant"(%30) {handshake.bb = 2 : ui32, handshake.name = "constant6", value = -1 : i32} : (!handshake.control<>) -> !handshake.channel<i32>
Operation %44:2 = "handshake.cond_br"(%24, %22) {handshake.bb = 4 : ui32, handshake.name = "cond_br17"} : (!handshake.channel<i1>, !handshake.channel<i32>) -> (!handshake.channel<i32>, !handshake.channel<i32>) is feeding %32:2 = "handshake.load"(%44#0, %0#0) {handshake.bb = 2 : ui32, handshake.deps = #handshake<deps[<"store1" (0)>]>, handshake.mem_interface = #handshake.mem_interface<LSQ: 0>, handshake.name = "load3"} : (!handshake.channel<i32>, !handshake.channel<i32>) -> (!handshake.channel<i32>, !handshake.channel<i32>)
Operation %0:4 = "handshake.lsq"(%arg0, %arg2, %26#1, %32#0, %35#1, %39#0, %43#1, %50#0, %52#0, %52#1, %55#0) {groupSizes = [1 : i32, 1 : i32, 2 : i32], handshake.name = "lsq1"} : (memref<10xi32>, !handshake.control<>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>) -> (!handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>) is feeding %32:2 = "handshake.load"(%44#0, %0#0) {handshake.bb = 2 : ui32, handshake.deps = #handshake<deps[<"store1" (0)>]>, handshake.mem_interface = #handshake.mem_interface<LSQ: 0>, handshake.name = "load3"} : (!handshake.channel<i32>, !handshake.channel<i32>) -> (!handshake.channel<i32>, !handshake.channel<i32>)
Operation %32:2 = "handshake.load"(%44#0, %0#0) {handshake.bb = 2 : ui32, handshake.deps = #handshake<deps[<"store1" (0)>]>, handshake.mem_interface = #handshake.mem_interface<LSQ: 0>, handshake.name = "load3"} : (!handshake.channel<i32>, !handshake.channel<i32>) -> (!handshake.channel<i32>, !handshake.channel<i32>) is feeding %33 = "handshake.cmpi"(%32#1, %31) {handshake.bb = 2 : ui32, handshake.name = "cmpi1", predicate = 1 : i64} : (!handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i1>
Operation %31 = "handshake.constant"(%30) {handshake.bb = 2 : ui32, handshake.name = "constant6", value = -1 : i32} : (!handshake.control<>) -> !handshake.channel<i32> is feeding %33 = "handshake.cmpi"(%32#1, %31) {handshake.bb = 2 : ui32, handshake.name = "cmpi1", predicate = 1 : i64} : (!handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i1>
Operation %33 = "handshake.cmpi"(%32#1, %31) {handshake.bb = 2 : ui32, handshake.name = "cmpi1", predicate = 1 : i64} : (!handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i1> is feeding %34:2 = "handshake.cond_br"(%33, %27#0) {handshake.bb = 2 : ui32, handshake.name = "cond_br11"} : (!handshake.channel<i1>, !handshake.control<>) -> (!handshake.control<>, !handshake.control<>)
Operation %27:2 = "handshake.control_merge"(%25#0) {handshake.bb = 2 : ui32, handshake.name = "control_merge1"} : (!handshake.control<>) -> (!handshake.control<>, !handshake.channel<i1>) is feeding %34:2 = "handshake.cond_br"(%33, %27#0) {handshake.bb = 2 : ui32, handshake.name = "cond_br11"} : (!handshake.channel<i1>, !handshake.control<>) -> (!handshake.control<>, !handshake.control<>)
Operation %33 = "handshake.cmpi"(%32#1, %31) {handshake.bb = 2 : ui32, handshake.name = "cmpi1", predicate = 1 : i64} : (!handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i1> is feeding "cf.cond_br"(%33)[^bb3, ^bb1] <{operandSegmentSizes = array<i32: 1, 0, 0>}> : (!handshake.channel<i1>) -> ()
  Operation %6 = "handshake.merge"(%43#0, %6, %6, %arg3) {nphi} : (!handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>) -> !handshake.control<> is feeding %35:2 = "handshake.lazy_fork"(%6) : (!handshake.control<>) -> (!handshake.control<>, !handshake.control<>)
Operation %34:2 = "handshake.cond_br"(%33, %27#0) {handshake.bb = 2 : ui32, handshake.name = "cond_br11"} : (!handshake.channel<i1>, !handshake.control<>) -> (!handshake.control<>, !handshake.control<>) is feeding %36:2 = "handshake.control_merge"(%34#0) {handshake.bb = 3 : ui32, handshake.name = "control_merge2"} : (!handshake.control<>) -> (!handshake.control<>, !handshake.channel<i1>)
Operation %37 = "handshake.source"() {handshake.bb = 3 : ui32, handshake.name = "source5"} : () -> !handshake.control<> is feeding %38 = "handshake.constant"(%37) {handshake.bb = 3 : ui32, handshake.name = "constant7", value = 0 : i32} : (!handshake.control<>) -> !handshake.channel<i32>
Operation %44:2 = "handshake.cond_br"(%24, %22) {handshake.bb = 4 : ui32, handshake.name = "cond_br17"} : (!handshake.channel<i1>, !handshake.channel<i32>) -> (!handshake.channel<i32>, !handshake.channel<i32>) is feeding %39:2 = "handshake.load"(%44#0, %0#1) {handshake.bb = 3 : ui32, handshake.deps = #handshake<deps[<"store1" (0)>]>, handshake.mem_interface = #handshake.mem_interface<LSQ: 1>, handshake.name = "load4"} : (!handshake.channel<i32>, !handshake.channel<i32>) -> (!handshake.channel<i32>, !handshake.channel<i32>)
Operation %0:4 = "handshake.lsq"(%arg0, %arg2, %26#1, %32#0, %35#1, %39#0, %43#1, %50#0, %52#0, %52#1, %55#0) {groupSizes = [1 : i32, 1 : i32, 2 : i32], handshake.name = "lsq1"} : (memref<10xi32>, !handshake.control<>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>) -> (!handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>) is feeding %39:2 = "handshake.load"(%44#0, %0#1) {handshake.bb = 3 : ui32, handshake.deps = #handshake<deps[<"store1" (0)>]>, handshake.mem_interface = #handshake.mem_interface<LSQ: 1>, handshake.name = "load4"} : (!handshake.channel<i32>, !handshake.channel<i32>) -> (!handshake.channel<i32>, !handshake.channel<i32>)
Operation %39:2 = "handshake.load"(%44#0, %0#1) {handshake.bb = 3 : ui32, handshake.deps = #handshake<deps[<"store1" (0)>]>, handshake.mem_interface = #handshake.mem_interface<LSQ: 1>, handshake.name = "load4"} : (!handshake.channel<i32>, !handshake.channel<i32>) -> (!handshake.channel<i32>, !handshake.channel<i32>) is feeding %40 = "handshake.cmpi"(%39#1, %38) {handshake.bb = 3 : ui32, handshake.name = "cmpi2", predicate = 1 : i64} : (!handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i1>
Operation %38 = "handshake.constant"(%37) {handshake.bb = 3 : ui32, handshake.name = "constant7", value = 0 : i32} : (!handshake.control<>) -> !handshake.channel<i32> is feeding %40 = "handshake.cmpi"(%39#1, %38) {handshake.bb = 3 : ui32, handshake.name = "cmpi2", predicate = 1 : i64} : (!handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i1>
Operation %40 = "handshake.cmpi"(%39#1, %38) {handshake.bb = 3 : ui32, handshake.name = "cmpi2", predicate = 1 : i64} : (!handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i1> is feeding %41:2 = "handshake.cond_br"(%40, %36#0) {handshake.bb = 3 : ui32, handshake.name = "cond_br12"} : (!handshake.channel<i1>, !handshake.control<>) -> (!handshake.control<>, !handshake.control<>)
Operation %36:2 = "handshake.control_merge"(%34#0) {handshake.bb = 3 : ui32, handshake.name = "control_merge2"} : (!handshake.control<>) -> (!handshake.control<>, !handshake.channel<i1>) is feeding %41:2 = "handshake.cond_br"(%40, %36#0) {handshake.bb = 3 : ui32, handshake.name = "cond_br12"} : (!handshake.channel<i1>, !handshake.control<>) -> (!handshake.control<>, !handshake.control<>)
Operation %40 = "handshake.cmpi"(%39#1, %38) {handshake.bb = 3 : ui32, handshake.name = "cmpi2", predicate = 1 : i64} : (!handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i1> is feeding "cf.cond_br"(%40)[^bb4, ^bb1] <{operandSegmentSizes = array<i32: 1, 0, 0>}> : (!handshake.channel<i1>) -> ()
Operation %26:2 = "handshake.lazy_fork"(%9) : (!handshake.control<>) -> (!handshake.control<>, !handshake.control<>) is feeding %42 = "handshake.join"(%26#0, %35#0) : (!handshake.control<>, !handshake.control<>) -> !handshake.control<>
Operation %35:2 = "handshake.lazy_fork"(%6) : (!handshake.control<>) -> (!handshake.control<>, !handshake.control<>) is feeding %42 = "handshake.join"(%26#0, %35#0) : (!handshake.control<>, !handshake.control<>) -> !handshake.control<>
    Operation %42 = "handshake.join"(%26#0, %35#0) : (!handshake.control<>, !handshake.control<>) -> !handshake.control<> is feeding %43:2 = "handshake.lazy_fork"(%42) : (!handshake.control<>) -> (!handshake.control<>, !handshake.control<>)
Operation %24 = "handshake.andi"(%23, %21) {handshake.bb = 1 : ui32, handshake.name = "andi0"} : (!handshake.channel<i1>, !handshake.channel<i1>) -> !handshake.channel<i1> is feeding %44:2 = "handshake.cond_br"(%24, %22) {handshake.bb = 4 : ui32, handshake.name = "cond_br17"} : (!handshake.channel<i1>, !handshake.channel<i32>) -> (!handshake.channel<i32>, !handshake.channel<i32>)
Operation %22 = "handshake.mux"(%14, %2, %10#0) {ftd.phi, handshake.bb = 1 : ui32, handshake.name = "mux6"} : (!handshake.channel<i1>, !handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i32> is feeding %44:2 = "handshake.cond_br"(%24, %22) {handshake.bb = 4 : ui32, handshake.name = "cond_br17"} : (!handshake.channel<i1>, !handshake.channel<i32>) -> (!handshake.channel<i32>, !handshake.channel<i32>)
Operation %41:2 = "handshake.cond_br"(%40, %36#0) {handshake.bb = 3 : ui32, handshake.name = "cond_br12"} : (!handshake.channel<i1>, !handshake.control<>) -> (!handshake.control<>, !handshake.control<>) is feeding %45:2 = "handshake.control_merge"(%41#0) {handshake.bb = 4 : ui32, handshake.name = "control_merge3"} : (!handshake.control<>) -> (!handshake.control<>, !handshake.channel<i1>)
Operation %46 = "handshake.source"() {handshake.bb = 4 : ui32, handshake.name = "source6"} : () -> !handshake.control<> is feeding %47 = "handshake.constant"(%46) {handshake.bb = 4 : ui32, handshake.name = "constant8", value = true} : (!handshake.control<>) -> !handshake.channel<i1>
Operation %48 = "handshake.source"() {handshake.bb = 4 : ui32, handshake.name = "source7"} : () -> !handshake.control<> is feeding %49 = "handshake.constant"(%48) {handshake.bb = 4 : ui32, handshake.name = "constant9", value = 1 : i32} : (!handshake.control<>) -> !handshake.channel<i32>
Operation %44:2 = "handshake.cond_br"(%24, %22) {handshake.bb = 4 : ui32, handshake.name = "cond_br17"} : (!handshake.channel<i1>, !handshake.channel<i32>) -> (!handshake.channel<i32>, !handshake.channel<i32>) is feeding %50:2 = "handshake.load"(%44#0, %0#2) {handshake.bb = 4 : ui32, handshake.deps = #handshake<deps[<"store1" (0)>]>, handshake.mem_interface = #handshake.mem_interface<LSQ: 2>, handshake.name = "load5"} : (!handshake.channel<i32>, !handshake.channel<i32>) -> (!handshake.channel<i32>, !handshake.channel<i32>)
Operation %0:4 = "handshake.lsq"(%arg0, %arg2, %26#1, %32#0, %35#1, %39#0, %43#1, %50#0, %52#0, %52#1, %55#0) {groupSizes = [1 : i32, 1 : i32, 2 : i32], handshake.name = "lsq1"} : (memref<10xi32>, !handshake.control<>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>) -> (!handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>) is feeding %50:2 = "handshake.load"(%44#0, %0#2) {handshake.bb = 4 : ui32, handshake.deps = #handshake<deps[<"store1" (0)>]>, handshake.mem_interface = #handshake.mem_interface<LSQ: 2>, handshake.name = "load5"} : (!handshake.channel<i32>, !handshake.channel<i32>) -> (!handshake.channel<i32>, !handshake.channel<i32>)
Operation %50:2 = "handshake.load"(%44#0, %0#2) {handshake.bb = 4 : ui32, handshake.deps = #handshake<deps[<"store1" (0)>]>, handshake.mem_interface = #handshake.mem_interface<LSQ: 2>, handshake.name = "load5"} : (!handshake.channel<i32>, !handshake.channel<i32>) -> (!handshake.channel<i32>, !handshake.channel<i32>) is feeding %51 = "handshake.addi"(%50#1, %49) {handshake.bb = 4 : ui32, handshake.name = "addi0"} : (!handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i32>
Operation %49 = "handshake.constant"(%48) {handshake.bb = 4 : ui32, handshake.name = "constant9", value = 1 : i32} : (!handshake.control<>) -> !handshake.channel<i32> is feeding %51 = "handshake.addi"(%50#1, %49) {handshake.bb = 4 : ui32, handshake.name = "addi0"} : (!handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i32>
Operation %44:2 = "handshake.cond_br"(%24, %22) {handshake.bb = 4 : ui32, handshake.name = "cond_br17"} : (!handshake.channel<i1>, !handshake.channel<i32>) -> (!handshake.channel<i32>, !handshake.channel<i32>) is feeding %52:2 = "handshake.store"(%44#0, %51) {handshake.bb = 4 : ui32, handshake.deps = #handshake<deps[<"load3" (0)>, <"load4" (0)>, <"load5" (0)>, <"store1" (0)>]>, handshake.mem_interface = #handshake.mem_interface<LSQ: 2>, handshake.name = "store1"} : (!handshake.channel<i32>, !handshake.channel<i32>) -> (!handshake.channel<i32>, !handshake.channel<i32>)
Operation %51 = "handshake.addi"(%50#1, %49) {handshake.bb = 4 : ui32, handshake.name = "addi0"} : (!handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i32> is feeding %52:2 = "handshake.store"(%44#0, %51) {handshake.bb = 4 : ui32, handshake.deps = #handshake<deps[<"load3" (0)>, <"load4" (0)>, <"load5" (0)>, <"store1" (0)>]>, handshake.mem_interface = #handshake.mem_interface<LSQ: 2>, handshake.name = "store1"} : (!handshake.channel<i32>, !handshake.channel<i32>) -> (!handshake.channel<i32>, !handshake.channel<i32>)
Operation %44:2 = "handshake.cond_br"(%24, %22) {handshake.bb = 4 : ui32, handshake.name = "cond_br17"} : (!handshake.channel<i1>, !handshake.channel<i32>) -> (!handshake.channel<i32>, !handshake.channel<i32>) is feeding %53 = "handshake.addi"(%44#0, %49) {handshake.bb = 4 : ui32, handshake.name = "addi1"} : (!handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i32>
Operation %49 = "handshake.constant"(%48) {handshake.bb = 4 : ui32, handshake.name = "constant9", value = 1 : i32} : (!handshake.control<>) -> !handshake.channel<i32> is feeding %53 = "handshake.addi"(%44#0, %49) {handshake.bb = 4 : ui32, handshake.name = "addi1"} : (!handshake.channel<i32>, !handshake.channel<i32>) -> !handshake.channel<i32>
Operation %45:2 = "handshake.control_merge"(%41#0) {handshake.bb = 4 : ui32, handshake.name = "control_merge3"} : (!handshake.control<>) -> (!handshake.control<>, !handshake.channel<i1>) is feeding %54 = "handshake.br"(%45#0) {handshake.bb = 4 : ui32, handshake.name = "br2"} : (!handshake.control<>) -> !handshake.control<>
Operation %25:2 = "handshake.cond_br"(%24, %16#0) {handshake.bb = 1 : ui32, handshake.name = "cond_br6"} : (!handshake.channel<i1>, !handshake.control<>) -> (!handshake.control<>, !handshake.control<>) is feeding %55:2 = "handshake.control_merge"(%25#1) {handshake.bb = 5 : ui32, handshake.name = "control_merge4"} : (!handshake.control<>) -> (!handshake.control<>, !handshake.channel<i1>)
Operation %0:4 = "handshake.lsq"(%arg0, %arg2, %26#1, %32#0, %35#1, %39#0, %43#1, %50#0, %52#0, %52#1, %55#0) {groupSizes = [1 : i32, 1 : i32, 2 : i32], handshake.name = "lsq1"} : (memref<10xi32>, !handshake.control<>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.control<>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>) -> (!handshake.channel<i32>, !handshake.channel<i32>, !handshake.channel<i32>, !handshake.control<>) is feeding "handshake.end"(%0#3, %arg3) {handshake.bb = 5 : ui32, handshake.name = "end0"} : (!handshake.control<>, !handshake.control<>) -> ()
Operation null is feeding "handshake.end"(%0#3, %arg3) {handshake.bb = 5 : ui32, handshake.name = "end0"} : (!handshake.control<>, !handshake.control<>) -> ()

