module {
  hw.module @iterative_sqrt(in %n : !handshake.channel<i32>, in %start : !handshake.control<>, in %clk : i1, in %rst : i1, out out0 : !handshake.channel<i32>, out end : !handshake.control<>) {
    %fork0.outs_0, %fork0.outs_1 = hw.instance "fork0" @handshake_fork_0(ins: %start: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.control<>, outs_1: !handshake.control<>)
    %fork1.outs_0, %fork1.outs_1 = hw.instance "fork1" @handshake_fork_1(ins: %n: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>)
    %source0.outs = hw.instance "source0" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant2.outs = hw.instance "constant2" @handshake_constant_0(ctrl: %source0.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %extsi0.outs = hw.instance "extsi0" @handshake_extsi_0(ins: %constant2.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %source1.outs = hw.instance "source1" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant3.outs = hw.instance "constant3" @handshake_constant_1(ctrl: %source1.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %fork2.outs_0, %fork2.outs_1 = hw.instance "fork2" @handshake_fork_2(ins: %constant3.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>)
    %buffer8.outs = hw.instance "buffer8" @handshake_buffer_0(ins: %mux6.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer9.outs = hw.instance "buffer9" @handshake_buffer_1(ins: %buffer8.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %cond_br39.trueOut, %cond_br39.falseOut = hw.instance "cond_br39" @handshake_cond_br_0(condition: %fork11.outs_6: !handshake.channel<i1>, data: %buffer9.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    hw.instance "sink0" @handshake_sink_0(ins: %cond_br39.falseOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> ()
    %buffer4.outs = hw.instance "buffer4" @handshake_buffer_0(ins: %mux4.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer5.outs = hw.instance "buffer5" @handshake_buffer_1(ins: %buffer4.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %cond_br40.trueOut, %cond_br40.falseOut = hw.instance "cond_br40" @handshake_cond_br_0(condition: %fork11.outs_7: !handshake.channel<i1>, data: %buffer5.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    hw.instance "sink1" @handshake_sink_0(ins: %cond_br40.falseOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> ()
    %cond_br41.trueOut, %cond_br41.falseOut = hw.instance "cond_br41" @handshake_cond_br_1(condition: %fork11.outs_8: !handshake.channel<i1>, data: %ori1.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i1>, falseOut: !handshake.channel<i1>)
    %constant1.outs = hw.instance "constant1" @handshake_constant_0(ctrl: %fork0.outs_1: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %fork3.outs_0, %fork3.outs_1 = hw.instance "fork3" @handshake_fork_2(ins: %constant1.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>)
    %extsi1.outs = hw.instance "extsi1" @handshake_extsi_0(ins: %fork3.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %merge0.outs = hw.instance "merge0" @handshake_merge_0(ins_0: %fork3.outs_0: !handshake.channel<i1>, ins_1: %fork11.outs_9: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer0.outs = hw.instance "buffer0" @handshake_buffer_2(ins: %merge0.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer1.outs = hw.instance "buffer1" @handshake_buffer_3(ins: %buffer0.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %fork4.outs_0, %fork4.outs_1, %fork4.outs_2, %fork4.outs_3, %fork4.outs_4, %fork4.outs_5 = hw.instance "fork4" @handshake_fork_3(ins: %buffer1.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>, outs_3: !handshake.channel<i1>, outs_4: !handshake.channel<i1>, outs_5: !handshake.channel<i1>)
    %mux0.outs = hw.instance "mux0" @handshake_mux_0(index: %fork4.outs_5: !handshake.channel<i1>, ins_0: %fork1.outs_1: !handshake.channel<i32>, ins_1: %fork18.outs_1: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer2.outs = hw.instance "buffer2" @handshake_buffer_0(ins: %mux0.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer3.outs = hw.instance "buffer3" @handshake_buffer_1(ins: %buffer2.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %fork5.outs_0, %fork5.outs_1 = hw.instance "fork5" @handshake_fork_1(ins: %buffer3.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>)
    %buffer6.outs = hw.instance "buffer6" @handshake_buffer_0(ins: %mux5.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer7.outs = hw.instance "buffer7" @handshake_buffer_1(ins: %buffer6.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %mux4.outs = hw.instance "mux4" @handshake_mux_0(index: %fork17.outs_1: !handshake.channel<i1>, ins_0: %buffer7.outs: !handshake.channel<i32>, ins_1: %fork8.outs_3: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %mux5.outs = hw.instance "mux5" @handshake_mux_0(index: %fork19.outs_1: !handshake.channel<i1>, ins_0: %fork8.outs_4: !handshake.channel<i32>, ins_1: %addi2.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer10.outs = hw.instance "buffer10" @handshake_buffer_0(ins: %mux7.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer11.outs = hw.instance "buffer11" @handshake_buffer_1(ins: %buffer10.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %mux6.outs = hw.instance "mux6" @handshake_mux_0(index: %fork17.outs_2: !handshake.channel<i1>, ins_0: %buffer11.outs: !handshake.channel<i32>, ins_1: %fork9.outs_3: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %mux7.outs = hw.instance "mux7" @handshake_mux_0(index: %fork19.outs_2: !handshake.channel<i1>, ins_0: %addi3.result: !handshake.channel<i32>, ins_1: %fork9.outs_4: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %mux8.outs = hw.instance "mux8" @handshake_mux_1(index: %fork4.outs_4: !handshake.channel<i1>, ins_0: %fork2.outs_1: !handshake.channel<i1>, ins_1: %ori2.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer12.outs = hw.instance "buffer12" @handshake_buffer_2(ins: %mux8.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer13.outs = hw.instance "buffer13" @handshake_buffer_3(ins: %buffer12.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %fork6.outs_0, %fork6.outs_1, %fork6.outs_2 = hw.instance "fork6" @handshake_fork_4(ins: %buffer13.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>)
    %mux9.outs = hw.instance "mux9" @handshake_mux_0(index: %fork4.outs_3: !handshake.channel<i1>, ins_0: %extsi1.outs: !handshake.channel<i32>, ins_1: %select0.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %mux10.outs = hw.instance "mux10" @handshake_mux_1(index: %fork4.outs_2: !handshake.channel<i1>, ins_0: %fork2.outs_0: !handshake.channel<i1>, ins_1: %cond_br41.trueOut: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer16.outs = hw.instance "buffer16" @handshake_buffer_2(ins: %mux10.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer17.outs = hw.instance "buffer17" @handshake_buffer_3(ins: %buffer16.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %fork7.outs_0, %fork7.outs_1, %fork7.outs_2 = hw.instance "fork7" @handshake_fork_4(ins: %buffer17.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>)
    %mux11.outs = hw.instance "mux11" @handshake_mux_0(index: %fork4.outs_1: !handshake.channel<i1>, ins_0: %extsi0.outs: !handshake.channel<i32>, ins_1: %cond_br40.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer18.outs = hw.instance "buffer18" @handshake_buffer_0(ins: %mux11.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer19.outs = hw.instance "buffer19" @handshake_buffer_1(ins: %buffer18.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %fork8.outs_0, %fork8.outs_1, %fork8.outs_2, %fork8.outs_3, %fork8.outs_4 = hw.instance "fork8" @handshake_fork_5(ins: %buffer19.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>, outs_2: !handshake.channel<i32>, outs_3: !handshake.channel<i32>, outs_4: !handshake.channel<i32>)
    %mux12.outs = hw.instance "mux12" @handshake_mux_0(index: %fork4.outs_0: !handshake.channel<i1>, ins_0: %fork1.outs_0: !handshake.channel<i32>, ins_1: %cond_br39.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer20.outs = hw.instance "buffer20" @handshake_buffer_0(ins: %mux12.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer21.outs = hw.instance "buffer21" @handshake_buffer_1(ins: %buffer20.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %fork9.outs_0, %fork9.outs_1, %fork9.outs_2, %fork9.outs_3, %fork9.outs_4 = hw.instance "fork9" @handshake_fork_5(ins: %buffer21.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>, outs_2: !handshake.channel<i32>, outs_3: !handshake.channel<i32>, outs_4: !handshake.channel<i32>)
    %source2.outs = hw.instance "source2" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant4.outs = hw.instance "constant4" @handshake_constant_1(ctrl: %source2.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %fork10.outs_0, %fork10.outs_1 = hw.instance "fork10" @handshake_fork_2(ins: %constant4.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>)
    %source3.outs = hw.instance "source3" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant9.outs = hw.instance "constant9" @handshake_constant_2(ctrl: %source3.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i2>)
    %extsi2.outs = hw.instance "extsi2" @handshake_extsi_1(ins: %constant9.outs: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %cmpi0.result = hw.instance "cmpi0" @handshake_cmpi_0(lhs: %fork8.outs_2: !handshake.channel<i32>, rhs: %fork9.outs_2: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %andi0.result = hw.instance "andi0" @handshake_andi_0(lhs: %cmpi0.result: !handshake.channel<i1>, rhs: %fork6.outs_2: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %fork11.outs_0, %fork11.outs_1, %fork11.outs_2, %fork11.outs_3, %fork11.outs_4, %fork11.outs_5, %fork11.outs_6, %fork11.outs_7, %fork11.outs_8, %fork11.outs_9 = hw.instance "fork11" @handshake_fork_6(ins: %andi0.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>, outs_3: !handshake.channel<i1>, outs_4: !handshake.channel<i1>, outs_5: !handshake.channel<i1>, outs_6: !handshake.channel<i1>, outs_7: !handshake.channel<i1>, outs_8: !handshake.channel<i1>, outs_9: !handshake.channel<i1>)
    %addi0.result = hw.instance "addi0" @handshake_addi_0(lhs: %fork8.outs_1: !handshake.channel<i32>, rhs: %fork9.outs_1: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %shrsi0.result = hw.instance "shrsi0" @handshake_shrsi_0(lhs: %addi0.result: !handshake.channel<i32>, rhs: %extsi2.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %fork12.outs_0, %fork12.outs_1 = hw.instance "fork12" @handshake_fork_1(ins: %shrsi0.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>)
    %muli0.result = hw.instance "muli0" @handshake_muli_0(lhs: %fork12.outs_0: !handshake.channel<i32>, rhs: %fork12.outs_1: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %cmpi1.result = hw.instance "cmpi1" @handshake_cmpi_1(lhs: %muli0.result: !handshake.channel<i32>, rhs: %fork5.outs_1: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %andi1.result = hw.instance "andi1" @handshake_andi_0(lhs: %cmpi1.result: !handshake.channel<i1>, rhs: %fork7.outs_2: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %xori0.result = hw.instance "xori0" @handshake_xori_0(lhs: %fork6.outs_1: !handshake.channel<i1>, rhs: %fork10.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %andi2.result = hw.instance "andi2" @handshake_andi_0(lhs: %fork6.outs_0: !handshake.channel<i1>, rhs: %andi1.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %andi3.result = hw.instance "andi3" @handshake_andi_0(lhs: %xori0.result: !handshake.channel<i1>, rhs: %fork7.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %ori0.result = hw.instance "ori0" @handshake_ori_0(lhs: %andi2.result: !handshake.channel<i1>, rhs: %andi3.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %xori1.result = hw.instance "xori1" @handshake_xori_0(lhs: %fork11.outs_5: !handshake.channel<i1>, rhs: %fork10.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %andi4.result = hw.instance "andi4" @handshake_andi_0(lhs: %fork11.outs_4: !handshake.channel<i1>, rhs: %ori0.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %andi5.result = hw.instance "andi5" @handshake_andi_0(lhs: %xori1.result: !handshake.channel<i1>, rhs: %fork7.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %ori1.result = hw.instance "ori1" @handshake_ori_0(lhs: %andi4.result: !handshake.channel<i1>, rhs: %andi5.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %buffer14.outs = hw.instance "buffer14" @handshake_buffer_0(ins: %mux9.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer15.outs = hw.instance "buffer15" @handshake_buffer_1(ins: %buffer14.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %cond_br42.trueOut, %cond_br42.falseOut = hw.instance "cond_br42" @handshake_cond_br_0(condition: %fork11.outs_3: !handshake.channel<i1>, data: %buffer15.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    %cond_br43.trueOut, %cond_br43.falseOut = hw.instance "cond_br43" @handshake_cond_br_0(condition: %fork11.outs_2: !handshake.channel<i1>, data: %fork8.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    hw.instance "sink2" @handshake_sink_0(ins: %cond_br43.falseOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> ()
    %fork13.outs_0, %fork13.outs_1, %fork13.outs_2 = hw.instance "fork13" @handshake_fork_7(ins: %cond_br43.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>, outs_2: !handshake.channel<i32>)
    %cond_br44.trueOut, %cond_br44.falseOut = hw.instance "cond_br44" @handshake_cond_br_0(condition: %fork11.outs_1: !handshake.channel<i1>, data: %fork9.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    %fork14.outs_0, %fork14.outs_1, %fork14.outs_2 = hw.instance "fork14" @handshake_fork_7(ins: %cond_br44.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>, outs_2: !handshake.channel<i32>)
    %source8.outs = hw.instance "source8" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant10.outs = hw.instance "constant10" @handshake_constant_2(ctrl: %source8.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i2>)
    %extsi3.outs = hw.instance "extsi3" @handshake_extsi_1(ins: %constant10.outs: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %addi1.result = hw.instance "addi1" @handshake_addi_0(lhs: %fork13.outs_2: !handshake.channel<i32>, rhs: %fork14.outs_2: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %shrsi1.result = hw.instance "shrsi1" @handshake_shrsi_0(lhs: %addi1.result: !handshake.channel<i32>, rhs: %extsi3.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %fork15.outs_0, %fork15.outs_1, %fork15.outs_2, %fork15.outs_3 = hw.instance "fork15" @handshake_fork_8(ins: %shrsi1.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>, outs_2: !handshake.channel<i32>, outs_3: !handshake.channel<i32>)
    %muli1.result = hw.instance "muli1" @handshake_muli_0(lhs: %fork15.outs_2: !handshake.channel<i32>, rhs: %fork15.outs_3: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %fork16.outs_0, %fork16.outs_1, %fork16.outs_2 = hw.instance "fork16" @handshake_fork_7(ins: %muli1.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>, outs_2: !handshake.channel<i32>)
    %cmpi2.result = hw.instance "cmpi2" @handshake_cmpi_1(lhs: %fork16.outs_2: !handshake.channel<i32>, rhs: %fork18.outs_2: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %cmpi3.result = hw.instance "cmpi3" @handshake_cmpi_0(lhs: %fork13.outs_1: !handshake.channel<i32>, rhs: %fork14.outs_1: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %cmpi4.result = hw.instance "cmpi4" @handshake_cmpi_2(lhs: %fork13.outs_0: !handshake.channel<i32>, rhs: %fork14.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %cmpi5.result = hw.instance "cmpi5" @handshake_cmpi_3(lhs: %fork16.outs_1: !handshake.channel<i32>, rhs: %fork18.outs_3: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %fork17.outs_0, %fork17.outs_1, %fork17.outs_2 = hw.instance "fork17" @handshake_fork_4(ins: %cmpi5.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>)
    %andi6.result = hw.instance "andi6" @handshake_andi_0(lhs: %cmpi3.result: !handshake.channel<i1>, rhs: %cmpi2.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %select0.result = hw.instance "select0" @handshake_select_0(condition: %fork17.outs_0: !handshake.channel<i1>, trueValue: %fork15.outs_1: !handshake.channel<i32>, falseValue: %cond_br42.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %ori2.result = hw.instance "ori2" @handshake_ori_0(lhs: %andi6.result: !handshake.channel<i1>, rhs: %cmpi4.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %cond_br45.trueOut, %cond_br45.falseOut = hw.instance "cond_br45" @handshake_cond_br_0(condition: %fork11.outs_0: !handshake.channel<i1>, data: %fork5.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    hw.instance "sink3" @handshake_sink_0(ins: %cond_br45.falseOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> ()
    %fork18.outs_0, %fork18.outs_1, %fork18.outs_2, %fork18.outs_3 = hw.instance "fork18" @handshake_fork_8(ins: %cond_br45.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>, outs_2: !handshake.channel<i32>, outs_3: !handshake.channel<i32>)
    %cmpi6.result = hw.instance "cmpi6" @handshake_cmpi_4(lhs: %fork16.outs_0: !handshake.channel<i32>, rhs: %fork18.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %fork19.outs_0, %fork19.outs_1, %fork19.outs_2 = hw.instance "fork19" @handshake_fork_4(ins: %cmpi6.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>)
    %cond_br46.trueOut, %cond_br46.falseOut = hw.instance "cond_br46" @handshake_cond_br_0(condition: %fork19.outs_0: !handshake.channel<i1>, data: %fork15.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    %source9.outs = hw.instance "source9" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant11.outs = hw.instance "constant11" @handshake_constant_2(ctrl: %source9.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i2>)
    %extsi4.outs = hw.instance "extsi4" @handshake_extsi_1(ins: %constant11.outs: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %addi2.result = hw.instance "addi2" @handshake_addi_0(lhs: %cond_br46.trueOut: !handshake.channel<i32>, rhs: %extsi4.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %source10.outs = hw.instance "source10" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant8.outs = hw.instance "constant8" @handshake_constant_3(ctrl: %source10.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %addi3.result = hw.instance "addi3" @handshake_addi_0(lhs: %cond_br46.falseOut: !handshake.channel<i32>, rhs: %constant8.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %select1.result = hw.instance "select1" @handshake_select_0(condition: %cond_br41.falseOut: !handshake.channel<i1>, trueValue: %cond_br44.falseOut: !handshake.channel<i32>, falseValue: %cond_br42.falseOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    hw.output %select1.result, %fork0.outs_0 : !handshake.channel<i32>, !handshake.control<>
  }
  hw.module.extern @handshake_fork_0(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.control<>, out outs_1 : !handshake.control<>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.control<>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_fork_1(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_source_0(in %clk : i1, in %rst : i1, out outs : !handshake.control<>) attributes {hw.name = "handshake.source", hw.parameters = {}}
  hw.module.extern @handshake_constant_0(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 1 : ui32, VALUE = "0"}}
  hw.module.extern @handshake_extsi_0(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i1>, OUTPUT_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_constant_1(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 1 : ui32, VALUE = "1"}}
  hw.module.extern @handshake_fork_2(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_0(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<i32>, NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 1, V: 1, R: 0}>}}
  hw.module.extern @handshake_buffer_1(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.channel<i32>, NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 0, V: 0, R: 1}>}}
  hw.module.extern @handshake_cond_br_0(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i32>, out falseOut : !handshake.channel<i32>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_sink_0(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_cond_br_1(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i1>, out falseOut : !handshake.channel<i1>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<i1>}}
  hw.module.extern @handshake_merge_0(in %ins_0 : !handshake.channel<i1>, in %ins_1 : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.merge", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_2(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<i1>, NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 1, V: 1, R: 0}>}}
  hw.module.extern @handshake_buffer_3(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.channel<i1>, NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 0, V: 0, R: 1}>}}
  hw.module.extern @handshake_fork_3(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>, out outs_2 : !handshake.channel<i1>, out outs_3 : !handshake.channel<i1>, out outs_4 : !handshake.channel<i1>, out outs_5 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 6 : ui32}}
  hw.module.extern @handshake_mux_0(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.channel<i32>, in %ins_1 : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_mux_1(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.channel<i1>, in %ins_1 : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_fork_4(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>, out outs_2 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 3 : ui32}}
  hw.module.extern @handshake_fork_5(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>, out outs_2 : !handshake.channel<i32>, out outs_3 : !handshake.channel<i32>, out outs_4 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, SIZE = 5 : ui32}}
  hw.module.extern @handshake_constant_2(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i2>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 2 : ui32, VALUE = "01"}}
  hw.module.extern @handshake_extsi_1(in %ins : !handshake.channel<i2>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i2>, OUTPUT_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_cmpi_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.cmpi", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, PREDICATE = "sle"}}
  hw.module.extern @handshake_andi_0(in %lhs : !handshake.channel<i1>, in %rhs : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.andi", hw.parameters = {DATA_TYPE = !handshake.channel<i1>}}
  hw.module.extern @handshake_fork_6(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>, out outs_2 : !handshake.channel<i1>, out outs_3 : !handshake.channel<i1>, out outs_4 : !handshake.channel<i1>, out outs_5 : !handshake.channel<i1>, out outs_6 : !handshake.channel<i1>, out outs_7 : !handshake.channel<i1>, out outs_8 : !handshake.channel<i1>, out outs_9 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 10 : ui32}}
  hw.module.extern @handshake_addi_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.addi", hw.parameters = {DATA_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_shrsi_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.shrsi", hw.parameters = {DATA_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_muli_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.muli", hw.parameters = {DATA_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_cmpi_1(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.cmpi", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, PREDICATE = "ne"}}
  hw.module.extern @handshake_xori_0(in %lhs : !handshake.channel<i1>, in %rhs : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.xori", hw.parameters = {DATA_TYPE = !handshake.channel<i1>}}
  hw.module.extern @handshake_ori_0(in %lhs : !handshake.channel<i1>, in %rhs : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.ori", hw.parameters = {DATA_TYPE = !handshake.channel<i1>}}
  hw.module.extern @handshake_fork_7(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>, out outs_2 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, SIZE = 3 : ui32}}
  hw.module.extern @handshake_fork_8(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>, out outs_2 : !handshake.channel<i32>, out outs_3 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, SIZE = 4 : ui32}}
  hw.module.extern @handshake_cmpi_2(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.cmpi", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, PREDICATE = "sgt"}}
  hw.module.extern @handshake_cmpi_3(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.cmpi", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, PREDICATE = "eq"}}
  hw.module.extern @handshake_select_0(in %condition : !handshake.channel<i1>, in %trueValue : !handshake.channel<i32>, in %falseValue : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.select", hw.parameters = {DATA_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_cmpi_4(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.cmpi", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, PREDICATE = "slt"}}
  hw.module.extern @handshake_constant_3(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 32 : ui32, VALUE = "11111111111111111111111111111111"}}
  hw.module @iterative_sqrt_wrapper(in %n : !handshake.channel<i32>, in %start : !handshake.control<>, in %clk : i1, in %rst : i1, out out0 : !handshake.channel<i32>, out end : !handshake.control<>) {
    %iterative_sqrt_wrapped.out0, %iterative_sqrt_wrapped.end = hw.instance "iterative_sqrt_wrapped" @iterative_sqrt(n: %n: !handshake.channel<i32>, start: %start: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (out0: !handshake.channel<i32>, end: !handshake.control<>)
    hw.output %iterative_sqrt_wrapped.out0, %iterative_sqrt_wrapped.end : !handshake.channel<i32>, !handshake.control<>
  }
}

