module {
  hw.module @bisection(in %a : !handshake.channel<i32>, in %b : !handshake.channel<i32>, in %tol : !handshake.channel<i32>, in %start : !handshake.control<>, in %clk : i1, in %rst : i1, out out0 : !handshake.channel<i32>, out end : !handshake.control<>) {
    %fork0.outs_0, %fork0.outs_1, %fork0.outs_2 = hw.instance "fork0" @handshake_fork_0(ins: %start: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.control<>, outs_1: !handshake.control<>, outs_2: !handshake.control<>)
    %fork1.outs_0, %fork1.outs_1, %fork1.outs_2 = hw.instance "fork1" @handshake_fork_1(ins: %a: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>, outs_2: !handshake.channel<i32>)
    %constant0.outs = hw.instance "constant0" @handshake_constant_0(ctrl: %fork0.outs_0: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %source0.outs = hw.instance "source0" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant5.outs = hw.instance "constant5" @handshake_constant_1(ctrl: %source0.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %mulf0.result = hw.instance "mulf0" @handshake_mulf_0(lhs: %fork1.outs_1: !handshake.channel<i32>, rhs: %fork1.outs_2: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %addf0.result = hw.instance "addf0" @handshake_addf_0(lhs: %mulf0.result: !handshake.channel<i32>, rhs: %constant5.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %extsi3.outs = hw.instance "extsi3" @handshake_extsi_0(ins: %constant0.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8>)
    %mux0.outs = hw.instance "mux0" @handshake_mux_0(index: %fork5.outs_1: !handshake.channel<i1>, ins_0: %fork1.outs_0: !handshake.channel<i32>, ins_1: %cond_br19.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer0.outs = hw.instance "buffer0" @handshake_buffer_0(ins: %mux0.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %fork2.outs_0, %fork2.outs_1 = hw.instance "fork2" @handshake_fork_2(ins: %buffer0.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>)
    %mux1.outs = hw.instance "mux1" @handshake_mux_1(index: %fork5.outs_2: !handshake.channel<i1>, ins_0: %b: !handshake.channel<i32>, ins_1: %cond_br20.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer2.outs = hw.instance "buffer2" @handshake_buffer_1(ins: %mux1.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %fork3.outs_0, %fork3.outs_1 = hw.instance "fork3" @handshake_fork_3(ins: %buffer2.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>)
    %mux2.outs = hw.instance "mux2" @handshake_mux_2(index: %fork5.outs_0: !handshake.channel<i1>, ins_0: %extsi3.outs: !handshake.channel<i8>, ins_1: %cond_br21.trueOut: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8>)
    %mux3.outs = hw.instance "mux3" @handshake_mux_3(index: %fork5.outs_3: !handshake.channel<i1>, ins_0: %addf0.result: !handshake.channel<i32>, ins_1: %cond_br22.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %mux4.outs = hw.instance "mux4" @handshake_mux_4(index: %fork5.outs_4: !handshake.channel<i1>, ins_0: %tol: !handshake.channel<i32>, ins_1: %cond_br23.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer8.outs = hw.instance "buffer8" @handshake_buffer_2(ins: %mux4.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer9.outs = hw.instance "buffer9" @handshake_buffer_3(ins: %buffer8.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %fork4.outs_0, %fork4.outs_1 = hw.instance "fork4" @handshake_fork_4(ins: %buffer9.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>)
    %control_merge0.outs, %control_merge0.index = hw.instance "control_merge0" @handshake_control_merge_0(ins_0: %fork0.outs_2: !handshake.control<>, ins_1: %cond_br24.trueOut: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>, index: !handshake.channel<i1>)
    %fork5.outs_0, %fork5.outs_1, %fork5.outs_2, %fork5.outs_3, %fork5.outs_4 = hw.instance "fork5" @handshake_fork_5(ins: %control_merge0.index: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>, outs_3: !handshake.channel<i1>, outs_4: !handshake.channel<i1>)
    %source1.outs = hw.instance "source1" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant6.outs = hw.instance "constant6" @handshake_constant_2(ctrl: %source1.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %source2.outs = hw.instance "source2" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant7.outs = hw.instance "constant7" @handshake_constant_3(ctrl: %source2.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %addf1.result = hw.instance "addf1" @handshake_addf_1(lhs: %fork2.outs_1: !handshake.channel<i32>, rhs: %fork3.outs_1: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %mulf1.result = hw.instance "mulf1" @handshake_mulf_1(lhs: %addf1.result: !handshake.channel<i32>, rhs: %constant7.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %fork6.outs_0, %fork6.outs_1, %fork6.outs_2 = hw.instance "fork6" @handshake_fork_6(ins: %mulf1.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>, outs_2: !handshake.channel<i32>)
    %mulf2.result = hw.instance "mulf2" @handshake_mulf_2(lhs: %fork6.outs_1: !handshake.channel<i32>, rhs: %fork6.outs_2: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %addf2.result = hw.instance "addf2" @handshake_addf_2(lhs: %mulf2.result: !handshake.channel<i32>, rhs: %constant6.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %fork7.outs_0, %fork7.outs_1 = hw.instance "fork7" @handshake_fork_7(ins: %addf2.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>)
    %absf0.outs = hw.instance "absf0" @handshake_absf_0(ins: %fork7.outs_1: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %cmpf0.result = hw.instance "cmpf0" @handshake_cmpf_0(lhs: %absf0.outs: !handshake.channel<i32>, rhs: %fork4.outs_1: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %fork8.outs_0, %fork8.outs_1, %fork8.outs_2, %fork8.outs_3, %fork8.outs_4, %fork8.outs_5, %fork8.outs_6, %fork8.outs_7 = hw.instance "fork8" @handshake_fork_8(ins: %cmpf0.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>, outs_3: !handshake.channel<i1>, outs_4: !handshake.channel<i1>, outs_5: !handshake.channel<i1>, outs_6: !handshake.channel<i1>, outs_7: !handshake.channel<i1>)
    %buffer11.outs = hw.instance "buffer11" @handshake_buffer_4(ins: %fork6.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer14.outs = hw.instance "buffer14" @handshake_buffer_5(ins: %fork8.outs_7: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %cond_br3.trueOut, %cond_br3.falseOut = hw.instance "cond_br3" @handshake_cond_br_0(condition: %buffer14.outs: !handshake.channel<i1>, data: %buffer11.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    %buffer10.outs = hw.instance "buffer10" @handshake_buffer_6(ins: %control_merge0.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %buffer13.outs = hw.instance "buffer13" @handshake_buffer_7(ins: %fork8.outs_6: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %cond_br4.trueOut, %cond_br4.falseOut = hw.instance "cond_br4" @handshake_cond_br_1(condition: %buffer13.outs: !handshake.channel<i1>, data: %buffer10.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.control<>, falseOut: !handshake.control<>)
    %cond_br5.trueOut, %cond_br5.falseOut = hw.instance "cond_br5" @handshake_cond_br_2(condition: %fork8.outs_5: !handshake.channel<i1>, data: %fork4.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    hw.instance "sink0" @handshake_sink_0(ins: %cond_br5.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> ()
    %buffer1.outs = hw.instance "buffer1" @handshake_buffer_8(ins: %fork2.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %cond_br6.trueOut, %cond_br6.falseOut = hw.instance "cond_br6" @handshake_cond_br_3(condition: %fork8.outs_4: !handshake.channel<i1>, data: %buffer1.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    hw.instance "sink1" @handshake_sink_1(ins: %cond_br6.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> ()
    %buffer3.outs = hw.instance "buffer3" @handshake_buffer_9(ins: %fork3.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %cond_br7.trueOut, %cond_br7.falseOut = hw.instance "cond_br7" @handshake_cond_br_4(condition: %fork8.outs_3: !handshake.channel<i1>, data: %buffer3.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    hw.instance "sink2" @handshake_sink_2(ins: %cond_br7.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> ()
    %buffer4.outs = hw.instance "buffer4" @handshake_buffer_10(ins: %mux2.outs: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8>)
    %buffer5.outs = hw.instance "buffer5" @handshake_buffer_11(ins: %buffer4.outs: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8>)
    %buffer12.outs = hw.instance "buffer12" @handshake_buffer_5(ins: %fork8.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %cond_br8.trueOut, %cond_br8.falseOut = hw.instance "cond_br8" @handshake_cond_br_5(condition: %buffer12.outs: !handshake.channel<i1>, data: %buffer5.outs: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i8>, falseOut: !handshake.channel<i8>)
    hw.instance "sink3" @handshake_sink_3(ins: %cond_br8.trueOut: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> ()
    %buffer6.outs = hw.instance "buffer6" @handshake_buffer_12(ins: %mux3.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer7.outs = hw.instance "buffer7" @handshake_buffer_13(ins: %buffer6.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %cond_br9.trueOut, %cond_br9.falseOut = hw.instance "cond_br9" @handshake_cond_br_6(condition: %fork8.outs_2: !handshake.channel<i1>, data: %buffer7.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    hw.instance "sink4" @handshake_sink_4(ins: %cond_br9.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> ()
    %cond_br10.trueOut, %cond_br10.falseOut = hw.instance "cond_br10" @handshake_cond_br_7(condition: %fork8.outs_1: !handshake.channel<i1>, data: %fork7.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    hw.instance "sink5" @handshake_sink_5(ins: %cond_br10.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> ()
    %buffer15.outs = hw.instance "buffer15" @handshake_buffer_14(ins: %cond_br5.falseOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %fork9.outs_0, %fork9.outs_1 = hw.instance "fork9" @handshake_fork_9(ins: %buffer15.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>)
    %fork10.outs_0, %fork10.outs_1 = hw.instance "fork10" @handshake_fork_10(ins: %cond_br6.falseOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>)
    %fork11.outs_0, %fork11.outs_1 = hw.instance "fork11" @handshake_fork_11(ins: %cond_br7.falseOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>)
    %source3.outs = hw.instance "source3" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant8.outs = hw.instance "constant8" @handshake_constant_4(ctrl: %source3.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %subf0.result = hw.instance "subf0" @handshake_subf_0(lhs: %fork11.outs_1: !handshake.channel<i32>, rhs: %fork10.outs_1: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %mulf3.result = hw.instance "mulf3" @handshake_mulf_3(lhs: %subf0.result: !handshake.channel<i32>, rhs: %constant8.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %cmpf1.result = hw.instance "cmpf1" @handshake_cmpf_1(lhs: %mulf3.result: !handshake.channel<i32>, rhs: %fork9.outs_1: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %fork12.outs_0, %fork12.outs_1, %fork12.outs_2, %fork12.outs_3, %fork12.outs_4, %fork12.outs_5, %fork12.outs_6, %fork12.outs_7 = hw.instance "fork12" @handshake_fork_8(ins: %cmpf1.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>, outs_3: !handshake.channel<i1>, outs_4: !handshake.channel<i1>, outs_5: !handshake.channel<i1>, outs_6: !handshake.channel<i1>, outs_7: !handshake.channel<i1>)
    %cond_br11.trueOut, %cond_br11.falseOut = hw.instance "cond_br11" @handshake_cond_br_8(condition: %fork12.outs_7: !handshake.channel<i1>, data: %cond_br3.falseOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    %buffer20.outs = hw.instance "buffer20" @handshake_buffer_5(ins: %fork12.outs_6: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %cond_br12.trueOut, %cond_br12.falseOut = hw.instance "cond_br12" @handshake_cond_br_1(condition: %buffer20.outs: !handshake.channel<i1>, data: %cond_br4.falseOut: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.control<>, falseOut: !handshake.control<>)
    %cond_br13.trueOut, %cond_br13.falseOut = hw.instance "cond_br13" @handshake_cond_br_9(condition: %fork12.outs_5: !handshake.channel<i1>, data: %fork9.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    hw.instance "sink7" @handshake_sink_6(ins: %cond_br13.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> ()
    %buffer18.outs = hw.instance "buffer18" @handshake_buffer_15(ins: %fork10.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %cond_br14.trueOut, %cond_br14.falseOut = hw.instance "cond_br14" @handshake_cond_br_10(condition: %fork12.outs_4: !handshake.channel<i1>, data: %buffer18.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    hw.instance "sink8" @handshake_sink_7(ins: %cond_br14.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> ()
    %buffer19.outs = hw.instance "buffer19" @handshake_buffer_16(ins: %fork11.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %cond_br15.trueOut, %cond_br15.falseOut = hw.instance "cond_br15" @handshake_cond_br_11(condition: %fork12.outs_3: !handshake.channel<i1>, data: %buffer19.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    hw.instance "sink9" @handshake_sink_8(ins: %cond_br15.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> ()
    %cond_br16.trueOut, %cond_br16.falseOut = hw.instance "cond_br16" @handshake_cond_br_5(condition: %fork12.outs_0: !handshake.channel<i1>, data: %cond_br8.falseOut: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i8>, falseOut: !handshake.channel<i8>)
    hw.instance "sink10" @handshake_sink_3(ins: %cond_br16.trueOut: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> ()
    %buffer16.outs = hw.instance "buffer16" @handshake_buffer_17(ins: %cond_br9.falseOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %cond_br17.trueOut, %cond_br17.falseOut = hw.instance "cond_br17" @handshake_cond_br_12(condition: %fork12.outs_2: !handshake.channel<i1>, data: %buffer16.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    hw.instance "sink11" @handshake_sink_9(ins: %cond_br17.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> ()
    %buffer17.outs = hw.instance "buffer17" @handshake_buffer_18(ins: %cond_br10.falseOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %cond_br18.trueOut, %cond_br18.falseOut = hw.instance "cond_br18" @handshake_cond_br_13(condition: %fork12.outs_1: !handshake.channel<i1>, data: %buffer17.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    hw.instance "sink12" @handshake_sink_10(ins: %cond_br18.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> ()
    %extsi4.outs = hw.instance "extsi4" @handshake_extsi_1(ins: %cond_br16.falseOut: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i9>)
    %fork13.outs_0, %fork13.outs_1 = hw.instance "fork13" @handshake_fork_12(ins: %cond_br17.falseOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>)
    %buffer21.outs = hw.instance "buffer21" @handshake_buffer_19(ins: %cond_br11.falseOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %fork14.outs_0, %fork14.outs_1 = hw.instance "fork14" @handshake_fork_13(ins: %buffer21.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>)
    %fork15.outs_0, %fork15.outs_1 = hw.instance "fork15" @handshake_fork_14(ins: %cond_br18.falseOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>)
    %fork16.outs_0, %fork16.outs_1 = hw.instance "fork16" @handshake_fork_15(ins: %cond_br12.falseOut: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.control<>, outs_1: !handshake.control<>)
    %constant9.outs = hw.instance "constant9" @handshake_constant_5(ctrl: %fork16.outs_1: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %fork17.outs_0, %fork17.outs_1 = hw.instance "fork17" @handshake_fork_16(ins: %constant9.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>)
    %source4.outs = hw.instance "source4" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant1.outs = hw.instance "constant1" @handshake_constant_6(ctrl: %source4.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i2>)
    %extsi5.outs = hw.instance "extsi5" @handshake_extsi_2(ins: %constant1.outs: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i9>)
    %source5.outs = hw.instance "source5" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant2.outs = hw.instance "constant2" @handshake_constant_7(ctrl: %source5.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8>)
    %extsi6.outs = hw.instance "extsi6" @handshake_extsi_1(ins: %constant2.outs: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i9>)
    %mulf4.result = hw.instance "mulf4" @handshake_mulf_4(lhs: %fork13.outs_1: !handshake.channel<i32>, rhs: %fork15.outs_1: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %cmpf2.result = hw.instance "cmpf2" @handshake_cmpf_2(lhs: %mulf4.result: !handshake.channel<i32>, rhs: %fork17.outs_1: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %fork18.outs_0, %fork18.outs_1, %fork18.outs_2 = hw.instance "fork18" @handshake_fork_17(ins: %cmpf2.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>)
    %buffer24.outs = hw.instance "buffer24" @handshake_buffer_20(ins: %cond_br15.falseOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %select0.result = hw.instance "select0" @handshake_select_0(condition: %fork18.outs_2: !handshake.channel<i1>, trueValue: %fork14.outs_1: !handshake.channel<i32>, falseValue: %buffer24.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %buffer23.outs = hw.instance "buffer23" @handshake_buffer_21(ins: %cond_br14.falseOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %select1.result = hw.instance "select1" @handshake_select_1(condition: %fork18.outs_1: !handshake.channel<i1>, trueValue: %buffer23.outs: !handshake.channel<i32>, falseValue: %fork14.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %buffer25.outs = hw.instance "buffer25" @handshake_buffer_22(ins: %fork13.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer26.outs = hw.instance "buffer26" @handshake_buffer_23(ins: %fork15.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %select2.result = hw.instance "select2" @handshake_select_2(condition: %fork18.outs_0: !handshake.channel<i1>, trueValue: %buffer25.outs: !handshake.channel<i32>, falseValue: %buffer26.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %addi0.result = hw.instance "addi0" @handshake_addi_0(lhs: %extsi4.outs: !handshake.channel<i9>, rhs: %extsi5.outs: !handshake.channel<i9>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i9>)
    %buffer27.outs = hw.instance "buffer27" @handshake_buffer_24(ins: %addi0.result: !handshake.channel<i9>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i9>)
    %fork19.outs_0, %fork19.outs_1 = hw.instance "fork19" @handshake_fork_18(ins: %buffer27.outs: !handshake.channel<i9>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i9>, outs_1: !handshake.channel<i9>)
    %trunci0.outs = hw.instance "trunci0" @handshake_trunci_0(ins: %fork19.outs_0: !handshake.channel<i9>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8>)
    %cmpi0.result = hw.instance "cmpi0" @handshake_cmpi_0(lhs: %fork19.outs_1: !handshake.channel<i9>, rhs: %extsi6.outs: !handshake.channel<i9>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %fork20.outs_0, %fork20.outs_1, %fork20.outs_2, %fork20.outs_3, %fork20.outs_4, %fork20.outs_5, %fork20.outs_6 = hw.instance "fork20" @handshake_fork_19(ins: %cmpi0.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>, outs_3: !handshake.channel<i1>, outs_4: !handshake.channel<i1>, outs_5: !handshake.channel<i1>, outs_6: !handshake.channel<i1>)
    %cond_br19.trueOut, %cond_br19.falseOut = hw.instance "cond_br19" @handshake_cond_br_14(condition: %fork20.outs_1: !handshake.channel<i1>, data: %select1.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    hw.instance "sink14" @handshake_sink_11(ins: %cond_br19.falseOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> ()
    %cond_br20.trueOut, %cond_br20.falseOut = hw.instance "cond_br20" @handshake_cond_br_15(condition: %fork20.outs_2: !handshake.channel<i1>, data: %select0.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    hw.instance "sink15" @handshake_sink_12(ins: %cond_br20.falseOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> ()
    %cond_br21.trueOut, %cond_br21.falseOut = hw.instance "cond_br21" @handshake_cond_br_5(condition: %fork20.outs_0: !handshake.channel<i1>, data: %trunci0.outs: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i8>, falseOut: !handshake.channel<i8>)
    hw.instance "sink16" @handshake_sink_3(ins: %cond_br21.falseOut: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> ()
    %cond_br22.trueOut, %cond_br22.falseOut = hw.instance "cond_br22" @handshake_cond_br_16(condition: %fork20.outs_3: !handshake.channel<i1>, data: %select2.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    hw.instance "sink17" @handshake_sink_13(ins: %cond_br22.falseOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> ()
    %buffer22.outs = hw.instance "buffer22" @handshake_buffer_25(ins: %cond_br13.falseOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %cond_br23.trueOut, %cond_br23.falseOut = hw.instance "cond_br23" @handshake_cond_br_17(condition: %fork20.outs_4: !handshake.channel<i1>, data: %buffer22.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    hw.instance "sink18" @handshake_sink_14(ins: %cond_br23.falseOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> ()
    %cond_br24.trueOut, %cond_br24.falseOut = hw.instance "cond_br24" @handshake_cond_br_1(condition: %fork20.outs_5: !handshake.channel<i1>, data: %fork16.outs_0: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.control<>, falseOut: !handshake.control<>)
    %cond_br25.trueOut, %cond_br25.falseOut = hw.instance "cond_br25" @handshake_cond_br_18(condition: %fork20.outs_6: !handshake.channel<i1>, data: %fork17.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    hw.instance "sink19" @handshake_sink_15(ins: %cond_br25.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> ()
    %mux5.outs = hw.instance "mux5" @handshake_mux_5(index: %control_merge3.index: !handshake.channel<i1>, ins_0: %cond_br3.trueOut: !handshake.channel<i32>, ins_1: %cond_br25.falseOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %control_merge3.outs, %control_merge3.index = hw.instance "control_merge3" @handshake_control_merge_0(ins_0: %cond_br4.trueOut: !handshake.control<>, ins_1: %cond_br24.falseOut: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>, index: !handshake.channel<i1>)
    %mux6.outs = hw.instance "mux6" @handshake_mux_6(index: %control_merge4.index: !handshake.channel<i1>, ins_0: %cond_br11.trueOut: !handshake.channel<i32>, ins_1: %mux5.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %control_merge4.outs, %control_merge4.index = hw.instance "control_merge4" @handshake_control_merge_0(ins_0: %cond_br12.trueOut: !handshake.control<>, ins_1: %control_merge3.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>, index: !handshake.channel<i1>)
    hw.instance "sink20" @handshake_sink_16(ins: %control_merge4.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> ()
    hw.output %mux6.outs, %fork0.outs_1 : !handshake.channel<i32>, !handshake.control<>
  }
  hw.module.extern @handshake_fork_0(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.control<>, out outs_1 : !handshake.control<>, out outs_2 : !handshake.control<>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.control<>, SIZE = 3 : ui32}}
  hw.module.extern @handshake_fork_1(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>, out outs_2 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SIZE = 3 : ui32}}
  hw.module.extern @handshake_constant_0(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 1 : ui32, VALUE = "0"}}
  hw.module.extern @handshake_source_0(in %clk : i1, in %rst : i1, out outs : !handshake.control<>) attributes {hw.name = "handshake.source", hw.parameters = {}}
  hw.module.extern @handshake_constant_1(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 32 : ui32, VALUE = "11000000000000000000000000000000"}}
  hw.module.extern @handshake_mulf_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.mulf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "2_875333"}}
  hw.module.extern @handshake_addf_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.addf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "2_922000"}}
  hw.module.extern @handshake_extsi_0(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i8>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i1>, OUTPUT_TYPE = !handshake.channel<i8>}}
  hw.module.extern @handshake_mux_0(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.channel<i32>, in %ins_1 : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_0(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_fork_2(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_mux_1(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.channel<i32>, in %ins_1 : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_1(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_fork_3(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_mux_2(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.channel<i8>, in %ins_1 : !handshake.channel<i8>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i8>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<i8>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_mux_3(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.channel<i32>, in %ins_1 : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_mux_4(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.channel<i32>, in %ins_1 : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_2(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_buffer_3(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_fork_4(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_control_merge_0(in %ins_0 : !handshake.control<>, in %ins_1 : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.control<>, out index : !handshake.channel<i1>) attributes {hw.name = "handshake.control_merge", hw.parameters = {DATA_TYPE = !handshake.control<>, INDEX_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_fork_5(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>, out outs_2 : !handshake.channel<i1>, out outs_3 : !handshake.channel<i1>, out outs_4 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 5 : ui32}}
  hw.module.extern @handshake_constant_2(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 32 : ui32, VALUE = "11000000000000000000000000000000"}}
  hw.module.extern @handshake_constant_3(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 32 : ui32, VALUE = "00111111000000000000000000000000"}}
  hw.module.extern @handshake_addf_1(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.addf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "2_922000"}}
  hw.module.extern @handshake_mulf_1(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.mulf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "2_875333"}}
  hw.module.extern @handshake_fork_6(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>, out outs_2 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SIZE = 3 : ui32}}
  hw.module.extern @handshake_mulf_2(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.mulf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "2_875333"}}
  hw.module.extern @handshake_addf_2(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.addf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "2_922000"}}
  hw.module.extern @handshake_fork_7(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_absf_0(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.absf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_cmpf_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.cmpf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "0_000000", PREDICATE = "olt"}}
  hw.module.extern @handshake_fork_8(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>, out outs_2 : !handshake.channel<i1>, out outs_3 : !handshake.channel<i1>, out outs_4 : !handshake.channel<i1>, out outs_5 : !handshake.channel<i1>, out outs_6 : !handshake.channel<i1>, out outs_7 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 8 : ui32}}
  hw.module.extern @handshake_buffer_4(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_buffer_5(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i1>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_cond_br_0(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i32>, out falseOut : !handshake.channel<i32>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_buffer_6(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.control<>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.control<>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_buffer_7(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<i1>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_cond_br_1(in %condition : !handshake.channel<i1>, in %data : !handshake.control<>, in %clk : i1, in %rst : i1, out trueOut : !handshake.control<>, out falseOut : !handshake.control<>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.control<>}}
  hw.module.extern @handshake_cond_br_2(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i32>, out falseOut : !handshake.channel<i32>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_sink_0(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_buffer_8(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_cond_br_3(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i32>, out falseOut : !handshake.channel<i32>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_sink_1(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_buffer_9(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_cond_br_4(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i32>, out falseOut : !handshake.channel<i32>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_sink_2(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_buffer_10(in %ins : !handshake.channel<i8>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i8>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i8>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_buffer_11(in %ins : !handshake.channel<i8>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i8>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.channel<i8>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_cond_br_5(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i8>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i8>, out falseOut : !handshake.channel<i8>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<i8>}}
  hw.module.extern @handshake_sink_3(in %ins : !handshake.channel<i8>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.channel<i8>}}
  hw.module.extern @handshake_buffer_12(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_buffer_13(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_cond_br_6(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i32>, out falseOut : !handshake.channel<i32>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_sink_4(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_cond_br_7(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i32>, out falseOut : !handshake.channel<i32>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_sink_5(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_buffer_14(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_fork_9(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_fork_10(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_fork_11(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_constant_4(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 32 : ui32, VALUE = "00111111000000000000000000000000"}}
  hw.module.extern @handshake_subf_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.subf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "2_000000"}}
  hw.module.extern @handshake_mulf_3(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.mulf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "2_875333"}}
  hw.module.extern @handshake_cmpf_1(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.cmpf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "0_000000", PREDICATE = "olt"}}
  hw.module.extern @handshake_cond_br_8(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i32>, out falseOut : !handshake.channel<i32>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_cond_br_9(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i32>, out falseOut : !handshake.channel<i32>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_sink_6(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_buffer_15(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_cond_br_10(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i32>, out falseOut : !handshake.channel<i32>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_sink_7(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_buffer_16(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_cond_br_11(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i32>, out falseOut : !handshake.channel<i32>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_sink_8(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_buffer_17(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_cond_br_12(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i32>, out falseOut : !handshake.channel<i32>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_sink_9(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_buffer_18(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_cond_br_13(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i32>, out falseOut : !handshake.channel<i32>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_sink_10(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_extsi_1(in %ins : !handshake.channel<i8>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i9>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i8>, OUTPUT_TYPE = !handshake.channel<i9>}}
  hw.module.extern @handshake_fork_12(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_19(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_fork_13(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_fork_14(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_fork_15(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.control<>, out outs_1 : !handshake.control<>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.control<>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_constant_5(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 32 : ui32, VALUE = "00000000000000000000000000000000"}}
  hw.module.extern @handshake_fork_16(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_constant_6(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i2>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 2 : ui32, VALUE = "01"}}
  hw.module.extern @handshake_extsi_2(in %ins : !handshake.channel<i2>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i9>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i2>, OUTPUT_TYPE = !handshake.channel<i9>}}
  hw.module.extern @handshake_constant_7(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i8>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 8 : ui32, VALUE = "01100100"}}
  hw.module.extern @handshake_mulf_4(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.mulf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "2_875333"}}
  hw.module.extern @handshake_cmpf_2(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.cmpf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "0_000000", PREDICATE = "olt"}}
  hw.module.extern @handshake_fork_17(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>, out outs_2 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 3 : ui32}}
  hw.module.extern @handshake_buffer_20(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_select_0(in %condition : !handshake.channel<i1>, in %trueValue : !handshake.channel<i32>, in %falseValue : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.select", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_buffer_21(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_select_1(in %condition : !handshake.channel<i1>, in %trueValue : !handshake.channel<i32>, in %falseValue : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.select", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_buffer_22(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_buffer_23(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_select_2(in %condition : !handshake.channel<i1>, in %trueValue : !handshake.channel<i32>, in %falseValue : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.select", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_addi_0(in %lhs : !handshake.channel<i9>, in %rhs : !handshake.channel<i9>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i9>) attributes {hw.name = "handshake.addi", hw.parameters = {DATA_TYPE = !handshake.channel<i9>}}
  hw.module.extern @handshake_buffer_24(in %ins : !handshake.channel<i9>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i9>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<i9>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_fork_18(in %ins : !handshake.channel<i9>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i9>, out outs_1 : !handshake.channel<i9>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i9>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_trunci_0(in %ins : !handshake.channel<i9>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i8>) attributes {hw.name = "handshake.trunci", hw.parameters = {INPUT_TYPE = !handshake.channel<i9>, OUTPUT_TYPE = !handshake.channel<i8>}}
  hw.module.extern @handshake_cmpi_0(in %lhs : !handshake.channel<i9>, in %rhs : !handshake.channel<i9>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.cmpi", hw.parameters = {DATA_TYPE = !handshake.channel<i9>, PREDICATE = "ult"}}
  hw.module.extern @handshake_fork_19(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>, out outs_2 : !handshake.channel<i1>, out outs_3 : !handshake.channel<i1>, out outs_4 : !handshake.channel<i1>, out outs_5 : !handshake.channel<i1>, out outs_6 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 7 : ui32}}
  hw.module.extern @handshake_cond_br_14(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i32>, out falseOut : !handshake.channel<i32>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_sink_11(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_cond_br_15(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i32>, out falseOut : !handshake.channel<i32>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_sink_12(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_cond_br_16(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i32>, out falseOut : !handshake.channel<i32>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_sink_13(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_buffer_25(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_cond_br_17(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i32>, out falseOut : !handshake.channel<i32>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_sink_14(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_cond_br_18(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i32>, out falseOut : !handshake.channel<i32>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_sink_15(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_mux_5(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.channel<i32>, in %ins_1 : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_mux_6(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.channel<i32>, in %ins_1 : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_sink_16(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.control<>}}
  hw.module @bisection_wrapper(in %a : !handshake.channel<i32>, in %b : !handshake.channel<i32>, in %tol : !handshake.channel<i32>, in %start : !handshake.control<>, in %clk : i1, in %rst : i1, out out0 : !handshake.channel<i32>, out end : !handshake.control<>) {
    %bisection_wrapped.out0, %bisection_wrapped.end = hw.instance "bisection_wrapped" @bisection(a: %a: !handshake.channel<i32>, b: %b: !handshake.channel<i32>, tol: %tol: !handshake.channel<i32>, start: %start: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (out0: !handshake.channel<i32>, end: !handshake.control<>)
    hw.output %bisection_wrapped.out0, %bisection_wrapped.end : !handshake.channel<i32>, !handshake.control<>
  }
}

