module {
  hw.module @golden_ratio(in %x0 : !handshake.channel<i32>, in %x1 : !handshake.channel<i32>, in %start : !handshake.control<>, in %clk : i1, in %rst : i1, out out0 : !handshake.channel<i32>, out end : !handshake.control<>) {
    %fork0.outs_0, %fork0.outs_1, %fork0.outs_2 = hw.instance "fork0" @handshake_fork_0(ins: %start: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.control<>, outs_1: !handshake.control<>, outs_2: !handshake.control<>)
    %constant0.outs = hw.instance "constant0" @handshake_constant_0(ctrl: %fork0.outs_0: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %extsi3.outs = hw.instance "extsi3" @handshake_extsi_0(ins: %constant0.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8>)
    %mux0.outs = hw.instance "mux0" @handshake_mux_0(index: %fork1.outs_0: !handshake.channel<i1>, ins_0: %extsi3.outs: !handshake.channel<i8>, ins_1: %cond_br7.trueOut: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8>)
    %buffer3.outs = hw.instance "buffer3" @handshake_buffer_0(ins: %fork1.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %mux1.outs = hw.instance "mux1" @handshake_mux_1(index: %buffer3.outs: !handshake.channel<i1>, ins_0: %x1: !handshake.channel<i32>, ins_1: %cond_br8.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %mux2.outs = hw.instance "mux2" @handshake_mux_2(index: %fork1.outs_2: !handshake.channel<i1>, ins_0: %x0: !handshake.channel<i32>, ins_1: %cond_br9.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %control_merge0.outs, %control_merge0.index = hw.instance "control_merge0" @handshake_control_merge_0(ins_0: %fork0.outs_2: !handshake.control<>, ins_1: %cond_br10.trueOut: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>, index: !handshake.channel<i1>)
    %fork1.outs_0, %fork1.outs_1, %fork1.outs_2 = hw.instance "fork1" @handshake_fork_1(ins: %control_merge0.index: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>)
    %buffer2.outs = hw.instance "buffer2" @handshake_buffer_1(ins: %mux2.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %mux3.outs = hw.instance "mux3" @handshake_mux_3(index: %fork3.outs_3: !handshake.channel<i1>, ins_0: %buffer2.outs: !handshake.channel<i32>, ins_1: %passer7.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer0.outs = hw.instance "buffer0" @handshake_buffer_2(ins: %mux0.outs: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8>)
    %mux4.outs = hw.instance "mux4" @handshake_mux_0(index: %fork3.outs_2: !handshake.channel<i1>, ins_0: %buffer0.outs: !handshake.channel<i8>, ins_1: %passer9.result: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8>)
    %buffer1.outs = hw.instance "buffer1" @handshake_buffer_3(ins: %mux1.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer16.outs = hw.instance "buffer16" @handshake_buffer_4(ins: %fork3.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %mux5.outs = hw.instance "mux5" @handshake_mux_4(index: %buffer16.outs: !handshake.channel<i1>, ins_0: %buffer1.outs: !handshake.channel<i32>, ins_1: %passer11.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %mux6.outs = hw.instance "mux6" @handshake_mux_5(index: %fork3.outs_0: !handshake.channel<i1>, ins_0: %control_merge0.outs: !handshake.control<>, ins_1: %passer10.result: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %source0.outs = hw.instance "source0" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant6.outs = hw.instance "constant6" @handshake_constant_1(ctrl: %source0.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %source1.outs = hw.instance "source1" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant7.outs = hw.instance "constant7" @handshake_constant_2(ctrl: %source1.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer21.outs = hw.instance "buffer21" @handshake_buffer_5(ins: %fork28.outs_3: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %mulf0.result = hw.instance "mulf0" @handshake_mulf_0(lhs: %buffer21.outs: !handshake.channel<i32>, rhs: %fork29.outs_1: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %buffer20.outs = hw.instance "buffer20" @handshake_buffer_6(ins: %fork28.outs_2: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %addf0.result = hw.instance "addf0" @handshake_addf_0(lhs: %buffer20.outs: !handshake.channel<i32>, rhs: %mulf0.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %passer7.result = hw.instance "passer7" @handshake_passer_0(data: %fork4.outs_0: !handshake.channel<i32>, ctrl: %fork2.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %fork4.outs_0, %fork4.outs_1 = hw.instance "fork4" @handshake_fork_2(ins: %mulf1.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>)
    %mulf1.result = hw.instance "mulf1" @handshake_mulf_1(lhs: %addf0.result: !handshake.channel<i32>, rhs: %constant6.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %buffer19.outs = hw.instance "buffer19" @handshake_buffer_7(ins: %fork28.outs_1: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %subf0.result = hw.instance "subf0" @handshake_subf_0(lhs: %fork4.outs_1: !handshake.channel<i32>, rhs: %buffer19.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %absf0.outs = hw.instance "absf0" @handshake_absf_0(ins: %subf0.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %cmpf0.result = hw.instance "cmpf0" @handshake_cmpf_0(lhs: %absf0.outs: !handshake.channel<i32>, rhs: %constant7.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %fork6.outs_0, %fork6.outs_1 = hw.instance "fork6" @handshake_fork_3(ins: %cmpf0.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>)
    %buffer12.outs = hw.instance "buffer12" @handshake_buffer_4(ins: %fork2.outs_2: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %passer8.result = hw.instance "passer8" @handshake_passer_1(data: %not0.outs: !handshake.channel<i1>, ctrl: %buffer12.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %not0.outs = hw.instance "not0" @handshake_not_0(ins: %fork6.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %spec_v2_repeating_init0.outs = hw.instance "spec_v2_repeating_init0" @handshake_spec_v2_repeating_init_0(ins: %passer8.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer10.outs = hw.instance "buffer10" @handshake_buffer_0(ins: %spec_v2_repeating_init0.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer11.outs = hw.instance "buffer11" @handshake_buffer_8(ins: %buffer10.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %fork2.outs_0, %fork2.outs_1, %fork2.outs_2, %fork2.outs_3, %fork2.outs_4, %fork2.outs_5, %fork2.outs_6 = hw.instance "fork2" @handshake_fork_4(ins: %buffer11.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>, outs_3: !handshake.channel<i1>, outs_4: !handshake.channel<i1>, outs_5: !handshake.channel<i1>, outs_6: !handshake.channel<i1>)
    %buffer15.outs = hw.instance "buffer15" @handshake_buffer_4(ins: %fork2.outs_6: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %init4.outs = hw.instance "init4" @handshake_init_0(ins: %buffer15.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %fork3.outs_0, %fork3.outs_1, %fork3.outs_2, %fork3.outs_3 = hw.instance "fork3" @handshake_fork_5(ins: %init4.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>, outs_3: !handshake.channel<i1>)
    %buffer14.outs = hw.instance "buffer14" @handshake_buffer_4(ins: %fork2.outs_5: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %andi0.result = hw.instance "andi0" @handshake_andi_0(lhs: %fork6.outs_1: !handshake.channel<i1>, rhs: %buffer14.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %fork33.outs_0, %fork33.outs_1, %fork33.outs_2, %fork33.outs_3, %fork33.outs_4, %fork33.outs_5, %fork33.outs_6, %fork33.outs_7 = hw.instance "fork33" @handshake_fork_6(ins: %andi0.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>, outs_3: !handshake.channel<i1>, outs_4: !handshake.channel<i1>, outs_5: !handshake.channel<i1>, outs_6: !handshake.channel<i1>, outs_7: !handshake.channel<i1>)
    %buffer13.outs = hw.instance "buffer13" @handshake_buffer_4(ins: %fork2.outs_4: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %passer9.result = hw.instance "passer9" @handshake_passer_2(data: %fork26.outs_0: !handshake.channel<i8>, ctrl: %buffer13.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i8>)
    %buffer5.outs = hw.instance "buffer5" @handshake_buffer_9(ins: %mux4.outs: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8>)
    %buffer6.outs = hw.instance "buffer6" @handshake_buffer_2(ins: %buffer5.outs: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8>)
    %fork26.outs_0, %fork26.outs_1 = hw.instance "fork26" @handshake_fork_7(ins: %buffer6.outs: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i8>, outs_1: !handshake.channel<i8>)
    %buffer18.outs = hw.instance "buffer18" @handshake_buffer_10(ins: %fork27.outs_0: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %passer3.result = hw.instance "passer3" @handshake_passer_3(data: %buffer18.outs: !handshake.control<>, ctrl: %fork33.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.control<>)
    %passer10.result = hw.instance "passer10" @handshake_passer_3(data: %fork27.outs_1: !handshake.control<>, ctrl: %fork2.outs_3: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.control<>)
    %buffer8.outs = hw.instance "buffer8" @handshake_buffer_10(ins: %mux6.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %buffer9.outs = hw.instance "buffer9" @handshake_buffer_11(ins: %buffer8.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %fork27.outs_0, %fork27.outs_1 = hw.instance "fork27" @handshake_fork_8(ins: %buffer9.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.control<>, outs_1: !handshake.control<>)
    %buffer4.outs = hw.instance "buffer4" @handshake_buffer_12(ins: %mux3.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %fork28.outs_0, %fork28.outs_1, %fork28.outs_2, %fork28.outs_3 = hw.instance "fork28" @handshake_fork_9(ins: %buffer4.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>, outs_2: !handshake.channel<i32>, outs_3: !handshake.channel<i32>)
    %buffer22.outs = hw.instance "buffer22" @handshake_buffer_13(ins: %fork29.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %passer11.result = hw.instance "passer11" @handshake_passer_4(data: %buffer22.outs: !handshake.channel<i32>, ctrl: %fork2.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %buffer7.outs = hw.instance "buffer7" @handshake_buffer_14(ins: %mux5.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %fork29.outs_0, %fork29.outs_1 = hw.instance "fork29" @handshake_fork_10(ins: %buffer7.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>)
    %extsi4.outs = hw.instance "extsi4" @handshake_extsi_1(ins: %fork26.outs_1: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i9>)
    %source2.outs = hw.instance "source2" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant8.outs = hw.instance "constant8" @handshake_constant_3(ctrl: %source2.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %fork7.outs_0, %fork7.outs_1 = hw.instance "fork7" @handshake_fork_11(ins: %constant8.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>)
    %source3.outs = hw.instance "source3" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant1.outs = hw.instance "constant1" @handshake_constant_4(ctrl: %source3.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i2>)
    %extsi5.outs = hw.instance "extsi5" @handshake_extsi_2(ins: %constant1.outs: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i9>)
    %source4.outs = hw.instance "source4" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant2.outs = hw.instance "constant2" @handshake_constant_5(ctrl: %source4.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8>)
    %extsi6.outs = hw.instance "extsi6" @handshake_extsi_1(ins: %constant2.outs: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i9>)
    %buffer24.outs = hw.instance "buffer24" @handshake_buffer_15(ins: %fork30.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %passer12.result = hw.instance "passer12" @handshake_passer_5(data: %buffer24.outs: !handshake.channel<i32>, ctrl: %fork33.outs_7: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %fork30.outs_0, %fork30.outs_1 = hw.instance "fork30" @handshake_fork_12(ins: %addf1.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>)
    %addf1.result = hw.instance "addf1" @handshake_addf_1(lhs: %fork28.outs_0: !handshake.channel<i32>, rhs: %fork7.outs_1: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %buffer17.outs = hw.instance "buffer17" @handshake_buffer_4(ins: %fork33.outs_6: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %passer13.result = hw.instance "passer13" @handshake_passer_6(data: %divf0.result: !handshake.channel<i32>, ctrl: %buffer17.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %buffer23.outs = hw.instance "buffer23" @handshake_buffer_16(ins: %fork7.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %divf0.result = hw.instance "divf0" @handshake_divf_0(lhs: %buffer23.outs: !handshake.channel<i32>, rhs: %fork30.outs_1: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %fork31.outs_0, %fork31.outs_1 = hw.instance "fork31" @handshake_fork_13(ins: %addi0.result: !handshake.channel<i9>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i9>, outs_1: !handshake.channel<i9>)
    %addi0.result = hw.instance "addi0" @handshake_addi_0(lhs: %extsi4.outs: !handshake.channel<i9>, rhs: %extsi5.outs: !handshake.channel<i9>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i9>)
    %passer14.result = hw.instance "passer14" @handshake_passer_2(data: %trunci0.outs: !handshake.channel<i8>, ctrl: %fork33.outs_5: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i8>)
    %trunci0.outs = hw.instance "trunci0" @handshake_trunci_0(ins: %fork31.outs_0: !handshake.channel<i9>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8>)
    %passer15.result = hw.instance "passer15" @handshake_passer_1(data: %fork32.outs_0: !handshake.channel<i1>, ctrl: %fork33.outs_4: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %passer16.result = hw.instance "passer16" @handshake_passer_1(data: %fork32.outs_1: !handshake.channel<i1>, ctrl: %fork33.outs_3: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %passer17.result = hw.instance "passer17" @handshake_passer_1(data: %fork32.outs_2: !handshake.channel<i1>, ctrl: %fork33.outs_2: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %passer18.result = hw.instance "passer18" @handshake_passer_1(data: %fork32.outs_3: !handshake.channel<i1>, ctrl: %fork33.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %fork32.outs_0, %fork32.outs_1, %fork32.outs_2, %fork32.outs_3 = hw.instance "fork32" @handshake_fork_5(ins: %cmpi0.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>, outs_3: !handshake.channel<i1>)
    %cmpi0.result = hw.instance "cmpi0" @handshake_cmpi_0(lhs: %fork31.outs_1: !handshake.channel<i9>, rhs: %extsi6.outs: !handshake.channel<i9>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %cond_br7.trueOut, %cond_br7.falseOut = hw.instance "cond_br7" @handshake_cond_br_0(condition: %passer15.result: !handshake.channel<i1>, data: %passer14.result: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i8>, falseOut: !handshake.channel<i8>)
    hw.instance "sink4" @handshake_sink_0(ins: %cond_br7.falseOut: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> ()
    %buffer25.outs = hw.instance "buffer25" @handshake_buffer_4(ins: %passer16.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %cond_br8.trueOut, %cond_br8.falseOut = hw.instance "cond_br8" @handshake_cond_br_1(condition: %buffer25.outs: !handshake.channel<i1>, data: %passer13.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    hw.instance "sink5" @handshake_sink_1(ins: %cond_br8.falseOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> ()
    %cond_br9.trueOut, %cond_br9.falseOut = hw.instance "cond_br9" @handshake_cond_br_2(condition: %passer17.result: !handshake.channel<i1>, data: %passer12.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    %cond_br10.trueOut, %cond_br10.falseOut = hw.instance "cond_br10" @handshake_cond_br_3(condition: %passer18.result: !handshake.channel<i1>, data: %passer3.result: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.control<>, falseOut: !handshake.control<>)
    hw.instance "sink6" @handshake_sink_2(ins: %cond_br10.falseOut: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> ()
    hw.output %cond_br9.falseOut, %fork0.outs_1 : !handshake.channel<i32>, !handshake.control<>
  }
  hw.module.extern @handshake_fork_0(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.control<>, out outs_1 : !handshake.control<>, out outs_2 : !handshake.control<>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.control<>, SIZE = 3 : ui32}}
  hw.module.extern @handshake_constant_0(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 1 : ui32, VALUE = "0"}}
  hw.module.extern @handshake_extsi_0(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i8>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i1>, OUTPUT_TYPE = !handshake.channel<i8>}}
  hw.module.extern @handshake_mux_0(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.channel<i8>, in %ins_1 : !handshake.channel<i8>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i8>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<i8>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_0(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<i1>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_mux_1(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.channel<i32>, in %ins_1 : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_mux_2(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.channel<i32>, in %ins_1 : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_control_merge_0(in %ins_0 : !handshake.control<>, in %ins_1 : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.control<>, out index : !handshake.channel<i1>) attributes {hw.name = "handshake.control_merge", hw.parameters = {DATA_TYPE = !handshake.control<>, INDEX_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_fork_1(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>, out outs_2 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 3 : ui32}}
  hw.module.extern @handshake_buffer_1(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_mux_3(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.channel<i32>, in %ins_1 : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_2(in %ins : !handshake.channel<i8>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i8>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.channel<i8>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_buffer_3(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_buffer_4(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i1>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_mux_4(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.channel<i32>, in %ins_1 : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_mux_5(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.control<>, in %ins_1 : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.control<>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.control<>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_source_0(in %clk : i1, in %rst : i1, out outs : !handshake.control<>) attributes {hw.name = "handshake.source", hw.parameters = {}}
  hw.module.extern @handshake_constant_1(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 32 : ui32, VALUE = "00111111000000000000000000000000"}}
  hw.module.extern @handshake_constant_2(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 32 : ui32, VALUE = "00111101110011001100110011001101"}}
  hw.module.extern @handshake_buffer_5(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_mulf_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.mulf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "2_875333"}}
  hw.module.extern @handshake_buffer_6(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_addf_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.addf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "2_922000"}}
  hw.module.extern @handshake_passer_0(in %data : !handshake.channel<i32>, in %ctrl : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.passer", hw.parameters = {}}
  hw.module.extern @handshake_fork_2(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_mulf_1(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.mulf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "2_875333"}}
  hw.module.extern @handshake_buffer_7(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_subf_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.subf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "2_000000"}}
  hw.module.extern @handshake_absf_0(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.absf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_cmpf_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.cmpf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "0_000000", PREDICATE = "olt"}}
  hw.module.extern @handshake_fork_3(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_passer_1(in %data : !handshake.channel<i1>, in %ctrl : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.passer", hw.parameters = {}}
  hw.module.extern @handshake_not_0(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.not", hw.parameters = {DATA_TYPE = !handshake.channel<i1>}}
  hw.module.extern @handshake_spec_v2_repeating_init_0(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.spec_v2_repeating_init", hw.parameters = {INIT_TOKEN = 1 : ui32}}
  hw.module.extern @handshake_buffer_8(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.channel<i1>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_fork_4(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>, out outs_2 : !handshake.channel<i1>, out outs_3 : !handshake.channel<i1>, out outs_4 : !handshake.channel<i1>, out outs_5 : !handshake.channel<i1>, out outs_6 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 7 : ui32}}
  hw.module.extern @handshake_init_0(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.init", hw.parameters = {INIT_TOKEN = 0 : ui32}}
  hw.module.extern @handshake_fork_5(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>, out outs_2 : !handshake.channel<i1>, out outs_3 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 4 : ui32}}
  hw.module.extern @handshake_andi_0(in %lhs : !handshake.channel<i1>, in %rhs : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.andi", hw.parameters = {DATA_TYPE = !handshake.channel<i1>}}
  hw.module.extern @handshake_fork_6(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>, out outs_2 : !handshake.channel<i1>, out outs_3 : !handshake.channel<i1>, out outs_4 : !handshake.channel<i1>, out outs_5 : !handshake.channel<i1>, out outs_6 : !handshake.channel<i1>, out outs_7 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 8 : ui32}}
  hw.module.extern @handshake_passer_2(in %data : !handshake.channel<i8>, in %ctrl : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i8>) attributes {hw.name = "handshake.passer", hw.parameters = {}}
  hw.module.extern @handshake_buffer_9(in %ins : !handshake.channel<i8>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i8>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<i8>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_fork_7(in %ins : !handshake.channel<i8>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i8>, out outs_1 : !handshake.channel<i8>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i8>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_10(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.control<>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.control<>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_passer_3(in %data : !handshake.control<>, in %ctrl : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.control<>) attributes {hw.name = "handshake.passer", hw.parameters = {}}
  hw.module.extern @handshake_buffer_11(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.control<>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.control<>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_fork_8(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.control<>, out outs_1 : !handshake.control<>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.control<>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_12(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_fork_9(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>, out outs_2 : !handshake.channel<i32>, out outs_3 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SIZE = 4 : ui32}}
  hw.module.extern @handshake_buffer_13(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_passer_4(in %data : !handshake.channel<i32>, in %ctrl : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.passer", hw.parameters = {}}
  hw.module.extern @handshake_buffer_14(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_fork_10(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_extsi_1(in %ins : !handshake.channel<i8>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i9>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i8>, OUTPUT_TYPE = !handshake.channel<i9>}}
  hw.module.extern @handshake_constant_3(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 32 : ui32, VALUE = "00111111100000000000000000000000"}}
  hw.module.extern @handshake_fork_11(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_constant_4(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i2>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 2 : ui32, VALUE = "01"}}
  hw.module.extern @handshake_extsi_2(in %ins : !handshake.channel<i2>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i9>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i2>, OUTPUT_TYPE = !handshake.channel<i9>}}
  hw.module.extern @handshake_constant_5(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i8>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 8 : ui32, VALUE = "01100100"}}
  hw.module.extern @handshake_buffer_15(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_passer_5(in %data : !handshake.channel<i32>, in %ctrl : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.passer", hw.parameters = {}}
  hw.module.extern @handshake_fork_12(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_addf_1(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.addf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "2_922000"}}
  hw.module.extern @handshake_passer_6(in %data : !handshake.channel<i32>, in %ctrl : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.passer", hw.parameters = {}}
  hw.module.extern @handshake_buffer_16(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_divf_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.divf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "3_812000"}}
  hw.module.extern @handshake_fork_13(in %ins : !handshake.channel<i9>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i9>, out outs_1 : !handshake.channel<i9>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i9>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_addi_0(in %lhs : !handshake.channel<i9>, in %rhs : !handshake.channel<i9>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i9>) attributes {hw.name = "handshake.addi", hw.parameters = {DATA_TYPE = !handshake.channel<i9>}}
  hw.module.extern @handshake_trunci_0(in %ins : !handshake.channel<i9>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i8>) attributes {hw.name = "handshake.trunci", hw.parameters = {INPUT_TYPE = !handshake.channel<i9>, OUTPUT_TYPE = !handshake.channel<i8>}}
  hw.module.extern @handshake_cmpi_0(in %lhs : !handshake.channel<i9>, in %rhs : !handshake.channel<i9>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.cmpi", hw.parameters = {DATA_TYPE = !handshake.channel<i9>, PREDICATE = "ult"}}
  hw.module.extern @handshake_cond_br_0(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i8>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i8>, out falseOut : !handshake.channel<i8>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<i8>}}
  hw.module.extern @handshake_sink_0(in %ins : !handshake.channel<i8>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.channel<i8>}}
  hw.module.extern @handshake_cond_br_1(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i32>, out falseOut : !handshake.channel<i32>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_sink_1(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_cond_br_2(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i32>, out falseOut : !handshake.channel<i32>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_cond_br_3(in %condition : !handshake.channel<i1>, in %data : !handshake.control<>, in %clk : i1, in %rst : i1, out trueOut : !handshake.control<>, out falseOut : !handshake.control<>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.control<>}}
  hw.module.extern @handshake_sink_2(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.control<>}}
  hw.module @golden_ratio_wrapper(in %x0 : !handshake.channel<i32>, in %x1 : !handshake.channel<i32>, in %start : !handshake.control<>, in %clk : i1, in %rst : i1, out out0 : !handshake.channel<i32>, out end : !handshake.control<>) {
    %golden_ratio_wrapped.out0, %golden_ratio_wrapped.end = hw.instance "golden_ratio_wrapped" @golden_ratio(x0: %x0: !handshake.channel<i32>, x1: %x1: !handshake.channel<i32>, start: %start: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (out0: !handshake.channel<i32>, end: !handshake.control<>)
    hw.output %golden_ratio_wrapped.out0, %golden_ratio_wrapped.end : !handshake.channel<i32>, !handshake.control<>
  }
}

