vlib work
vmap work work
project new . simulation work modelsim.ini 0
project open simulation
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_mem_controller_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_buffer_4.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_fork_3.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_constant_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_constant_5.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_extsi_2.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/types.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_trunci_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_extsi_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_trunci_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_mux_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_extsi_5.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_constant_3.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_mux_2.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_source_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_buffer_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/single_argument.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_cond_br_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/two_port_RAM.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_extsi_7.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_extsi_3.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_fork_2.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_muli_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_cond_br_2.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_constant_2.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_cmpi_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_buffer_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_buffer_3.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_mem_controller_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_extsi_6.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_cond_br_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_andi_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/collision_donut.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_cmpi_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_shli_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_buffer_2.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_addi_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_fork_7.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_fork_5.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_constant_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_fork_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_cmpi_2.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_mux_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_addi_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/tb_join.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_fork_4.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_fork_6.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_buffer_5.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_cond_br_3.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_sink_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_constant_6.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_constant_4.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_control_merge_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_load_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_cond_br_4.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/simpackage.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_extsi_4.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_fork_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_extsi_1.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/mem_to_bram_32_10.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/tb_collision_donut.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/handshake_sink_0.vhd
project addfile /home/shundroid/dynamatic/integration-test/collision_donut/out_standard/sim/HDL_SRC/collision_donut_wrapper.vhd
project calculateorder
project compileall
eval vsim tb
log -r *
run 40000ns -all
exit
