#ifndef DYNAMATIC_TRANSFORMS_HANDSHAKEOPTIMIZATION_H
#define DYNAMATIC_TRANSFORMS_HANDSHAKEOPTIMIZATION_H

#include "dynamatic/Support/DynamaticPass.h"
#include "dynamatic/Support/LLVM.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/IR/DialectRegistry.h"
#include "mlir/Pass/Pass.h"

namespace dynamatic {

/// The following include file is autogenerated by LLVM/MLIR during the build
/// process from the Passes.td file we just edited. We only want to include the
/// part of the file that refers to our pass (it contains delcaration code for
/// all transformation passes), which we select using the two macros below.
#define GEN_PASS_DECL_HANDSHAKEOPTIMIZATION
#define GEN_PASS_DEF_HANDSHAKEOPTIMIZATION
#include "dynamatic/Transforms/Passes.h.inc"

std::unique_ptr<dynamatic::DynamaticPass> createHandshakeOptimization();

} // namespace dynamatic

#endif