module {
  hw.module @subdiag_fast(in %d1_loadData : i32, in %d2_loadData : i32, in %e_loadData : i32, in %d1_start : !handshake.control<>, in %d2_start : !handshake.control<>, in %e_start : !handshake.control<>, in %start : !handshake.control<>, in %clk : i1, in %rst : i1, out out0 : !handshake.channel<i32>, out d1_end : !handshake.control<>, out d2_end : !handshake.control<>, out e_end : !handshake.control<>, out end : !handshake.control<>, out d1_loadEn : i1, out d1_loadAddr : i10, out d1_storeEn : i1, out d1_storeAddr : i10, out d1_storeData : i32, out d2_loadEn : i1, out d2_loadAddr : i10, out d2_storeEn : i1, out d2_storeAddr : i10, out d2_storeData : i32, out e_loadEn : i1, out e_loadAddr : i10, out e_storeEn : i1, out e_storeAddr : i10, out e_storeData : i32) {
    %fork0.outs_0, %fork0.outs_1, %fork0.outs_2 = hw.instance "fork0" @handshake_fork_0(ins: %start: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.control<>, outs_1: !handshake.control<>, outs_2: !handshake.control<>)
    %non_spec0.dataOut = hw.instance "non_spec0" @handshake_non_spec_0(dataIn: %fork0.outs_2: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (dataOut: !handshake.control<[spec: i1]>)
    %buffer7.outs = hw.instance "buffer7" @handshake_buffer_0(ins: %fork8.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer8.outs = hw.instance "buffer8" @handshake_buffer_1(ins: %fork4.outs_2: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<[spec: i1]>)
    %spec_commit0.outs = hw.instance "spec_commit0" @handshake_spec_commit_0(ins: %buffer8.outs: !handshake.control<[spec: i1]>, ctrl: %buffer7.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %mem_controller3.ldData_0, %mem_controller3.memEnd, %mem_controller3.loadEn, %mem_controller3.loadAddr, %mem_controller3.storeEn, %mem_controller3.storeAddr, %mem_controller3.storeData = hw.instance "mem_controller3" @handshake_mem_controller_0(loadData: %e_loadData: i32, memStart: %e_start: !handshake.control<>, ldAddr_0: %load2.addrOut: !handshake.channel<i10>, ctrlEnd: %spec_commit0.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (ldData_0: !handshake.channel<i32>, memEnd: !handshake.control<>, loadEn: i1, loadAddr: i10, storeEn: i1, storeAddr: i10, storeData: i32)
    %buffer9.outs = hw.instance "buffer9" @handshake_buffer_0(ins: %fork8.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer10.outs = hw.instance "buffer10" @handshake_buffer_1(ins: %fork4.outs_1: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<[spec: i1]>)
    %spec_commit1.outs = hw.instance "spec_commit1" @handshake_spec_commit_0(ins: %buffer10.outs: !handshake.control<[spec: i1]>, ctrl: %buffer9.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %mem_controller4.ldData_0, %mem_controller4.memEnd, %mem_controller4.loadEn, %mem_controller4.loadAddr, %mem_controller4.storeEn, %mem_controller4.storeAddr, %mem_controller4.storeData = hw.instance "mem_controller4" @handshake_mem_controller_1(loadData: %d2_loadData: i32, memStart: %d2_start: !handshake.control<>, ldAddr_0: %load1.addrOut: !handshake.channel<i10>, ctrlEnd: %spec_commit1.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (ldData_0: !handshake.channel<i32>, memEnd: !handshake.control<>, loadEn: i1, loadAddr: i10, storeEn: i1, storeAddr: i10, storeData: i32)
    %buffer11.outs = hw.instance "buffer11" @handshake_buffer_0(ins: %fork8.outs_2: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer12.outs = hw.instance "buffer12" @handshake_buffer_1(ins: %fork4.outs_0: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<[spec: i1]>)
    %spec_commit2.outs = hw.instance "spec_commit2" @handshake_spec_commit_0(ins: %buffer12.outs: !handshake.control<[spec: i1]>, ctrl: %buffer11.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %mem_controller5.ldData_0, %mem_controller5.memEnd, %mem_controller5.loadEn, %mem_controller5.loadAddr, %mem_controller5.storeEn, %mem_controller5.storeAddr, %mem_controller5.storeData = hw.instance "mem_controller5" @handshake_mem_controller_2(loadData: %d1_loadData: i32, memStart: %d1_start: !handshake.control<>, ldAddr_0: %load0.addrOut: !handshake.channel<i10>, ctrlEnd: %spec_commit2.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (ldData_0: !handshake.channel<i32>, memEnd: !handshake.control<>, loadEn: i1, loadAddr: i10, storeEn: i1, storeAddr: i10, storeData: i32)
    %constant0.outs = hw.instance "constant0" @handshake_constant_0(ctrl: %fork0.outs_0: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %extsi3.outs = hw.instance "extsi3" @handshake_extsi_0(ins: %constant0.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %non_spec1.dataOut = hw.instance "non_spec1" @handshake_non_spec_1(dataIn: %extsi3.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (dataOut: !handshake.channel<i32, [spec: i1]>)
    %mux0.outs = hw.instance "mux0" @handshake_mux_0(index: %control_merge0.index: !handshake.channel<i1, [spec: i1]>, ins_0: %non_spec1.dataOut: !handshake.channel<i32, [spec: i1]>, ins_1: %cond_br1.trueOut: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %buffer0.outs = hw.instance "buffer0" @handshake_buffer_2(ins: %mux0.outs: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %buffer1.outs = hw.instance "buffer1" @handshake_buffer_3(ins: %buffer0.outs: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %fork1.outs_0, %fork1.outs_1, %fork1.outs_2, %fork1.outs_3, %fork1.outs_4, %fork1.outs_5 = hw.instance "fork1" @handshake_fork_1(ins: %buffer1.outs: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32, [spec: i1]>, outs_1: !handshake.channel<i32, [spec: i1]>, outs_2: !handshake.channel<i32, [spec: i1]>, outs_3: !handshake.channel<i32, [spec: i1]>, outs_4: !handshake.channel<i32, [spec: i1]>, outs_5: !handshake.channel<i32, [spec: i1]>)
    %trunci0.outs = hw.instance "trunci0" @handshake_trunci_0(ins: %fork1.outs_0: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i10, [spec: i1]>)
    %trunci1.outs = hw.instance "trunci1" @handshake_trunci_0(ins: %fork1.outs_1: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i10, [spec: i1]>)
    %trunci2.outs = hw.instance "trunci2" @handshake_trunci_0(ins: %fork1.outs_2: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i10, [spec: i1]>)
    %control_merge0.outs, %control_merge0.index = hw.instance "control_merge0" @handshake_control_merge_0(ins_0: %non_spec0.dataOut: !handshake.control<[spec: i1]>, ins_1: %cond_br2.trueOut: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<[spec: i1]>, index: !handshake.channel<i1, [spec: i1]>)
    %buffer3.outs = hw.instance "buffer3" @handshake_buffer_4(ins: %control_merge0.outs: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<[spec: i1]>)
    %fork5.outs_0, %fork5.outs_1 = hw.instance "fork5" @handshake_fork_2(ins: %buffer3.outs: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.control<[spec: i1]>, outs_1: !handshake.control<[spec: i1]>)
    %source0.outs = hw.instance "source0" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<[spec: i1]>)
    %constant1.outs = hw.instance "constant1" @handshake_constant_1(ctrl: %source0.outs: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i2, [spec: i1]>)
    %fork2.outs_0, %fork2.outs_1 = hw.instance "fork2" @handshake_fork_3(ins: %constant1.outs: !handshake.channel<i2, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i2, [spec: i1]>, outs_1: !handshake.channel<i2, [spec: i1]>)
    %extsi4.outs = hw.instance "extsi4" @handshake_extsi_1(ins: %fork2.outs_0: !handshake.channel<i2, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i10, [spec: i1]>)
    %extsi1.outs = hw.instance "extsi1" @handshake_extsi_2(ins: %fork2.outs_1: !handshake.channel<i2, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %source1.outs = hw.instance "source1" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<[spec: i1]>)
    %constant5.outs = hw.instance "constant5" @handshake_constant_2(ctrl: %source1.outs: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %source2.outs = hw.instance "source2" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<[spec: i1]>)
    %constant2.outs = hw.instance "constant2" @handshake_constant_3(ctrl: %source2.outs: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i11, [spec: i1]>)
    %extsi2.outs = hw.instance "extsi2" @handshake_extsi_3(ins: %constant2.outs: !handshake.channel<i11, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %load0.addrOut, %load0.dataOut = hw.instance "load0" @handshake_load_0(addrIn: %trunci2.outs: !handshake.channel<i10, [spec: i1]>, dataFromMem: %mem_controller5.ldData_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (addrOut: !handshake.channel<i10>, dataOut: !handshake.channel<i32, [spec: i1]>)
    %addi0.result = hw.instance "addi0" @handshake_addi_0(lhs: %trunci0.outs: !handshake.channel<i10, [spec: i1]>, rhs: %extsi4.outs: !handshake.channel<i10, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i10, [spec: i1]>)
    %load1.addrOut, %load1.dataOut = hw.instance "load1" @handshake_load_1(addrIn: %addi0.result: !handshake.channel<i10, [spec: i1]>, dataFromMem: %mem_controller4.ldData_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (addrOut: !handshake.channel<i10>, dataOut: !handshake.channel<i32, [spec: i1]>)
    %addf0.result = hw.instance "addf0" @handshake_addf_0(lhs: %load0.dataOut: !handshake.channel<i32, [spec: i1]>, rhs: %load1.dataOut: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32, [spec: i1]>)
    %addi1.result = hw.instance "addi1" @handshake_addi_1(lhs: %fork1.outs_5: !handshake.channel<i32, [spec: i1]>, rhs: %extsi1.outs: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32, [spec: i1]>)
    %load2.addrOut, %load2.dataOut = hw.instance "load2" @handshake_load_2(addrIn: %trunci1.outs: !handshake.channel<i10, [spec: i1]>, dataFromMem: %mem_controller3.ldData_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (addrOut: !handshake.channel<i10>, dataOut: !handshake.channel<i32, [spec: i1]>)
    %mulf0.result = hw.instance "mulf0" @handshake_mulf_0(lhs: %addf0.result: !handshake.channel<i32, [spec: i1]>, rhs: %constant5.outs: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32, [spec: i1]>)
    %buffer4.outs = hw.instance "buffer4" @handshake_buffer_5(ins: %load2.dataOut: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %cmpf0.result = hw.instance "cmpf0" @handshake_cmpf_0(lhs: %buffer4.outs: !handshake.channel<i32, [spec: i1]>, rhs: %mulf0.result: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1, [spec: i1]>)
    %buffer2.outs = hw.instance "buffer2" @handshake_buffer_6(ins: %fork1.outs_4: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %cmpi0.result = hw.instance "cmpi0" @handshake_cmpi_0(lhs: %buffer2.outs: !handshake.channel<i32, [spec: i1]>, rhs: %extsi2.outs: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1, [spec: i1]>)
    %andi0.result = hw.instance "andi0" @handshake_andi_0(lhs: %cmpi0.result: !handshake.channel<i1, [spec: i1]>, rhs: %cmpf0.result: !handshake.channel<i1, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1, [spec: i1]>)
    %speculator0.outs, %speculator0.ctrl_save, %speculator0.ctrl_commit, %speculator0.ctrl_sc_save, %speculator0.ctrl_sc_commit, %speculator0.ctrl_sc_branch = hw.instance "speculator0" @handshake_speculator_0(ins: %andi0.result: !handshake.channel<i1, [spec: i1]>, trigger: %fork5.outs_1: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1, [spec: i1]>, ctrl_save: !handshake.channel<i1>, ctrl_commit: !handshake.channel<i1>, ctrl_sc_save: !handshake.channel<i3>, ctrl_sc_commit: !handshake.channel<i3>, ctrl_sc_branch: !handshake.channel<i1>)
    %cond_br5.trueOut, %cond_br5.falseOut = hw.instance "cond_br5" @handshake_cond_br_0(condition: %cond_br4.trueOut: !handshake.channel<i1>, data: %speculator0.ctrl_sc_commit: !handshake.channel<i3>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i3>, falseOut: !handshake.channel<i3>)
    hw.instance "sink7" @handshake_sink_0(ins: %cond_br5.falseOut: !handshake.channel<i3>, clk: %clk: i1, rst: %rst: i1) -> ()
    %merge0.outs = hw.instance "merge0" @handshake_merge_0(ins_0: %speculator0.ctrl_sc_save: !handshake.channel<i3>, ins_1: %cond_br5.trueOut: !handshake.channel<i3>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i3>)
    %fork6.outs_0, %fork6.outs_1, %fork6.outs_2 = hw.instance "fork6" @handshake_fork_4(ins: %merge0.outs: !handshake.channel<i3>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i3>, outs_1: !handshake.channel<i3>, outs_2: !handshake.channel<i3>)
    %fork7.outs_0, %fork7.outs_1, %fork7.outs_2, %fork7.outs_3, %fork7.outs_4 = hw.instance "fork7" @handshake_fork_5(ins: %speculator0.outs: !handshake.channel<i1, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1, [spec: i1]>, outs_1: !handshake.channel<i1, [spec: i1]>, outs_2: !handshake.channel<i1, [spec: i1]>, outs_3: !handshake.channel<i1, [spec: i1]>, outs_4: !handshake.channel<i1, [spec: i1]>)
    hw.instance "sink2" @handshake_sink_1(ins: %speculator0.ctrl_save: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> ()
    %buffer13.outs = hw.instance "buffer13" @handshake_buffer_0(ins: %fork9.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %cond_br0.trueOut, %cond_br0.falseOut = hw.instance "cond_br0" @handshake_cond_br_1(condition: %buffer13.outs: !handshake.channel<i1>, data: %speculator0.ctrl_commit: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i1>, falseOut: !handshake.channel<i1>)
    %fork8.outs_0, %fork8.outs_1, %fork8.outs_2, %fork8.outs_3 = hw.instance "fork8" @handshake_fork_6(ins: %cond_br0.falseOut: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>, outs_3: !handshake.channel<i1>)
    hw.instance "sink3" @handshake_sink_1(ins: %cond_br0.trueOut: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> ()
    %speculating_branch0.trueOut, %speculating_branch0.falseOut = hw.instance "speculating_branch0" @handshake_speculating_branch_0(spec_tag_data: %fork7.outs_0: !handshake.channel<i1, [spec: i1]>, data: %fork7.outs_3: !handshake.channel<i1, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i1>, falseOut: !handshake.channel<i1>)
    hw.instance "sink4" @handshake_sink_1(ins: %speculating_branch0.falseOut: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> ()
    %buffer5.outs = hw.instance "buffer5" @handshake_buffer_7(ins: %speculating_branch0.trueOut: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %fork9.outs_0, %fork9.outs_1 = hw.instance "fork9" @handshake_fork_7(ins: %buffer5.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>)
    %buffer14.outs = hw.instance "buffer14" @handshake_buffer_0(ins: %fork9.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %cond_br4.trueOut, %cond_br4.falseOut = hw.instance "cond_br4" @handshake_cond_br_1(condition: %speculator0.ctrl_sc_branch: !handshake.channel<i1>, data: %buffer14.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i1>, falseOut: !handshake.channel<i1>)
    hw.instance "sink5" @handshake_sink_1(ins: %cond_br4.falseOut: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> ()
    %spec_save_commit0.outs = hw.instance "spec_save_commit0" @handshake_spec_save_commit_0(ins: %addi1.result: !handshake.channel<i32, [spec: i1]>, ctrl: %fork6.outs_2: !handshake.channel<i3>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %cond_br1.trueOut, %cond_br1.falseOut = hw.instance "cond_br1" @handshake_cond_br_2(condition: %fork7.outs_4: !handshake.channel<i1, [spec: i1]>, data: %spec_save_commit0.outs: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32, [spec: i1]>, falseOut: !handshake.channel<i32, [spec: i1]>)
    hw.instance "sink0" @handshake_sink_2(ins: %cond_br1.falseOut: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> ()
    %spec_save_commit1.outs = hw.instance "spec_save_commit1" @handshake_spec_save_commit_1(ins: %fork5.outs_0: !handshake.control<[spec: i1]>, ctrl: %fork6.outs_1: !handshake.channel<i3>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<[spec: i1]>)
    %cond_br2.trueOut, %cond_br2.falseOut = hw.instance "cond_br2" @handshake_cond_br_3(condition: %fork7.outs_2: !handshake.channel<i1, [spec: i1]>, data: %spec_save_commit1.outs: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.control<[spec: i1]>, falseOut: !handshake.control<[spec: i1]>)
    %spec_save_commit2.outs = hw.instance "spec_save_commit2" @handshake_spec_save_commit_0(ins: %fork1.outs_3: !handshake.channel<i32, [spec: i1]>, ctrl: %fork6.outs_0: !handshake.channel<i3>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %cond_br3.trueOut, %cond_br3.falseOut = hw.instance "cond_br3" @handshake_cond_br_2(condition: %fork7.outs_1: !handshake.channel<i1, [spec: i1]>, data: %spec_save_commit2.outs: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32, [spec: i1]>, falseOut: !handshake.channel<i32, [spec: i1]>)
    hw.instance "sink1" @handshake_sink_2(ins: %cond_br3.trueOut: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> ()
    %fork4.outs_0, %fork4.outs_1, %fork4.outs_2 = hw.instance "fork4" @handshake_fork_8(ins: %cond_br2.falseOut: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.control<[spec: i1]>, outs_1: !handshake.control<[spec: i1]>, outs_2: !handshake.control<[spec: i1]>)
    %buffer6.outs = hw.instance "buffer6" @handshake_buffer_6(ins: %cond_br3.falseOut: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %buffer15.outs = hw.instance "buffer15" @handshake_buffer_0(ins: %fork8.outs_3: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer16.outs = hw.instance "buffer16" @handshake_buffer_8(ins: %buffer6.outs: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %spec_commit3.outs = hw.instance "spec_commit3" @handshake_spec_commit_1(ins: %buffer16.outs: !handshake.channel<i32, [spec: i1]>, ctrl: %buffer15.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    hw.output %spec_commit3.outs, %mem_controller5.memEnd, %mem_controller4.memEnd, %mem_controller3.memEnd, %fork0.outs_1, %mem_controller5.loadEn, %mem_controller5.loadAddr, %mem_controller5.storeEn, %mem_controller5.storeAddr, %mem_controller5.storeData, %mem_controller4.loadEn, %mem_controller4.loadAddr, %mem_controller4.storeEn, %mem_controller4.storeAddr, %mem_controller4.storeData, %mem_controller3.loadEn, %mem_controller3.loadAddr, %mem_controller3.storeEn, %mem_controller3.storeAddr, %mem_controller3.storeData : !handshake.channel<i32>, !handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>, i1, i10, i1, i10, i32, i1, i10, i1, i10, i32, i1, i10, i1, i10, i32
  }
  hw.module.extern @handshake_fork_0(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.control<>, out outs_1 : !handshake.control<>, out outs_2 : !handshake.control<>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.control<>, SIZE = 3 : ui32}}
  hw.module.extern @handshake_non_spec_0(in %dataIn : !handshake.control<>, in %clk : i1, in %rst : i1, out dataOut : !handshake.control<[spec: i1]>) attributes {hw.name = "handshake.non_spec", hw.parameters = {}}
  hw.module.extern @handshake_buffer_0(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i1>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_buffer_1(in %ins : !handshake.control<[spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.control<[spec: i1]>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.control<[spec: i1]>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_spec_commit_0(in %ins : !handshake.control<[spec: i1]>, in %ctrl : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.control<>) attributes {hw.name = "handshake.spec_commit", hw.parameters = {}}
  hw.module.extern @handshake_mem_controller_0(in %loadData : i32, in %memStart : !handshake.control<>, in %ldAddr_0 : !handshake.channel<i10>, in %ctrlEnd : !handshake.control<>, in %clk : i1, in %rst : i1, out ldData_0 : !handshake.channel<i32>, out memEnd : !handshake.control<>, out loadEn : i1, out loadAddr : i10, out storeEn : i1, out storeAddr : i10, out storeData : i32) attributes {hw.name = "handshake.mem_controller", hw.parameters = {ADDR_TYPE = !handshake.channel<i10>, DATA_TYPE = !handshake.channel<i32>, NUM_CONTROLS = 0 : ui32, NUM_LOADS = 1 : ui32, NUM_STORES = 0 : ui32}}
  hw.module.extern @handshake_mem_controller_1(in %loadData : i32, in %memStart : !handshake.control<>, in %ldAddr_0 : !handshake.channel<i10>, in %ctrlEnd : !handshake.control<>, in %clk : i1, in %rst : i1, out ldData_0 : !handshake.channel<i32>, out memEnd : !handshake.control<>, out loadEn : i1, out loadAddr : i10, out storeEn : i1, out storeAddr : i10, out storeData : i32) attributes {hw.name = "handshake.mem_controller", hw.parameters = {ADDR_TYPE = !handshake.channel<i10>, DATA_TYPE = !handshake.channel<i32>, NUM_CONTROLS = 0 : ui32, NUM_LOADS = 1 : ui32, NUM_STORES = 0 : ui32}}
  hw.module.extern @handshake_mem_controller_2(in %loadData : i32, in %memStart : !handshake.control<>, in %ldAddr_0 : !handshake.channel<i10>, in %ctrlEnd : !handshake.control<>, in %clk : i1, in %rst : i1, out ldData_0 : !handshake.channel<i32>, out memEnd : !handshake.control<>, out loadEn : i1, out loadAddr : i10, out storeEn : i1, out storeAddr : i10, out storeData : i32) attributes {hw.name = "handshake.mem_controller", hw.parameters = {ADDR_TYPE = !handshake.channel<i10>, DATA_TYPE = !handshake.channel<i32>, NUM_CONTROLS = 0 : ui32, NUM_LOADS = 1 : ui32, NUM_STORES = 0 : ui32}}
  hw.module.extern @handshake_constant_0(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 1 : ui32, VALUE = "0"}}
  hw.module.extern @handshake_extsi_0(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i1>, OUTPUT_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_non_spec_1(in %dataIn : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out dataOut : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.non_spec", hw.parameters = {}}
  hw.module.extern @handshake_mux_0(in %index : !handshake.channel<i1, [spec: i1]>, in %ins_0 : !handshake.channel<i32, [spec: i1]>, in %ins_1 : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<i32, [spec: i1]>, SELECT_TYPE = !handshake.channel<i1, [spec: i1]>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_2(in %ins : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<i32, [spec: i1]>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_buffer_3(in %ins : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.channel<i32, [spec: i1]>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_fork_1(in %ins : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32, [spec: i1]>, out outs_1 : !handshake.channel<i32, [spec: i1]>, out outs_2 : !handshake.channel<i32, [spec: i1]>, out outs_3 : !handshake.channel<i32, [spec: i1]>, out outs_4 : !handshake.channel<i32, [spec: i1]>, out outs_5 : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i32, [spec: i1]>, SIZE = 6 : ui32}}
  hw.module.extern @handshake_trunci_0(in %ins : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i10, [spec: i1]>) attributes {hw.name = "handshake.trunci", hw.parameters = {INPUT_TYPE = !handshake.channel<i32, [spec: i1]>, OUTPUT_TYPE = !handshake.channel<i10, [spec: i1]>}}
  hw.module.extern @handshake_control_merge_0(in %ins_0 : !handshake.control<[spec: i1]>, in %ins_1 : !handshake.control<[spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.control<[spec: i1]>, out index : !handshake.channel<i1, [spec: i1]>) attributes {hw.name = "handshake.control_merge", hw.parameters = {DATA_TYPE = !handshake.control<[spec: i1]>, INDEX_TYPE = !handshake.channel<i1, [spec: i1]>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_4(in %ins : !handshake.control<[spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.control<[spec: i1]>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.control<[spec: i1]>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_fork_2(in %ins : !handshake.control<[spec: i1]>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.control<[spec: i1]>, out outs_1 : !handshake.control<[spec: i1]>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.control<[spec: i1]>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_source_0(in %clk : i1, in %rst : i1, out outs : !handshake.control<[spec: i1]>) attributes {hw.name = "handshake.source", hw.parameters = {}}
  hw.module.extern @handshake_constant_1(in %ctrl : !handshake.control<[spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i2, [spec: i1]>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 2 : ui32, VALUE = "01"}}
  hw.module.extern @handshake_fork_3(in %ins : !handshake.channel<i2, [spec: i1]>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i2, [spec: i1]>, out outs_1 : !handshake.channel<i2, [spec: i1]>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i2, [spec: i1]>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_extsi_1(in %ins : !handshake.channel<i2, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i10, [spec: i1]>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i2, [spec: i1]>, OUTPUT_TYPE = !handshake.channel<i10, [spec: i1]>}}
  hw.module.extern @handshake_extsi_2(in %ins : !handshake.channel<i2, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i2, [spec: i1]>, OUTPUT_TYPE = !handshake.channel<i32, [spec: i1]>}}
  hw.module.extern @handshake_constant_2(in %ctrl : !handshake.control<[spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 32 : ui32, VALUE = "00111010100000110001001001101111"}}
  hw.module.extern @handshake_constant_3(in %ctrl : !handshake.control<[spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i11, [spec: i1]>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 11 : ui32, VALUE = "01111100110"}}
  hw.module.extern @handshake_extsi_3(in %ins : !handshake.channel<i11, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i11, [spec: i1]>, OUTPUT_TYPE = !handshake.channel<i32, [spec: i1]>}}
  hw.module.extern @handshake_load_0(in %addrIn : !handshake.channel<i10, [spec: i1]>, in %dataFromMem : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out addrOut : !handshake.channel<i10>, out dataOut : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.load", hw.parameters = {ADDR_TYPE = !handshake.channel<i10, [spec: i1]>, DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_addi_0(in %lhs : !handshake.channel<i10, [spec: i1]>, in %rhs : !handshake.channel<i10, [spec: i1]>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i10, [spec: i1]>) attributes {hw.name = "handshake.addi", hw.parameters = {DATA_TYPE = !handshake.channel<i10, [spec: i1]>}}
  hw.module.extern @handshake_load_1(in %addrIn : !handshake.channel<i10, [spec: i1]>, in %dataFromMem : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out addrOut : !handshake.channel<i10>, out dataOut : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.load", hw.parameters = {ADDR_TYPE = !handshake.channel<i10, [spec: i1]>, DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_addf_0(in %lhs : !handshake.channel<i32, [spec: i1]>, in %rhs : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.addf", hw.parameters = {DATA_TYPE = !handshake.channel<f32, [spec: i1]>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "2_922000"}}
  hw.module.extern @handshake_addi_1(in %lhs : !handshake.channel<i32, [spec: i1]>, in %rhs : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.addi", hw.parameters = {DATA_TYPE = !handshake.channel<i32, [spec: i1]>}}
  hw.module.extern @handshake_load_2(in %addrIn : !handshake.channel<i10, [spec: i1]>, in %dataFromMem : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out addrOut : !handshake.channel<i10>, out dataOut : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.load", hw.parameters = {ADDR_TYPE = !handshake.channel<i10, [spec: i1]>, DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_mulf_0(in %lhs : !handshake.channel<i32, [spec: i1]>, in %rhs : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.mulf", hw.parameters = {DATA_TYPE = !handshake.channel<f32, [spec: i1]>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "2_875333"}}
  hw.module.extern @handshake_buffer_5(in %ins : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<f32, [spec: i1]>, DEBUG_COUNTER = false, NUM_SLOTS = 13 : ui32}}
  hw.module.extern @handshake_cmpf_0(in %lhs : !handshake.channel<i32, [spec: i1]>, in %rhs : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1, [spec: i1]>) attributes {hw.name = "handshake.cmpf", hw.parameters = {DATA_TYPE = !handshake.channel<f32, [spec: i1]>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "0_000000", PREDICATE = "ugt"}}
  hw.module.extern @handshake_buffer_6(in %ins : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i32, [spec: i1]>, DEBUG_COUNTER = false, NUM_SLOTS = 14 : ui32}}
  hw.module.extern @handshake_cmpi_0(in %lhs : !handshake.channel<i32, [spec: i1]>, in %rhs : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1, [spec: i1]>) attributes {hw.name = "handshake.cmpi", hw.parameters = {DATA_TYPE = !handshake.channel<i32, [spec: i1]>, PREDICATE = "ult"}}
  hw.module.extern @handshake_andi_0(in %lhs : !handshake.channel<i1, [spec: i1]>, in %rhs : !handshake.channel<i1, [spec: i1]>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1, [spec: i1]>) attributes {hw.name = "handshake.andi", hw.parameters = {DATA_TYPE = !handshake.channel<i1, [spec: i1]>}}
  hw.module.extern @handshake_speculator_0(in %ins : !handshake.channel<i1, [spec: i1]>, in %trigger : !handshake.control<[spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1, [spec: i1]>, out ctrl_save : !handshake.channel<i1>, out ctrl_commit : !handshake.channel<i1>, out ctrl_sc_save : !handshake.channel<i3>, out ctrl_sc_commit : !handshake.channel<i3>, out ctrl_sc_branch : !handshake.channel<i1>) attributes {hw.name = "handshake.speculator", hw.parameters = {CONSTANT = true, DEFAULT_VALUE = 1 : ui32, FIFO_DEPTH = 16 : ui32}}
  hw.module.extern @handshake_cond_br_0(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i3>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i3>, out falseOut : !handshake.channel<i3>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<i3>}}
  hw.module.extern @handshake_sink_0(in %ins : !handshake.channel<i3>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.channel<i3>}}
  hw.module.extern @handshake_merge_0(in %ins_0 : !handshake.channel<i3>, in %ins_1 : !handshake.channel<i3>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i3>) attributes {hw.name = "handshake.merge", hw.parameters = {DATA_TYPE = !handshake.channel<i3>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_fork_4(in %ins : !handshake.channel<i3>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i3>, out outs_1 : !handshake.channel<i3>, out outs_2 : !handshake.channel<i3>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i3>, SIZE = 3 : ui32}}
  hw.module.extern @handshake_fork_5(in %ins : !handshake.channel<i1, [spec: i1]>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1, [spec: i1]>, out outs_1 : !handshake.channel<i1, [spec: i1]>, out outs_2 : !handshake.channel<i1, [spec: i1]>, out outs_3 : !handshake.channel<i1, [spec: i1]>, out outs_4 : !handshake.channel<i1, [spec: i1]>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1, [spec: i1]>, SIZE = 5 : ui32}}
  hw.module.extern @handshake_sink_1(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.channel<i1>}}
  hw.module.extern @handshake_cond_br_1(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i1>, out falseOut : !handshake.channel<i1>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<i1>}}
  hw.module.extern @handshake_fork_6(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>, out outs_2 : !handshake.channel<i1>, out outs_3 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 4 : ui32}}
  hw.module.extern @handshake_speculating_branch_0(in %spec_tag_data : !handshake.channel<i1, [spec: i1]>, in %data : !handshake.channel<i1, [spec: i1]>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i1>, out falseOut : !handshake.channel<i1>) attributes {hw.name = "handshake.speculating_branch", hw.parameters = {}}
  hw.module.extern @handshake_buffer_7(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i1>, DEBUG_COUNTER = false, NUM_SLOTS = 14 : ui32}}
  hw.module.extern @handshake_fork_7(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_spec_save_commit_0(in %ins : !handshake.channel<i32, [spec: i1]>, in %ctrl : !handshake.channel<i3>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.spec_save_commit", hw.parameters = {FIFO_DEPTH = 16 : ui32}}
  hw.module.extern @handshake_cond_br_2(in %condition : !handshake.channel<i1, [spec: i1]>, in %data : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i32, [spec: i1]>, out falseOut : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<i32, [spec: i1]>}}
  hw.module.extern @handshake_sink_2(in %ins : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.channel<i32, [spec: i1]>}}
  hw.module.extern @handshake_spec_save_commit_1(in %ins : !handshake.control<[spec: i1]>, in %ctrl : !handshake.channel<i3>, in %clk : i1, in %rst : i1, out outs : !handshake.control<[spec: i1]>) attributes {hw.name = "handshake.spec_save_commit", hw.parameters = {FIFO_DEPTH = 16 : ui32}}
  hw.module.extern @handshake_cond_br_3(in %condition : !handshake.channel<i1, [spec: i1]>, in %data : !handshake.control<[spec: i1]>, in %clk : i1, in %rst : i1, out trueOut : !handshake.control<[spec: i1]>, out falseOut : !handshake.control<[spec: i1]>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.control<[spec: i1]>}}
  hw.module.extern @handshake_fork_8(in %ins : !handshake.control<[spec: i1]>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.control<[spec: i1]>, out outs_1 : !handshake.control<[spec: i1]>, out outs_2 : !handshake.control<[spec: i1]>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.control<[spec: i1]>, SIZE = 3 : ui32}}
  hw.module.extern @handshake_buffer_8(in %ins : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i32, [spec: i1]>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_spec_commit_1(in %ins : !handshake.channel<i32, [spec: i1]>, in %ctrl : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.spec_commit", hw.parameters = {}}
  hw.module.extern @mem_to_bram_32_10(in %loadEn : i1, in %loadAddr : i10, in %storeEn : i1, in %storeAddr : i10, in %storeData : i32, in %din0 : i32, in %din1 : i32, out ce0 : i1, out we0 : i1, out address0 : i10, out dout0 : i32, out ce1 : i1, out we1 : i1, out address1 : i10, out dout1 : i32, out loadData : i32) attributes {hw.name = "mem_to_bram", hw.parameters = {ADDR_WIDTH = 10 : ui32, DATA_WIDTH = 32 : ui32}}
  hw.module @subdiag_fast_wrapper(in %d1_din0 : i32, in %d1_din1 : i32, in %d2_din0 : i32, in %d2_din1 : i32, in %e_din0 : i32, in %e_din1 : i32, in %d1_start : !handshake.control<>, in %d2_start : !handshake.control<>, in %e_start : !handshake.control<>, in %start : !handshake.control<>, in %clk : i1, in %rst : i1, out out0 : !handshake.channel<i32>, out d1_end : !handshake.control<>, out d2_end : !handshake.control<>, out e_end : !handshake.control<>, out end : !handshake.control<>, out d1_ce0 : i1, out d1_we0 : i1, out d1_address0 : i10, out d1_dout0 : i32, out d1_ce1 : i1, out d1_we1 : i1, out d1_address1 : i10, out d1_dout1 : i32, out d2_ce0 : i1, out d2_we0 : i1, out d2_address0 : i10, out d2_dout0 : i32, out d2_ce1 : i1, out d2_we1 : i1, out d2_address1 : i10, out d2_dout1 : i32, out e_ce0 : i1, out e_we0 : i1, out e_address0 : i10, out e_dout0 : i32, out e_ce1 : i1, out e_we1 : i1, out e_address1 : i10, out e_dout1 : i32) {
    %mem_to_bram_converter_d2.ce0, %mem_to_bram_converter_d2.we0, %mem_to_bram_converter_d2.address0, %mem_to_bram_converter_d2.dout0, %mem_to_bram_converter_d2.ce1, %mem_to_bram_converter_d2.we1, %mem_to_bram_converter_d2.address1, %mem_to_bram_converter_d2.dout1, %mem_to_bram_converter_d2.loadData = hw.instance "mem_to_bram_converter_d2" @mem_to_bram_32_10(loadEn: %subdiag_fast_wrapped.d2_loadEn: i1, loadAddr: %subdiag_fast_wrapped.d2_loadAddr: i10, storeEn: %subdiag_fast_wrapped.d2_storeEn: i1, storeAddr: %subdiag_fast_wrapped.d2_storeAddr: i10, storeData: %subdiag_fast_wrapped.d2_storeData: i32, din0: %d2_din0: i32, din1: %d2_din1: i32) -> (ce0: i1, we0: i1, address0: i10, dout0: i32, ce1: i1, we1: i1, address1: i10, dout1: i32, loadData: i32)
    %mem_to_bram_converter_d1.ce0, %mem_to_bram_converter_d1.we0, %mem_to_bram_converter_d1.address0, %mem_to_bram_converter_d1.dout0, %mem_to_bram_converter_d1.ce1, %mem_to_bram_converter_d1.we1, %mem_to_bram_converter_d1.address1, %mem_to_bram_converter_d1.dout1, %mem_to_bram_converter_d1.loadData = hw.instance "mem_to_bram_converter_d1" @mem_to_bram_32_10(loadEn: %subdiag_fast_wrapped.d1_loadEn: i1, loadAddr: %subdiag_fast_wrapped.d1_loadAddr: i10, storeEn: %subdiag_fast_wrapped.d1_storeEn: i1, storeAddr: %subdiag_fast_wrapped.d1_storeAddr: i10, storeData: %subdiag_fast_wrapped.d1_storeData: i32, din0: %d1_din0: i32, din1: %d1_din1: i32) -> (ce0: i1, we0: i1, address0: i10, dout0: i32, ce1: i1, we1: i1, address1: i10, dout1: i32, loadData: i32)
    %mem_to_bram_converter_e.ce0, %mem_to_bram_converter_e.we0, %mem_to_bram_converter_e.address0, %mem_to_bram_converter_e.dout0, %mem_to_bram_converter_e.ce1, %mem_to_bram_converter_e.we1, %mem_to_bram_converter_e.address1, %mem_to_bram_converter_e.dout1, %mem_to_bram_converter_e.loadData = hw.instance "mem_to_bram_converter_e" @mem_to_bram_32_10(loadEn: %subdiag_fast_wrapped.e_loadEn: i1, loadAddr: %subdiag_fast_wrapped.e_loadAddr: i10, storeEn: %subdiag_fast_wrapped.e_storeEn: i1, storeAddr: %subdiag_fast_wrapped.e_storeAddr: i10, storeData: %subdiag_fast_wrapped.e_storeData: i32, din0: %e_din0: i32, din1: %e_din1: i32) -> (ce0: i1, we0: i1, address0: i10, dout0: i32, ce1: i1, we1: i1, address1: i10, dout1: i32, loadData: i32)
    %subdiag_fast_wrapped.out0, %subdiag_fast_wrapped.d1_end, %subdiag_fast_wrapped.d2_end, %subdiag_fast_wrapped.e_end, %subdiag_fast_wrapped.end, %subdiag_fast_wrapped.d1_loadEn, %subdiag_fast_wrapped.d1_loadAddr, %subdiag_fast_wrapped.d1_storeEn, %subdiag_fast_wrapped.d1_storeAddr, %subdiag_fast_wrapped.d1_storeData, %subdiag_fast_wrapped.d2_loadEn, %subdiag_fast_wrapped.d2_loadAddr, %subdiag_fast_wrapped.d2_storeEn, %subdiag_fast_wrapped.d2_storeAddr, %subdiag_fast_wrapped.d2_storeData, %subdiag_fast_wrapped.e_loadEn, %subdiag_fast_wrapped.e_loadAddr, %subdiag_fast_wrapped.e_storeEn, %subdiag_fast_wrapped.e_storeAddr, %subdiag_fast_wrapped.e_storeData = hw.instance "subdiag_fast_wrapped" @subdiag_fast(d1_loadData: %mem_to_bram_converter_d1.loadData: i32, d2_loadData: %mem_to_bram_converter_d2.loadData: i32, e_loadData: %mem_to_bram_converter_e.loadData: i32, d1_start: %d1_start: !handshake.control<>, d2_start: %d2_start: !handshake.control<>, e_start: %e_start: !handshake.control<>, start: %start: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (out0: !handshake.channel<i32>, d1_end: !handshake.control<>, d2_end: !handshake.control<>, e_end: !handshake.control<>, end: !handshake.control<>, d1_loadEn: i1, d1_loadAddr: i10, d1_storeEn: i1, d1_storeAddr: i10, d1_storeData: i32, d2_loadEn: i1, d2_loadAddr: i10, d2_storeEn: i1, d2_storeAddr: i10, d2_storeData: i32, e_loadEn: i1, e_loadAddr: i10, e_storeEn: i1, e_storeAddr: i10, e_storeData: i32)
    hw.output %subdiag_fast_wrapped.out0, %subdiag_fast_wrapped.d1_end, %subdiag_fast_wrapped.d2_end, %subdiag_fast_wrapped.e_end, %subdiag_fast_wrapped.end, %mem_to_bram_converter_d1.ce0, %mem_to_bram_converter_d1.we0, %mem_to_bram_converter_d1.address0, %mem_to_bram_converter_d1.dout0, %mem_to_bram_converter_d1.ce1, %mem_to_bram_converter_d1.we1, %mem_to_bram_converter_d1.address1, %mem_to_bram_converter_d1.dout1, %mem_to_bram_converter_d2.ce0, %mem_to_bram_converter_d2.we0, %mem_to_bram_converter_d2.address0, %mem_to_bram_converter_d2.dout0, %mem_to_bram_converter_d2.ce1, %mem_to_bram_converter_d2.we1, %mem_to_bram_converter_d2.address1, %mem_to_bram_converter_d2.dout1, %mem_to_bram_converter_e.ce0, %mem_to_bram_converter_e.we0, %mem_to_bram_converter_e.address0, %mem_to_bram_converter_e.dout0, %mem_to_bram_converter_e.ce1, %mem_to_bram_converter_e.we1, %mem_to_bram_converter_e.address1, %mem_to_bram_converter_e.dout1 : !handshake.channel<i32>, !handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>, i1, i1, i10, i32, i1, i1, i10, i32, i1, i1, i10, i32, i1, i1, i10, i32, i1, i1, i10, i32, i1, i1, i10, i32
  }
}

