// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py
// RUN: dynamatic-opt --exp-lower-std-to-handshake-fpl22 %s --split-input-file | FileCheck %s

// CHECK-LABEL:   handshake.func @test1(
// CHECK-SAME:                          %[[VAL_0:.*]]: i32,
// CHECK-SAME:                          %[[VAL_1:.*]]: i1,
// CHECK-SAME:                          %[[VAL_2:.*]]: none, ...) -> none attributes {argNames = ["in0", "in1", "in2"], resNames = ["out0"]} {
// CHECK:           %[[VAL_3:.*]] = merge %[[VAL_0]] : i32
// CHECK:           %[[VAL_4:.*]] = merge %[[VAL_1]] : i1
// CHECK:           %[[VAL_5:.*]] = merge %[[VAL_2]] : none
// CHECK:           %[[VAL_6:.*]] = constant %[[VAL_5]] {value = 0 : i32} : i32
// CHECK:           %[[VAL_7:.*]] = merge %[[VAL_6]], %[[VAL_3]] : i32
// CHECK:           %[[VAL_8:.*]] = d_return %[[VAL_5]] : none
// CHECK:           end %[[VAL_8]] : none
// CHECK:         }
func.func @test1(%arg0 : i32, %arg1: i1) {
  %cst = arith.constant 0 : i32
  cf.cond_br %arg1, ^bb1, ^bb2(%arg0 : i32)
  ^bb1:
    cf.br ^bb2(%cst : i32)
  ^bb2(%x : i32):
    return
}

// -----

// CHECK-LABEL:   handshake.func @test2(
// CHECK-SAME:                          %[[VAL_0:.*]]: i32,
// CHECK-SAME:                          %[[VAL_1:.*]]: i1,
// CHECK-SAME:                          %[[VAL_2:.*]]: none, ...) -> none attributes {argNames = ["in0", "in1", "in2"], resNames = ["out0"]} {
// CHECK:           %[[VAL_3:.*]] = merge %[[VAL_0]] : i32
// CHECK:           %[[VAL_4:.*]] = merge %[[VAL_1]] : i1
// CHECK:           %[[VAL_5:.*]] = merge %[[VAL_2]] : none
// CHECK:           %[[VAL_6:.*]] = constant %[[VAL_5]] {value = 1 : i32} : i32
// CHECK:           %[[VAL_7:.*]] = arith.addi %[[VAL_3]], %[[VAL_6]] : i32
// CHECK:           %[[VAL_8:.*]] = merge %[[VAL_9:.*]], %[[VAL_7]] : i32
// CHECK:           %[[VAL_10:.*]] = merge %[[VAL_6]], %[[VAL_11:.*]] : i32
// CHECK:           %[[VAL_11]], %[[VAL_12:.*]] = cond_br %[[VAL_13:.*]], %[[VAL_10]] : i32
// CHECK:           %[[VAL_14:.*]] = merge %[[VAL_5]], %[[VAL_15:.*]] : none
// CHECK:           %[[VAL_15]], %[[VAL_16:.*]] = cond_br %[[VAL_13]], %[[VAL_14]] : none
// CHECK:           %[[VAL_13]] = merge %[[VAL_4]], %[[VAL_17:.*]] : i1
// CHECK:           %[[VAL_17]], %[[VAL_18:.*]] = cond_br %[[VAL_13]], %[[VAL_13]] : i1
// CHECK:           %[[VAL_19:.*]] = merge %[[VAL_8]] : i32
// CHECK:           %[[VAL_20:.*]] = arith.addi %[[VAL_19]], %[[VAL_10]] : i32
// CHECK:           %[[VAL_21:.*]] = constant %[[VAL_14]] {value = 38 : i32} : i32
// CHECK:           %[[VAL_22:.*]] = arith.addi %[[VAL_21]], %[[VAL_21]] : i32
// CHECK:           %[[VAL_9]] = br %[[VAL_20]] : i32
// CHECK:           %[[VAL_23:.*]] = d_return %[[VAL_5]] : none
// CHECK:           end %[[VAL_23]] : none
// CHECK:         }
func.func @test2(%arg0 : i32, %arg1 : i1) {
  %cst = arith.constant 1 : i32
  %add = arith.addi %arg0, %cst : i32
  cf.br ^bb1(%add : i32)
^bb1(%x : i32):
  cf.cond_br %arg1, ^bb2(%x: i32), ^bb3
^bb2(%y : i32):
  %add2 = arith.addi %y, %cst : i32
  %cst2 = arith.constant 38 : i32
  %add3 = arith.addi %cst2, %cst2 : i32
  cf.br ^bb1(%add2 : i32)
^bb3:
  return
}

// -----

// CHECK-LABEL:   handshake.func @test3(
// CHECK-SAME:                          %[[VAL_0:.*]]: none, ...) -> none attributes {argNames = ["in0"], resNames = ["out0"]} {
// CHECK:           %[[VAL_1:.*]] = merge %[[VAL_0]] : none
// CHECK:           %[[VAL_2:.*]] = constant %[[VAL_1]] {value = false} : i1
// CHECK:           %[[VAL_3:.*]] = constant %[[VAL_1]] {value = 378 : i32} : i32
// CHECK:           %[[VAL_4:.*]] = constant %[[VAL_1]] {value = 121378 : i32} : i32
// CHECK:           %[[VAL_5:.*]] = merge %[[VAL_6:.*]], %[[VAL_3]] : i32
// CHECK:           %[[VAL_6]] = merge %[[VAL_3]], %[[VAL_7:.*]] : i32
// CHECK:           %[[VAL_7]], %[[VAL_8:.*]] = cond_br %[[VAL_9:.*]], %[[VAL_6]] : i32
// CHECK:           %[[VAL_9]] = merge %[[VAL_2]], %[[VAL_10:.*]] : i1
// CHECK:           %[[VAL_10]], %[[VAL_11:.*]] = cond_br %[[VAL_9]], %[[VAL_9]] : i1
// CHECK:           %[[VAL_12:.*]] = arith.addi %[[VAL_6]], %[[VAL_5]] : i32
// CHECK:           %[[VAL_13:.*]] = arith.addi %[[VAL_6]], %[[VAL_5]] : i32
// CHECK:           %[[VAL_14:.*]] = merge %[[VAL_12]] : i32
// CHECK:           %[[VAL_15:.*]] = d_return %[[VAL_1]] : none
// CHECK:           end %[[VAL_15]] : none
// CHECK:         }
func.func @test3() {
  %b = arith.constant 0 : i1
  %n = arith.constant 378 : i32
  %n1 = arith.constant 121378 : i32
  cf.br ^bb1
^bb1:
  cf.br ^bb2(%n : i32)
^bb2(%n2 : i32):
  %add = arith.addi %n, %n2 : i32
  %add2 = arith.addi %n, %n2 : i32
  cf.cond_br %b, ^bb3(%add: i32), ^bb4
^bb3(%y : i32):
  cf.br ^bb2(%n : i32)
^bb4:
  return
}

// -----

// CHECK-LABEL:   handshake.func @test4(
// CHECK-SAME:                          %[[VAL_0:.*]]: i32,
// CHECK-SAME:                          %[[VAL_1:.*]]: none, ...) -> none attributes {argNames = ["in0", "in1"], resNames = ["out0"]} {
// CHECK:           %[[VAL_2:.*]] = merge %[[VAL_0]] : i32
// CHECK:           %[[VAL_3:.*]] = merge %[[VAL_1]] : none
// CHECK:           %[[VAL_4:.*]] = constant %[[VAL_3]] {value = false} : i1
// CHECK:           %[[VAL_5:.*]] = constant %[[VAL_3]] {value = 378 : i32} : i32
// CHECK:           %[[VAL_6:.*]] = merge %[[VAL_5]], %[[VAL_7:.*]] : i32
// CHECK:           %[[VAL_7]], %[[VAL_8:.*]] = cond_br %[[VAL_9:.*]], %[[VAL_6]] : i32
// CHECK:           %[[VAL_10:.*]] = merge %[[VAL_4]], %[[VAL_11:.*]] : i1
// CHECK:           %[[VAL_11]], %[[VAL_12:.*]] = cond_br %[[VAL_9]], %[[VAL_10]] : i1
// CHECK:           %[[VAL_13:.*]] = merge %[[VAL_3]], %[[VAL_14:.*]] : none
// CHECK:           %[[VAL_14]], %[[VAL_15:.*]] = cond_br %[[VAL_9]], %[[VAL_13]] : none
// CHECK:           %[[VAL_16:.*]] = merge %[[VAL_2]], %[[VAL_17:.*]] : i32
// CHECK:           %[[VAL_17]], %[[VAL_18:.*]] = cond_br %[[VAL_9]], %[[VAL_16]] : i32
// CHECK:           %[[VAL_19:.*]] = constant %[[VAL_13]] {value = 121378 : i32} : i32
// CHECK:           %[[VAL_9]] = constant %[[VAL_13]] {value = false} : i1
// CHECK:           %[[VAL_20:.*]] = merge %[[VAL_21:.*]], %[[VAL_6]] : i32
// CHECK:           %[[VAL_22:.*]] = merge %[[VAL_6]], %[[VAL_23:.*]] : i32
// CHECK:           %[[VAL_24:.*]], %[[VAL_23]] = cond_br %[[VAL_25:.*]], %[[VAL_22]] : i32
// CHECK:           %[[VAL_25]] = merge %[[VAL_10]], %[[VAL_26:.*]] : i1
// CHECK:           %[[VAL_27:.*]], %[[VAL_26]] = cond_br %[[VAL_25]], %[[VAL_25]] : i1
// CHECK:           %[[VAL_28:.*]] = merge %[[VAL_13]], %[[VAL_29:.*]] : none
// CHECK:           %[[VAL_30:.*]], %[[VAL_29]] = cond_br %[[VAL_25]], %[[VAL_28]] : none
// CHECK:           %[[VAL_31:.*]] = merge %[[VAL_16]], %[[VAL_32:.*]] : i32
// CHECK:           %[[VAL_33:.*]], %[[VAL_32]] = cond_br %[[VAL_25]], %[[VAL_31]] : i32
// CHECK:           %[[VAL_34:.*]] = arith.addi %[[VAL_22]], %[[VAL_31]] : i32
// CHECK:           %[[VAL_35:.*]] = arith.addi %[[VAL_22]], %[[VAL_20]] : i32
// CHECK:           %[[VAL_36:.*]] = constant %[[VAL_28]] {value = false} : i1
// CHECK:           %[[VAL_37:.*]], %[[VAL_21]] = cond_br %[[VAL_25]], %[[VAL_35]] : i32
// CHECK:           %[[VAL_38:.*]] = merge %[[VAL_34]] : i32
// CHECK:           %[[VAL_39:.*]] = d_return %[[VAL_3]] : none
// CHECK:           end %[[VAL_39]] : none
// CHECK:         }
func.func @test4(%arg0 : i32) {
  %b = arith.constant 0 : i1
  %n = arith.constant 378 : i32
  cf.br ^bb1
^bb1:
  %n1 = arith.constant 121378 : i32
  %b1 = arith.constant 0 : i1
  cf.cond_br %b1, ^bb2(%n : i32), ^bb4
^bb2(%n2 : i32):
  %add = arith.addi %n, %arg0 : i32
  %add2 = arith.addi %n, %n2 : i32
  %b2 = arith.constant 0 : i1
  cf.cond_br %b, ^bb3(%add: i32), ^bb2(%add2: i32)
^bb3(%y : i32):
  cf.br ^bb1
^bb4:
  return
}

// -----

// CHECK-LABEL:   handshake.func @test5(
// CHECK-SAME:                          %[[VAL_0:.*]]: none, ...) -> none attributes {argNames = ["in0"], resNames = ["out0"]} {
// CHECK:           %[[VAL_1:.*]] = merge %[[VAL_0]] : none
// CHECK:           %[[VAL_2:.*]] = constant %[[VAL_1]] {value = 1 : i32} : i32
// CHECK:           %[[VAL_3:.*]] = merge %[[VAL_2]] : i32
// CHECK:           %[[VAL_4:.*]] = merge %[[VAL_2]] : i32
// CHECK:           %[[VAL_5:.*]] = arith.addi %[[VAL_4]], %[[VAL_3]] : i32
// CHECK:           %[[VAL_6:.*]] = d_return %[[VAL_1]] : none
// CHECK:           end %[[VAL_6]] : none
// CHECK:         }
func.func @test5() {
  %cst = arith.constant 1 : i32
  cf.br ^bb1(%cst : i32)
^bb1(%x : i32):
  cf.br ^bb2(%cst: i32)
^bb2(%y : i32):
  %add2 = arith.addi %y, %x : i32
  return
}

// -----

// CHECK-LABEL:   handshake.func @test6(
// CHECK-SAME:                          %[[VAL_0:.*]]: i32,
// CHECK-SAME:                          %[[VAL_1:.*]]: none, ...) -> none attributes {argNames = ["in0", "in1"], resNames = ["out0"]} {
// CHECK:           %[[VAL_2:.*]] = merge %[[VAL_0]] : i32
// CHECK:           %[[VAL_3:.*]] = merge %[[VAL_1]] : none
// CHECK:           %[[VAL_4:.*]] = constant %[[VAL_3]] {value = 7776343 : i32} : i32
// CHECK:           %[[VAL_5:.*]] = merge %[[VAL_3]], %[[VAL_6:.*]] : none
// CHECK:           %[[VAL_6]], %[[VAL_7:.*]] = cond_br %[[VAL_8:.*]], %[[VAL_5]] : none
// CHECK:           %[[VAL_8]] = constant %[[VAL_5]] {value = true} : i1
// CHECK:           %[[VAL_9:.*]] = merge %[[VAL_10:.*]], %[[VAL_4]] : i32
// CHECK:           %[[VAL_11:.*]] = merge %[[VAL_3]], %[[VAL_12:.*]] : none
// CHECK:           %[[VAL_12]], %[[VAL_13:.*]] = cond_br %[[VAL_14:.*]], %[[VAL_11]] : none
// CHECK:           %[[VAL_14]] = constant %[[VAL_11]] {value = true} : i1
// CHECK:           %[[VAL_10]] = constant %[[VAL_11]] {value = 343 : i32} : i32
// CHECK:           %[[VAL_15:.*]] = merge %[[VAL_9]] : i32
// CHECK:           %[[VAL_16:.*]] = arith.addi %[[VAL_15]], %[[VAL_15]] : i32
// CHECK:           %[[VAL_17:.*]] = d_return %[[VAL_3]] : none
// CHECK:           end %[[VAL_17]] : none
// CHECK:         }
func.func @test6(%arg0 : i32) {
  %cst = arith.constant 7776343 : i32
  cf.br ^bb1
^bb1:
  %b1 = arith.constant 1 : i1
  cf.cond_br %b1, ^bb1, ^bb2(%cst : i32)
^bb2(%x : i32):
  %b2 = arith.constant 1 : i1
  %cst2 = arith.constant 343 : i32
  cf.cond_br %b2, ^bb2(%cst2 : i32), ^bb3(%x : i32)
^bb3(%y : i32):
  %add3 = arith.addi %y, %y : i32
  return
}

// -----

// CHECK-LABEL:   handshake.func @test7(
// CHECK-SAME:                          %[[VAL_0:.*]]: none, ...) -> none attributes {argNames = ["in0"], resNames = ["out0"]} {
// CHECK:           %[[VAL_1:.*]] = merge %[[VAL_0]] : none
// CHECK:           %[[VAL_2:.*]] = constant %[[VAL_1]] {value = true} : i1
// CHECK:           %[[VAL_3:.*]] = merge %[[VAL_2]], %[[VAL_4:.*]] : i1
// CHECK:           %[[VAL_4]], %[[VAL_5:.*]] = cond_br %[[VAL_3]], %[[VAL_3]] : i1
// CHECK:           %[[VAL_6:.*]] = merge %[[VAL_1]], %[[VAL_7:.*]] : none
// CHECK:           %[[VAL_7]], %[[VAL_8:.*]] = cond_br %[[VAL_3]], %[[VAL_6]] : none
// CHECK:           %[[VAL_9:.*]] = constant %[[VAL_6]] {value = true} : i1
// CHECK:           %[[VAL_10:.*]] = merge %[[VAL_2]], %[[VAL_11:.*]] : i1
// CHECK:           %[[VAL_11]], %[[VAL_12:.*]] = cond_br %[[VAL_10]], %[[VAL_10]] : i1
// CHECK:           %[[VAL_13:.*]] = arith.addi %[[VAL_10]], %[[VAL_10]] : i1
// CHECK:           %[[VAL_14:.*]] = arith.subi %[[VAL_10]], %[[VAL_10]] : i1
// CHECK:           %[[VAL_15:.*]] = d_return %[[VAL_1]] : none
// CHECK:           end %[[VAL_15]] : none
// CHECK:         }
func.func @test7() {
  %b = arith.constant 1 : i1
  cf.br ^bb1
^bb1:
  %b1 = arith.constant 1 : i1
  cf.cond_br %b, ^bb1, ^bb2
^bb2:
  cf.br ^bb3
^bb3:
  %b2 = arith.addi %b , %b : i1
  %b3 = arith.subi %b , %b : i1
  cf.cond_br %b, ^bb3, ^bb4
^bb4:
  return
}

// -----

// CHECK-LABEL:   handshake.func @test8(
// CHECK-SAME:                          %[[VAL_0:.*]]: none, ...) -> none attributes {argNames = ["in0"], resNames = ["out0"]} {
// CHECK:           %[[VAL_1:.*]] = merge %[[VAL_0]] : none
// CHECK:           %[[VAL_2:.*]] = constant %[[VAL_1]] {value = 378 : i32} : i32
// CHECK:           %[[VAL_3:.*]] = merge %[[VAL_2]], %[[VAL_4:.*]] : i32
// CHECK:           %[[VAL_4]], %[[VAL_5:.*]] = cond_br %[[VAL_6:.*]], %[[VAL_3]] : i32
// CHECK:           %[[VAL_7:.*]] = merge %[[VAL_1]], %[[VAL_8:.*]] : none
// CHECK:           %[[VAL_8]], %[[VAL_9:.*]] = cond_br %[[VAL_6]], %[[VAL_7]] : none
// CHECK:           %[[VAL_10:.*]] = constant %[[VAL_7]] {value = 133378 : i32} : i32
// CHECK:           %[[VAL_6]] = constant %[[VAL_7]] {value = false} : i1
// CHECK:           %[[VAL_11:.*]] = merge %[[VAL_12:.*]], %[[VAL_3]] : i32
// CHECK:           %[[VAL_13:.*]] = merge %[[VAL_3]], %[[VAL_14:.*]] : i32
// CHECK:           %[[VAL_15:.*]], %[[VAL_14]] = cond_br %[[VAL_16:.*]], %[[VAL_13]] : i32
// CHECK:           %[[VAL_17:.*]] = merge %[[VAL_7]], %[[VAL_18:.*]] : none
// CHECK:           %[[VAL_19:.*]], %[[VAL_18]] = cond_br %[[VAL_16]], %[[VAL_17]] : none
// CHECK:           %[[VAL_20:.*]] = arith.addi %[[VAL_13]], %[[VAL_11]] : i32
// CHECK:           %[[VAL_16]] = constant %[[VAL_17]] {value = false} : i1
// CHECK:           %[[VAL_21:.*]], %[[VAL_12]] = cond_br %[[VAL_16]], %[[VAL_20]] : i32
// CHECK:           %[[VAL_22:.*]] = d_return %[[VAL_1]] : none
// CHECK:           end %[[VAL_22]] : none
// CHECK:         }
func.func @test8() {
  %n = arith.constant 378 : i32
  cf.br ^bb1
^bb1:
  %n1 = arith.constant 133378 : i32
  %b1 = arith.constant 0 : i1
  cf.cond_br %b1, ^bb2(%n : i32), ^bb4
^bb2(%x2 : i32):
  %add2 = arith.addi %n, %x2 : i32
  %b2 = arith.constant 0 : i1
  cf.cond_br %b2, ^bb3, ^bb2(%add2: i32)
^bb3:
  cf.br ^bb1
^bb4:
  return
}