// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py
// RUN: dynamatic-opt --canonicalize %s --split-input-file | FileCheck %s

// CHECK-LABEL:   handshake.func @constantFoldExtUI(
// CHECK-SAME:                                      %[[VAL_0:.*]]: !handshake.control<>, ...) -> !handshake.channel<i32> attributes {argNames = ["start"], resNames = ["out0"]} {
// CHECK:           %[[VAL_1:.*]] = constant %[[VAL_0]] {value = 64170 : i32} : <>, <i32>
// CHECK:           end %[[VAL_1]] : <i32>
// CHECK:         }
handshake.func @constantFoldExtUI(%start: !handshake.control<>) -> !handshake.channel<i32> {
  %c = constant %start {value = 0xFAAA : i16} : <>, <i16>
  %d = extui %c : <i16> to <i32>
  end %d : <i32>
}

// -----

// CHECK-LABEL:   handshake.func @constantFoldExtSI(
// CHECK-SAME:                                      %[[VAL_0:.*]]: !handshake.control<>, ...) -> !handshake.channel<i32> attributes {argNames = ["start"], resNames = ["out0"]} {
// CHECK:           %[[VAL_1:.*]] = constant %[[VAL_0]] {value = -1366 : i32} : <>, <i32>
// CHECK:           end %[[VAL_1]] : <i32>
// CHECK:         }
handshake.func @constantFoldExtSI(%start: !handshake.control<>) -> !handshake.channel<i32> {
  %c = constant %start {value = 0xFAAA : i16} : <>, <i16>
  %d = extsi %c : <i16> to <i32>
  end %d : <i32>
}
