/// Classical C-style header guard
#ifndef DYNAMATIC_TRANSFORMS_DUPLICATIONLOGIC_H
#define DYNAMATIC_TRANSFORMS_DUPLICATIONLOGIC_H

/// Include some basic headers
#include "dynamatic/Support/DynamaticPass.h"
#include "dynamatic/Support/LLVM.h"
#include "mlir/Pass/Pass.h"

namespace dynamatic {

/// The following include file is autogenerated by LLVM/MLIR during the build
/// process from the Passes.td file we just edited. We only want to include the
/// part of the file that refers to our pass (it contains delcaration code for
/// all transformation passes), which we select using the two macros below. 
#define GEN_PASS_DECL_DUPLICATIONLOGIC
#define GEN_PASS_DEF_DUPLICATIONLOGIC
#include "dynamatic/Transforms/Passes.h.inc"

/// The pass constructor, with the same name we specified in TableGen in the
/// previous subsection.
std::unique_ptr<dynamatic::DynamaticPass> createPipelineDuplicationPass();

} // namespace dynamatic

#endif // DYNAMATIC_TRANSFORMS_DUPLICATIONLOGIC_H
