#ifndef HOME_KOSSAYBA_DYNAMATIC_TUTORIALS_INTRODUCTION_CH3_LOOP_MULTIPLY_H
#define HOME_KOSSAYBA_DYNAMATIC_TUTORIALS_INTRODUCTION_CH3_LOOP_MULTIPLY_H

#define N 10

typedef int in_int_t;

unsigned loopMultiply(in_int_t a[N]);

#endif // HOME_KOSSAYBA_DYNAMATIC_TUTORIALS_INTRODUCTION_CH3_LOOP_MULTIPLY_H
