// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py
// RUN: dynamatic-opt %s --exp-test-handshake-simulator="path-to-tests=%S/tests.json" --split-input-file | FileCheck %s

// CHECK-LABEL:   handshake.func @fibonacci
handshake.func @fibonacci(%arg0: !handshake.channel<i32>, %arg1: !handshake.control<>, ...) -> (!handshake.channel<i32>, !handshake.control<>) attributes {argNames = ["n", "start"], resNames = ["out0", "end"]} {
  %0:3 = fork [3] %arg1 {bufProps = #handshake<bufProps{"0": [0,0], [0,0], 0.000000e+00, 0.000000e+00, 0.000000e+00}>, handshake.bb = 0 : ui32, handshake.name = "fork0"} : <>
  %1:4 = fork [4] %arg0 {bufProps = #handshake<bufProps{"0": [0,0], [0,0], 0.000000e+00, 0.000000e+00, 0.000000e+00}>, handshake.bb = 0 : ui32, handshake.name = "fork1"} : <i32>
  %2 = source {handshake.bb = 0 : ui32, handshake.name = "source0"}
  %3 = constant %2 {handshake.bb = 0 : ui32, handshake.name = "constant2", value = 1 : i2} : <i2>
  %4 = extsi %3 {handshake.bb = 0 : ui32, handshake.name = "extsi0"} : <i2> to <i32>
  %5 = source {handshake.bb = 0 : ui32, handshake.name = "source1"}
  %6 = constant %5 {handshake.bb = 0 : ui32, handshake.name = "constant3", value = false} : <i1>
  %7:2 = fork [2] %6 {handshake.bb = 0 : ui32, handshake.name = "fork2"} : <i1>
  %8 = extsi %7#1 {handshake.bb = 0 : ui32, handshake.name = "extsi1"} : <i1> to <i32>
  %9:2 = fork [2] %8 {handshake.bb = 0 : ui32, handshake.name = "fork3"} : <i32>
  %10 = constant %0#0 {handshake.bb = 0 : ui32, handshake.name = "constant9", value = false} : <i1>
  %11 = cmpi sle, %1#3, %9#0 {handshake.bb = 0 : ui32, handshake.name = "cmpi0"} : <i32>
  %12 = cmpi sgt, %1#2, %9#1 {handshake.bb = 0 : ui32, handshake.name = "cmpi1"} : <i32>
  %13 = select %11[%7#0, %10] {handshake.bb = 0 : ui32, handshake.name = "select1"} : <i1>, <i1>
  %14 = cmpi ne, %1#1, %4 {handshake.bb = 0 : ui32, handshake.name = "cmpi2"} : <i32>
  %15 = andi %12, %14 {handshake.bb = 0 : ui32, handshake.name = "andi0"} : <i1>
  %16:3 = fork [3] %15 {handshake.bb = 0 : ui32, handshake.name = "fork4"} : <i1>
  %trueResult, %falseResult = cond_br %16#2, %1#0 {handshake.bb = 0 : ui32, handshake.name = "cond_br2"} : <i1>, <i32>
  sink %falseResult {handshake.name = "sink0"} : <i32>
  %trueResult_0, %falseResult_1 = cond_br %16#1, %0#2 {handshake.bb = 0 : ui32, handshake.name = "cond_br3"} : <i1>, <>
  %trueResult_2, %falseResult_3 = cond_br %16#0, %13 {handshake.bb = 0 : ui32, handshake.name = "cond_br0"} : <i1>, <i1>
  sink %trueResult_2 {handshake.name = "sink1"} : <i1>
  %17 = extsi %falseResult_3 {handshake.bb = 0 : ui32, handshake.name = "extsi8"} : <i1> to <i32>
  %18:4 = fork [4] %trueResult_0 {handshake.bb = 1 : ui32, handshake.name = "fork5"} : <>
  %19 = source {handshake.bb = 1 : ui32, handshake.name = "source2"}
  %20 = constant %19 {handshake.bb = 1 : ui32, handshake.name = "constant10", value = 1 : i2} : <i2>
  %21 = extsi %20 {handshake.bb = 1 : ui32, handshake.name = "extsi3"} : <i2> to <i32>
  %22 = constant %18#2 {handshake.bb = 1 : ui32, handshake.name = "constant11", value = 2 : i3} : <i3>
  %23 = constant %18#1 {handshake.bb = 1 : ui32, handshake.name = "constant12", value = false} : <i1>
  %24 = constant %18#0 {handshake.bb = 1 : ui32, handshake.name = "constant13", value = 1 : i2} : <i2>
  %25 = addi %trueResult, %21 {handshake.bb = 1 : ui32, handshake.name = "addi1"} : <i32>
  %26 = extsi %22 {handshake.bb = 1 : ui32, handshake.name = "extsi9"} : <i3> to <i32>
  %27 = extsi %24 {handshake.bb = 1 : ui32, handshake.name = "extsi10"} : <i2> to <i32>
  %28 = extsi %23 {handshake.bb = 1 : ui32, handshake.name = "extsi11"} : <i1> to <i32>
  %29 = mux %40#0 [%26, %56] {handshake.bb = 2 : ui32, handshake.name = "mux0"} : <i1>, <i32>
  %30 = buffer %29 {handshake.bb = 2 : ui32, handshake.name = "buffer0", hw.parameters = {NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 1, V: 1, R: 0}>}} : <i32>
  %31:2 = fork [2] %30 {handshake.bb = 2 : ui32, handshake.name = "fork6"} : <i32>
  %32 = mux %40#1 [%27, %55] {handshake.bb = 2 : ui32, handshake.name = "mux1"} : <i1>, <i32>
  %33 = mux %40#2 [%28, %50#0] {handshake.bb = 2 : ui32, handshake.name = "mux2"} : <i1>, <i32>
  %34 = mux %40#3 [%25, %57] {handshake.bb = 2 : ui32, handshake.name = "mux3"} : <i1>, <i32>
  %35 = buffer %34 {handshake.bb = 2 : ui32, handshake.name = "buffer3", hw.parameters = {NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 1, V: 1, R: 0}>}} : <i32>
  %36 = buffer %35 {handshake.bb = 2 : ui32, handshake.name = "buffer4", hw.parameters = {NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {R: 1}>}} : <i32>
  %37:2 = fork [2] %36 {handshake.bb = 2 : ui32, handshake.name = "fork7"} : <i32>
  %38 = buffer %trueResult_12 {handshake.bb = 2 : ui32, handshake.name = "buffer12", hw.parameters = {NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 1, V: 1, R: 0}>}} : <>
  %39 = buffer %38 {handshake.bb = 2 : ui32, handshake.name = "buffer13", hw.parameters = {NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {R: 1}>}} : <>
  %result, %index = control_merge %18#3, %39  {handshake.bb = 2 : ui32, handshake.name = "control_merge1"} : <>, <i1>
  %40:4 = fork [4] %index {handshake.bb = 2 : ui32, handshake.name = "fork8"} : <i1>
  %41 = cmpi ult, %31#1, %37#1 {handshake.bb = 2 : ui32, handshake.name = "cmpi3"} : <i32>
  %42:5 = fork [5] %41 {handshake.bb = 2 : ui32, handshake.name = "fork9"} : <i1>
  %trueResult_4, %falseResult_5 = cond_br %42#4, %37#0 {handshake.bb = 2 : ui32, handshake.name = "cond_br5"} : <i1>, <i32>
  sink %falseResult_5 {handshake.name = "sink3"} : <i32>
  %trueResult_6, %falseResult_7 = cond_br %42#3, %31#0 {handshake.bb = 2 : ui32, handshake.name = "cond_br6"} : <i1>, <i32>
  sink %falseResult_7 {handshake.name = "sink4"} : <i32>
  %43 = buffer %32 {handshake.bb = 2 : ui32, handshake.name = "buffer1", hw.parameters = {NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 1, V: 1, R: 0}>}} : <i32>
  %trueResult_8, %falseResult_9 = cond_br %42#2, %43 {handshake.bb = 2 : ui32, handshake.name = "cond_br7"} : <i1>, <i32>
  %44 = buffer %33 {handshake.bb = 2 : ui32, handshake.name = "buffer2", hw.parameters = {NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 1, V: 1, R: 0}>}} : <i32>
  %trueResult_10, %falseResult_11 = cond_br %42#1, %44 {handshake.bb = 2 : ui32, handshake.name = "cond_br8"} : <i1>, <i32>
  sink %falseResult_11 {handshake.name = "sink5"} : <i32>
  %45 = buffer %result {handshake.bb = 2 : ui32, handshake.name = "buffer5", hw.parameters = {NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 1, V: 1, R: 0}>}} : <>
  %trueResult_12, %falseResult_13 = cond_br %42#0, %45 {handshake.bb = 2 : ui32, handshake.name = "cond_br9"} : <i1>, <>
  %46 = buffer %trueResult_6 {handshake.bb = 3 : ui32, handshake.name = "buffer6", hw.parameters = {NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 1, V: 1, R: 0}>}} : <i32>
  %47 = buffer %46 {handshake.bb = 3 : ui32, handshake.name = "buffer7", hw.parameters = {NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {R: 1}>}} : <i32>
  %48 = buffer %trueResult_8 {handshake.bb = 3 : ui32, handshake.name = "buffer10", hw.parameters = {NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 1, V: 1, R: 0}>}} : <i32>
  %49 = buffer %48 {handshake.bb = 3 : ui32, handshake.name = "buffer11", hw.parameters = {NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {R: 1}>}} : <i32>
  %50:2 = fork [2] %49 {handshake.bb = 3 : ui32, handshake.name = "fork10"} : <i32>
  %51 = buffer %trueResult_10 {handshake.bb = 3 : ui32, handshake.name = "buffer8", hw.parameters = {NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 1, V: 1, R: 0}>}} : <i32>
  %52 = source {handshake.bb = 3 : ui32, handshake.name = "source3"}
  %53 = constant %52 {handshake.bb = 3 : ui32, handshake.name = "constant14", value = 1 : i2} : <i2>
  %54 = extsi %53 {handshake.bb = 3 : ui32, handshake.name = "extsi7"} : <i2> to <i32>
  %55 = addi %51, %50#1 {handshake.bb = 3 : ui32, handshake.name = "addi0"} : <i32>
  %56 = addi %47, %54 {handshake.bb = 3 : ui32, handshake.name = "addi2"} : <i32>
  %57 = buffer %trueResult_4 {handshake.bb = 3 : ui32, handshake.name = "buffer9", hw.parameters = {NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 1, V: 1, R: 0}>}} : <i32>
  %58 = buffer %17 {handshake.bb = 4 : ui32, handshake.name = "buffer14", hw.parameters = {NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 1, V: 1, R: 0}>}} : <i32>
  %59 = buffer %index_15 {handshake.bb = 4 : ui32, handshake.name = "buffer15", hw.parameters = {NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 1, V: 1, R: 0}>}} : <i1>
  %60 = mux %59 [%58, %falseResult_9] {handshake.bb = 4 : ui32, handshake.name = "mux4"} : <i1>, <i32>
  %result_14, %index_15 = control_merge %falseResult_1, %falseResult_13  {handshake.bb = 4 : ui32, handshake.name = "control_merge3"} : <>, <i1>
  sink %result_14 {handshake.name = "sink7"} : <>
  end {handshake.bb = 4 : ui32, handshake.name = "end0"} %60, %0#1 : <i32>, <>
}
