module {
  hw.module @collision_donut(in %x_loadData : i32, in %y_loadData : i32, in %x_start : !handshake.control<>, in %y_start : !handshake.control<>, in %start : !handshake.control<>, in %clk : i1, in %rst : i1, out out0 : !handshake.channel<i32>, out x_end : !handshake.control<>, out y_end : !handshake.control<>, out end : !handshake.control<>, out x_loadEn : i1, out x_loadAddr : i10, out x_storeEn : i1, out x_storeAddr : i10, out x_storeData : i32, out y_loadEn : i1, out y_loadAddr : i10, out y_storeEn : i1, out y_storeAddr : i10, out y_storeData : i32) {
    %fork0.outs_0, %fork0.outs_1, %fork0.outs_2 = hw.instance "fork0" @handshake_fork_0(ins: %start: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.control<>, outs_1: !handshake.control<>, outs_2: !handshake.control<>)
    %mem_controller2.ldData_0, %mem_controller2.memEnd, %mem_controller2.loadEn, %mem_controller2.loadAddr, %mem_controller2.storeEn, %mem_controller2.storeAddr, %mem_controller2.storeData = hw.instance "mem_controller2" @handshake_mem_controller_0(loadData: %y_loadData: i32, memStart: %y_start: !handshake.control<>, ldAddr_0: %load1.addrOut: !handshake.channel<i10>, ctrlEnd: %fork14.outs_1: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (ldData_0: !handshake.channel<i32>, memEnd: !handshake.control<>, loadEn: i1, loadAddr: i10, storeEn: i1, storeAddr: i10, storeData: i32)
    %mem_controller3.ldData_0, %mem_controller3.memEnd, %mem_controller3.loadEn, %mem_controller3.loadAddr, %mem_controller3.storeEn, %mem_controller3.storeAddr, %mem_controller3.storeData = hw.instance "mem_controller3" @handshake_mem_controller_1(loadData: %x_loadData: i32, memStart: %x_start: !handshake.control<>, ldAddr_0: %load0.addrOut: !handshake.channel<i10>, ctrlEnd: %fork14.outs_0: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (ldData_0: !handshake.channel<i32>, memEnd: !handshake.control<>, loadEn: i1, loadAddr: i10, storeEn: i1, storeAddr: i10, storeData: i32)
    %constant0.outs = hw.instance "constant0" @handshake_constant_0(ctrl: %fork0.outs_0: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %extsi7.outs = hw.instance "extsi7" @handshake_extsi_0(ins: %constant0.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i11>)
    %buffer23.outs = hw.instance "buffer23" @handshake_buffer_0(ins: %fork33.outs_3: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %init0.outs = hw.instance "init0" @handshake_init_0(ins: %buffer23.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer24.outs = hw.instance "buffer24" @handshake_buffer_1(ins: %fork33.outs_4: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer25.outs = hw.instance "buffer25" @handshake_buffer_2(ins: %buffer24.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %init1.outs = hw.instance "init1" @handshake_init_0(ins: %buffer25.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %mux0.outs = hw.instance "mux0" @handshake_mux_0(index: %init0.outs: !handshake.channel<i1>, ins_0: %extsi7.outs: !handshake.channel<i11>, ins_1: %passer19.result: !handshake.channel<i11>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i11>)
    %trunci0.outs = hw.instance "trunci0" @handshake_trunci_0(ins: %fork38.outs_0: !handshake.channel<i11>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i10>)
    %trunci1.outs = hw.instance "trunci1" @handshake_trunci_0(ins: %fork38.outs_1: !handshake.channel<i11>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i10>)
    %mux7.outs = hw.instance "mux7" @handshake_mux_1(index: %init1.outs: !handshake.channel<i1>, ins_0: %fork0.outs_2: !handshake.control<>, ins_1: %passer20.result: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %source0.outs = hw.instance "source0" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant1.outs = hw.instance "constant1" @handshake_constant_1(ctrl: %source0.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i4>)
    %extsi1.outs = hw.instance "extsi1" @handshake_extsi_1(ins: %constant1.outs: !handshake.channel<i4>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %constant8.outs = hw.instance "constant8" @handshake_constant_2(ctrl: %fork39.outs_0: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %fork1.outs_0, %fork1.outs_1 = hw.instance "fork1" @handshake_fork_1(ins: %load0.dataOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>)
    %load0.addrOut, %load0.dataOut = hw.instance "load0" @handshake_load_0(addrIn: %trunci1.outs: !handshake.channel<i10>, dataFromMem: %mem_controller3.ldData_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (addrOut: !handshake.channel<i10>, dataOut: !handshake.channel<i32>)
    %fork2.outs_0, %fork2.outs_1 = hw.instance "fork2" @handshake_fork_1(ins: %load1.dataOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>)
    %load1.addrOut, %load1.dataOut = hw.instance "load1" @handshake_load_0(addrIn: %trunci0.outs: !handshake.channel<i10>, dataFromMem: %mem_controller2.ldData_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (addrOut: !handshake.channel<i10>, dataOut: !handshake.channel<i32>)
    %muli0.result = hw.instance "muli0" @handshake_muli_0(lhs: %fork1.outs_0: !handshake.channel<i32>, rhs: %fork1.outs_1: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %muli1.result = hw.instance "muli1" @handshake_muli_0(lhs: %fork2.outs_0: !handshake.channel<i32>, rhs: %fork2.outs_1: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %fork6.outs_0, %fork6.outs_1 = hw.instance "fork6" @handshake_fork_1(ins: %addi0.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>)
    %addi0.result = hw.instance "addi0" @handshake_addi_0(lhs: %muli0.result: !handshake.channel<i32>, rhs: %muli1.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %cmpi0.result = hw.instance "cmpi0" @handshake_cmpi_0(lhs: %fork6.outs_1: !handshake.channel<i32>, rhs: %extsi1.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %fork7.outs_0, %fork7.outs_1 = hw.instance "fork7" @handshake_fork_2(ins: %cmpi0.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>)
    %fork8.outs_0, %fork8.outs_1 = hw.instance "fork8" @handshake_fork_2(ins: %not0.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>)
    %not0.outs = hw.instance "not0" @handshake_not_0(ins: %fork7.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %andi1.result = hw.instance "andi1" @handshake_andi_0(lhs: %not2.outs: !handshake.channel<i1>, rhs: %fork10.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %andi2.result = hw.instance "andi2" @handshake_andi_0(lhs: %fork9.outs_1: !handshake.channel<i1>, rhs: %fork8.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %buffer5.outs = hw.instance "buffer5" @handshake_buffer_3(ins: %extsi8.outs: !handshake.channel<i12>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i12>)
    %buffer6.outs = hw.instance "buffer6" @handshake_buffer_4(ins: %buffer5.outs: !handshake.channel<i12>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i12>)
    %passer16.result = hw.instance "passer16" @handshake_passer_0(data: %buffer6.outs: !handshake.channel<i12>, ctrl: %fork37.outs_2: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i12>)
    %extsi8.outs = hw.instance "extsi8" @handshake_extsi_2(ins: %fork38.outs_4: !handshake.channel<i11>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i12>)
    %passer2.result = hw.instance "passer2" @handshake_passer_1(data: %constant8.outs: !handshake.channel<i32>, ctrl: %fork37.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %passer3.result = hw.instance "passer3" @handshake_passer_2(data: %fork39.outs_6: !handshake.control<>, ctrl: %fork37.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.control<>)
    %source1.outs = hw.instance "source1" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant2.outs = hw.instance "constant2" @handshake_constant_3(ctrl: %source1.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i16>)
    %extsi2.outs = hw.instance "extsi2" @handshake_extsi_3(ins: %constant2.outs: !handshake.channel<i16>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %constant10.outs = hw.instance "constant10" @handshake_constant_4(ctrl: %fork39.outs_1: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %fork9.outs_0, %fork9.outs_1 = hw.instance "fork9" @handshake_fork_2(ins: %cmpi1.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>)
    %cmpi1.result = hw.instance "cmpi1" @handshake_cmpi_1(lhs: %fork6.outs_0: !handshake.channel<i32>, rhs: %extsi2.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %not1.outs = hw.instance "not1" @handshake_not_0(ins: %fork9.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer7.outs = hw.instance "buffer7" @handshake_buffer_1(ins: %andi3.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %fork10.outs_0, %fork10.outs_1 = hw.instance "fork10" @handshake_fork_2(ins: %buffer7.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>)
    %andi3.result = hw.instance "andi3" @handshake_andi_0(lhs: %fork8.outs_1: !handshake.channel<i1>, rhs: %not1.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %passer17.result = hw.instance "passer17" @handshake_passer_0(data: %extsi9.outs: !handshake.channel<i12>, ctrl: %fork35.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i12>)
    %buffer27.outs = hw.instance "buffer27" @handshake_buffer_5(ins: %fork38.outs_3: !handshake.channel<i11>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i11>)
    %buffer28.outs = hw.instance "buffer28" @handshake_buffer_6(ins: %buffer27.outs: !handshake.channel<i11>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i11>)
    %extsi9.outs = hw.instance "extsi9" @handshake_extsi_2(ins: %buffer28.outs: !handshake.channel<i11>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i12>)
    %passer8.result = hw.instance "passer8" @handshake_passer_1(data: %constant10.outs: !handshake.channel<i32>, ctrl: %fork35.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %passer9.result = hw.instance "passer9" @handshake_passer_2(data: %fork39.outs_5: !handshake.control<>, ctrl: %fork35.outs_2: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.control<>)
    %buffer26.outs = hw.instance "buffer26" @handshake_buffer_5(ins: %fork38.outs_2: !handshake.channel<i11>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i11>)
    %extsi10.outs = hw.instance "extsi10" @handshake_extsi_2(ins: %buffer26.outs: !handshake.channel<i11>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i12>)
    %constant3.outs = hw.instance "constant3" @handshake_constant_0(ctrl: %fork39.outs_2: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %source2.outs = hw.instance "source2" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant4.outs = hw.instance "constant4" @handshake_constant_5(ctrl: %source2.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i2>)
    %extsi11.outs = hw.instance "extsi11" @handshake_extsi_4(ins: %constant4.outs: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i12>)
    %source3.outs = hw.instance "source3" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant5.outs = hw.instance "constant5" @handshake_constant_6(ctrl: %source3.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i11>)
    %extsi12.outs = hw.instance "extsi12" @handshake_extsi_2(ins: %constant5.outs: !handshake.channel<i11>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i12>)
    %fork11.outs_0, %fork11.outs_1, %fork11.outs_2 = hw.instance "fork11" @handshake_fork_3(ins: %addi1.result: !handshake.channel<i12>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i12>, outs_1: !handshake.channel<i12>, outs_2: !handshake.channel<i12>)
    %addi1.result = hw.instance "addi1" @handshake_addi_1(lhs: %extsi10.outs: !handshake.channel<i12>, rhs: %extsi11.outs: !handshake.channel<i12>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i12>)
    %buffer9.outs = hw.instance "buffer9" @handshake_buffer_1(ins: %cmpi2.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer10.outs = hw.instance "buffer10" @handshake_buffer_2(ins: %buffer9.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %fork28.outs_0, %fork28.outs_1 = hw.instance "fork28" @handshake_fork_2(ins: %buffer10.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>)
    %cmpi2.result = hw.instance "cmpi2" @handshake_cmpi_2(lhs: %fork11.outs_0: !handshake.channel<i12>, rhs: %extsi12.outs: !handshake.channel<i12>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %passer18.result = hw.instance "passer18" @handshake_passer_3(data: %andi4.result: !handshake.channel<i1>, ctrl: %fork34.outs_3: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %andi4.result = hw.instance "andi4" @handshake_andi_0(lhs: %fork10.outs_1: !handshake.channel<i1>, rhs: %fork28.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %spec_v2_repeating_init0.outs = hw.instance "spec_v2_repeating_init0" @handshake_spec_v2_repeating_init_0(ins: %passer18.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer11.outs = hw.instance "buffer11" @handshake_buffer_0(ins: %spec_v2_repeating_init0.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %fork29.outs_0, %fork29.outs_1 = hw.instance "fork29" @handshake_fork_2(ins: %buffer11.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>)
    %spec_v2_repeating_init1.outs = hw.instance "spec_v2_repeating_init1" @handshake_spec_v2_repeating_init_0(ins: %fork29.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer12.outs = hw.instance "buffer12" @handshake_buffer_0(ins: %spec_v2_repeating_init1.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %fork30.outs_0, %fork30.outs_1 = hw.instance "fork30" @handshake_fork_2(ins: %buffer12.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>)
    %buffer13.outs = hw.instance "buffer13" @handshake_buffer_1(ins: %fork30.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %source5.outs = hw.instance "source5" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant6.outs = hw.instance "constant6" @handshake_constant_0(ctrl: %source5.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %mux5.outs = hw.instance "mux5" @handshake_mux_2(index: %buffer13.outs: !handshake.channel<i1>, ins_0: %constant6.outs: !handshake.channel<i1>, ins_1: %fork29.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %spec_v2_repeating_init2.outs = hw.instance "spec_v2_repeating_init2" @handshake_spec_v2_repeating_init_0(ins: %fork30.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer14.outs = hw.instance "buffer14" @handshake_buffer_0(ins: %spec_v2_repeating_init2.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %fork31.outs_0, %fork31.outs_1 = hw.instance "fork31" @handshake_fork_2(ins: %buffer14.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>)
    %buffer15.outs = hw.instance "buffer15" @handshake_buffer_7(ins: %fork31.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %source6.outs = hw.instance "source6" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant7.outs = hw.instance "constant7" @handshake_constant_0(ctrl: %source6.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %mux6.outs = hw.instance "mux6" @handshake_mux_2(index: %buffer15.outs: !handshake.channel<i1>, ins_0: %constant7.outs: !handshake.channel<i1>, ins_1: %mux5.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %spec_v2_repeating_init3.outs = hw.instance "spec_v2_repeating_init3" @handshake_spec_v2_repeating_init_0(ins: %fork31.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer16.outs = hw.instance "buffer16" @handshake_buffer_0(ins: %spec_v2_repeating_init3.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %fork32.outs_0, %fork32.outs_1 = hw.instance "fork32" @handshake_fork_2(ins: %buffer16.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>)
    %buffer17.outs = hw.instance "buffer17" @handshake_buffer_8(ins: %fork32.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %source7.outs = hw.instance "source7" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant9.outs = hw.instance "constant9" @handshake_constant_0(ctrl: %source7.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %mux8.outs = hw.instance "mux8" @handshake_mux_2(index: %buffer17.outs: !handshake.channel<i1>, ins_0: %constant9.outs: !handshake.channel<i1>, ins_1: %mux6.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %spec_v2_repeating_init4.outs = hw.instance "spec_v2_repeating_init4" @handshake_spec_v2_repeating_init_0(ins: %fork32.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer19.outs = hw.instance "buffer19" @handshake_buffer_0(ins: %spec_v2_repeating_init4.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %fork33.outs_0, %fork33.outs_1, %fork33.outs_2, %fork33.outs_3, %fork33.outs_4 = hw.instance "fork33" @handshake_fork_4(ins: %buffer19.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>, outs_3: !handshake.channel<i1>, outs_4: !handshake.channel<i1>)
    %buffer18.outs = hw.instance "buffer18" @handshake_buffer_1(ins: %mux8.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer20.outs = hw.instance "buffer20" @handshake_buffer_1(ins: %fork33.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer21.outs = hw.instance "buffer21" @handshake_buffer_2(ins: %buffer20.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %source8.outs = hw.instance "source8" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant11.outs = hw.instance "constant11" @handshake_constant_0(ctrl: %source8.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %mux9.outs = hw.instance "mux9" @handshake_mux_2(index: %buffer21.outs: !handshake.channel<i1>, ins_0: %constant11.outs: !handshake.channel<i1>, ins_1: %buffer18.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %fork34.outs_0, %fork34.outs_1, %fork34.outs_2, %fork34.outs_3 = hw.instance "fork34" @handshake_fork_5(ins: %mux9.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>, outs_3: !handshake.channel<i1>)
    %buffer4.outs = hw.instance "buffer4" @handshake_buffer_1(ins: %andi2.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %andi9.result = hw.instance "andi9" @handshake_andi_0(lhs: %buffer4.outs: !handshake.channel<i1>, rhs: %fork34.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %fork35.outs_0, %fork35.outs_1, %fork35.outs_2 = hw.instance "fork35" @handshake_fork_6(ins: %andi9.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>)
    %andi10.result = hw.instance "andi10" @handshake_andi_0(lhs: %andi1.result: !handshake.channel<i1>, rhs: %fork34.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %fork36.outs_0, %fork36.outs_1, %fork36.outs_2 = hw.instance "fork36" @handshake_fork_6(ins: %andi10.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>)
    %buffer3.outs = hw.instance "buffer3" @handshake_buffer_1(ins: %fork7.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %andi11.result = hw.instance "andi11" @handshake_andi_0(lhs: %buffer3.outs: !handshake.channel<i1>, rhs: %fork34.outs_2: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %fork37.outs_0, %fork37.outs_1, %fork37.outs_2 = hw.instance "fork37" @handshake_fork_6(ins: %andi11.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>)
    %not2.outs = hw.instance "not2" @handshake_not_0(ins: %fork28.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer8.outs = hw.instance "buffer8" @handshake_buffer_4(ins: %fork11.outs_1: !handshake.channel<i12>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i12>)
    %passer12.result = hw.instance "passer12" @handshake_passer_0(data: %buffer8.outs: !handshake.channel<i12>, ctrl: %fork36.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i12>)
    %buffer0.outs = hw.instance "buffer0" @handshake_buffer_9(ins: %mux0.outs: !handshake.channel<i11>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i11>)
    %fork38.outs_0, %fork38.outs_1, %fork38.outs_2, %fork38.outs_3, %fork38.outs_4 = hw.instance "fork38" @handshake_fork_7(ins: %buffer0.outs: !handshake.channel<i11>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i11>, outs_1: !handshake.channel<i11>, outs_2: !handshake.channel<i11>, outs_3: !handshake.channel<i11>, outs_4: !handshake.channel<i11>)
    %passer19.result = hw.instance "passer19" @handshake_passer_4(data: %trunci2.outs: !handshake.channel<i11>, ctrl: %fork33.outs_2: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i11>)
    %trunci2.outs = hw.instance "trunci2" @handshake_trunci_1(ins: %fork11.outs_2: !handshake.channel<i12>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i11>)
    %buffer22.outs = hw.instance "buffer22" @handshake_buffer_10(ins: %fork33.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %passer20.result = hw.instance "passer20" @handshake_passer_2(data: %fork39.outs_4: !handshake.control<>, ctrl: %buffer22.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.control<>)
    %buffer1.outs = hw.instance "buffer1" @handshake_buffer_11(ins: %mux7.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %buffer2.outs = hw.instance "buffer2" @handshake_buffer_12(ins: %buffer1.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %fork39.outs_0, %fork39.outs_1, %fork39.outs_2, %fork39.outs_3, %fork39.outs_4, %fork39.outs_5, %fork39.outs_6 = hw.instance "fork39" @handshake_fork_8(ins: %buffer2.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.control<>, outs_1: !handshake.control<>, outs_2: !handshake.control<>, outs_3: !handshake.control<>, outs_4: !handshake.control<>, outs_5: !handshake.control<>, outs_6: !handshake.control<>)
    %passer14.result = hw.instance "passer14" @handshake_passer_2(data: %fork39.outs_3: !handshake.control<>, ctrl: %fork36.outs_2: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.control<>)
    %passer21.result = hw.instance "passer21" @handshake_passer_1(data: %extsi13.outs: !handshake.channel<i32>, ctrl: %fork36.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %extsi13.outs = hw.instance "extsi13" @handshake_extsi_5(ins: %constant3.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %mux1.outs = hw.instance "mux1" @handshake_mux_3(index: %fork12.outs_0: !handshake.channel<i1>, ins_0: %passer16.result: !handshake.channel<i12>, ins_1: %passer12.result: !handshake.channel<i12>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i12>)
    %mux2.outs = hw.instance "mux2" @handshake_mux_4(index: %fork12.outs_1: !handshake.channel<i1>, ins_0: %passer2.result: !handshake.channel<i32>, ins_1: %passer21.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %control_merge3.outs, %control_merge3.index = hw.instance "control_merge3" @handshake_control_merge_0(ins_0: %passer3.result: !handshake.control<>, ins_1: %passer14.result: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>, index: !handshake.channel<i1>)
    %fork12.outs_0, %fork12.outs_1 = hw.instance "fork12" @handshake_fork_2(ins: %control_merge3.index: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>)
    %mux3.outs = hw.instance "mux3" @handshake_mux_3(index: %fork13.outs_0: !handshake.channel<i1>, ins_0: %passer17.result: !handshake.channel<i12>, ins_1: %mux1.outs: !handshake.channel<i12>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i12>)
    %buffer29.outs = hw.instance "buffer29" @handshake_buffer_3(ins: %mux3.outs: !handshake.channel<i12>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i12>)
    %extsi14.outs = hw.instance "extsi14" @handshake_extsi_6(ins: %buffer29.outs: !handshake.channel<i12>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %mux4.outs = hw.instance "mux4" @handshake_mux_4(index: %fork13.outs_1: !handshake.channel<i1>, ins_0: %passer8.result: !handshake.channel<i32>, ins_1: %mux2.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %control_merge4.outs, %control_merge4.index = hw.instance "control_merge4" @handshake_control_merge_0(ins_0: %passer9.result: !handshake.control<>, ins_1: %control_merge3.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>, index: !handshake.channel<i1>)
    %fork13.outs_0, %fork13.outs_1 = hw.instance "fork13" @handshake_fork_2(ins: %control_merge4.index: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>)
    %fork14.outs_0, %fork14.outs_1 = hw.instance "fork14" @handshake_fork_9(ins: %control_merge4.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.control<>, outs_1: !handshake.control<>)
    %source4.outs = hw.instance "source4" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant15.outs = hw.instance "constant15" @handshake_constant_5(ctrl: %source4.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i2>)
    %extsi6.outs = hw.instance "extsi6" @handshake_extsi_7(ins: %constant15.outs: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %shli0.result = hw.instance "shli0" @handshake_shli_0(lhs: %extsi14.outs: !handshake.channel<i32>, rhs: %extsi6.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %buffer30.outs = hw.instance "buffer30" @handshake_buffer_13(ins: %mux4.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %andi0.result = hw.instance "andi0" @handshake_andi_1(lhs: %shli0.result: !handshake.channel<i32>, rhs: %buffer30.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    hw.output %andi0.result, %mem_controller3.memEnd, %mem_controller2.memEnd, %fork0.outs_1, %mem_controller3.loadEn, %mem_controller3.loadAddr, %mem_controller3.storeEn, %mem_controller3.storeAddr, %mem_controller3.storeData, %mem_controller2.loadEn, %mem_controller2.loadAddr, %mem_controller2.storeEn, %mem_controller2.storeAddr, %mem_controller2.storeData : !handshake.channel<i32>, !handshake.control<>, !handshake.control<>, !handshake.control<>, i1, i10, i1, i10, i32, i1, i10, i1, i10, i32
  }
  hw.module.extern @handshake_fork_0(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.control<>, out outs_1 : !handshake.control<>, out outs_2 : !handshake.control<>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.control<>, SIZE = 3 : ui32}}
  hw.module.extern @handshake_mem_controller_0(in %loadData : i32, in %memStart : !handshake.control<>, in %ldAddr_0 : !handshake.channel<i10>, in %ctrlEnd : !handshake.control<>, in %clk : i1, in %rst : i1, out ldData_0 : !handshake.channel<i32>, out memEnd : !handshake.control<>, out loadEn : i1, out loadAddr : i10, out storeEn : i1, out storeAddr : i10, out storeData : i32) attributes {hw.name = "handshake.mem_controller", hw.parameters = {ADDR_TYPE = !handshake.channel<i10>, DATA_TYPE = !handshake.channel<i32>, NUM_CONTROLS = 0 : ui32, NUM_LOADS = 1 : ui32, NUM_STORES = 0 : ui32}}
  hw.module.extern @handshake_mem_controller_1(in %loadData : i32, in %memStart : !handshake.control<>, in %ldAddr_0 : !handshake.channel<i10>, in %ctrlEnd : !handshake.control<>, in %clk : i1, in %rst : i1, out ldData_0 : !handshake.channel<i32>, out memEnd : !handshake.control<>, out loadEn : i1, out loadAddr : i10, out storeEn : i1, out storeAddr : i10, out storeData : i32) attributes {hw.name = "handshake.mem_controller", hw.parameters = {ADDR_TYPE = !handshake.channel<i10>, DATA_TYPE = !handshake.channel<i32>, NUM_CONTROLS = 0 : ui32, NUM_LOADS = 1 : ui32, NUM_STORES = 0 : ui32}}
  hw.module.extern @handshake_constant_0(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 1 : ui32, VALUE = "0"}}
  hw.module.extern @handshake_extsi_0(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i11>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i1>, OUTPUT_TYPE = !handshake.channel<i11>}}
  hw.module.extern @handshake_buffer_0(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i1>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_init_0(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.init", hw.parameters = {INIT_TOKEN = 0 : ui32}}
  hw.module.extern @handshake_buffer_1(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<i1>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_buffer_2(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i1>, DEBUG_COUNTER = false, NUM_SLOTS = 4 : ui32}}
  hw.module.extern @handshake_mux_0(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.channel<i11>, in %ins_1 : !handshake.channel<i11>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i11>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<i11>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_trunci_0(in %ins : !handshake.channel<i11>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i10>) attributes {hw.name = "handshake.trunci", hw.parameters = {INPUT_TYPE = !handshake.channel<i11>, OUTPUT_TYPE = !handshake.channel<i10>}}
  hw.module.extern @handshake_mux_1(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.control<>, in %ins_1 : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.control<>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.control<>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_source_0(in %clk : i1, in %rst : i1, out outs : !handshake.control<>) attributes {hw.name = "handshake.source", hw.parameters = {}}
  hw.module.extern @handshake_constant_1(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i4>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 4 : ui32, VALUE = "0100"}}
  hw.module.extern @handshake_extsi_1(in %ins : !handshake.channel<i4>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i4>, OUTPUT_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_constant_2(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 32 : ui32, VALUE = "11111111111111111111111111111111"}}
  hw.module.extern @handshake_fork_1(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_load_0(in %addrIn : !handshake.channel<i10>, in %dataFromMem : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out addrOut : !handshake.channel<i10>, out dataOut : !handshake.channel<i32>) attributes {hw.name = "handshake.load", hw.parameters = {ADDR_TYPE = !handshake.channel<i10>, DATA_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_muli_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.muli", hw.parameters = {DATA_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_addi_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.addi", hw.parameters = {DATA_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_cmpi_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.cmpi", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, PREDICATE = "ult"}}
  hw.module.extern @handshake_fork_2(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_not_0(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.not", hw.parameters = {DATA_TYPE = !handshake.channel<i1>}}
  hw.module.extern @handshake_andi_0(in %lhs : !handshake.channel<i1>, in %rhs : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.andi", hw.parameters = {DATA_TYPE = !handshake.channel<i1>}}
  hw.module.extern @handshake_buffer_3(in %ins : !handshake.channel<i12>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i12>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<i12>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_buffer_4(in %ins : !handshake.channel<i12>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i12>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i12>, DEBUG_COUNTER = false, NUM_SLOTS = 5 : ui32}}
  hw.module.extern @handshake_passer_0(in %data : !handshake.channel<i12>, in %ctrl : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i12>) attributes {hw.name = "handshake.passer", hw.parameters = {}}
  hw.module.extern @handshake_extsi_2(in %ins : !handshake.channel<i11>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i12>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i11>, OUTPUT_TYPE = !handshake.channel<i12>}}
  hw.module.extern @handshake_passer_1(in %data : !handshake.channel<i32>, in %ctrl : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.passer", hw.parameters = {}}
  hw.module.extern @handshake_passer_2(in %data : !handshake.control<>, in %ctrl : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.control<>) attributes {hw.name = "handshake.passer", hw.parameters = {}}
  hw.module.extern @handshake_constant_3(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i16>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 16 : ui32, VALUE = "0100101000111000"}}
  hw.module.extern @handshake_extsi_3(in %ins : !handshake.channel<i16>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i16>, OUTPUT_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_constant_4(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 32 : ui32, VALUE = "11111111111111111111111111111110"}}
  hw.module.extern @handshake_cmpi_1(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.cmpi", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, PREDICATE = "ugt"}}
  hw.module.extern @handshake_buffer_5(in %ins : !handshake.channel<i11>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i11>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<i11>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_buffer_6(in %ins : !handshake.channel<i11>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i11>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i11>, DEBUG_COUNTER = false, NUM_SLOTS = 5 : ui32}}
  hw.module.extern @handshake_constant_5(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i2>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 2 : ui32, VALUE = "01"}}
  hw.module.extern @handshake_extsi_4(in %ins : !handshake.channel<i2>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i12>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i2>, OUTPUT_TYPE = !handshake.channel<i12>}}
  hw.module.extern @handshake_constant_6(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i11>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 11 : ui32, VALUE = "01111101000"}}
  hw.module.extern @handshake_fork_3(in %ins : !handshake.channel<i12>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i12>, out outs_1 : !handshake.channel<i12>, out outs_2 : !handshake.channel<i12>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i12>, SIZE = 3 : ui32}}
  hw.module.extern @handshake_addi_1(in %lhs : !handshake.channel<i12>, in %rhs : !handshake.channel<i12>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i12>) attributes {hw.name = "handshake.addi", hw.parameters = {DATA_TYPE = !handshake.channel<i12>}}
  hw.module.extern @handshake_cmpi_2(in %lhs : !handshake.channel<i12>, in %rhs : !handshake.channel<i12>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.cmpi", hw.parameters = {DATA_TYPE = !handshake.channel<i12>, PREDICATE = "ult"}}
  hw.module.extern @handshake_passer_3(in %data : !handshake.channel<i1>, in %ctrl : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.passer", hw.parameters = {}}
  hw.module.extern @handshake_spec_v2_repeating_init_0(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.spec_v2_repeating_init", hw.parameters = {INIT_TOKEN = 1 : ui32}}
  hw.module.extern @handshake_mux_2(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.channel<i1>, in %ins_1 : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_7(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i1>, DEBUG_COUNTER = false, NUM_SLOTS = 2 : ui32}}
  hw.module.extern @handshake_buffer_8(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i1>, DEBUG_COUNTER = false, NUM_SLOTS = 3 : ui32}}
  hw.module.extern @handshake_fork_4(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>, out outs_2 : !handshake.channel<i1>, out outs_3 : !handshake.channel<i1>, out outs_4 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 5 : ui32}}
  hw.module.extern @handshake_fork_5(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>, out outs_2 : !handshake.channel<i1>, out outs_3 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 4 : ui32}}
  hw.module.extern @handshake_fork_6(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>, out outs_2 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 3 : ui32}}
  hw.module.extern @handshake_buffer_9(in %ins : !handshake.channel<i11>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i11>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.channel<i11>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_fork_7(in %ins : !handshake.channel<i11>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i11>, out outs_1 : !handshake.channel<i11>, out outs_2 : !handshake.channel<i11>, out outs_3 : !handshake.channel<i11>, out outs_4 : !handshake.channel<i11>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i11>, SIZE = 5 : ui32}}
  hw.module.extern @handshake_passer_4(in %data : !handshake.channel<i11>, in %ctrl : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i11>) attributes {hw.name = "handshake.passer", hw.parameters = {}}
  hw.module.extern @handshake_trunci_1(in %ins : !handshake.channel<i12>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i11>) attributes {hw.name = "handshake.trunci", hw.parameters = {INPUT_TYPE = !handshake.channel<i12>, OUTPUT_TYPE = !handshake.channel<i11>}}
  hw.module.extern @handshake_buffer_10(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i1>, DEBUG_COUNTER = false, NUM_SLOTS = 5 : ui32}}
  hw.module.extern @handshake_buffer_11(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.control<>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.control<>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_buffer_12(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.control<>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.control<>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_fork_8(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.control<>, out outs_1 : !handshake.control<>, out outs_2 : !handshake.control<>, out outs_3 : !handshake.control<>, out outs_4 : !handshake.control<>, out outs_5 : !handshake.control<>, out outs_6 : !handshake.control<>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.control<>, SIZE = 7 : ui32}}
  hw.module.extern @handshake_extsi_5(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i1>, OUTPUT_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_mux_3(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.channel<i12>, in %ins_1 : !handshake.channel<i12>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i12>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<i12>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_mux_4(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.channel<i32>, in %ins_1 : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_control_merge_0(in %ins_0 : !handshake.control<>, in %ins_1 : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.control<>, out index : !handshake.channel<i1>) attributes {hw.name = "handshake.control_merge", hw.parameters = {DATA_TYPE = !handshake.control<>, INDEX_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_extsi_6(in %ins : !handshake.channel<i12>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i12>, OUTPUT_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_fork_9(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.control<>, out outs_1 : !handshake.control<>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.control<>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_extsi_7(in %ins : !handshake.channel<i2>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i2>, OUTPUT_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_shli_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.shli", hw.parameters = {DATA_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_buffer_13(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<i32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_andi_1(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.andi", hw.parameters = {DATA_TYPE = !handshake.channel<i32>}}
  hw.module.extern @mem_to_bram_32_10(in %loadEn : i1, in %loadAddr : i10, in %storeEn : i1, in %storeAddr : i10, in %storeData : i32, in %din0 : i32, in %din1 : i32, out ce0 : i1, out we0 : i1, out address0 : i10, out dout0 : i32, out ce1 : i1, out we1 : i1, out address1 : i10, out dout1 : i32, out loadData : i32) attributes {hw.name = "mem_to_bram", hw.parameters = {ADDR_WIDTH = 10 : ui32, DATA_WIDTH = 32 : ui32}}
  hw.module @collision_donut_wrapper(in %x_din0 : i32, in %x_din1 : i32, in %y_din0 : i32, in %y_din1 : i32, in %x_start : !handshake.control<>, in %y_start : !handshake.control<>, in %start : !handshake.control<>, in %clk : i1, in %rst : i1, out out0 : !handshake.channel<i32>, out x_end : !handshake.control<>, out y_end : !handshake.control<>, out end : !handshake.control<>, out x_ce0 : i1, out x_we0 : i1, out x_address0 : i10, out x_dout0 : i32, out x_ce1 : i1, out x_we1 : i1, out x_address1 : i10, out x_dout1 : i32, out y_ce0 : i1, out y_we0 : i1, out y_address0 : i10, out y_dout0 : i32, out y_ce1 : i1, out y_we1 : i1, out y_address1 : i10, out y_dout1 : i32) {
    %mem_to_bram_converter_y.ce0, %mem_to_bram_converter_y.we0, %mem_to_bram_converter_y.address0, %mem_to_bram_converter_y.dout0, %mem_to_bram_converter_y.ce1, %mem_to_bram_converter_y.we1, %mem_to_bram_converter_y.address1, %mem_to_bram_converter_y.dout1, %mem_to_bram_converter_y.loadData = hw.instance "mem_to_bram_converter_y" @mem_to_bram_32_10(loadEn: %collision_donut_wrapped.y_loadEn: i1, loadAddr: %collision_donut_wrapped.y_loadAddr: i10, storeEn: %collision_donut_wrapped.y_storeEn: i1, storeAddr: %collision_donut_wrapped.y_storeAddr: i10, storeData: %collision_donut_wrapped.y_storeData: i32, din0: %y_din0: i32, din1: %y_din1: i32) -> (ce0: i1, we0: i1, address0: i10, dout0: i32, ce1: i1, we1: i1, address1: i10, dout1: i32, loadData: i32)
    %mem_to_bram_converter_x.ce0, %mem_to_bram_converter_x.we0, %mem_to_bram_converter_x.address0, %mem_to_bram_converter_x.dout0, %mem_to_bram_converter_x.ce1, %mem_to_bram_converter_x.we1, %mem_to_bram_converter_x.address1, %mem_to_bram_converter_x.dout1, %mem_to_bram_converter_x.loadData = hw.instance "mem_to_bram_converter_x" @mem_to_bram_32_10(loadEn: %collision_donut_wrapped.x_loadEn: i1, loadAddr: %collision_donut_wrapped.x_loadAddr: i10, storeEn: %collision_donut_wrapped.x_storeEn: i1, storeAddr: %collision_donut_wrapped.x_storeAddr: i10, storeData: %collision_donut_wrapped.x_storeData: i32, din0: %x_din0: i32, din1: %x_din1: i32) -> (ce0: i1, we0: i1, address0: i10, dout0: i32, ce1: i1, we1: i1, address1: i10, dout1: i32, loadData: i32)
    %collision_donut_wrapped.out0, %collision_donut_wrapped.x_end, %collision_donut_wrapped.y_end, %collision_donut_wrapped.end, %collision_donut_wrapped.x_loadEn, %collision_donut_wrapped.x_loadAddr, %collision_donut_wrapped.x_storeEn, %collision_donut_wrapped.x_storeAddr, %collision_donut_wrapped.x_storeData, %collision_donut_wrapped.y_loadEn, %collision_donut_wrapped.y_loadAddr, %collision_donut_wrapped.y_storeEn, %collision_donut_wrapped.y_storeAddr, %collision_donut_wrapped.y_storeData = hw.instance "collision_donut_wrapped" @collision_donut(x_loadData: %mem_to_bram_converter_x.loadData: i32, y_loadData: %mem_to_bram_converter_y.loadData: i32, x_start: %x_start: !handshake.control<>, y_start: %y_start: !handshake.control<>, start: %start: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (out0: !handshake.channel<i32>, x_end: !handshake.control<>, y_end: !handshake.control<>, end: !handshake.control<>, x_loadEn: i1, x_loadAddr: i10, x_storeEn: i1, x_storeAddr: i10, x_storeData: i32, y_loadEn: i1, y_loadAddr: i10, y_storeEn: i1, y_storeAddr: i10, y_storeData: i32)
    hw.output %collision_donut_wrapped.out0, %collision_donut_wrapped.x_end, %collision_donut_wrapped.y_end, %collision_donut_wrapped.end, %mem_to_bram_converter_x.ce0, %mem_to_bram_converter_x.we0, %mem_to_bram_converter_x.address0, %mem_to_bram_converter_x.dout0, %mem_to_bram_converter_x.ce1, %mem_to_bram_converter_x.we1, %mem_to_bram_converter_x.address1, %mem_to_bram_converter_x.dout1, %mem_to_bram_converter_y.ce0, %mem_to_bram_converter_y.we0, %mem_to_bram_converter_y.address0, %mem_to_bram_converter_y.dout0, %mem_to_bram_converter_y.ce1, %mem_to_bram_converter_y.we1, %mem_to_bram_converter_y.address1, %mem_to_bram_converter_y.dout1 : !handshake.channel<i32>, !handshake.control<>, !handshake.control<>, !handshake.control<>, i1, i1, i10, i32, i1, i1, i10, i32, i1, i1, i10, i32, i1, i1, i10, i32
  }
}

