module {
  hw.module @nested_loop(in %a_loadData : i32, in %b_loadData : i32, in %c_loadData : i32, in %a_start : !handshake.control<>, in %b_start : !handshake.control<>, in %c_start : !handshake.control<>, in %start : !handshake.control<>, in %clk : i1, in %rst : i1, out a_end : !handshake.control<>, out b_end : !handshake.control<>, out c_end : !handshake.control<>, out end : !handshake.control<>, out a_loadEn : i1, out a_loadAddr : i10, out a_storeEn : i1, out a_storeAddr : i10, out a_storeData : i32, out b_loadEn : i1, out b_loadAddr : i10, out b_storeEn : i1, out b_storeAddr : i10, out b_storeData : i32, out c_loadEn : i1, out c_loadAddr : i10, out c_storeEn : i1, out c_storeAddr : i10, out c_storeData : i32) {
    %fork0.outs_0, %fork0.outs_1, %fork0.outs_2 = hw.instance "fork0" @handshake_fork_0(ins: %start: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.control<>, outs_1: !handshake.control<>, outs_2: !handshake.control<>)
    %mem_controller3.memEnd, %mem_controller3.loadEn, %mem_controller3.loadAddr, %mem_controller3.storeEn, %mem_controller3.storeAddr, %mem_controller3.storeData = hw.instance "mem_controller3" @handshake_mem_controller_0(loadData: %c_loadData: i32, memStart: %c_start: !handshake.control<>, ctrl_0: %passer2.result: !handshake.channel<i32>, stAddr_0: %store1.addrOut: !handshake.channel<i10>, stData_0: %store1.dataToMem: !handshake.channel<i32>, ctrlEnd: %fork11.outs_2: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (memEnd: !handshake.control<>, loadEn: i1, loadAddr: i10, storeEn: i1, storeAddr: i10, storeData: i32)
    %mem_controller4.ldData_0, %mem_controller4.memEnd, %mem_controller4.loadEn, %mem_controller4.loadAddr, %mem_controller4.storeEn, %mem_controller4.storeAddr, %mem_controller4.storeData = hw.instance "mem_controller4" @handshake_mem_controller_1(loadData: %b_loadData: i32, memStart: %b_start: !handshake.control<>, ldAddr_0: %load3.addrOut: !handshake.channel<i10>, ctrlEnd: %fork11.outs_1: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (ldData_0: !handshake.channel<i32>, memEnd: !handshake.control<>, loadEn: i1, loadAddr: i10, storeEn: i1, storeAddr: i10, storeData: i32)
    %mem_controller5.ldData_0, %mem_controller5.memEnd, %mem_controller5.loadEn, %mem_controller5.loadAddr, %mem_controller5.storeEn, %mem_controller5.storeAddr, %mem_controller5.storeData = hw.instance "mem_controller5" @handshake_mem_controller_2(loadData: %a_loadData: i32, memStart: %a_start: !handshake.control<>, ldAddr_0: %load2.addrOut: !handshake.channel<i10>, ctrlEnd: %fork11.outs_0: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (ldData_0: !handshake.channel<i32>, memEnd: !handshake.control<>, loadEn: i1, loadAddr: i10, storeEn: i1, storeAddr: i10, storeData: i32)
    %constant3.outs = hw.instance "constant3" @handshake_constant_0(ctrl: %fork0.outs_0: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %extsi8.outs = hw.instance "extsi8" @handshake_extsi_0(ins: %constant3.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i2>)
    %mux0.outs = hw.instance "mux0" @handshake_mux_0(index: %control_merge0.index: !handshake.channel<i1>, ins_0: %extsi8.outs: !handshake.channel<i2>, ins_1: %cond_br6.trueOut: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i2>)
    %buffer0.outs = hw.instance "buffer0" @handshake_buffer_0(ins: %mux0.outs: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i2>)
    %fork1.outs_0, %fork1.outs_1 = hw.instance "fork1" @handshake_fork_1(ins: %buffer0.outs: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i2>, outs_1: !handshake.channel<i2>)
    %extsi9.outs = hw.instance "extsi9" @handshake_extsi_1(ins: %fork1.outs_0: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i12>)
    %control_merge0.outs, %control_merge0.index = hw.instance "control_merge0" @handshake_control_merge_0(ins_0: %fork0.outs_2: !handshake.control<>, ins_1: %cond_br7.trueOut: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>, index: !handshake.channel<i1>)
    %fork2.outs_0, %fork2.outs_1 = hw.instance "fork2" @handshake_fork_2(ins: %control_merge0.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.control<>, outs_1: !handshake.control<>)
    %source0.outs = hw.instance "source0" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant4.outs = hw.instance "constant4" @handshake_constant_1(ctrl: %source0.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i10>)
    %extsi10.outs = hw.instance "extsi10" @handshake_extsi_2(ins: %constant4.outs: !handshake.channel<i10>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i12>)
    %constant5.outs = hw.instance "constant5" @handshake_constant_0(ctrl: %fork2.outs_0: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %muli0.result = hw.instance "muli0" @handshake_muli_0(lhs: %extsi9.outs: !handshake.channel<i12>, rhs: %extsi10.outs: !handshake.channel<i12>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i12>)
    %extsi11.outs = hw.instance "extsi11" @handshake_extsi_3(ins: %constant5.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %mux1.outs = hw.instance "mux1" @handshake_mux_1(index: %fork18.outs_3: !handshake.channel<i1>, ins_0: %extsi11.outs: !handshake.channel<i32>, ins_1: %passer4.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer1.outs = hw.instance "buffer1" @handshake_buffer_1(ins: %mux1.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %fork3.outs_0, %fork3.outs_1, %fork3.outs_2, %fork3.outs_3 = hw.instance "fork3" @handshake_fork_3(ins: %buffer1.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>, outs_2: !handshake.channel<i32>, outs_3: !handshake.channel<i32>)
    %trunci0.outs = hw.instance "trunci0" @handshake_trunci_0(ins: %fork3.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i10>)
    %trunci1.outs = hw.instance "trunci1" @handshake_trunci_0(ins: %fork3.outs_1: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i10>)
    %trunci2.outs = hw.instance "trunci2" @handshake_trunci_0(ins: %fork3.outs_2: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i10>)
    %mux2.outs = hw.instance "mux2" @handshake_mux_0(index: %fork18.outs_2: !handshake.channel<i1>, ins_0: %fork1.outs_1: !handshake.channel<i2>, ins_1: %passer5.result: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i2>)
    %buffer12.outs = hw.instance "buffer12" @handshake_buffer_2(ins: %fork18.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer13.outs = hw.instance "buffer13" @handshake_buffer_3(ins: %passer3.result: !handshake.channel<i12>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i12>)
    %mux3.outs = hw.instance "mux3" @handshake_mux_2(index: %buffer12.outs: !handshake.channel<i1>, ins_0: %muli0.result: !handshake.channel<i12>, ins_1: %buffer13.outs: !handshake.channel<i12>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i12>)
    %buffer6.outs = hw.instance "buffer6" @handshake_buffer_4(ins: %mux3.outs: !handshake.channel<i12>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i12>)
    %fork4.outs_0, %fork4.outs_1 = hw.instance "fork4" @handshake_fork_4(ins: %buffer6.outs: !handshake.channel<i12>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i12>, outs_1: !handshake.channel<i12>)
    %trunci3.outs = hw.instance "trunci3" @handshake_trunci_1(ins: %fork4.outs_0: !handshake.channel<i12>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i10>)
    %mux4.outs = hw.instance "mux4" @handshake_mux_3(index: %fork18.outs_0: !handshake.channel<i1>, ins_0: %fork2.outs_1: !handshake.control<>, ins_1: %passer6.result: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %buffer7.outs = hw.instance "buffer7" @handshake_buffer_5(ins: %mux4.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %buffer8.outs = hw.instance "buffer8" @handshake_buffer_6(ins: %buffer7.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %fork17.outs_0, %fork17.outs_1, %fork17.outs_2 = hw.instance "fork17" @handshake_fork_0(ins: %buffer8.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.control<>, outs_1: !handshake.control<>, outs_2: !handshake.control<>)
    %constant6.outs = hw.instance "constant6" @handshake_constant_2(ctrl: %fork17.outs_0: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i2>)
    %extsi3.outs = hw.instance "extsi3" @handshake_extsi_4(ins: %constant6.outs: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %source1.outs = hw.instance "source1" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant13.outs = hw.instance "constant13" @handshake_constant_2(ctrl: %source1.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i2>)
    %extsi4.outs = hw.instance "extsi4" @handshake_extsi_4(ins: %constant13.outs: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %source2.outs = hw.instance "source2" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant14.outs = hw.instance "constant14" @handshake_constant_3(ctrl: %source2.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i11>)
    %extsi5.outs = hw.instance "extsi5" @handshake_extsi_5(ins: %constant14.outs: !handshake.channel<i11>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %load2.addrOut, %load2.dataOut = hw.instance "load2" @handshake_load_0(addrIn: %trunci2.outs: !handshake.channel<i10>, dataFromMem: %mem_controller5.ldData_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (addrOut: !handshake.channel<i10>, dataOut: !handshake.channel<i32>)
    %load3.addrOut, %load3.dataOut = hw.instance "load3" @handshake_load_0(addrIn: %trunci1.outs: !handshake.channel<i10>, dataFromMem: %mem_controller4.ldData_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (addrOut: !handshake.channel<i10>, dataOut: !handshake.channel<i32>)
    %muli1.result = hw.instance "muli1" @handshake_muli_1(lhs: %load2.dataOut: !handshake.channel<i32>, rhs: %load3.dataOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %fork7.outs_0, %fork7.outs_1 = hw.instance "fork7" @handshake_fork_5(ins: %muli1.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>)
    %buffer3.outs = hw.instance "buffer3" @handshake_buffer_7(ins: %trunci0.outs: !handshake.channel<i10>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i10>)
    %addi0.result = hw.instance "addi0" @handshake_addi_0(lhs: %buffer3.outs: !handshake.channel<i10>, rhs: %trunci3.outs: !handshake.channel<i10>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i10>)
    %store1.addrOut, %store1.dataToMem = hw.instance "store1" @handshake_store_0(addrIn: %passer1.result: !handshake.channel<i10>, dataIn: %passer0.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (addrOut: !handshake.channel<i10>, dataToMem: !handshake.channel<i32>)
    %cmpi0.result = hw.instance "cmpi0" @handshake_cmpi_0(lhs: %fork7.outs_1: !handshake.channel<i32>, rhs: %extsi5.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %not0.outs = hw.instance "not0" @handshake_not_0(ins: %fork22.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %passer0.result = hw.instance "passer0" @handshake_passer_0(data: %fork7.outs_0: !handshake.channel<i32>, ctrl: %fork21.outs_3: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %buffer11.outs = hw.instance "buffer11" @handshake_buffer_8(ins: %addi0.result: !handshake.channel<i10>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i10>)
    %passer1.result = hw.instance "passer1" @handshake_passer_1(data: %buffer11.outs: !handshake.channel<i10>, ctrl: %fork21.outs_2: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i10>)
    %buffer10.outs = hw.instance "buffer10" @handshake_buffer_9(ins: %extsi3.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %passer2.result = hw.instance "passer2" @handshake_passer_0(data: %buffer10.outs: !handshake.channel<i32>, ctrl: %fork21.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %buffer15.outs = hw.instance "buffer15" @handshake_buffer_10(ins: %fork19.outs_5: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %init0.outs = hw.instance "init0" @handshake_init_0(ins: %buffer15.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %fork18.outs_0, %fork18.outs_1, %fork18.outs_2, %fork18.outs_3 = hw.instance "fork18" @handshake_fork_6(ins: %init0.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>, outs_3: !handshake.channel<i1>)
    %passer3.result = hw.instance "passer3" @handshake_passer_2(data: %fork4.outs_1: !handshake.channel<i12>, ctrl: %fork19.outs_4: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i12>)
    %passer4.result = hw.instance "passer4" @handshake_passer_0(data: %addi1.result: !handshake.channel<i32>, ctrl: %fork19.outs_3: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %passer5.result = hw.instance "passer5" @handshake_passer_3(data: %fork16.outs_1: !handshake.channel<i2>, ctrl: %fork19.outs_2: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i2>)
    %passer6.result = hw.instance "passer6" @handshake_passer_4(data: %fork17.outs_2: !handshake.control<>, ctrl: %fork19.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.control<>)
    %buffer16.outs = hw.instance "buffer16" @handshake_buffer_11(ins: %spec_v2_repeating_init1.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer17.outs = hw.instance "buffer17" @handshake_buffer_2(ins: %buffer16.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %spec_v2_repeating_init0.outs = hw.instance "spec_v2_repeating_init0" @handshake_spec_v2_repeating_init_0(ins: %buffer17.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %fork19.outs_0, %fork19.outs_1, %fork19.outs_2, %fork19.outs_3, %fork19.outs_4, %fork19.outs_5 = hw.instance "fork19" @handshake_fork_7(ins: %spec_v2_repeating_init0.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>, outs_3: !handshake.channel<i1>, outs_4: !handshake.channel<i1>, outs_5: !handshake.channel<i1>)
    %buffer18.outs = hw.instance "buffer18" @handshake_buffer_10(ins: %spec_v2_repeating_init2.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %spec_v2_repeating_init1.outs = hw.instance "spec_v2_repeating_init1" @handshake_spec_v2_repeating_init_0(ins: %buffer18.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer19.outs = hw.instance "buffer19" @handshake_buffer_10(ins: %spec_v2_repeating_init3.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %spec_v2_repeating_init2.outs = hw.instance "spec_v2_repeating_init2" @handshake_spec_v2_repeating_init_0(ins: %buffer19.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer20.outs = hw.instance "buffer20" @handshake_buffer_10(ins: %spec_v2_repeating_init4.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %spec_v2_repeating_init3.outs = hw.instance "spec_v2_repeating_init3" @handshake_spec_v2_repeating_init_0(ins: %buffer20.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer21.outs = hw.instance "buffer21" @handshake_buffer_10(ins: %passer7.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %spec_v2_repeating_init4.outs = hw.instance "spec_v2_repeating_init4" @handshake_spec_v2_repeating_init_0(ins: %buffer21.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %passer7.result = hw.instance "passer7" @handshake_passer_5(data: %fork22.outs_2: !handshake.channel<i1>, ctrl: %fork21.outs_4: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %andi0.result = hw.instance "andi0" @handshake_andi_0(lhs: %fork21.outs_0: !handshake.channel<i1>, rhs: %not0.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %buffer22.outs = hw.instance "buffer22" @handshake_buffer_11(ins: %andi0.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %fork20.outs_0, %fork20.outs_1 = hw.instance "fork20" @handshake_fork_8(ins: %buffer22.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>)
    %buffer14.outs = hw.instance "buffer14" @handshake_buffer_12(ins: %fork19.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %spec_v2_resolver0.confirmSpec = hw.instance "spec_v2_resolver0" @handshake_spec_v2_resolver_0(actualCondition: %fork22.outs_1: !handshake.channel<i1>, generatedCondition: %buffer14.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (confirmSpec: !handshake.channel<i1>)
    %fork21.outs_0, %fork21.outs_1, %fork21.outs_2, %fork21.outs_3, %fork21.outs_4 = hw.instance "fork21" @handshake_fork_9(ins: %spec_v2_resolver0.confirmSpec: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>, outs_3: !handshake.channel<i1>, outs_4: !handshake.channel<i1>)
    %fork22.outs_0, %fork22.outs_1, %fork22.outs_2 = hw.instance "fork22" @handshake_fork_10(ins: %cmpi0.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>)
    %buffer2.outs = hw.instance "buffer2" @handshake_buffer_13(ins: %fork3.outs_3: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %addi1.result = hw.instance "addi1" @handshake_addi_1(lhs: %buffer2.outs: !handshake.channel<i32>, rhs: %extsi4.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %buffer4.outs = hw.instance "buffer4" @handshake_buffer_14(ins: %mux2.outs: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i2>)
    %buffer5.outs = hw.instance "buffer5" @handshake_buffer_0(ins: %buffer4.outs: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i2>)
    %fork16.outs_0, %fork16.outs_1 = hw.instance "fork16" @handshake_fork_1(ins: %buffer5.outs: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i2>, outs_1: !handshake.channel<i2>)
    %buffer23.outs = hw.instance "buffer23" @handshake_buffer_15(ins: %fork16.outs_0: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i2>)
    %passer8.result = hw.instance "passer8" @handshake_passer_3(data: %buffer23.outs: !handshake.channel<i2>, ctrl: %fork20.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i2>)
    %buffer9.outs = hw.instance "buffer9" @handshake_buffer_16(ins: %fork17.outs_1: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %passer9.result = hw.instance "passer9" @handshake_passer_4(data: %buffer9.outs: !handshake.control<>, ctrl: %fork20.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.control<>)
    %extsi12.outs = hw.instance "extsi12" @handshake_extsi_6(ins: %passer8.result: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i3>)
    %source3.outs = hw.instance "source3" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant15.outs = hw.instance "constant15" @handshake_constant_4(ctrl: %source3.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i3>)
    %source4.outs = hw.instance "source4" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant16.outs = hw.instance "constant16" @handshake_constant_2(ctrl: %source4.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i2>)
    %extsi13.outs = hw.instance "extsi13" @handshake_extsi_6(ins: %constant16.outs: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i3>)
    %addi2.result = hw.instance "addi2" @handshake_addi_2(lhs: %extsi12.outs: !handshake.channel<i3>, rhs: %extsi13.outs: !handshake.channel<i3>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i3>)
    %fork9.outs_0, %fork9.outs_1 = hw.instance "fork9" @handshake_fork_11(ins: %addi2.result: !handshake.channel<i3>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i3>, outs_1: !handshake.channel<i3>)
    %trunci4.outs = hw.instance "trunci4" @handshake_trunci_2(ins: %fork9.outs_0: !handshake.channel<i3>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i2>)
    %cmpi1.result = hw.instance "cmpi1" @handshake_cmpi_1(lhs: %fork9.outs_1: !handshake.channel<i3>, rhs: %constant15.outs: !handshake.channel<i3>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %fork10.outs_0, %fork10.outs_1 = hw.instance "fork10" @handshake_fork_8(ins: %cmpi1.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>)
    %cond_br6.trueOut, %cond_br6.falseOut = hw.instance "cond_br6" @handshake_cond_br_0(condition: %fork10.outs_0: !handshake.channel<i1>, data: %trunci4.outs: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i2>, falseOut: !handshake.channel<i2>)
    hw.instance "sink3" @handshake_sink_0(ins: %cond_br6.falseOut: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> ()
    %cond_br7.trueOut, %cond_br7.falseOut = hw.instance "cond_br7" @handshake_cond_br_1(condition: %fork10.outs_1: !handshake.channel<i1>, data: %passer9.result: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.control<>, falseOut: !handshake.control<>)
    %fork11.outs_0, %fork11.outs_1, %fork11.outs_2 = hw.instance "fork11" @handshake_fork_0(ins: %cond_br7.falseOut: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.control<>, outs_1: !handshake.control<>, outs_2: !handshake.control<>)
    hw.output %mem_controller5.memEnd, %mem_controller4.memEnd, %mem_controller3.memEnd, %fork0.outs_1, %mem_controller5.loadEn, %mem_controller5.loadAddr, %mem_controller5.storeEn, %mem_controller5.storeAddr, %mem_controller5.storeData, %mem_controller4.loadEn, %mem_controller4.loadAddr, %mem_controller4.storeEn, %mem_controller4.storeAddr, %mem_controller4.storeData, %mem_controller3.loadEn, %mem_controller3.loadAddr, %mem_controller3.storeEn, %mem_controller3.storeAddr, %mem_controller3.storeData : !handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>, i1, i10, i1, i10, i32, i1, i10, i1, i10, i32, i1, i10, i1, i10, i32
  }
  hw.module.extern @handshake_fork_0(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.control<>, out outs_1 : !handshake.control<>, out outs_2 : !handshake.control<>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.control<>, SIZE = 3 : ui32}}
  hw.module.extern @handshake_mem_controller_0(in %loadData : i32, in %memStart : !handshake.control<>, in %ctrl_0 : !handshake.channel<i32>, in %stAddr_0 : !handshake.channel<i10>, in %stData_0 : !handshake.channel<i32>, in %ctrlEnd : !handshake.control<>, in %clk : i1, in %rst : i1, out memEnd : !handshake.control<>, out loadEn : i1, out loadAddr : i10, out storeEn : i1, out storeAddr : i10, out storeData : i32) attributes {hw.name = "handshake.mem_controller", hw.parameters = {ADDR_TYPE = !handshake.channel<i10>, DATA_TYPE = !handshake.channel<i32>, NUM_CONTROLS = 1 : ui32, NUM_LOADS = 0 : ui32, NUM_STORES = 1 : ui32}}
  hw.module.extern @handshake_mem_controller_1(in %loadData : i32, in %memStart : !handshake.control<>, in %ldAddr_0 : !handshake.channel<i10>, in %ctrlEnd : !handshake.control<>, in %clk : i1, in %rst : i1, out ldData_0 : !handshake.channel<i32>, out memEnd : !handshake.control<>, out loadEn : i1, out loadAddr : i10, out storeEn : i1, out storeAddr : i10, out storeData : i32) attributes {hw.name = "handshake.mem_controller", hw.parameters = {ADDR_TYPE = !handshake.channel<i10>, DATA_TYPE = !handshake.channel<i32>, NUM_CONTROLS = 0 : ui32, NUM_LOADS = 1 : ui32, NUM_STORES = 0 : ui32}}
  hw.module.extern @handshake_mem_controller_2(in %loadData : i32, in %memStart : !handshake.control<>, in %ldAddr_0 : !handshake.channel<i10>, in %ctrlEnd : !handshake.control<>, in %clk : i1, in %rst : i1, out ldData_0 : !handshake.channel<i32>, out memEnd : !handshake.control<>, out loadEn : i1, out loadAddr : i10, out storeEn : i1, out storeAddr : i10, out storeData : i32) attributes {hw.name = "handshake.mem_controller", hw.parameters = {ADDR_TYPE = !handshake.channel<i10>, DATA_TYPE = !handshake.channel<i32>, NUM_CONTROLS = 0 : ui32, NUM_LOADS = 1 : ui32, NUM_STORES = 0 : ui32}}
  hw.module.extern @handshake_constant_0(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 1 : ui32, VALUE = "0"}}
  hw.module.extern @handshake_extsi_0(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i2>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i1>, OUTPUT_TYPE = !handshake.channel<i2>}}
  hw.module.extern @handshake_mux_0(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.channel<i2>, in %ins_1 : !handshake.channel<i2>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i2>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<i2>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_0(in %ins : !handshake.channel<i2>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i2>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.channel<i2>, NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 0, V: 0, R: 1}>}}
  hw.module.extern @handshake_fork_1(in %ins : !handshake.channel<i2>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i2>, out outs_1 : !handshake.channel<i2>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i2>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_extsi_1(in %ins : !handshake.channel<i2>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i12>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i2>, OUTPUT_TYPE = !handshake.channel<i12>}}
  hw.module.extern @handshake_control_merge_0(in %ins_0 : !handshake.control<>, in %ins_1 : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.control<>, out index : !handshake.channel<i1>) attributes {hw.name = "handshake.control_merge", hw.parameters = {DATA_TYPE = !handshake.control<>, INDEX_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_fork_2(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.control<>, out outs_1 : !handshake.control<>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.control<>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_source_0(in %clk : i1, in %rst : i1, out outs : !handshake.control<>) attributes {hw.name = "handshake.source", hw.parameters = {}}
  hw.module.extern @handshake_constant_1(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i10>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 10 : ui32, VALUE = "0110010000"}}
  hw.module.extern @handshake_extsi_2(in %ins : !handshake.channel<i10>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i12>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i10>, OUTPUT_TYPE = !handshake.channel<i12>}}
  hw.module.extern @handshake_muli_0(in %lhs : !handshake.channel<i12>, in %rhs : !handshake.channel<i12>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i12>) attributes {hw.name = "handshake.muli", hw.parameters = {DATA_TYPE = !handshake.channel<i12>, INTERNAL_DELAY = "1_000000"}}
  hw.module.extern @handshake_extsi_3(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i1>, OUTPUT_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_mux_1(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.channel<i32>, in %ins_1 : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_1(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.channel<i32>, NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 0, V: 0, R: 1}>}}
  hw.module.extern @handshake_fork_3(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>, out outs_2 : !handshake.channel<i32>, out outs_3 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, SIZE = 4 : ui32}}
  hw.module.extern @handshake_trunci_0(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i10>) attributes {hw.name = "handshake.trunci", hw.parameters = {INPUT_TYPE = !handshake.channel<i32>, OUTPUT_TYPE = !handshake.channel<i10>}}
  hw.module.extern @handshake_buffer_2(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i1>, NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 0, V: 0, R: 0}>}}
  hw.module.extern @handshake_buffer_3(in %ins : !handshake.channel<i12>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i12>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<i12>, NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 1, V: 1, R: 0}>}}
  hw.module.extern @handshake_mux_2(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.channel<i12>, in %ins_1 : !handshake.channel<i12>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i12>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<i12>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_4(in %ins : !handshake.channel<i12>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i12>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.channel<i12>, NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 0, V: 0, R: 1}>}}
  hw.module.extern @handshake_fork_4(in %ins : !handshake.channel<i12>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i12>, out outs_1 : !handshake.channel<i12>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i12>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_trunci_1(in %ins : !handshake.channel<i12>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i10>) attributes {hw.name = "handshake.trunci", hw.parameters = {INPUT_TYPE = !handshake.channel<i12>, OUTPUT_TYPE = !handshake.channel<i10>}}
  hw.module.extern @handshake_mux_3(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.control<>, in %ins_1 : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.control<>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.control<>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_5(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.control<>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.control<>, NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 1, V: 1, R: 0}>}}
  hw.module.extern @handshake_buffer_6(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.control<>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.control<>, NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 0, V: 0, R: 1}>}}
  hw.module.extern @handshake_constant_2(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i2>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 2 : ui32, VALUE = "01"}}
  hw.module.extern @handshake_extsi_4(in %ins : !handshake.channel<i2>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i2>, OUTPUT_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_constant_3(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i11>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 11 : ui32, VALUE = "01111101000"}}
  hw.module.extern @handshake_extsi_5(in %ins : !handshake.channel<i11>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i11>, OUTPUT_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_load_0(in %addrIn : !handshake.channel<i10>, in %dataFromMem : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out addrOut : !handshake.channel<i10>, out dataOut : !handshake.channel<i32>) attributes {hw.name = "handshake.load", hw.parameters = {ADDR_TYPE = !handshake.channel<i10>, DATA_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_muli_1(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.muli", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, INTERNAL_DELAY = "1_000000"}}
  hw.module.extern @handshake_fork_5(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_7(in %ins : !handshake.channel<i10>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i10>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i10>, NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 0, V: 0, R: 0}>}}
  hw.module.extern @handshake_addi_0(in %lhs : !handshake.channel<i10>, in %rhs : !handshake.channel<i10>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i10>) attributes {hw.name = "handshake.addi", hw.parameters = {DATA_TYPE = !handshake.channel<i10>, INTERNAL_DELAY = "0_000000"}}
  hw.module.extern @handshake_store_0(in %addrIn : !handshake.channel<i10>, in %dataIn : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out addrOut : !handshake.channel<i10>, out dataToMem : !handshake.channel<i32>) attributes {hw.name = "handshake.store", hw.parameters = {ADDR_TYPE = !handshake.channel<i10>, DATA_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_cmpi_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.cmpi", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, PREDICATE = "slt"}}
  hw.module.extern @handshake_not_0(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.not", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, INTERNAL_DELAY = "0.0"}}
  hw.module.extern @handshake_passer_0(in %data : !handshake.channel<i32>, in %ctrl : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.passer", hw.parameters = {}}
  hw.module.extern @handshake_buffer_8(in %ins : !handshake.channel<i10>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i10>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i10>, NUM_SLOTS = 4 : ui32, TIMING = #handshake<timing {D: 0, V: 0, R: 0}>}}
  hw.module.extern @handshake_passer_1(in %data : !handshake.channel<i10>, in %ctrl : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i10>) attributes {hw.name = "handshake.passer", hw.parameters = {}}
  hw.module.extern @handshake_buffer_9(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i32>, NUM_SLOTS = 4 : ui32, TIMING = #handshake<timing {D: 0, V: 0, R: 0}>}}
  hw.module.extern @handshake_buffer_10(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i1>, NUM_SLOTS = 2 : ui32, TIMING = #handshake<timing {D: 0, V: 0, R: 0}>}}
  hw.module.extern @handshake_init_0(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.init", hw.parameters = {}}
  hw.module.extern @handshake_fork_6(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>, out outs_2 : !handshake.channel<i1>, out outs_3 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 4 : ui32}}
  hw.module.extern @handshake_passer_2(in %data : !handshake.channel<i12>, in %ctrl : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i12>) attributes {hw.name = "handshake.passer", hw.parameters = {}}
  hw.module.extern @handshake_passer_3(in %data : !handshake.channel<i2>, in %ctrl : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i2>) attributes {hw.name = "handshake.passer", hw.parameters = {}}
  hw.module.extern @handshake_passer_4(in %data : !handshake.control<>, in %ctrl : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.control<>) attributes {hw.name = "handshake.passer", hw.parameters = {}}
  hw.module.extern @handshake_buffer_11(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<i1>, NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 1, V: 1, R: 0}>}}
  hw.module.extern @handshake_spec_v2_repeating_init_0(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.spec_v2_repeating_init", hw.parameters = {}}
  hw.module.extern @handshake_fork_7(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>, out outs_2 : !handshake.channel<i1>, out outs_3 : !handshake.channel<i1>, out outs_4 : !handshake.channel<i1>, out outs_5 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 6 : ui32}}
  hw.module.extern @handshake_passer_5(in %data : !handshake.channel<i1>, in %ctrl : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.passer", hw.parameters = {}}
  hw.module.extern @handshake_andi_0(in %lhs : !handshake.channel<i1>, in %rhs : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.andi", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, INTERNAL_DELAY = "0_000000"}}
  hw.module.extern @handshake_fork_8(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_12(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i1>, NUM_SLOTS = 4 : ui32, TIMING = #handshake<timing {D: 0, V: 0, R: 0}>}}
  hw.module.extern @handshake_spec_v2_resolver_0(in %actualCondition : !handshake.channel<i1>, in %generatedCondition : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out confirmSpec : !handshake.channel<i1>) attributes {hw.name = "handshake.spec_v2_resolver", hw.parameters = {}}
  hw.module.extern @handshake_fork_9(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>, out outs_2 : !handshake.channel<i1>, out outs_3 : !handshake.channel<i1>, out outs_4 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 5 : ui32}}
  hw.module.extern @handshake_fork_10(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>, out outs_2 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 3 : ui32}}
  hw.module.extern @handshake_buffer_13(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<i32>, NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 1, V: 1, R: 0}>}}
  hw.module.extern @handshake_addi_1(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.addi", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, INTERNAL_DELAY = "0_000000"}}
  hw.module.extern @handshake_buffer_14(in %ins : !handshake.channel<i2>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i2>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<i2>, NUM_SLOTS = 1 : ui32, TIMING = #handshake<timing {D: 1, V: 1, R: 0}>}}
  hw.module.extern @handshake_buffer_15(in %ins : !handshake.channel<i2>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i2>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i2>, NUM_SLOTS = 5 : ui32, TIMING = #handshake<timing {D: 0, V: 0, R: 0}>}}
  hw.module.extern @handshake_buffer_16(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.control<>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.control<>, NUM_SLOTS = 5 : ui32, TIMING = #handshake<timing {D: 0, V: 0, R: 0}>}}
  hw.module.extern @handshake_extsi_6(in %ins : !handshake.channel<i2>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i3>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i2>, OUTPUT_TYPE = !handshake.channel<i3>}}
  hw.module.extern @handshake_constant_4(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i3>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 3 : ui32, VALUE = "010"}}
  hw.module.extern @handshake_addi_2(in %lhs : !handshake.channel<i3>, in %rhs : !handshake.channel<i3>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i3>) attributes {hw.name = "handshake.addi", hw.parameters = {DATA_TYPE = !handshake.channel<i3>, INTERNAL_DELAY = "0_000000"}}
  hw.module.extern @handshake_fork_11(in %ins : !handshake.channel<i3>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i3>, out outs_1 : !handshake.channel<i3>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i3>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_trunci_2(in %ins : !handshake.channel<i3>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i2>) attributes {hw.name = "handshake.trunci", hw.parameters = {INPUT_TYPE = !handshake.channel<i3>, OUTPUT_TYPE = !handshake.channel<i2>}}
  hw.module.extern @handshake_cmpi_1(in %lhs : !handshake.channel<i3>, in %rhs : !handshake.channel<i3>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.cmpi", hw.parameters = {DATA_TYPE = !handshake.channel<i3>, PREDICATE = "ult"}}
  hw.module.extern @handshake_cond_br_0(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i2>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i2>, out falseOut : !handshake.channel<i2>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<i2>}}
  hw.module.extern @handshake_sink_0(in %ins : !handshake.channel<i2>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.channel<i2>}}
  hw.module.extern @handshake_cond_br_1(in %condition : !handshake.channel<i1>, in %data : !handshake.control<>, in %clk : i1, in %rst : i1, out trueOut : !handshake.control<>, out falseOut : !handshake.control<>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.control<>}}
  hw.module.extern @mem_to_bram_32_10(in %loadEn : i1, in %loadAddr : i10, in %storeEn : i1, in %storeAddr : i10, in %storeData : i32, in %din0 : i32, in %din1 : i32, out ce0 : i1, out we0 : i1, out address0 : i10, out dout0 : i32, out ce1 : i1, out we1 : i1, out address1 : i10, out dout1 : i32, out loadData : i32) attributes {hw.name = "mem_to_bram", hw.parameters = {ADDR_WIDTH = 10 : ui32, DATA_WIDTH = 32 : ui32}}
  hw.module @nested_loop_wrapper(in %a_din0 : i32, in %a_din1 : i32, in %b_din0 : i32, in %b_din1 : i32, in %c_din0 : i32, in %c_din1 : i32, in %a_start : !handshake.control<>, in %b_start : !handshake.control<>, in %c_start : !handshake.control<>, in %start : !handshake.control<>, in %clk : i1, in %rst : i1, out a_end : !handshake.control<>, out b_end : !handshake.control<>, out c_end : !handshake.control<>, out end : !handshake.control<>, out a_ce0 : i1, out a_we0 : i1, out a_address0 : i10, out a_dout0 : i32, out a_ce1 : i1, out a_we1 : i1, out a_address1 : i10, out a_dout1 : i32, out b_ce0 : i1, out b_we0 : i1, out b_address0 : i10, out b_dout0 : i32, out b_ce1 : i1, out b_we1 : i1, out b_address1 : i10, out b_dout1 : i32, out c_ce0 : i1, out c_we0 : i1, out c_address0 : i10, out c_dout0 : i32, out c_ce1 : i1, out c_we1 : i1, out c_address1 : i10, out c_dout1 : i32) {
    %mem_to_bram_converter_c.ce0, %mem_to_bram_converter_c.we0, %mem_to_bram_converter_c.address0, %mem_to_bram_converter_c.dout0, %mem_to_bram_converter_c.ce1, %mem_to_bram_converter_c.we1, %mem_to_bram_converter_c.address1, %mem_to_bram_converter_c.dout1, %mem_to_bram_converter_c.loadData = hw.instance "mem_to_bram_converter_c" @mem_to_bram_32_10(loadEn: %nested_loop_wrapped.c_loadEn: i1, loadAddr: %nested_loop_wrapped.c_loadAddr: i10, storeEn: %nested_loop_wrapped.c_storeEn: i1, storeAddr: %nested_loop_wrapped.c_storeAddr: i10, storeData: %nested_loop_wrapped.c_storeData: i32, din0: %c_din0: i32, din1: %c_din1: i32) -> (ce0: i1, we0: i1, address0: i10, dout0: i32, ce1: i1, we1: i1, address1: i10, dout1: i32, loadData: i32)
    %mem_to_bram_converter_a.ce0, %mem_to_bram_converter_a.we0, %mem_to_bram_converter_a.address0, %mem_to_bram_converter_a.dout0, %mem_to_bram_converter_a.ce1, %mem_to_bram_converter_a.we1, %mem_to_bram_converter_a.address1, %mem_to_bram_converter_a.dout1, %mem_to_bram_converter_a.loadData = hw.instance "mem_to_bram_converter_a" @mem_to_bram_32_10(loadEn: %nested_loop_wrapped.a_loadEn: i1, loadAddr: %nested_loop_wrapped.a_loadAddr: i10, storeEn: %nested_loop_wrapped.a_storeEn: i1, storeAddr: %nested_loop_wrapped.a_storeAddr: i10, storeData: %nested_loop_wrapped.a_storeData: i32, din0: %a_din0: i32, din1: %a_din1: i32) -> (ce0: i1, we0: i1, address0: i10, dout0: i32, ce1: i1, we1: i1, address1: i10, dout1: i32, loadData: i32)
    %mem_to_bram_converter_b.ce0, %mem_to_bram_converter_b.we0, %mem_to_bram_converter_b.address0, %mem_to_bram_converter_b.dout0, %mem_to_bram_converter_b.ce1, %mem_to_bram_converter_b.we1, %mem_to_bram_converter_b.address1, %mem_to_bram_converter_b.dout1, %mem_to_bram_converter_b.loadData = hw.instance "mem_to_bram_converter_b" @mem_to_bram_32_10(loadEn: %nested_loop_wrapped.b_loadEn: i1, loadAddr: %nested_loop_wrapped.b_loadAddr: i10, storeEn: %nested_loop_wrapped.b_storeEn: i1, storeAddr: %nested_loop_wrapped.b_storeAddr: i10, storeData: %nested_loop_wrapped.b_storeData: i32, din0: %b_din0: i32, din1: %b_din1: i32) -> (ce0: i1, we0: i1, address0: i10, dout0: i32, ce1: i1, we1: i1, address1: i10, dout1: i32, loadData: i32)
    %nested_loop_wrapped.a_end, %nested_loop_wrapped.b_end, %nested_loop_wrapped.c_end, %nested_loop_wrapped.end, %nested_loop_wrapped.a_loadEn, %nested_loop_wrapped.a_loadAddr, %nested_loop_wrapped.a_storeEn, %nested_loop_wrapped.a_storeAddr, %nested_loop_wrapped.a_storeData, %nested_loop_wrapped.b_loadEn, %nested_loop_wrapped.b_loadAddr, %nested_loop_wrapped.b_storeEn, %nested_loop_wrapped.b_storeAddr, %nested_loop_wrapped.b_storeData, %nested_loop_wrapped.c_loadEn, %nested_loop_wrapped.c_loadAddr, %nested_loop_wrapped.c_storeEn, %nested_loop_wrapped.c_storeAddr, %nested_loop_wrapped.c_storeData = hw.instance "nested_loop_wrapped" @nested_loop(a_loadData: %mem_to_bram_converter_a.loadData: i32, b_loadData: %mem_to_bram_converter_b.loadData: i32, c_loadData: %mem_to_bram_converter_c.loadData: i32, a_start: %a_start: !handshake.control<>, b_start: %b_start: !handshake.control<>, c_start: %c_start: !handshake.control<>, start: %start: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (a_end: !handshake.control<>, b_end: !handshake.control<>, c_end: !handshake.control<>, end: !handshake.control<>, a_loadEn: i1, a_loadAddr: i10, a_storeEn: i1, a_storeAddr: i10, a_storeData: i32, b_loadEn: i1, b_loadAddr: i10, b_storeEn: i1, b_storeAddr: i10, b_storeData: i32, c_loadEn: i1, c_loadAddr: i10, c_storeEn: i1, c_storeAddr: i10, c_storeData: i32)
    hw.output %nested_loop_wrapped.a_end, %nested_loop_wrapped.b_end, %nested_loop_wrapped.c_end, %nested_loop_wrapped.end, %mem_to_bram_converter_a.ce0, %mem_to_bram_converter_a.we0, %mem_to_bram_converter_a.address0, %mem_to_bram_converter_a.dout0, %mem_to_bram_converter_a.ce1, %mem_to_bram_converter_a.we1, %mem_to_bram_converter_a.address1, %mem_to_bram_converter_a.dout1, %mem_to_bram_converter_b.ce0, %mem_to_bram_converter_b.we0, %mem_to_bram_converter_b.address0, %mem_to_bram_converter_b.dout0, %mem_to_bram_converter_b.ce1, %mem_to_bram_converter_b.we1, %mem_to_bram_converter_b.address1, %mem_to_bram_converter_b.dout1, %mem_to_bram_converter_c.ce0, %mem_to_bram_converter_c.we0, %mem_to_bram_converter_c.address0, %mem_to_bram_converter_c.dout0, %mem_to_bram_converter_c.ce1, %mem_to_bram_converter_c.we1, %mem_to_bram_converter_c.address1, %mem_to_bram_converter_c.dout1 : !handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>, i1, i1, i10, i32, i1, i1, i10, i32, i1, i1, i10, i32, i1, i1, i10, i32, i1, i1, i10, i32, i1, i1, i10, i32
  }
}

