module {
  hw.module @if_float2(in %x0 : !handshake.channel<i32>, in %a_loadData : i32, in %minus_trace_loadData : i32, in %a_start : !handshake.control<>, in %minus_trace_start : !handshake.control<>, in %start : !handshake.control<>, in %clk : i1, in %rst : i1, out out0 : !handshake.channel<i32>, out a_end : !handshake.control<>, out minus_trace_end : !handshake.control<>, out end : !handshake.control<>, out a_loadEn : i1, out a_loadAddr : i7, out a_storeEn : i1, out a_storeAddr : i7, out a_storeData : i32, out minus_trace_loadEn : i1, out minus_trace_loadAddr : i7, out minus_trace_storeEn : i1, out minus_trace_storeAddr : i7, out minus_trace_storeData : i32) {
    %fork0.outs_0, %fork0.outs_1, %fork0.outs_2 = hw.instance "fork0" @handshake_fork_0(ins: %start: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.control<>, outs_1: !handshake.control<>, outs_2: !handshake.control<>)
    %mem_controller2.memEnd, %mem_controller2.loadEn, %mem_controller2.loadAddr, %mem_controller2.storeEn, %mem_controller2.storeAddr, %mem_controller2.storeData = hw.instance "mem_controller2" @handshake_mem_controller_0(loadData: %minus_trace_loadData: i32, memStart: %minus_trace_start: !handshake.control<>, ctrl_0: %extsi1.outs: !handshake.channel<i32>, stAddr_0: %store0.addrOut: !handshake.channel<i7>, stData_0: %store0.dataToMem: !handshake.channel<i32>, ctrlEnd: %fork11.outs_1: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (memEnd: !handshake.control<>, loadEn: i1, loadAddr: i7, storeEn: i1, storeAddr: i7, storeData: i32)
    %mem_controller3.ldData_0, %mem_controller3.memEnd, %mem_controller3.loadEn, %mem_controller3.loadAddr, %mem_controller3.storeEn, %mem_controller3.storeAddr, %mem_controller3.storeData = hw.instance "mem_controller3" @handshake_mem_controller_1(loadData: %a_loadData: i32, memStart: %a_start: !handshake.control<>, ldAddr_0: %load0.addrOut: !handshake.channel<i7>, ctrlEnd: %fork11.outs_0: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (ldData_0: !handshake.channel<i32>, memEnd: !handshake.control<>, loadEn: i1, loadAddr: i7, storeEn: i1, storeAddr: i7, storeData: i32)
    %constant2.outs = hw.instance "constant2" @handshake_constant_0(ctrl: %fork0.outs_0: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %extsi4.outs = hw.instance "extsi4" @handshake_extsi_0(ins: %constant2.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8>)
    %mux0.outs = hw.instance "mux0" @handshake_mux_0(index: %fork3.outs_0: !handshake.channel<i1>, ins_0: %extsi4.outs: !handshake.channel<i8>, ins_1: %cond_br5.trueOut: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8>)
    %buffer0.outs = hw.instance "buffer0" @handshake_buffer_0(ins: %mux0.outs: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8>)
    %fork1.outs_0, %fork1.outs_1 = hw.instance "fork1" @handshake_fork_1(ins: %buffer0.outs: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i8>, outs_1: !handshake.channel<i8>)
    %buffer1.outs = hw.instance "buffer1" @handshake_buffer_1(ins: %fork1.outs_0: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8>)
    %trunci0.outs = hw.instance "trunci0" @handshake_trunci_0(ins: %buffer1.outs: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i7>)
    %buffer6.outs = hw.instance "buffer6" @handshake_buffer_2(ins: %fork3.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %mux1.outs = hw.instance "mux1" @handshake_mux_1(index: %buffer6.outs: !handshake.channel<i1>, ins_0: %x0: !handshake.channel<i32>, ins_1: %cond_br6.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer3.outs = hw.instance "buffer3" @handshake_buffer_3(ins: %mux1.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %fork2.outs_0, %fork2.outs_1, %fork2.outs_2 = hw.instance "fork2" @handshake_fork_2(ins: %buffer3.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>, outs_2: !handshake.channel<i32>)
    %control_merge0.outs, %control_merge0.index = hw.instance "control_merge0" @handshake_control_merge_0(ins_0: %fork0.outs_2: !handshake.control<>, ins_1: %cond_br7.trueOut: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>, index: !handshake.channel<i1>)
    %fork3.outs_0, %fork3.outs_1 = hw.instance "fork3" @handshake_fork_3(ins: %control_merge0.index: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>)
    %source0.outs = hw.instance "source0" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant7.outs = hw.instance "constant7" @handshake_constant_1(ctrl: %source0.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %source1.outs = hw.instance "source1" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant8.outs = hw.instance "constant8" @handshake_constant_2(ctrl: %source1.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %load0.addrOut, %load0.dataOut = hw.instance "load0" @handshake_load_0(addrIn: %trunci0.outs: !handshake.channel<i7>, dataFromMem: %mem_controller3.ldData_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (addrOut: !handshake.channel<i7>, dataOut: !handshake.channel<i32>)
    %mulf0.result = hw.instance "mulf0" @handshake_mulf_0(lhs: %load0.dataOut: !handshake.channel<i32>, rhs: %fork2.outs_2: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %mulf1.result = hw.instance "mulf1" @handshake_mulf_1(lhs: %fork2.outs_1: !handshake.channel<i32>, rhs: %constant7.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %addf0.result = hw.instance "addf0" @handshake_addf_0(lhs: %mulf0.result: !handshake.channel<i32>, rhs: %mulf1.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %cmpf0.result = hw.instance "cmpf0" @handshake_cmpf_0(lhs: %addf0.result: !handshake.channel<i32>, rhs: %constant8.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %fork4.outs_0, %fork4.outs_1, %fork4.outs_2 = hw.instance "fork4" @handshake_fork_4(ins: %cmpf0.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>)
    %buffer2.outs = hw.instance "buffer2" @handshake_buffer_4(ins: %fork1.outs_1: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8>)
    %cond_br2.trueOut, %cond_br2.falseOut = hw.instance "cond_br2" @handshake_cond_br_0(condition: %fork4.outs_0: !handshake.channel<i1>, data: %buffer2.outs: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i8>, falseOut: !handshake.channel<i8>)
    %buffer4.outs = hw.instance "buffer4" @handshake_buffer_5(ins: %fork2.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %cond_br3.trueOut, %cond_br3.falseOut = hw.instance "cond_br3" @handshake_cond_br_1(condition: %fork4.outs_2: !handshake.channel<i1>, data: %buffer4.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    %buffer5.outs = hw.instance "buffer5" @handshake_buffer_6(ins: %control_merge0.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %cond_br4.trueOut, %cond_br4.falseOut = hw.instance "cond_br4" @handshake_cond_br_2(condition: %fork4.outs_1: !handshake.channel<i1>, data: %buffer5.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.control<>, falseOut: !handshake.control<>)
    %source2.outs = hw.instance "source2" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant9.outs = hw.instance "constant9" @handshake_constant_3(ctrl: %source2.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %addf1.result = hw.instance "addf1" @handshake_addf_1(lhs: %cond_br3.falseOut: !handshake.channel<i32>, rhs: %constant9.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %fork5.outs_0, %fork5.outs_1 = hw.instance "fork5" @handshake_fork_1(ins: %cond_br2.trueOut: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i8>, outs_1: !handshake.channel<i8>)
    %trunci1.outs = hw.instance "trunci1" @handshake_trunci_0(ins: %fork5.outs_0: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i7>)
    %fork6.outs_0, %fork6.outs_1 = hw.instance "fork6" @handshake_fork_5(ins: %cond_br3.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>)
    %fork7.outs_0, %fork7.outs_1 = hw.instance "fork7" @handshake_fork_6(ins: %cond_br4.trueOut: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.control<>, outs_1: !handshake.control<>)
    %constant3.outs = hw.instance "constant3" @handshake_constant_4(ctrl: %fork7.outs_0: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i2>)
    %extsi1.outs = hw.instance "extsi1" @handshake_extsi_1(ins: %constant3.outs: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %source3.outs = hw.instance "source3" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant10.outs = hw.instance "constant10" @handshake_constant_5(ctrl: %source3.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %store0.addrOut, %store0.dataToMem = hw.instance "store0" @handshake_store_0(addrIn: %trunci1.outs: !handshake.channel<i7>, dataIn: %fork6.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (addrOut: !handshake.channel<i7>, dataToMem: !handshake.channel<i32>)
    %addf2.result = hw.instance "addf2" @handshake_addf_2(lhs: %fork6.outs_1: !handshake.channel<i32>, rhs: %constant10.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %buffer9.outs = hw.instance "buffer9" @handshake_buffer_2(ins: %fork8.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %mux2.outs = hw.instance "mux2" @handshake_mux_2(index: %buffer9.outs: !handshake.channel<i1>, ins_0: %addf1.result: !handshake.channel<i32>, ins_1: %addf2.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %mux3.outs = hw.instance "mux3" @handshake_mux_0(index: %fork8.outs_0: !handshake.channel<i1>, ins_0: %cond_br2.falseOut: !handshake.channel<i8>, ins_1: %fork5.outs_1: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8>)
    %buffer8.outs = hw.instance "buffer8" @handshake_buffer_0(ins: %mux3.outs: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8>)
    %extsi5.outs = hw.instance "extsi5" @handshake_extsi_2(ins: %buffer8.outs: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i9>)
    %control_merge3.outs, %control_merge3.index = hw.instance "control_merge3" @handshake_control_merge_0(ins_0: %cond_br4.falseOut: !handshake.control<>, ins_1: %fork7.outs_1: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>, index: !handshake.channel<i1>)
    %fork8.outs_0, %fork8.outs_1 = hw.instance "fork8" @handshake_fork_3(ins: %control_merge3.index: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>)
    %source4.outs = hw.instance "source4" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant11.outs = hw.instance "constant11" @handshake_constant_6(ctrl: %source4.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %source5.outs = hw.instance "source5" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant4.outs = hw.instance "constant4" @handshake_constant_4(ctrl: %source5.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i2>)
    %extsi6.outs = hw.instance "extsi6" @handshake_extsi_3(ins: %constant4.outs: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i9>)
    %source6.outs = hw.instance "source6" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant5.outs = hw.instance "constant5" @handshake_constant_7(ctrl: %source6.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8>)
    %extsi7.outs = hw.instance "extsi7" @handshake_extsi_2(ins: %constant5.outs: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i9>)
    %buffer7.outs = hw.instance "buffer7" @handshake_buffer_7(ins: %mux2.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %divf0.result = hw.instance "divf0" @handshake_divf_0(lhs: %constant11.outs: !handshake.channel<i32>, rhs: %buffer7.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %addi0.result = hw.instance "addi0" @handshake_addi_0(lhs: %extsi5.outs: !handshake.channel<i9>, rhs: %extsi6.outs: !handshake.channel<i9>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i9>)
    %fork9.outs_0, %fork9.outs_1 = hw.instance "fork9" @handshake_fork_7(ins: %addi0.result: !handshake.channel<i9>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i9>, outs_1: !handshake.channel<i9>)
    %trunci2.outs = hw.instance "trunci2" @handshake_trunci_1(ins: %fork9.outs_0: !handshake.channel<i9>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8>)
    %cmpi0.result = hw.instance "cmpi0" @handshake_cmpi_0(lhs: %fork9.outs_1: !handshake.channel<i9>, rhs: %extsi7.outs: !handshake.channel<i9>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %fork10.outs_0, %fork10.outs_1, %fork10.outs_2 = hw.instance "fork10" @handshake_fork_4(ins: %cmpi0.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>)
    %cond_br5.trueOut, %cond_br5.falseOut = hw.instance "cond_br5" @handshake_cond_br_0(condition: %fork10.outs_0: !handshake.channel<i1>, data: %trunci2.outs: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i8>, falseOut: !handshake.channel<i8>)
    hw.instance "sink2" @handshake_sink_0(ins: %cond_br5.falseOut: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> ()
    %buffer10.outs = hw.instance "buffer10" @handshake_buffer_2(ins: %fork10.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %cond_br6.trueOut, %cond_br6.falseOut = hw.instance "cond_br6" @handshake_cond_br_3(condition: %buffer10.outs: !handshake.channel<i1>, data: %divf0.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    %cond_br7.trueOut, %cond_br7.falseOut = hw.instance "cond_br7" @handshake_cond_br_2(condition: %fork10.outs_2: !handshake.channel<i1>, data: %control_merge3.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.control<>, falseOut: !handshake.control<>)
    %fork11.outs_0, %fork11.outs_1 = hw.instance "fork11" @handshake_fork_6(ins: %cond_br7.falseOut: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.control<>, outs_1: !handshake.control<>)
    hw.output %cond_br6.falseOut, %mem_controller3.memEnd, %mem_controller2.memEnd, %fork0.outs_1, %mem_controller3.loadEn, %mem_controller3.loadAddr, %mem_controller3.storeEn, %mem_controller3.storeAddr, %mem_controller3.storeData, %mem_controller2.loadEn, %mem_controller2.loadAddr, %mem_controller2.storeEn, %mem_controller2.storeAddr, %mem_controller2.storeData : !handshake.channel<i32>, !handshake.control<>, !handshake.control<>, !handshake.control<>, i1, i7, i1, i7, i32, i1, i7, i1, i7, i32
  }
  hw.module.extern @handshake_fork_0(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.control<>, out outs_1 : !handshake.control<>, out outs_2 : !handshake.control<>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.control<>, SIZE = 3 : ui32}}
  hw.module.extern @handshake_mem_controller_0(in %loadData : i32, in %memStart : !handshake.control<>, in %ctrl_0 : !handshake.channel<i32>, in %stAddr_0 : !handshake.channel<i7>, in %stData_0 : !handshake.channel<i32>, in %ctrlEnd : !handshake.control<>, in %clk : i1, in %rst : i1, out memEnd : !handshake.control<>, out loadEn : i1, out loadAddr : i7, out storeEn : i1, out storeAddr : i7, out storeData : i32) attributes {hw.name = "handshake.mem_controller", hw.parameters = {ADDR_TYPE = !handshake.channel<i7>, DATA_TYPE = !handshake.channel<i32>, NUM_CONTROLS = 1 : ui32, NUM_LOADS = 0 : ui32, NUM_STORES = 1 : ui32}}
  hw.module.extern @handshake_mem_controller_1(in %loadData : i32, in %memStart : !handshake.control<>, in %ldAddr_0 : !handshake.channel<i7>, in %ctrlEnd : !handshake.control<>, in %clk : i1, in %rst : i1, out ldData_0 : !handshake.channel<i32>, out memEnd : !handshake.control<>, out loadEn : i1, out loadAddr : i7, out storeEn : i1, out storeAddr : i7, out storeData : i32) attributes {hw.name = "handshake.mem_controller", hw.parameters = {ADDR_TYPE = !handshake.channel<i7>, DATA_TYPE = !handshake.channel<i32>, NUM_CONTROLS = 0 : ui32, NUM_LOADS = 1 : ui32, NUM_STORES = 0 : ui32}}
  hw.module.extern @handshake_constant_0(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 1 : ui32, VALUE = "0"}}
  hw.module.extern @handshake_extsi_0(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i8>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i1>, OUTPUT_TYPE = !handshake.channel<i8>}}
  hw.module.extern @handshake_mux_0(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.channel<i8>, in %ins_1 : !handshake.channel<i8>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i8>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<i8>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_0(in %ins : !handshake.channel<i8>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i8>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.channel<i8>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_fork_1(in %ins : !handshake.channel<i8>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i8>, out outs_1 : !handshake.channel<i8>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i8>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_1(in %ins : !handshake.channel<i8>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i8>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i8>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_trunci_0(in %ins : !handshake.channel<i8>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i7>) attributes {hw.name = "handshake.trunci", hw.parameters = {INPUT_TYPE = !handshake.channel<i8>, OUTPUT_TYPE = !handshake.channel<i7>}}
  hw.module.extern @handshake_buffer_2(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i1>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_mux_1(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.channel<i32>, in %ins_1 : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_3(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_fork_2(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>, out outs_2 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SIZE = 3 : ui32}}
  hw.module.extern @handshake_control_merge_0(in %ins_0 : !handshake.control<>, in %ins_1 : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.control<>, out index : !handshake.channel<i1>) attributes {hw.name = "handshake.control_merge", hw.parameters = {DATA_TYPE = !handshake.control<>, INDEX_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_fork_3(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_source_0(in %clk : i1, in %rst : i1, out outs : !handshake.control<>) attributes {hw.name = "handshake.source", hw.parameters = {}}
  hw.module.extern @handshake_constant_1(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 32 : ui32, VALUE = "10111111011001100110011001100110"}}
  hw.module.extern @handshake_constant_2(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 32 : ui32, VALUE = "00000000000000000000000000000000"}}
  hw.module.extern @handshake_load_0(in %addrIn : !handshake.channel<i7>, in %dataFromMem : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out addrOut : !handshake.channel<i7>, out dataOut : !handshake.channel<i32>) attributes {hw.name = "handshake.load", hw.parameters = {ADDR_TYPE = !handshake.channel<i7>, DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_mulf_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.mulf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "2_875333"}}
  hw.module.extern @handshake_mulf_1(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.mulf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "2_875333"}}
  hw.module.extern @handshake_addf_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.addf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "2_922000"}}
  hw.module.extern @handshake_cmpf_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.cmpf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "0_000000", PREDICATE = "ugt"}}
  hw.module.extern @handshake_fork_4(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>, out outs_2 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 3 : ui32}}
  hw.module.extern @handshake_buffer_4(in %ins : !handshake.channel<i8>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i8>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<i8>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_cond_br_0(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i8>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i8>, out falseOut : !handshake.channel<i8>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<i8>}}
  hw.module.extern @handshake_buffer_5(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_cond_br_1(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i32>, out falseOut : !handshake.channel<i32>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_buffer_6(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.control<>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.control<>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_cond_br_2(in %condition : !handshake.channel<i1>, in %data : !handshake.control<>, in %clk : i1, in %rst : i1, out trueOut : !handshake.control<>, out falseOut : !handshake.control<>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.control<>}}
  hw.module.extern @handshake_constant_3(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 32 : ui32, VALUE = "01000000010000000000000000000000"}}
  hw.module.extern @handshake_addf_1(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.addf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "2_922000"}}
  hw.module.extern @handshake_fork_5(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_fork_6(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.control<>, out outs_1 : !handshake.control<>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.control<>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_constant_4(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i2>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 2 : ui32, VALUE = "01"}}
  hw.module.extern @handshake_extsi_1(in %ins : !handshake.channel<i2>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i2>, OUTPUT_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_constant_5(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 32 : ui32, VALUE = "00111111100000000000000000000000"}}
  hw.module.extern @handshake_store_0(in %addrIn : !handshake.channel<i7>, in %dataIn : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out addrOut : !handshake.channel<i7>, out dataToMem : !handshake.channel<i32>) attributes {hw.name = "handshake.store", hw.parameters = {ADDR_TYPE = !handshake.channel<i7>, DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_addf_2(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.addf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "2_922000"}}
  hw.module.extern @handshake_mux_2(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.channel<i32>, in %ins_1 : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_extsi_2(in %ins : !handshake.channel<i8>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i9>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i8>, OUTPUT_TYPE = !handshake.channel<i9>}}
  hw.module.extern @handshake_constant_6(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 32 : ui32, VALUE = "00111111100000000000000000000000"}}
  hw.module.extern @handshake_extsi_3(in %ins : !handshake.channel<i2>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i9>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i2>, OUTPUT_TYPE = !handshake.channel<i9>}}
  hw.module.extern @handshake_constant_7(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i8>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 8 : ui32, VALUE = "01100100"}}
  hw.module.extern @handshake_buffer_7(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_divf_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.divf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "3_812000"}}
  hw.module.extern @handshake_addi_0(in %lhs : !handshake.channel<i9>, in %rhs : !handshake.channel<i9>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i9>) attributes {hw.name = "handshake.addi", hw.parameters = {DATA_TYPE = !handshake.channel<i9>}}
  hw.module.extern @handshake_fork_7(in %ins : !handshake.channel<i9>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i9>, out outs_1 : !handshake.channel<i9>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i9>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_trunci_1(in %ins : !handshake.channel<i9>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i8>) attributes {hw.name = "handshake.trunci", hw.parameters = {INPUT_TYPE = !handshake.channel<i9>, OUTPUT_TYPE = !handshake.channel<i8>}}
  hw.module.extern @handshake_cmpi_0(in %lhs : !handshake.channel<i9>, in %rhs : !handshake.channel<i9>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.cmpi", hw.parameters = {DATA_TYPE = !handshake.channel<i9>, PREDICATE = "ult"}}
  hw.module.extern @handshake_sink_0(in %ins : !handshake.channel<i8>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.channel<i8>}}
  hw.module.extern @handshake_cond_br_3(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i32>, out falseOut : !handshake.channel<i32>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @mem_to_bram_32_7(in %loadEn : i1, in %loadAddr : i7, in %storeEn : i1, in %storeAddr : i7, in %storeData : i32, in %din0 : i32, in %din1 : i32, out ce0 : i1, out we0 : i1, out address0 : i7, out dout0 : i32, out ce1 : i1, out we1 : i1, out address1 : i7, out dout1 : i32, out loadData : i32) attributes {hw.name = "mem_to_bram", hw.parameters = {ADDR_WIDTH = 7 : ui32, DATA_WIDTH = 32 : ui32}}
  hw.module @if_float2_wrapper(in %x0 : !handshake.channel<i32>, in %a_din0 : i32, in %a_din1 : i32, in %minus_trace_din0 : i32, in %minus_trace_din1 : i32, in %a_start : !handshake.control<>, in %minus_trace_start : !handshake.control<>, in %start : !handshake.control<>, in %clk : i1, in %rst : i1, out out0 : !handshake.channel<i32>, out a_end : !handshake.control<>, out minus_trace_end : !handshake.control<>, out end : !handshake.control<>, out a_ce0 : i1, out a_we0 : i1, out a_address0 : i7, out a_dout0 : i32, out a_ce1 : i1, out a_we1 : i1, out a_address1 : i7, out a_dout1 : i32, out minus_trace_ce0 : i1, out minus_trace_we0 : i1, out minus_trace_address0 : i7, out minus_trace_dout0 : i32, out minus_trace_ce1 : i1, out minus_trace_we1 : i1, out minus_trace_address1 : i7, out minus_trace_dout1 : i32) {
    %mem_to_bram_converter_a.ce0, %mem_to_bram_converter_a.we0, %mem_to_bram_converter_a.address0, %mem_to_bram_converter_a.dout0, %mem_to_bram_converter_a.ce1, %mem_to_bram_converter_a.we1, %mem_to_bram_converter_a.address1, %mem_to_bram_converter_a.dout1, %mem_to_bram_converter_a.loadData = hw.instance "mem_to_bram_converter_a" @mem_to_bram_32_7(loadEn: %if_float2_wrapped.a_loadEn: i1, loadAddr: %if_float2_wrapped.a_loadAddr: i7, storeEn: %if_float2_wrapped.a_storeEn: i1, storeAddr: %if_float2_wrapped.a_storeAddr: i7, storeData: %if_float2_wrapped.a_storeData: i32, din0: %a_din0: i32, din1: %a_din1: i32) -> (ce0: i1, we0: i1, address0: i7, dout0: i32, ce1: i1, we1: i1, address1: i7, dout1: i32, loadData: i32)
    %mem_to_bram_converter_minus_trace.ce0, %mem_to_bram_converter_minus_trace.we0, %mem_to_bram_converter_minus_trace.address0, %mem_to_bram_converter_minus_trace.dout0, %mem_to_bram_converter_minus_trace.ce1, %mem_to_bram_converter_minus_trace.we1, %mem_to_bram_converter_minus_trace.address1, %mem_to_bram_converter_minus_trace.dout1, %mem_to_bram_converter_minus_trace.loadData = hw.instance "mem_to_bram_converter_minus_trace" @mem_to_bram_32_7(loadEn: %if_float2_wrapped.minus_trace_loadEn: i1, loadAddr: %if_float2_wrapped.minus_trace_loadAddr: i7, storeEn: %if_float2_wrapped.minus_trace_storeEn: i1, storeAddr: %if_float2_wrapped.minus_trace_storeAddr: i7, storeData: %if_float2_wrapped.minus_trace_storeData: i32, din0: %minus_trace_din0: i32, din1: %minus_trace_din1: i32) -> (ce0: i1, we0: i1, address0: i7, dout0: i32, ce1: i1, we1: i1, address1: i7, dout1: i32, loadData: i32)
    %if_float2_wrapped.out0, %if_float2_wrapped.a_end, %if_float2_wrapped.minus_trace_end, %if_float2_wrapped.end, %if_float2_wrapped.a_loadEn, %if_float2_wrapped.a_loadAddr, %if_float2_wrapped.a_storeEn, %if_float2_wrapped.a_storeAddr, %if_float2_wrapped.a_storeData, %if_float2_wrapped.minus_trace_loadEn, %if_float2_wrapped.minus_trace_loadAddr, %if_float2_wrapped.minus_trace_storeEn, %if_float2_wrapped.minus_trace_storeAddr, %if_float2_wrapped.minus_trace_storeData = hw.instance "if_float2_wrapped" @if_float2(x0: %x0: !handshake.channel<i32>, a_loadData: %mem_to_bram_converter_a.loadData: i32, minus_trace_loadData: %mem_to_bram_converter_minus_trace.loadData: i32, a_start: %a_start: !handshake.control<>, minus_trace_start: %minus_trace_start: !handshake.control<>, start: %start: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (out0: !handshake.channel<i32>, a_end: !handshake.control<>, minus_trace_end: !handshake.control<>, end: !handshake.control<>, a_loadEn: i1, a_loadAddr: i7, a_storeEn: i1, a_storeAddr: i7, a_storeData: i32, minus_trace_loadEn: i1, minus_trace_loadAddr: i7, minus_trace_storeEn: i1, minus_trace_storeAddr: i7, minus_trace_storeData: i32)
    hw.output %if_float2_wrapped.out0, %if_float2_wrapped.a_end, %if_float2_wrapped.minus_trace_end, %if_float2_wrapped.end, %mem_to_bram_converter_a.ce0, %mem_to_bram_converter_a.we0, %mem_to_bram_converter_a.address0, %mem_to_bram_converter_a.dout0, %mem_to_bram_converter_a.ce1, %mem_to_bram_converter_a.we1, %mem_to_bram_converter_a.address1, %mem_to_bram_converter_a.dout1, %mem_to_bram_converter_minus_trace.ce0, %mem_to_bram_converter_minus_trace.we0, %mem_to_bram_converter_minus_trace.address0, %mem_to_bram_converter_minus_trace.dout0, %mem_to_bram_converter_minus_trace.ce1, %mem_to_bram_converter_minus_trace.we1, %mem_to_bram_converter_minus_trace.address1, %mem_to_bram_converter_minus_trace.dout1 : !handshake.channel<i32>, !handshake.control<>, !handshake.control<>, !handshake.control<>, i1, i1, i7, i32, i1, i1, i7, i32, i1, i1, i7, i32, i1, i1, i7, i32
  }
}

