// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py
// RUN: dynamatic-opt --test-cdg-analysis %s --split-input-file | FileCheck %s

// func.func @test1(%arg0: i1, %arg1: i32) {
//   cf.cond_br %arg0, ^bb1(%arg1: i32), ^bb2(%arg1: i32)
//   ^bb1(%0: i32):
//     cf.br ^bb4
//   ^bb2(%1: i32):
//     cf.br ^bb3
//   ^bb3():
//     cf.br ^bb4
//   ^bb4:
//     return
// }

// func.func @test2(%c0: i1, %c2: i1, %c3: i1) {
//   cf.cond_br %c0, ^bb1, ^bb2
//   ^bb1:
//     cf.br ^bb6
//   ^bb2:
//     cf.cond_br %c2, ^bb3, ^bb4
//   ^bb3:
//     cf.cond_br %c2, ^bb5, ^bb4
//   ^bb4:
//     cf.br ^bb5
//   ^bb5:
//     cf.br ^bb6
//   ^bb6:
//     return
// }

func.func @test2(%c0: i1, %c2: i1, %c3: i1) {
  cf.cond_br %c0, ^bb1, ^bb2
  ^bb1:
    cf.cond_br %c2, ^bb3, ^bb4
  ^bb2:
    cf.cond_br %c3, ^bb4, ^bb6
  ^bb3:
    cf.br ^bb5
  ^bb4:
    cf.br ^bb5
  ^bb5:
    cf.br ^bb6
  ^bb6:
    return
}
