module {
  hw.module @subdiag_fast(in %d1_loadData : i32, in %d2_loadData : i32, in %e_loadData : i32, in %d1_start : !handshake.control<>, in %d2_start : !handshake.control<>, in %e_start : !handshake.control<>, in %start : !handshake.control<>, in %clk : i1, in %rst : i1, out out0 : !handshake.channel<i32>, out d1_end : !handshake.control<>, out d2_end : !handshake.control<>, out e_end : !handshake.control<>, out end : !handshake.control<>, out d1_loadEn : i1, out d1_loadAddr : i10, out d1_storeEn : i1, out d1_storeAddr : i10, out d1_storeData : i32, out d2_loadEn : i1, out d2_loadAddr : i10, out d2_storeEn : i1, out d2_storeAddr : i10, out d2_storeData : i32, out e_loadEn : i1, out e_loadAddr : i10, out e_storeEn : i1, out e_storeAddr : i10, out e_storeData : i32) {
    %fork0.outs_0, %fork0.outs_1, %fork0.outs_2 = hw.instance "fork0" @handshake_fork_0(ins: %start: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.control<>, outs_1: !handshake.control<>, outs_2: !handshake.control<>)
    %mem_controller3.ldData_0, %mem_controller3.memEnd, %mem_controller3.loadEn, %mem_controller3.loadAddr, %mem_controller3.storeEn, %mem_controller3.storeAddr, %mem_controller3.storeData = hw.instance "mem_controller3" @handshake_mem_controller_0(loadData: %e_loadData: i32, memStart: %e_start: !handshake.control<>, ldAddr_0: %load2.addrOut: !handshake.channel<i10>, ctrlEnd: %fork5.outs_2: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (ldData_0: !handshake.channel<i32>, memEnd: !handshake.control<>, loadEn: i1, loadAddr: i10, storeEn: i1, storeAddr: i10, storeData: i32)
    %mem_controller4.ldData_0, %mem_controller4.memEnd, %mem_controller4.loadEn, %mem_controller4.loadAddr, %mem_controller4.storeEn, %mem_controller4.storeAddr, %mem_controller4.storeData = hw.instance "mem_controller4" @handshake_mem_controller_1(loadData: %d2_loadData: i32, memStart: %d2_start: !handshake.control<>, ldAddr_0: %load1.addrOut: !handshake.channel<i10>, ctrlEnd: %fork5.outs_1: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (ldData_0: !handshake.channel<i32>, memEnd: !handshake.control<>, loadEn: i1, loadAddr: i10, storeEn: i1, storeAddr: i10, storeData: i32)
    %mem_controller5.ldData_0, %mem_controller5.memEnd, %mem_controller5.loadEn, %mem_controller5.loadAddr, %mem_controller5.storeEn, %mem_controller5.storeAddr, %mem_controller5.storeData = hw.instance "mem_controller5" @handshake_mem_controller_2(loadData: %d1_loadData: i32, memStart: %d1_start: !handshake.control<>, ldAddr_0: %load0.addrOut: !handshake.channel<i10>, ctrlEnd: %fork5.outs_0: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (ldData_0: !handshake.channel<i32>, memEnd: !handshake.control<>, loadEn: i1, loadAddr: i10, storeEn: i1, storeAddr: i10, storeData: i32)
    %constant0.outs = hw.instance "constant0" @handshake_constant_0(ctrl: %fork0.outs_0: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %extsi3.outs = hw.instance "extsi3" @handshake_extsi_0(ins: %constant0.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i11>)
    %mux0.outs = hw.instance "mux0" @handshake_mux_0(index: %control_merge0.index: !handshake.channel<i1>, ins_0: %extsi3.outs: !handshake.channel<i11>, ins_1: %trunci3.outs: !handshake.channel<i11>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i11>)
    %buffer0.outs = hw.instance "buffer0" @handshake_buffer_0(ins: %mux0.outs: !handshake.channel<i11>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i11>)
    %fork1.outs_0, %fork1.outs_1, %fork1.outs_2, %fork1.outs_3 = hw.instance "fork1" @handshake_fork_1(ins: %buffer0.outs: !handshake.channel<i11>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i11>, outs_1: !handshake.channel<i11>, outs_2: !handshake.channel<i11>, outs_3: !handshake.channel<i11>)
    %trunci0.outs = hw.instance "trunci0" @handshake_trunci_0(ins: %fork1.outs_0: !handshake.channel<i11>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i10>)
    %trunci1.outs = hw.instance "trunci1" @handshake_trunci_0(ins: %fork1.outs_1: !handshake.channel<i11>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i10>)
    %trunci2.outs = hw.instance "trunci2" @handshake_trunci_0(ins: %fork1.outs_2: !handshake.channel<i11>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i10>)
    %control_merge0.outs, %control_merge0.index = hw.instance "control_merge0" @handshake_control_merge_0(ins_0: %fork0.outs_2: !handshake.control<>, ins_1: %cond_br5.trueOut: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>, index: !handshake.channel<i1>)
    %source0.outs = hw.instance "source0" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant4.outs = hw.instance "constant4" @handshake_constant_1(ctrl: %source0.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %load0.addrOut, %load0.dataOut = hw.instance "load0" @handshake_load_0(addrIn: %trunci2.outs: !handshake.channel<i10>, dataFromMem: %mem_controller5.ldData_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (addrOut: !handshake.channel<i10>, dataOut: !handshake.channel<i32>)
    %load1.addrOut, %load1.dataOut = hw.instance "load1" @handshake_load_1(addrIn: %trunci1.outs: !handshake.channel<i10>, dataFromMem: %mem_controller4.ldData_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (addrOut: !handshake.channel<i10>, dataOut: !handshake.channel<i32>)
    %addf0.result = hw.instance "addf0" @handshake_addf_0(lhs: %load0.dataOut: !handshake.channel<i32>, rhs: %load1.dataOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %load2.addrOut, %load2.dataOut = hw.instance "load2" @handshake_load_2(addrIn: %trunci0.outs: !handshake.channel<i10>, dataFromMem: %mem_controller3.ldData_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (addrOut: !handshake.channel<i10>, dataOut: !handshake.channel<i32>)
    %mulf0.result = hw.instance "mulf0" @handshake_mulf_0(lhs: %addf0.result: !handshake.channel<i32>, rhs: %constant4.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %buffer3.outs = hw.instance "buffer3" @handshake_buffer_1(ins: %load2.dataOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %cmpf0.result = hw.instance "cmpf0" @handshake_cmpf_0(lhs: %buffer3.outs: !handshake.channel<i32>, rhs: %mulf0.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %fork2.outs_0, %fork2.outs_1 = hw.instance "fork2" @handshake_fork_2(ins: %cmpf0.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>)
    %buffer1.outs = hw.instance "buffer1" @handshake_buffer_2(ins: %fork1.outs_3: !handshake.channel<i11>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i11>)
    %cond_br2.trueOut, %cond_br2.falseOut = hw.instance "cond_br2" @handshake_cond_br_0(condition: %fork2.outs_0: !handshake.channel<i1>, data: %buffer1.outs: !handshake.channel<i11>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i11>, falseOut: !handshake.channel<i11>)
    %extsi4.outs = hw.instance "extsi4" @handshake_extsi_1(ins: %cond_br2.falseOut: !handshake.channel<i11>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i12>)
    %buffer2.outs = hw.instance "buffer2" @handshake_buffer_3(ins: %control_merge0.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %cond_br3.trueOut, %cond_br3.falseOut = hw.instance "cond_br3" @handshake_cond_br_1(condition: %fork2.outs_1: !handshake.channel<i1>, data: %buffer2.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.control<>, falseOut: !handshake.control<>)
    %extsi5.outs = hw.instance "extsi5" @handshake_extsi_1(ins: %cond_br2.trueOut: !handshake.channel<i11>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i12>)
    %source1.outs = hw.instance "source1" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant1.outs = hw.instance "constant1" @handshake_constant_2(ctrl: %source1.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i2>)
    %extsi6.outs = hw.instance "extsi6" @handshake_extsi_2(ins: %constant1.outs: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i12>)
    %source2.outs = hw.instance "source2" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant2.outs = hw.instance "constant2" @handshake_constant_3(ctrl: %source2.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i11>)
    %extsi7.outs = hw.instance "extsi7" @handshake_extsi_1(ins: %constant2.outs: !handshake.channel<i11>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i12>)
    %addi0.result = hw.instance "addi0" @handshake_addi_0(lhs: %extsi5.outs: !handshake.channel<i12>, rhs: %extsi6.outs: !handshake.channel<i12>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i12>)
    %fork3.outs_0, %fork3.outs_1 = hw.instance "fork3" @handshake_fork_3(ins: %addi0.result: !handshake.channel<i12>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i12>, outs_1: !handshake.channel<i12>)
    %cmpi0.result = hw.instance "cmpi0" @handshake_cmpi_0(lhs: %fork3.outs_1: !handshake.channel<i12>, rhs: %extsi7.outs: !handshake.channel<i12>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %fork4.outs_0, %fork4.outs_1 = hw.instance "fork4" @handshake_fork_2(ins: %cmpi0.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>)
    %cond_br4.trueOut, %cond_br4.falseOut = hw.instance "cond_br4" @handshake_cond_br_2(condition: %fork4.outs_0: !handshake.channel<i1>, data: %fork3.outs_0: !handshake.channel<i12>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i12>, falseOut: !handshake.channel<i12>)
    %trunci3.outs = hw.instance "trunci3" @handshake_trunci_1(ins: %cond_br4.trueOut: !handshake.channel<i12>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i11>)
    %cond_br5.trueOut, %cond_br5.falseOut = hw.instance "cond_br5" @handshake_cond_br_1(condition: %fork4.outs_1: !handshake.channel<i1>, data: %cond_br3.trueOut: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.control<>, falseOut: !handshake.control<>)
    %mux1.outs = hw.instance "mux1" @handshake_mux_1(index: %control_merge2.index: !handshake.channel<i1>, ins_0: %extsi4.outs: !handshake.channel<i12>, ins_1: %cond_br4.falseOut: !handshake.channel<i12>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i12>)
    %extsi8.outs = hw.instance "extsi8" @handshake_extsi_3(ins: %mux1.outs: !handshake.channel<i12>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %control_merge2.outs, %control_merge2.index = hw.instance "control_merge2" @handshake_control_merge_0(ins_0: %cond_br3.falseOut: !handshake.control<>, ins_1: %cond_br5.falseOut: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>, index: !handshake.channel<i1>)
    %fork5.outs_0, %fork5.outs_1, %fork5.outs_2 = hw.instance "fork5" @handshake_fork_0(ins: %control_merge2.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.control<>, outs_1: !handshake.control<>, outs_2: !handshake.control<>)
    hw.output %extsi8.outs, %mem_controller5.memEnd, %mem_controller4.memEnd, %mem_controller3.memEnd, %fork0.outs_1, %mem_controller5.loadEn, %mem_controller5.loadAddr, %mem_controller5.storeEn, %mem_controller5.storeAddr, %mem_controller5.storeData, %mem_controller4.loadEn, %mem_controller4.loadAddr, %mem_controller4.storeEn, %mem_controller4.storeAddr, %mem_controller4.storeData, %mem_controller3.loadEn, %mem_controller3.loadAddr, %mem_controller3.storeEn, %mem_controller3.storeAddr, %mem_controller3.storeData : !handshake.channel<i32>, !handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>, i1, i10, i1, i10, i32, i1, i10, i1, i10, i32, i1, i10, i1, i10, i32
  }
  hw.module.extern @handshake_fork_0(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.control<>, out outs_1 : !handshake.control<>, out outs_2 : !handshake.control<>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.control<>, SIZE = 3 : ui32}}
  hw.module.extern @handshake_mem_controller_0(in %loadData : i32, in %memStart : !handshake.control<>, in %ldAddr_0 : !handshake.channel<i10>, in %ctrlEnd : !handshake.control<>, in %clk : i1, in %rst : i1, out ldData_0 : !handshake.channel<i32>, out memEnd : !handshake.control<>, out loadEn : i1, out loadAddr : i10, out storeEn : i1, out storeAddr : i10, out storeData : i32) attributes {hw.name = "handshake.mem_controller", hw.parameters = {ADDR_TYPE = !handshake.channel<i10>, DATA_TYPE = !handshake.channel<i32>, NUM_CONTROLS = 0 : ui32, NUM_LOADS = 1 : ui32, NUM_STORES = 0 : ui32}}
  hw.module.extern @handshake_mem_controller_1(in %loadData : i32, in %memStart : !handshake.control<>, in %ldAddr_0 : !handshake.channel<i10>, in %ctrlEnd : !handshake.control<>, in %clk : i1, in %rst : i1, out ldData_0 : !handshake.channel<i32>, out memEnd : !handshake.control<>, out loadEn : i1, out loadAddr : i10, out storeEn : i1, out storeAddr : i10, out storeData : i32) attributes {hw.name = "handshake.mem_controller", hw.parameters = {ADDR_TYPE = !handshake.channel<i10>, DATA_TYPE = !handshake.channel<i32>, NUM_CONTROLS = 0 : ui32, NUM_LOADS = 1 : ui32, NUM_STORES = 0 : ui32}}
  hw.module.extern @handshake_mem_controller_2(in %loadData : i32, in %memStart : !handshake.control<>, in %ldAddr_0 : !handshake.channel<i10>, in %ctrlEnd : !handshake.control<>, in %clk : i1, in %rst : i1, out ldData_0 : !handshake.channel<i32>, out memEnd : !handshake.control<>, out loadEn : i1, out loadAddr : i10, out storeEn : i1, out storeAddr : i10, out storeData : i32) attributes {hw.name = "handshake.mem_controller", hw.parameters = {ADDR_TYPE = !handshake.channel<i10>, DATA_TYPE = !handshake.channel<i32>, NUM_CONTROLS = 0 : ui32, NUM_LOADS = 1 : ui32, NUM_STORES = 0 : ui32}}
  hw.module.extern @handshake_constant_0(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 1 : ui32, VALUE = "0"}}
  hw.module.extern @handshake_extsi_0(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i11>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i1>, OUTPUT_TYPE = !handshake.channel<i11>}}
  hw.module.extern @handshake_mux_0(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.channel<i11>, in %ins_1 : !handshake.channel<i11>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i11>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<i11>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_0(in %ins : !handshake.channel<i11>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i11>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.channel<i11>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_fork_1(in %ins : !handshake.channel<i11>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i11>, out outs_1 : !handshake.channel<i11>, out outs_2 : !handshake.channel<i11>, out outs_3 : !handshake.channel<i11>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i11>, SIZE = 4 : ui32}}
  hw.module.extern @handshake_trunci_0(in %ins : !handshake.channel<i11>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i10>) attributes {hw.name = "handshake.trunci", hw.parameters = {INPUT_TYPE = !handshake.channel<i11>, OUTPUT_TYPE = !handshake.channel<i10>}}
  hw.module.extern @handshake_control_merge_0(in %ins_0 : !handshake.control<>, in %ins_1 : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.control<>, out index : !handshake.channel<i1>) attributes {hw.name = "handshake.control_merge", hw.parameters = {DATA_TYPE = !handshake.control<>, INDEX_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_source_0(in %clk : i1, in %rst : i1, out outs : !handshake.control<>) attributes {hw.name = "handshake.source", hw.parameters = {}}
  hw.module.extern @handshake_constant_1(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 32 : ui32, VALUE = "00111010100000110001001001101111"}}
  hw.module.extern @handshake_load_0(in %addrIn : !handshake.channel<i10>, in %dataFromMem : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out addrOut : !handshake.channel<i10>, out dataOut : !handshake.channel<i32>) attributes {hw.name = "handshake.load", hw.parameters = {ADDR_TYPE = !handshake.channel<i10>, DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_load_1(in %addrIn : !handshake.channel<i10>, in %dataFromMem : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out addrOut : !handshake.channel<i10>, out dataOut : !handshake.channel<i32>) attributes {hw.name = "handshake.load", hw.parameters = {ADDR_TYPE = !handshake.channel<i10>, DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_addf_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.addf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "2_922000"}}
  hw.module.extern @handshake_load_2(in %addrIn : !handshake.channel<i10>, in %dataFromMem : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out addrOut : !handshake.channel<i10>, out dataOut : !handshake.channel<i32>) attributes {hw.name = "handshake.load", hw.parameters = {ADDR_TYPE = !handshake.channel<i10>, DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_mulf_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.mulf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "2_875333"}}
  hw.module.extern @handshake_buffer_1(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<f32>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_cmpf_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.cmpf", hw.parameters = {DATA_TYPE = !handshake.channel<f32>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "0_000000", PREDICATE = "ugt"}}
  hw.module.extern @handshake_fork_2(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_2(in %ins : !handshake.channel<i11>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i11>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<i11>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_cond_br_0(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i11>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i11>, out falseOut : !handshake.channel<i11>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<i11>}}
  hw.module.extern @handshake_extsi_1(in %ins : !handshake.channel<i11>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i12>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i11>, OUTPUT_TYPE = !handshake.channel<i12>}}
  hw.module.extern @handshake_buffer_3(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.control<>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.control<>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_cond_br_1(in %condition : !handshake.channel<i1>, in %data : !handshake.control<>, in %clk : i1, in %rst : i1, out trueOut : !handshake.control<>, out falseOut : !handshake.control<>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.control<>}}
  hw.module.extern @handshake_constant_2(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i2>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 2 : ui32, VALUE = "01"}}
  hw.module.extern @handshake_extsi_2(in %ins : !handshake.channel<i2>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i12>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i2>, OUTPUT_TYPE = !handshake.channel<i12>}}
  hw.module.extern @handshake_constant_3(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i11>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 11 : ui32, VALUE = "01111100111"}}
  hw.module.extern @handshake_addi_0(in %lhs : !handshake.channel<i12>, in %rhs : !handshake.channel<i12>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i12>) attributes {hw.name = "handshake.addi", hw.parameters = {DATA_TYPE = !handshake.channel<i12>}}
  hw.module.extern @handshake_fork_3(in %ins : !handshake.channel<i12>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i12>, out outs_1 : !handshake.channel<i12>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i12>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_cmpi_0(in %lhs : !handshake.channel<i12>, in %rhs : !handshake.channel<i12>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.cmpi", hw.parameters = {DATA_TYPE = !handshake.channel<i12>, PREDICATE = "ult"}}
  hw.module.extern @handshake_cond_br_2(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i12>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i12>, out falseOut : !handshake.channel<i12>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<i12>}}
  hw.module.extern @handshake_trunci_1(in %ins : !handshake.channel<i12>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i11>) attributes {hw.name = "handshake.trunci", hw.parameters = {INPUT_TYPE = !handshake.channel<i12>, OUTPUT_TYPE = !handshake.channel<i11>}}
  hw.module.extern @handshake_mux_1(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.channel<i12>, in %ins_1 : !handshake.channel<i12>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i12>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<i12>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_extsi_3(in %ins : !handshake.channel<i12>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i12>, OUTPUT_TYPE = !handshake.channel<i32>}}
  hw.module.extern @mem_to_bram_32_10(in %loadEn : i1, in %loadAddr : i10, in %storeEn : i1, in %storeAddr : i10, in %storeData : i32, in %din0 : i32, in %din1 : i32, out ce0 : i1, out we0 : i1, out address0 : i10, out dout0 : i32, out ce1 : i1, out we1 : i1, out address1 : i10, out dout1 : i32, out loadData : i32) attributes {hw.name = "mem_to_bram", hw.parameters = {ADDR_WIDTH = 10 : ui32, DATA_WIDTH = 32 : ui32}}
  hw.module @subdiag_fast_wrapper(in %d1_din0 : i32, in %d1_din1 : i32, in %d2_din0 : i32, in %d2_din1 : i32, in %e_din0 : i32, in %e_din1 : i32, in %d1_start : !handshake.control<>, in %d2_start : !handshake.control<>, in %e_start : !handshake.control<>, in %start : !handshake.control<>, in %clk : i1, in %rst : i1, out out0 : !handshake.channel<i32>, out d1_end : !handshake.control<>, out d2_end : !handshake.control<>, out e_end : !handshake.control<>, out end : !handshake.control<>, out d1_ce0 : i1, out d1_we0 : i1, out d1_address0 : i10, out d1_dout0 : i32, out d1_ce1 : i1, out d1_we1 : i1, out d1_address1 : i10, out d1_dout1 : i32, out d2_ce0 : i1, out d2_we0 : i1, out d2_address0 : i10, out d2_dout0 : i32, out d2_ce1 : i1, out d2_we1 : i1, out d2_address1 : i10, out d2_dout1 : i32, out e_ce0 : i1, out e_we0 : i1, out e_address0 : i10, out e_dout0 : i32, out e_ce1 : i1, out e_we1 : i1, out e_address1 : i10, out e_dout1 : i32) {
    %mem_to_bram_converter_d2.ce0, %mem_to_bram_converter_d2.we0, %mem_to_bram_converter_d2.address0, %mem_to_bram_converter_d2.dout0, %mem_to_bram_converter_d2.ce1, %mem_to_bram_converter_d2.we1, %mem_to_bram_converter_d2.address1, %mem_to_bram_converter_d2.dout1, %mem_to_bram_converter_d2.loadData = hw.instance "mem_to_bram_converter_d2" @mem_to_bram_32_10(loadEn: %subdiag_fast_wrapped.d2_loadEn: i1, loadAddr: %subdiag_fast_wrapped.d2_loadAddr: i10, storeEn: %subdiag_fast_wrapped.d2_storeEn: i1, storeAddr: %subdiag_fast_wrapped.d2_storeAddr: i10, storeData: %subdiag_fast_wrapped.d2_storeData: i32, din0: %d2_din0: i32, din1: %d2_din1: i32) -> (ce0: i1, we0: i1, address0: i10, dout0: i32, ce1: i1, we1: i1, address1: i10, dout1: i32, loadData: i32)
    %mem_to_bram_converter_d1.ce0, %mem_to_bram_converter_d1.we0, %mem_to_bram_converter_d1.address0, %mem_to_bram_converter_d1.dout0, %mem_to_bram_converter_d1.ce1, %mem_to_bram_converter_d1.we1, %mem_to_bram_converter_d1.address1, %mem_to_bram_converter_d1.dout1, %mem_to_bram_converter_d1.loadData = hw.instance "mem_to_bram_converter_d1" @mem_to_bram_32_10(loadEn: %subdiag_fast_wrapped.d1_loadEn: i1, loadAddr: %subdiag_fast_wrapped.d1_loadAddr: i10, storeEn: %subdiag_fast_wrapped.d1_storeEn: i1, storeAddr: %subdiag_fast_wrapped.d1_storeAddr: i10, storeData: %subdiag_fast_wrapped.d1_storeData: i32, din0: %d1_din0: i32, din1: %d1_din1: i32) -> (ce0: i1, we0: i1, address0: i10, dout0: i32, ce1: i1, we1: i1, address1: i10, dout1: i32, loadData: i32)
    %mem_to_bram_converter_e.ce0, %mem_to_bram_converter_e.we0, %mem_to_bram_converter_e.address0, %mem_to_bram_converter_e.dout0, %mem_to_bram_converter_e.ce1, %mem_to_bram_converter_e.we1, %mem_to_bram_converter_e.address1, %mem_to_bram_converter_e.dout1, %mem_to_bram_converter_e.loadData = hw.instance "mem_to_bram_converter_e" @mem_to_bram_32_10(loadEn: %subdiag_fast_wrapped.e_loadEn: i1, loadAddr: %subdiag_fast_wrapped.e_loadAddr: i10, storeEn: %subdiag_fast_wrapped.e_storeEn: i1, storeAddr: %subdiag_fast_wrapped.e_storeAddr: i10, storeData: %subdiag_fast_wrapped.e_storeData: i32, din0: %e_din0: i32, din1: %e_din1: i32) -> (ce0: i1, we0: i1, address0: i10, dout0: i32, ce1: i1, we1: i1, address1: i10, dout1: i32, loadData: i32)
    %subdiag_fast_wrapped.out0, %subdiag_fast_wrapped.d1_end, %subdiag_fast_wrapped.d2_end, %subdiag_fast_wrapped.e_end, %subdiag_fast_wrapped.end, %subdiag_fast_wrapped.d1_loadEn, %subdiag_fast_wrapped.d1_loadAddr, %subdiag_fast_wrapped.d1_storeEn, %subdiag_fast_wrapped.d1_storeAddr, %subdiag_fast_wrapped.d1_storeData, %subdiag_fast_wrapped.d2_loadEn, %subdiag_fast_wrapped.d2_loadAddr, %subdiag_fast_wrapped.d2_storeEn, %subdiag_fast_wrapped.d2_storeAddr, %subdiag_fast_wrapped.d2_storeData, %subdiag_fast_wrapped.e_loadEn, %subdiag_fast_wrapped.e_loadAddr, %subdiag_fast_wrapped.e_storeEn, %subdiag_fast_wrapped.e_storeAddr, %subdiag_fast_wrapped.e_storeData = hw.instance "subdiag_fast_wrapped" @subdiag_fast(d1_loadData: %mem_to_bram_converter_d1.loadData: i32, d2_loadData: %mem_to_bram_converter_d2.loadData: i32, e_loadData: %mem_to_bram_converter_e.loadData: i32, d1_start: %d1_start: !handshake.control<>, d2_start: %d2_start: !handshake.control<>, e_start: %e_start: !handshake.control<>, start: %start: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (out0: !handshake.channel<i32>, d1_end: !handshake.control<>, d2_end: !handshake.control<>, e_end: !handshake.control<>, end: !handshake.control<>, d1_loadEn: i1, d1_loadAddr: i10, d1_storeEn: i1, d1_storeAddr: i10, d1_storeData: i32, d2_loadEn: i1, d2_loadAddr: i10, d2_storeEn: i1, d2_storeAddr: i10, d2_storeData: i32, e_loadEn: i1, e_loadAddr: i10, e_storeEn: i1, e_storeAddr: i10, e_storeData: i32)
    hw.output %subdiag_fast_wrapped.out0, %subdiag_fast_wrapped.d1_end, %subdiag_fast_wrapped.d2_end, %subdiag_fast_wrapped.e_end, %subdiag_fast_wrapped.end, %mem_to_bram_converter_d1.ce0, %mem_to_bram_converter_d1.we0, %mem_to_bram_converter_d1.address0, %mem_to_bram_converter_d1.dout0, %mem_to_bram_converter_d1.ce1, %mem_to_bram_converter_d1.we1, %mem_to_bram_converter_d1.address1, %mem_to_bram_converter_d1.dout1, %mem_to_bram_converter_d2.ce0, %mem_to_bram_converter_d2.we0, %mem_to_bram_converter_d2.address0, %mem_to_bram_converter_d2.dout0, %mem_to_bram_converter_d2.ce1, %mem_to_bram_converter_d2.we1, %mem_to_bram_converter_d2.address1, %mem_to_bram_converter_d2.dout1, %mem_to_bram_converter_e.ce0, %mem_to_bram_converter_e.we0, %mem_to_bram_converter_e.address0, %mem_to_bram_converter_e.dout0, %mem_to_bram_converter_e.ce1, %mem_to_bram_converter_e.we1, %mem_to_bram_converter_e.address1, %mem_to_bram_converter_e.dout1 : !handshake.channel<i32>, !handshake.control<>, !handshake.control<>, !handshake.control<>, !handshake.control<>, i1, i1, i10, i32, i1, i1, i10, i32, i1, i1, i10, i32, i1, i1, i10, i32, i1, i1, i10, i32, i1, i1, i10, i32
  }
}

