module {
  hw.module @if_float(in %x0 : !handshake.channel<i32>, in %a_loadData : i32, in %minus_trace_loadData : i32, in %a_start : !handshake.control<>, in %minus_trace_start : !handshake.control<>, in %start : !handshake.control<>, in %clk : i1, in %rst : i1, out out0 : !handshake.channel<i32>, out a_end : !handshake.control<>, out minus_trace_end : !handshake.control<>, out end : !handshake.control<>, out a_loadEn : i1, out a_loadAddr : i7, out a_storeEn : i1, out a_storeAddr : i7, out a_storeData : i32, out minus_trace_loadEn : i1, out minus_trace_loadAddr : i7, out minus_trace_storeEn : i1, out minus_trace_storeAddr : i7, out minus_trace_storeData : i32) {
    %non_spec0.dataOut = hw.instance "non_spec0" @handshake_non_spec_0(dataIn: %x0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (dataOut: !handshake.channel<i32, [spec: i1]>)
    %fork0.outs_0, %fork0.outs_1, %fork0.outs_2 = hw.instance "fork0" @handshake_fork_0(ins: %start: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.control<>, outs_1: !handshake.control<>, outs_2: !handshake.control<>)
    %non_spec1.dataOut = hw.instance "non_spec1" @handshake_non_spec_1(dataIn: %fork0.outs_2: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (dataOut: !handshake.control<[spec: i1]>)
    %buffer18.outs = hw.instance "buffer18" @handshake_buffer_0(ins: %fork15.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer19.outs = hw.instance "buffer19" @handshake_buffer_1(ins: %fork12.outs_1: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<[spec: i1]>)
    %spec_commit0.outs = hw.instance "spec_commit0" @handshake_spec_commit_0(ins: %buffer19.outs: !handshake.control<[spec: i1]>, ctrl: %buffer18.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %buffer20.outs = hw.instance "buffer20" @handshake_buffer_0(ins: %fork16.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer21.outs = hw.instance "buffer21" @handshake_buffer_2(ins: %extsi1.outs: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %spec_commit1.outs = hw.instance "spec_commit1" @handshake_spec_commit_1(ins: %buffer21.outs: !handshake.channel<i32, [spec: i1]>, ctrl: %buffer20.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %mem_controller2.memEnd, %mem_controller2.loadEn, %mem_controller2.loadAddr, %mem_controller2.storeEn, %mem_controller2.storeAddr, %mem_controller2.storeData = hw.instance "mem_controller2" @handshake_mem_controller_0(loadData: %minus_trace_loadData: i32, memStart: %minus_trace_start: !handshake.control<>, ctrl_0: %spec_commit1.outs: !handshake.channel<i32>, stAddr_0: %store0.addrOut: !handshake.channel<i7>, stData_0: %store0.dataToMem: !handshake.channel<i32>, ctrlEnd: %spec_commit0.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (memEnd: !handshake.control<>, loadEn: i1, loadAddr: i7, storeEn: i1, storeAddr: i7, storeData: i32)
    %buffer22.outs = hw.instance "buffer22" @handshake_buffer_0(ins: %fork15.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer23.outs = hw.instance "buffer23" @handshake_buffer_1(ins: %fork12.outs_0: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<[spec: i1]>)
    %spec_commit2.outs = hw.instance "spec_commit2" @handshake_spec_commit_0(ins: %buffer23.outs: !handshake.control<[spec: i1]>, ctrl: %buffer22.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %mem_controller3.ldData_0, %mem_controller3.memEnd, %mem_controller3.loadEn, %mem_controller3.loadAddr, %mem_controller3.storeEn, %mem_controller3.storeAddr, %mem_controller3.storeData = hw.instance "mem_controller3" @handshake_mem_controller_1(loadData: %a_loadData: i32, memStart: %a_start: !handshake.control<>, ldAddr_0: %load0.addrOut: !handshake.channel<i7>, ctrlEnd: %spec_commit2.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (ldData_0: !handshake.channel<i32>, memEnd: !handshake.control<>, loadEn: i1, loadAddr: i7, storeEn: i1, storeAddr: i7, storeData: i32)
    %constant2.outs = hw.instance "constant2" @handshake_constant_0(ctrl: %fork0.outs_0: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %extsi4.outs = hw.instance "extsi4" @handshake_extsi_0(ins: %constant2.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8>)
    %non_spec2.dataOut = hw.instance "non_spec2" @handshake_non_spec_2(dataIn: %extsi4.outs: !handshake.channel<i8>, clk: %clk: i1, rst: %rst: i1) -> (dataOut: !handshake.channel<i8, [spec: i1]>)
    %mux0.outs = hw.instance "mux0" @handshake_mux_0(index: %fork3.outs_0: !handshake.channel<i1, [spec: i1]>, ins_0: %non_spec2.dataOut: !handshake.channel<i8, [spec: i1]>, ins_1: %cond_br5.trueOut: !handshake.channel<i8, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8, [spec: i1]>)
    %buffer0.outs = hw.instance "buffer0" @handshake_buffer_3(ins: %mux0.outs: !handshake.channel<i8, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8, [spec: i1]>)
    %fork1.outs_0, %fork1.outs_1 = hw.instance "fork1" @handshake_fork_1(ins: %buffer0.outs: !handshake.channel<i8, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i8, [spec: i1]>, outs_1: !handshake.channel<i8, [spec: i1]>)
    %trunci0.outs = hw.instance "trunci0" @handshake_trunci_0(ins: %fork1.outs_0: !handshake.channel<i8, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i7, [spec: i1]>)
    %mux1.outs = hw.instance "mux1" @handshake_mux_1(index: %fork3.outs_1: !handshake.channel<i1, [spec: i1]>, ins_0: %non_spec0.dataOut: !handshake.channel<i32, [spec: i1]>, ins_1: %cond_br6.trueOut: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %buffer1.outs = hw.instance "buffer1" @handshake_buffer_4(ins: %mux1.outs: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %fork2.outs_0, %fork2.outs_1, %fork2.outs_2 = hw.instance "fork2" @handshake_fork_2(ins: %buffer1.outs: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32, [spec: i1]>, outs_1: !handshake.channel<i32, [spec: i1]>, outs_2: !handshake.channel<i32, [spec: i1]>)
    %control_merge0.outs, %control_merge0.index = hw.instance "control_merge0" @handshake_control_merge_0(ins_0: %non_spec1.dataOut: !handshake.control<[spec: i1]>, ins_1: %cond_br7.trueOut: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<[spec: i1]>, index: !handshake.channel<i1, [spec: i1]>)
    %fork4.outs_0, %fork4.outs_1 = hw.instance "fork4" @handshake_fork_3(ins: %control_merge0.outs: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.control<[spec: i1]>, outs_1: !handshake.control<[spec: i1]>)
    %fork3.outs_0, %fork3.outs_1 = hw.instance "fork3" @handshake_fork_4(ins: %control_merge0.index: !handshake.channel<i1, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1, [spec: i1]>, outs_1: !handshake.channel<i1, [spec: i1]>)
    %source0.outs = hw.instance "source0" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<[spec: i1]>)
    %constant6.outs = hw.instance "constant6" @handshake_constant_1(ctrl: %source0.outs: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %source1.outs = hw.instance "source1" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<[spec: i1]>)
    %constant7.outs = hw.instance "constant7" @handshake_constant_2(ctrl: %source1.outs: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %load0.addrOut, %load0.dataOut = hw.instance "load0" @handshake_load_0(addrIn: %trunci0.outs: !handshake.channel<i7, [spec: i1]>, dataFromMem: %mem_controller3.ldData_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (addrOut: !handshake.channel<i7>, dataOut: !handshake.channel<i32, [spec: i1]>)
    %buffer2.outs = hw.instance "buffer2" @handshake_buffer_5(ins: %fork2.outs_2: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %buffer3.outs = hw.instance "buffer3" @handshake_buffer_6(ins: %load0.dataOut: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %mulf0.result = hw.instance "mulf0" @handshake_mulf_0(lhs: %buffer3.outs: !handshake.channel<i32, [spec: i1]>, rhs: %buffer2.outs: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32, [spec: i1]>)
    %mulf1.result = hw.instance "mulf1" @handshake_mulf_1(lhs: %fork2.outs_1: !handshake.channel<i32, [spec: i1]>, rhs: %constant6.outs: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32, [spec: i1]>)
    %buffer4.outs = hw.instance "buffer4" @handshake_buffer_7(ins: %mulf1.result: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %addf0.result = hw.instance "addf0" @handshake_addf_0(lhs: %mulf0.result: !handshake.channel<i32, [spec: i1]>, rhs: %buffer4.outs: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32, [spec: i1]>)
    %cmpf0.result = hw.instance "cmpf0" @handshake_cmpf_0(lhs: %addf0.result: !handshake.channel<i32, [spec: i1]>, rhs: %constant7.outs: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1, [spec: i1]>)
    %speculator0.outs, %speculator0.ctrl_save, %speculator0.ctrl_commit, %speculator0.ctrl_sc_save, %speculator0.ctrl_sc_commit, %speculator0.ctrl_sc_branch = hw.instance "speculator0" @handshake_speculator_0(ins: %cmpf0.result: !handshake.channel<i1, [spec: i1]>, trigger: %fork4.outs_1: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1, [spec: i1]>, ctrl_save: !handshake.channel<i1>, ctrl_commit: !handshake.channel<i1>, ctrl_sc_save: !handshake.channel<i3>, ctrl_sc_commit: !handshake.channel<i3>, ctrl_sc_branch: !handshake.channel<i1>)
    %cond_br9.trueOut, %cond_br9.falseOut = hw.instance "cond_br9" @handshake_cond_br_0(condition: %cond_br8.trueOut: !handshake.channel<i1>, data: %speculator0.ctrl_sc_commit: !handshake.channel<i3>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i3>, falseOut: !handshake.channel<i3>)
    hw.instance "sink8" @handshake_sink_0(ins: %cond_br9.falseOut: !handshake.channel<i3>, clk: %clk: i1, rst: %rst: i1) -> ()
    %merge0.outs = hw.instance "merge0" @handshake_merge_0(ins_0: %speculator0.ctrl_sc_save: !handshake.channel<i3>, ins_1: %cond_br9.trueOut: !handshake.channel<i3>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i3>)
    %fork9.outs_0, %fork9.outs_1, %fork9.outs_2 = hw.instance "fork9" @handshake_fork_5(ins: %merge0.outs: !handshake.channel<i3>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i3>, outs_1: !handshake.channel<i3>, outs_2: !handshake.channel<i3>)
    %fork13.outs_0, %fork13.outs_1 = hw.instance "fork13" @handshake_fork_6(ins: %speculator0.ctrl_commit: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>)
    hw.instance "sink0" @handshake_sink_1(ins: %speculator0.ctrl_save: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> ()
    %buffer24.outs = hw.instance "buffer24" @handshake_buffer_0(ins: %fork17.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %cond_br0.trueOut, %cond_br0.falseOut = hw.instance "cond_br0" @handshake_cond_br_1(condition: %buffer24.outs: !handshake.channel<i1>, data: %fork13.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i1>, falseOut: !handshake.channel<i1>)
    %fork15.outs_0, %fork15.outs_1, %fork15.outs_2 = hw.instance "fork15" @handshake_fork_7(ins: %cond_br0.falseOut: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>)
    hw.instance "sink1" @handshake_sink_1(ins: %cond_br0.trueOut: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> ()
    %speculating_branch0.trueOut, %speculating_branch0.falseOut = hw.instance "speculating_branch0" @handshake_speculating_branch_0(spec_tag_data: %fork18.outs_5: !handshake.channel<i1, [spec: i1]>, data: %fork18.outs_6: !handshake.channel<i1, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i1>, falseOut: !handshake.channel<i1>)
    hw.instance "sink3" @handshake_sink_1(ins: %speculating_branch0.falseOut: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> ()
    %buffer5.outs = hw.instance "buffer5" @handshake_buffer_0(ins: %speculating_branch0.trueOut: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer25.outs = hw.instance "buffer25" @handshake_buffer_0(ins: %buffer5.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %cond_br1.trueOut, %cond_br1.falseOut = hw.instance "cond_br1" @handshake_cond_br_1(condition: %buffer25.outs: !handshake.channel<i1>, data: %fork13.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i1>, falseOut: !handshake.channel<i1>)
    hw.instance "sink4" @handshake_sink_1(ins: %cond_br1.falseOut: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> ()
    %fork16.outs_0, %fork16.outs_1, %fork16.outs_2 = hw.instance "fork16" @handshake_fork_7(ins: %cond_br1.trueOut: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>)
    %speculating_branch1.trueOut, %speculating_branch1.falseOut = hw.instance "speculating_branch1" @handshake_speculating_branch_0(spec_tag_data: %fork19.outs_2: !handshake.channel<i1, [spec: i1]>, data: %fork19.outs_3: !handshake.channel<i1, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i1>, falseOut: !handshake.channel<i1>)
    hw.instance "sink5" @handshake_sink_1(ins: %speculating_branch1.falseOut: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> ()
    %fork17.outs_0, %fork17.outs_1 = hw.instance "fork17" @handshake_fork_6(ins: %speculating_branch1.trueOut: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>)
    %buffer26.outs = hw.instance "buffer26" @handshake_buffer_0(ins: %fork17.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %cond_br8.trueOut, %cond_br8.falseOut = hw.instance "cond_br8" @handshake_cond_br_1(condition: %speculator0.ctrl_sc_branch: !handshake.channel<i1>, data: %buffer26.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i1>, falseOut: !handshake.channel<i1>)
    hw.instance "sink6" @handshake_sink_1(ins: %cond_br8.falseOut: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> ()
    %fork18.outs_0, %fork18.outs_1, %fork18.outs_2, %fork18.outs_3, %fork18.outs_4, %fork18.outs_5, %fork18.outs_6, %fork18.outs_7 = hw.instance "fork18" @handshake_fork_8(ins: %speculator0.outs: !handshake.channel<i1, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1, [spec: i1]>, outs_1: !handshake.channel<i1, [spec: i1]>, outs_2: !handshake.channel<i1, [spec: i1]>, outs_3: !handshake.channel<i1, [spec: i1]>, outs_4: !handshake.channel<i1, [spec: i1]>, outs_5: !handshake.channel<i1, [spec: i1]>, outs_6: !handshake.channel<i1, [spec: i1]>, outs_7: !handshake.channel<i1, [spec: i1]>)
    %spec_save_commit0.outs = hw.instance "spec_save_commit0" @handshake_spec_save_commit_0(ins: %fork1.outs_1: !handshake.channel<i8, [spec: i1]>, ctrl: %fork9.outs_0: !handshake.channel<i3>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8, [spec: i1]>)
    %cond_br2.trueOut, %cond_br2.falseOut = hw.instance "cond_br2" @handshake_cond_br_2(condition: %fork18.outs_7: !handshake.channel<i1, [spec: i1]>, data: %spec_save_commit0.outs: !handshake.channel<i8, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i8, [spec: i1]>, falseOut: !handshake.channel<i8, [spec: i1]>)
    %spec_save_commit1.outs = hw.instance "spec_save_commit1" @handshake_spec_save_commit_1(ins: %fork2.outs_0: !handshake.channel<i32, [spec: i1]>, ctrl: %fork9.outs_1: !handshake.channel<i3>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %cond_br3.trueOut, %cond_br3.falseOut = hw.instance "cond_br3" @handshake_cond_br_3(condition: %fork18.outs_4: !handshake.channel<i1, [spec: i1]>, data: %spec_save_commit1.outs: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32, [spec: i1]>, falseOut: !handshake.channel<i32, [spec: i1]>)
    %spec_save_commit2.outs = hw.instance "spec_save_commit2" @handshake_spec_save_commit_2(ins: %fork4.outs_0: !handshake.control<[spec: i1]>, ctrl: %fork9.outs_2: !handshake.channel<i3>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<[spec: i1]>)
    %cond_br4.trueOut, %cond_br4.falseOut = hw.instance "cond_br4" @handshake_cond_br_4(condition: %fork18.outs_3: !handshake.channel<i1, [spec: i1]>, data: %spec_save_commit2.outs: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.control<[spec: i1]>, falseOut: !handshake.control<[spec: i1]>)
    %source2.outs = hw.instance "source2" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<[spec: i1]>)
    %constant8.outs = hw.instance "constant8" @handshake_constant_3(ctrl: %source2.outs: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %buffer8.outs = hw.instance "buffer8" @handshake_buffer_8(ins: %cond_br3.falseOut: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %mulf2.result = hw.instance "mulf2" @handshake_mulf_2(lhs: %buffer8.outs: !handshake.channel<i32, [spec: i1]>, rhs: %constant8.outs: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32, [spec: i1]>)
    %fork5.outs_0, %fork5.outs_1 = hw.instance "fork5" @handshake_fork_1(ins: %cond_br2.trueOut: !handshake.channel<i8, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i8, [spec: i1]>, outs_1: !handshake.channel<i8, [spec: i1]>)
    %buffer10.outs = hw.instance "buffer10" @handshake_buffer_9(ins: %fork5.outs_0: !handshake.channel<i8, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8, [spec: i1]>)
    %trunci1.outs = hw.instance "trunci1" @handshake_trunci_0(ins: %buffer10.outs: !handshake.channel<i8, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i7, [spec: i1]>)
    %fork6.outs_0, %fork6.outs_1 = hw.instance "fork6" @handshake_fork_9(ins: %cond_br3.trueOut: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32, [spec: i1]>, outs_1: !handshake.channel<i32, [spec: i1]>)
    %fork7.outs_0, %fork7.outs_1 = hw.instance "fork7" @handshake_fork_3(ins: %cond_br4.trueOut: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.control<[spec: i1]>, outs_1: !handshake.control<[spec: i1]>)
    %buffer12.outs = hw.instance "buffer12" @handshake_buffer_1(ins: %fork7.outs_0: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<[spec: i1]>)
    %constant3.outs = hw.instance "constant3" @handshake_constant_4(ctrl: %buffer12.outs: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i2, [spec: i1]>)
    %extsi1.outs = hw.instance "extsi1" @handshake_extsi_1(ins: %constant3.outs: !handshake.channel<i2, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %source3.outs = hw.instance "source3" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<[spec: i1]>)
    %constant9.outs = hw.instance "constant9" @handshake_constant_5(ctrl: %source3.outs: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %buffer27.outs = hw.instance "buffer27" @handshake_buffer_0(ins: %fork16.outs_2: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer28.outs = hw.instance "buffer28" @handshake_buffer_10(ins: %trunci1.outs: !handshake.channel<i7, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i7, [spec: i1]>)
    %spec_commit3.outs = hw.instance "spec_commit3" @handshake_spec_commit_2(ins: %buffer28.outs: !handshake.channel<i7, [spec: i1]>, ctrl: %buffer27.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i7>)
    %buffer11.outs = hw.instance "buffer11" @handshake_buffer_11(ins: %fork6.outs_0: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %buffer29.outs = hw.instance "buffer29" @handshake_buffer_0(ins: %fork16.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer30.outs = hw.instance "buffer30" @handshake_buffer_12(ins: %buffer11.outs: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %spec_commit4.outs = hw.instance "spec_commit4" @handshake_spec_commit_3(ins: %buffer30.outs: !handshake.channel<i32, [spec: i1]>, ctrl: %buffer29.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %store0.addrOut, %store0.dataToMem = hw.instance "store0" @handshake_store_0(addrIn: %spec_commit3.outs: !handshake.channel<i7>, dataIn: %spec_commit4.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (addrOut: !handshake.channel<i7>, dataToMem: !handshake.channel<i32>)
    %divf0.result = hw.instance "divf0" @handshake_divf_0(lhs: %fork6.outs_1: !handshake.channel<i32, [spec: i1]>, rhs: %constant9.outs: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32, [spec: i1]>)
    %buffer6.outs = hw.instance "buffer6" @handshake_buffer_13(ins: %fork18.outs_1: !handshake.channel<i1, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1, [spec: i1]>)
    %mux2.outs = hw.instance "mux2" @handshake_mux_2(index: %buffer6.outs: !handshake.channel<i1, [spec: i1]>, ins_0: %mulf2.result: !handshake.channel<i32, [spec: i1]>, ins_1: %divf0.result: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %buffer13.outs = hw.instance "buffer13" @handshake_buffer_14(ins: %mux2.outs: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %fork8.outs_0, %fork8.outs_1 = hw.instance "fork8" @handshake_fork_10(ins: %buffer13.outs: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32, [spec: i1]>, outs_1: !handshake.channel<i32, [spec: i1]>)
    %buffer7.outs = hw.instance "buffer7" @handshake_buffer_15(ins: %cond_br2.falseOut: !handshake.channel<i8, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8, [spec: i1]>)
    %mux3.outs = hw.instance "mux3" @handshake_mux_0(index: %fork18.outs_0: !handshake.channel<i1, [spec: i1]>, ins_0: %buffer7.outs: !handshake.channel<i8, [spec: i1]>, ins_1: %fork5.outs_1: !handshake.channel<i8, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8, [spec: i1]>)
    %buffer14.outs = hw.instance "buffer14" @handshake_buffer_3(ins: %mux3.outs: !handshake.channel<i8, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8, [spec: i1]>)
    %extsi5.outs = hw.instance "extsi5" @handshake_extsi_2(ins: %buffer14.outs: !handshake.channel<i8, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i9, [spec: i1]>)
    %buffer9.outs = hw.instance "buffer9" @handshake_buffer_16(ins: %cond_br4.falseOut: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<[spec: i1]>)
    %mux4.outs = hw.instance "mux4" @handshake_mux_3(index: %fork18.outs_2: !handshake.channel<i1, [spec: i1]>, ins_0: %buffer9.outs: !handshake.control<[spec: i1]>, ins_1: %fork7.outs_1: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<[spec: i1]>)
    %source4.outs = hw.instance "source4" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<[spec: i1]>)
    %constant4.outs = hw.instance "constant4" @handshake_constant_4(ctrl: %source4.outs: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i2, [spec: i1]>)
    %extsi6.outs = hw.instance "extsi6" @handshake_extsi_3(ins: %constant4.outs: !handshake.channel<i2, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i9, [spec: i1]>)
    %source5.outs = hw.instance "source5" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<[spec: i1]>)
    %constant12.outs = hw.instance "constant12" @handshake_constant_6(ctrl: %source5.outs: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8, [spec: i1]>)
    %extsi7.outs = hw.instance "extsi7" @handshake_extsi_2(ins: %constant12.outs: !handshake.channel<i8, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i9, [spec: i1]>)
    %addf1.result = hw.instance "addf1" @handshake_addf_1(lhs: %fork8.outs_0: !handshake.channel<i32, [spec: i1]>, rhs: %fork8.outs_1: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32, [spec: i1]>)
    %buffer15.outs = hw.instance "buffer15" @handshake_buffer_17(ins: %extsi5.outs: !handshake.channel<i9, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i9, [spec: i1]>)
    %addi0.result = hw.instance "addi0" @handshake_addi_0(lhs: %buffer15.outs: !handshake.channel<i9, [spec: i1]>, rhs: %extsi6.outs: !handshake.channel<i9, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i9, [spec: i1]>)
    %fork10.outs_0, %fork10.outs_1 = hw.instance "fork10" @handshake_fork_11(ins: %addi0.result: !handshake.channel<i9, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i9, [spec: i1]>, outs_1: !handshake.channel<i9, [spec: i1]>)
    %trunci2.outs = hw.instance "trunci2" @handshake_trunci_1(ins: %fork10.outs_0: !handshake.channel<i9, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8, [spec: i1]>)
    %cmpi0.result = hw.instance "cmpi0" @handshake_cmpi_0(lhs: %fork10.outs_1: !handshake.channel<i9, [spec: i1]>, rhs: %extsi7.outs: !handshake.channel<i9, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1, [spec: i1]>)
    %fork19.outs_0, %fork19.outs_1, %fork19.outs_2, %fork19.outs_3, %fork19.outs_4 = hw.instance "fork19" @handshake_fork_12(ins: %cmpi0.result: !handshake.channel<i1, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1, [spec: i1]>, outs_1: !handshake.channel<i1, [spec: i1]>, outs_2: !handshake.channel<i1, [spec: i1]>, outs_3: !handshake.channel<i1, [spec: i1]>, outs_4: !handshake.channel<i1, [spec: i1]>)
    %cond_br5.trueOut, %cond_br5.falseOut = hw.instance "cond_br5" @handshake_cond_br_2(condition: %fork19.outs_4: !handshake.channel<i1, [spec: i1]>, data: %trunci2.outs: !handshake.channel<i8, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i8, [spec: i1]>, falseOut: !handshake.channel<i8, [spec: i1]>)
    hw.instance "sink2" @handshake_sink_2(ins: %cond_br5.falseOut: !handshake.channel<i8, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> ()
    %cond_br6.trueOut, %cond_br6.falseOut = hw.instance "cond_br6" @handshake_cond_br_5(condition: %fork19.outs_0: !handshake.channel<i1, [spec: i1]>, data: %addf1.result: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32, [spec: i1]>, falseOut: !handshake.channel<i32, [spec: i1]>)
    %buffer16.outs = hw.instance "buffer16" @handshake_buffer_16(ins: %mux4.outs: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<[spec: i1]>)
    %buffer17.outs = hw.instance "buffer17" @handshake_buffer_18(ins: %buffer16.outs: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<[spec: i1]>)
    %cond_br7.trueOut, %cond_br7.falseOut = hw.instance "cond_br7" @handshake_cond_br_4(condition: %fork19.outs_1: !handshake.channel<i1, [spec: i1]>, data: %buffer17.outs: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.control<[spec: i1]>, falseOut: !handshake.control<[spec: i1]>)
    %fork12.outs_0, %fork12.outs_1 = hw.instance "fork12" @handshake_fork_3(ins: %cond_br7.falseOut: !handshake.control<[spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.control<[spec: i1]>, outs_1: !handshake.control<[spec: i1]>)
    %buffer31.outs = hw.instance "buffer31" @handshake_buffer_0(ins: %fork15.outs_2: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer32.outs = hw.instance "buffer32" @handshake_buffer_19(ins: %cond_br6.falseOut: !handshake.channel<i32, [spec: i1]>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32, [spec: i1]>)
    %spec_commit5.outs = hw.instance "spec_commit5" @handshake_spec_commit_4(ins: %buffer32.outs: !handshake.channel<i32, [spec: i1]>, ctrl: %buffer31.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    hw.output %spec_commit5.outs, %mem_controller3.memEnd, %mem_controller2.memEnd, %fork0.outs_1, %mem_controller3.loadEn, %mem_controller3.loadAddr, %mem_controller3.storeEn, %mem_controller3.storeAddr, %mem_controller3.storeData, %mem_controller2.loadEn, %mem_controller2.loadAddr, %mem_controller2.storeEn, %mem_controller2.storeAddr, %mem_controller2.storeData : !handshake.channel<i32>, !handshake.control<>, !handshake.control<>, !handshake.control<>, i1, i7, i1, i7, i32, i1, i7, i1, i7, i32
  }
  hw.module.extern @handshake_non_spec_0(in %dataIn : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out dataOut : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.non_spec", hw.parameters = {}}
  hw.module.extern @handshake_fork_0(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.control<>, out outs_1 : !handshake.control<>, out outs_2 : !handshake.control<>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.control<>, SIZE = 3 : ui32}}
  hw.module.extern @handshake_non_spec_1(in %dataIn : !handshake.control<>, in %clk : i1, in %rst : i1, out dataOut : !handshake.control<[spec: i1]>) attributes {hw.name = "handshake.non_spec", hw.parameters = {}}
  hw.module.extern @handshake_buffer_0(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i1>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_buffer_1(in %ins : !handshake.control<[spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.control<[spec: i1]>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.control<[spec: i1]>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_spec_commit_0(in %ins : !handshake.control<[spec: i1]>, in %ctrl : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.control<>) attributes {hw.name = "handshake.spec_commit", hw.parameters = {}}
  hw.module.extern @handshake_buffer_2(in %ins : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i32, [spec: i1]>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_spec_commit_1(in %ins : !handshake.channel<i32, [spec: i1]>, in %ctrl : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.spec_commit", hw.parameters = {}}
  hw.module.extern @handshake_mem_controller_0(in %loadData : i32, in %memStart : !handshake.control<>, in %ctrl_0 : !handshake.channel<i32>, in %stAddr_0 : !handshake.channel<i7>, in %stData_0 : !handshake.channel<i32>, in %ctrlEnd : !handshake.control<>, in %clk : i1, in %rst : i1, out memEnd : !handshake.control<>, out loadEn : i1, out loadAddr : i7, out storeEn : i1, out storeAddr : i7, out storeData : i32) attributes {hw.name = "handshake.mem_controller", hw.parameters = {ADDR_TYPE = !handshake.channel<i7>, DATA_TYPE = !handshake.channel<i32>, NUM_CONTROLS = 1 : ui32, NUM_LOADS = 0 : ui32, NUM_STORES = 1 : ui32}}
  hw.module.extern @handshake_mem_controller_1(in %loadData : i32, in %memStart : !handshake.control<>, in %ldAddr_0 : !handshake.channel<i7>, in %ctrlEnd : !handshake.control<>, in %clk : i1, in %rst : i1, out ldData_0 : !handshake.channel<i32>, out memEnd : !handshake.control<>, out loadEn : i1, out loadAddr : i7, out storeEn : i1, out storeAddr : i7, out storeData : i32) attributes {hw.name = "handshake.mem_controller", hw.parameters = {ADDR_TYPE = !handshake.channel<i7>, DATA_TYPE = !handshake.channel<i32>, NUM_CONTROLS = 0 : ui32, NUM_LOADS = 1 : ui32, NUM_STORES = 0 : ui32}}
  hw.module.extern @handshake_constant_0(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 1 : ui32, VALUE = "0"}}
  hw.module.extern @handshake_extsi_0(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i8>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i1>, OUTPUT_TYPE = !handshake.channel<i8>}}
  hw.module.extern @handshake_non_spec_2(in %dataIn : !handshake.channel<i8>, in %clk : i1, in %rst : i1, out dataOut : !handshake.channel<i8, [spec: i1]>) attributes {hw.name = "handshake.non_spec", hw.parameters = {}}
  hw.module.extern @handshake_mux_0(in %index : !handshake.channel<i1, [spec: i1]>, in %ins_0 : !handshake.channel<i8, [spec: i1]>, in %ins_1 : !handshake.channel<i8, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i8, [spec: i1]>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<i8, [spec: i1]>, SELECT_TYPE = !handshake.channel<i1, [spec: i1]>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_3(in %ins : !handshake.channel<i8, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i8, [spec: i1]>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.channel<i8, [spec: i1]>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_fork_1(in %ins : !handshake.channel<i8, [spec: i1]>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i8, [spec: i1]>, out outs_1 : !handshake.channel<i8, [spec: i1]>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i8, [spec: i1]>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_trunci_0(in %ins : !handshake.channel<i8, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i7, [spec: i1]>) attributes {hw.name = "handshake.trunci", hw.parameters = {INPUT_TYPE = !handshake.channel<i8, [spec: i1]>, OUTPUT_TYPE = !handshake.channel<i7, [spec: i1]>}}
  hw.module.extern @handshake_mux_1(in %index : !handshake.channel<i1, [spec: i1]>, in %ins_0 : !handshake.channel<i32, [spec: i1]>, in %ins_1 : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<f32, [spec: i1]>, SELECT_TYPE = !handshake.channel<i1, [spec: i1]>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_4(in %ins : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.channel<f32, [spec: i1]>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_fork_2(in %ins : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32, [spec: i1]>, out outs_1 : !handshake.channel<i32, [spec: i1]>, out outs_2 : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<f32, [spec: i1]>, SIZE = 3 : ui32}}
  hw.module.extern @handshake_control_merge_0(in %ins_0 : !handshake.control<[spec: i1]>, in %ins_1 : !handshake.control<[spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.control<[spec: i1]>, out index : !handshake.channel<i1, [spec: i1]>) attributes {hw.name = "handshake.control_merge", hw.parameters = {DATA_TYPE = !handshake.control<[spec: i1]>, INDEX_TYPE = !handshake.channel<i1, [spec: i1]>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_fork_3(in %ins : !handshake.control<[spec: i1]>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.control<[spec: i1]>, out outs_1 : !handshake.control<[spec: i1]>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.control<[spec: i1]>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_fork_4(in %ins : !handshake.channel<i1, [spec: i1]>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1, [spec: i1]>, out outs_1 : !handshake.channel<i1, [spec: i1]>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1, [spec: i1]>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_source_0(in %clk : i1, in %rst : i1, out outs : !handshake.control<[spec: i1]>) attributes {hw.name = "handshake.source", hw.parameters = {}}
  hw.module.extern @handshake_constant_1(in %ctrl : !handshake.control<[spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 32 : ui32, VALUE = "10111111011001100110011001100110"}}
  hw.module.extern @handshake_constant_2(in %ctrl : !handshake.control<[spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 32 : ui32, VALUE = "00000000000000000000000000000000"}}
  hw.module.extern @handshake_load_0(in %addrIn : !handshake.channel<i7, [spec: i1]>, in %dataFromMem : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out addrOut : !handshake.channel<i7>, out dataOut : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.load", hw.parameters = {ADDR_TYPE = !handshake.channel<i7, [spec: i1]>, DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_buffer_5(in %ins : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<f32, [spec: i1]>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_buffer_6(in %ins : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<f32, [spec: i1]>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_mulf_0(in %lhs : !handshake.channel<i32, [spec: i1]>, in %rhs : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.mulf", hw.parameters = {DATA_TYPE = !handshake.channel<f32, [spec: i1]>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "2_875333"}}
  hw.module.extern @handshake_mulf_1(in %lhs : !handshake.channel<i32, [spec: i1]>, in %rhs : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.mulf", hw.parameters = {DATA_TYPE = !handshake.channel<f32, [spec: i1]>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "2_875333"}}
  hw.module.extern @handshake_buffer_7(in %ins : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<f32, [spec: i1]>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_addf_0(in %lhs : !handshake.channel<i32, [spec: i1]>, in %rhs : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.addf", hw.parameters = {DATA_TYPE = !handshake.channel<f32, [spec: i1]>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "2_922000"}}
  hw.module.extern @handshake_cmpf_0(in %lhs : !handshake.channel<i32, [spec: i1]>, in %rhs : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1, [spec: i1]>) attributes {hw.name = "handshake.cmpf", hw.parameters = {DATA_TYPE = !handshake.channel<f32, [spec: i1]>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "0_000000", PREDICATE = "ugt"}}
  hw.module.extern @handshake_speculator_0(in %ins : !handshake.channel<i1, [spec: i1]>, in %trigger : !handshake.control<[spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1, [spec: i1]>, out ctrl_save : !handshake.channel<i1>, out ctrl_commit : !handshake.channel<i1>, out ctrl_sc_save : !handshake.channel<i3>, out ctrl_sc_commit : !handshake.channel<i3>, out ctrl_sc_branch : !handshake.channel<i1>) attributes {hw.name = "handshake.speculator", hw.parameters = {CONSTANT = true, DEFAULT_VALUE = 0 : ui32, FIFO_DEPTH = 30 : ui32}}
  hw.module.extern @handshake_cond_br_0(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i3>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i3>, out falseOut : !handshake.channel<i3>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<i3>}}
  hw.module.extern @handshake_sink_0(in %ins : !handshake.channel<i3>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.channel<i3>}}
  hw.module.extern @handshake_merge_0(in %ins_0 : !handshake.channel<i3>, in %ins_1 : !handshake.channel<i3>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i3>) attributes {hw.name = "handshake.merge", hw.parameters = {DATA_TYPE = !handshake.channel<i3>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_fork_5(in %ins : !handshake.channel<i3>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i3>, out outs_1 : !handshake.channel<i3>, out outs_2 : !handshake.channel<i3>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i3>, SIZE = 3 : ui32}}
  hw.module.extern @handshake_fork_6(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_sink_1(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.channel<i1>}}
  hw.module.extern @handshake_cond_br_1(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i1>, out falseOut : !handshake.channel<i1>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<i1>}}
  hw.module.extern @handshake_fork_7(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>, out outs_2 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 3 : ui32}}
  hw.module.extern @handshake_speculating_branch_0(in %spec_tag_data : !handshake.channel<i1, [spec: i1]>, in %data : !handshake.channel<i1, [spec: i1]>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i1>, out falseOut : !handshake.channel<i1>) attributes {hw.name = "handshake.speculating_branch", hw.parameters = {}}
  hw.module.extern @handshake_fork_8(in %ins : !handshake.channel<i1, [spec: i1]>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1, [spec: i1]>, out outs_1 : !handshake.channel<i1, [spec: i1]>, out outs_2 : !handshake.channel<i1, [spec: i1]>, out outs_3 : !handshake.channel<i1, [spec: i1]>, out outs_4 : !handshake.channel<i1, [spec: i1]>, out outs_5 : !handshake.channel<i1, [spec: i1]>, out outs_6 : !handshake.channel<i1, [spec: i1]>, out outs_7 : !handshake.channel<i1, [spec: i1]>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1, [spec: i1]>, SIZE = 8 : ui32}}
  hw.module.extern @handshake_spec_save_commit_0(in %ins : !handshake.channel<i8, [spec: i1]>, in %ctrl : !handshake.channel<i3>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i8, [spec: i1]>) attributes {hw.name = "handshake.spec_save_commit", hw.parameters = {FIFO_DEPTH = 30 : ui32}}
  hw.module.extern @handshake_cond_br_2(in %condition : !handshake.channel<i1, [spec: i1]>, in %data : !handshake.channel<i8, [spec: i1]>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i8, [spec: i1]>, out falseOut : !handshake.channel<i8, [spec: i1]>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<i8, [spec: i1]>}}
  hw.module.extern @handshake_spec_save_commit_1(in %ins : !handshake.channel<i32, [spec: i1]>, in %ctrl : !handshake.channel<i3>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.spec_save_commit", hw.parameters = {FIFO_DEPTH = 30 : ui32}}
  hw.module.extern @handshake_cond_br_3(in %condition : !handshake.channel<i1, [spec: i1]>, in %data : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i32, [spec: i1]>, out falseOut : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<f32, [spec: i1]>}}
  hw.module.extern @handshake_spec_save_commit_2(in %ins : !handshake.control<[spec: i1]>, in %ctrl : !handshake.channel<i3>, in %clk : i1, in %rst : i1, out outs : !handshake.control<[spec: i1]>) attributes {hw.name = "handshake.spec_save_commit", hw.parameters = {FIFO_DEPTH = 30 : ui32}}
  hw.module.extern @handshake_cond_br_4(in %condition : !handshake.channel<i1, [spec: i1]>, in %data : !handshake.control<[spec: i1]>, in %clk : i1, in %rst : i1, out trueOut : !handshake.control<[spec: i1]>, out falseOut : !handshake.control<[spec: i1]>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.control<[spec: i1]>}}
  hw.module.extern @handshake_constant_3(in %ctrl : !handshake.control<[spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 32 : ui32, VALUE = "00111111100011001100110011001101"}}
  hw.module.extern @handshake_buffer_8(in %ins : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<f32, [spec: i1]>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_mulf_2(in %lhs : !handshake.channel<i32, [spec: i1]>, in %rhs : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.mulf", hw.parameters = {DATA_TYPE = !handshake.channel<f32, [spec: i1]>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "2_875333"}}
  hw.module.extern @handshake_buffer_9(in %ins : !handshake.channel<i8, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i8, [spec: i1]>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i8, [spec: i1]>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_fork_9(in %ins : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32, [spec: i1]>, out outs_1 : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<f32, [spec: i1]>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_constant_4(in %ctrl : !handshake.control<[spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i2, [spec: i1]>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 2 : ui32, VALUE = "01"}}
  hw.module.extern @handshake_extsi_1(in %ins : !handshake.channel<i2, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i2, [spec: i1]>, OUTPUT_TYPE = !handshake.channel<i32, [spec: i1]>}}
  hw.module.extern @handshake_constant_5(in %ctrl : !handshake.control<[spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 32 : ui32, VALUE = "00111111100011001100110011001101"}}
  hw.module.extern @handshake_buffer_10(in %ins : !handshake.channel<i7, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i7, [spec: i1]>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i7, [spec: i1]>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_spec_commit_2(in %ins : !handshake.channel<i7, [spec: i1]>, in %ctrl : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i7>) attributes {hw.name = "handshake.spec_commit", hw.parameters = {}}
  hw.module.extern @handshake_buffer_11(in %ins : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<f32, [spec: i1]>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_buffer_12(in %ins : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<f32, [spec: i1]>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_spec_commit_3(in %ins : !handshake.channel<i32, [spec: i1]>, in %ctrl : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.spec_commit", hw.parameters = {}}
  hw.module.extern @handshake_store_0(in %addrIn : !handshake.channel<i7>, in %dataIn : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out addrOut : !handshake.channel<i7>, out dataToMem : !handshake.channel<i32>) attributes {hw.name = "handshake.store", hw.parameters = {ADDR_TYPE = !handshake.channel<i7>, DATA_TYPE = !handshake.channel<f32>}}
  hw.module.extern @handshake_divf_0(in %lhs : !handshake.channel<i32, [spec: i1]>, in %rhs : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.divf", hw.parameters = {DATA_TYPE = !handshake.channel<f32, [spec: i1]>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "3_812000"}}
  hw.module.extern @handshake_buffer_13(in %ins : !handshake.channel<i1, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1, [spec: i1]>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i1, [spec: i1]>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_mux_2(in %index : !handshake.channel<i1, [spec: i1]>, in %ins_0 : !handshake.channel<i32, [spec: i1]>, in %ins_1 : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<f32, [spec: i1]>, SELECT_TYPE = !handshake.channel<i1, [spec: i1]>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_14(in %ins : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.channel<f32, [spec: i1]>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_fork_10(in %ins : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32, [spec: i1]>, out outs_1 : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<f32, [spec: i1]>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_15(in %ins : !handshake.channel<i8, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i8, [spec: i1]>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<i8, [spec: i1]>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_extsi_2(in %ins : !handshake.channel<i8, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i9, [spec: i1]>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i8, [spec: i1]>, OUTPUT_TYPE = !handshake.channel<i9, [spec: i1]>}}
  hw.module.extern @handshake_buffer_16(in %ins : !handshake.control<[spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.control<[spec: i1]>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.control<[spec: i1]>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_mux_3(in %index : !handshake.channel<i1, [spec: i1]>, in %ins_0 : !handshake.control<[spec: i1]>, in %ins_1 : !handshake.control<[spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.control<[spec: i1]>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.control<[spec: i1]>, SELECT_TYPE = !handshake.channel<i1, [spec: i1]>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_extsi_3(in %ins : !handshake.channel<i2, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i9, [spec: i1]>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i2, [spec: i1]>, OUTPUT_TYPE = !handshake.channel<i9, [spec: i1]>}}
  hw.module.extern @handshake_constant_6(in %ctrl : !handshake.control<[spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i8, [spec: i1]>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 8 : ui32, VALUE = "01100100"}}
  hw.module.extern @handshake_addf_1(in %lhs : !handshake.channel<i32, [spec: i1]>, in %rhs : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.addf", hw.parameters = {DATA_TYPE = !handshake.channel<f32, [spec: i1]>, FPU_IMPL = "flopoco", INTERNAL_DELAY = "2_922000"}}
  hw.module.extern @handshake_buffer_17(in %ins : !handshake.channel<i9, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i9, [spec: i1]>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<i9, [spec: i1]>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_addi_0(in %lhs : !handshake.channel<i9, [spec: i1]>, in %rhs : !handshake.channel<i9, [spec: i1]>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i9, [spec: i1]>) attributes {hw.name = "handshake.addi", hw.parameters = {DATA_TYPE = !handshake.channel<i9, [spec: i1]>}}
  hw.module.extern @handshake_fork_11(in %ins : !handshake.channel<i9, [spec: i1]>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i9, [spec: i1]>, out outs_1 : !handshake.channel<i9, [spec: i1]>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i9, [spec: i1]>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_trunci_1(in %ins : !handshake.channel<i9, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i8, [spec: i1]>) attributes {hw.name = "handshake.trunci", hw.parameters = {INPUT_TYPE = !handshake.channel<i9, [spec: i1]>, OUTPUT_TYPE = !handshake.channel<i8, [spec: i1]>}}
  hw.module.extern @handshake_cmpi_0(in %lhs : !handshake.channel<i9, [spec: i1]>, in %rhs : !handshake.channel<i9, [spec: i1]>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1, [spec: i1]>) attributes {hw.name = "handshake.cmpi", hw.parameters = {DATA_TYPE = !handshake.channel<i9, [spec: i1]>, PREDICATE = "ult"}}
  hw.module.extern @handshake_fork_12(in %ins : !handshake.channel<i1, [spec: i1]>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1, [spec: i1]>, out outs_1 : !handshake.channel<i1, [spec: i1]>, out outs_2 : !handshake.channel<i1, [spec: i1]>, out outs_3 : !handshake.channel<i1, [spec: i1]>, out outs_4 : !handshake.channel<i1, [spec: i1]>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1, [spec: i1]>, SIZE = 5 : ui32}}
  hw.module.extern @handshake_sink_2(in %ins : !handshake.channel<i8, [spec: i1]>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.channel<i8, [spec: i1]>}}
  hw.module.extern @handshake_cond_br_5(in %condition : !handshake.channel<i1, [spec: i1]>, in %data : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i32, [spec: i1]>, out falseOut : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<f32, [spec: i1]>}}
  hw.module.extern @handshake_buffer_18(in %ins : !handshake.control<[spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.control<[spec: i1]>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.control<[spec: i1]>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_buffer_19(in %ins : !handshake.channel<i32, [spec: i1]>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32, [spec: i1]>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<f32, [spec: i1]>, DEBUG_COUNTER = false, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_spec_commit_4(in %ins : !handshake.channel<i32, [spec: i1]>, in %ctrl : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.spec_commit", hw.parameters = {}}
  hw.module.extern @mem_to_bram_32_7(in %loadEn : i1, in %loadAddr : i7, in %storeEn : i1, in %storeAddr : i7, in %storeData : i32, in %din0 : i32, in %din1 : i32, out ce0 : i1, out we0 : i1, out address0 : i7, out dout0 : i32, out ce1 : i1, out we1 : i1, out address1 : i7, out dout1 : i32, out loadData : i32) attributes {hw.name = "mem_to_bram", hw.parameters = {ADDR_WIDTH = 7 : ui32, DATA_WIDTH = 32 : ui32}}
  hw.module @if_float_wrapper(in %x0 : !handshake.channel<i32>, in %a_din0 : i32, in %a_din1 : i32, in %minus_trace_din0 : i32, in %minus_trace_din1 : i32, in %a_start : !handshake.control<>, in %minus_trace_start : !handshake.control<>, in %start : !handshake.control<>, in %clk : i1, in %rst : i1, out out0 : !handshake.channel<i32>, out a_end : !handshake.control<>, out minus_trace_end : !handshake.control<>, out end : !handshake.control<>, out a_ce0 : i1, out a_we0 : i1, out a_address0 : i7, out a_dout0 : i32, out a_ce1 : i1, out a_we1 : i1, out a_address1 : i7, out a_dout1 : i32, out minus_trace_ce0 : i1, out minus_trace_we0 : i1, out minus_trace_address0 : i7, out minus_trace_dout0 : i32, out minus_trace_ce1 : i1, out minus_trace_we1 : i1, out minus_trace_address1 : i7, out minus_trace_dout1 : i32) {
    %mem_to_bram_converter_a.ce0, %mem_to_bram_converter_a.we0, %mem_to_bram_converter_a.address0, %mem_to_bram_converter_a.dout0, %mem_to_bram_converter_a.ce1, %mem_to_bram_converter_a.we1, %mem_to_bram_converter_a.address1, %mem_to_bram_converter_a.dout1, %mem_to_bram_converter_a.loadData = hw.instance "mem_to_bram_converter_a" @mem_to_bram_32_7(loadEn: %if_float_wrapped.a_loadEn: i1, loadAddr: %if_float_wrapped.a_loadAddr: i7, storeEn: %if_float_wrapped.a_storeEn: i1, storeAddr: %if_float_wrapped.a_storeAddr: i7, storeData: %if_float_wrapped.a_storeData: i32, din0: %a_din0: i32, din1: %a_din1: i32) -> (ce0: i1, we0: i1, address0: i7, dout0: i32, ce1: i1, we1: i1, address1: i7, dout1: i32, loadData: i32)
    %mem_to_bram_converter_minus_trace.ce0, %mem_to_bram_converter_minus_trace.we0, %mem_to_bram_converter_minus_trace.address0, %mem_to_bram_converter_minus_trace.dout0, %mem_to_bram_converter_minus_trace.ce1, %mem_to_bram_converter_minus_trace.we1, %mem_to_bram_converter_minus_trace.address1, %mem_to_bram_converter_minus_trace.dout1, %mem_to_bram_converter_minus_trace.loadData = hw.instance "mem_to_bram_converter_minus_trace" @mem_to_bram_32_7(loadEn: %if_float_wrapped.minus_trace_loadEn: i1, loadAddr: %if_float_wrapped.minus_trace_loadAddr: i7, storeEn: %if_float_wrapped.minus_trace_storeEn: i1, storeAddr: %if_float_wrapped.minus_trace_storeAddr: i7, storeData: %if_float_wrapped.minus_trace_storeData: i32, din0: %minus_trace_din0: i32, din1: %minus_trace_din1: i32) -> (ce0: i1, we0: i1, address0: i7, dout0: i32, ce1: i1, we1: i1, address1: i7, dout1: i32, loadData: i32)
    %if_float_wrapped.out0, %if_float_wrapped.a_end, %if_float_wrapped.minus_trace_end, %if_float_wrapped.end, %if_float_wrapped.a_loadEn, %if_float_wrapped.a_loadAddr, %if_float_wrapped.a_storeEn, %if_float_wrapped.a_storeAddr, %if_float_wrapped.a_storeData, %if_float_wrapped.minus_trace_loadEn, %if_float_wrapped.minus_trace_loadAddr, %if_float_wrapped.minus_trace_storeEn, %if_float_wrapped.minus_trace_storeAddr, %if_float_wrapped.minus_trace_storeData = hw.instance "if_float_wrapped" @if_float(x0: %x0: !handshake.channel<i32>, a_loadData: %mem_to_bram_converter_a.loadData: i32, minus_trace_loadData: %mem_to_bram_converter_minus_trace.loadData: i32, a_start: %a_start: !handshake.control<>, minus_trace_start: %minus_trace_start: !handshake.control<>, start: %start: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (out0: !handshake.channel<i32>, a_end: !handshake.control<>, minus_trace_end: !handshake.control<>, end: !handshake.control<>, a_loadEn: i1, a_loadAddr: i7, a_storeEn: i1, a_storeAddr: i7, a_storeData: i32, minus_trace_loadEn: i1, minus_trace_loadAddr: i7, minus_trace_storeEn: i1, minus_trace_storeAddr: i7, minus_trace_storeData: i32)
    hw.output %if_float_wrapped.out0, %if_float_wrapped.a_end, %if_float_wrapped.minus_trace_end, %if_float_wrapped.end, %mem_to_bram_converter_a.ce0, %mem_to_bram_converter_a.we0, %mem_to_bram_converter_a.address0, %mem_to_bram_converter_a.dout0, %mem_to_bram_converter_a.ce1, %mem_to_bram_converter_a.we1, %mem_to_bram_converter_a.address1, %mem_to_bram_converter_a.dout1, %mem_to_bram_converter_minus_trace.ce0, %mem_to_bram_converter_minus_trace.we0, %mem_to_bram_converter_minus_trace.address0, %mem_to_bram_converter_minus_trace.dout0, %mem_to_bram_converter_minus_trace.ce1, %mem_to_bram_converter_minus_trace.we1, %mem_to_bram_converter_minus_trace.address1, %mem_to_bram_converter_minus_trace.dout1 : !handshake.channel<i32>, !handshake.control<>, !handshake.control<>, !handshake.control<>, i1, i1, i7, i32, i1, i1, i7, i32, i1, i1, i7, i32, i1, i1, i7, i32
  }
}

