// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py
// RUN: dynamatic-opt --handshake-optimize-bitwidths --remove-operation-names %s --split-input-file | FileCheck %s

// CHECK-LABEL:   handshake.func @test_and_sext_unknown(
// CHECK-SAME:                                          %[[VAL_0:.*]]: !handshake.channel<i1>,
// CHECK-SAME:                                          %[[VAL_1:.*]]: !handshake.channel<i32>,
// CHECK-SAME:                                          %[[VAL_2:.*]]: !handshake.control<>, ...) -> (!handshake.channel<i32>, !handshake.control<>) attributes {argNames = ["arg0", "arg1", "start"], resNames = ["out0", "end"]} {
// CHECK:           %[[VAL_3:.*]] = extsi %[[VAL_0]] {handshake.bb = 0 : ui32} : <i1> to <i32>
// CHECK:           %[[VAL_4:.*]] = andi %[[VAL_3]], %[[VAL_1]] {handshake.bb = 0 : ui32} : <i32>
// CHECK:           end {handshake.bb = 0 : ui32} %[[VAL_4]], %[[VAL_2]] : <i32>, <>
// CHECK:         }
handshake.func @test_and_sext_unknown(%arg0: !handshake.channel<i1>, %arg1: !handshake.channel<i32>, %arg2: !handshake.control<>, ...) -> (!handshake.channel<i32>, !handshake.control<>) attributes {argNames = ["arg0", "arg1", "start"], resNames = ["out0", "end"]} {
  %0 = extsi %arg0 {handshake.bb = 0 : ui32, handshake.name = "extsi0"} : <i1> to <i32>
  %1 = andi %0, %arg1 {handshake.bb = 0 : ui32, handshake.name = "andi0"} : <i32>
  end {handshake.bb = 0 : ui32, handshake.name = "end0"} %1, %arg2 : <i32>, <>
}

// -----

// CHECK-LABEL:   handshake.func @test_and_sext_zext(
// CHECK-SAME:                                       %[[VAL_0:.*]]: !handshake.channel<i1>,
// CHECK-SAME:                                       %[[VAL_1:.*]]: !handshake.channel<i16>,
// CHECK-SAME:                                       %[[VAL_2:.*]]: !handshake.control<>, ...) -> (!handshake.channel<i32>, !handshake.control<>) attributes {argNames = ["arg0", "arg1", "start"], resNames = ["out0", "end"]} {
// CHECK:           %[[VAL_3:.*]] = extsi %[[VAL_0]] {handshake.bb = 0 : ui32} : <i1> to <i16>
// CHECK:           %[[VAL_4:.*]] = andi %[[VAL_3]], %[[VAL_1]] {handshake.bb = 0 : ui32} : <i16>
// CHECK:           %[[VAL_5:.*]] = extui %[[VAL_4]] : <i16> to <i32>
// CHECK:           end {handshake.bb = 0 : ui32} %[[VAL_5]], %[[VAL_2]] : <i32>, <>
// CHECK:         }
handshake.func @test_and_sext_zext(%arg0: !handshake.channel<i1>, %arg1: !handshake.channel<i16>, %arg2: !handshake.control<>, ...) -> (!handshake.channel<i32>, !handshake.control<>) attributes {argNames = ["arg0", "arg1", "start"], resNames = ["out0", "end"]} {
  %0 = extsi %arg0 {handshake.bb = 0 : ui32, handshake.name = "extsi0"} : <i1> to <i32>
  %1 = extui %arg1 {handshake.bb = 0 : ui32, handshake.name = "extui0"} : <i16> to <i32>
  %2 = andi %0, %1 {handshake.bb = 0 : ui32, handshake.name = "andi0"} : <i32>
  end {handshake.bb = 0 : ui32, handshake.name = "end0"} %2, %arg2 : <i32>, <>
}

// -----

// CHECK-LABEL:   handshake.func @test_and_sext_sext(
// CHECK-SAME:                                       %[[VAL_0:.*]]: !handshake.channel<i1>,
// CHECK-SAME:                                       %[[VAL_1:.*]]: !handshake.control<>, ...) -> (!handshake.channel<i32>, !handshake.control<>) attributes {argNames = ["var2", "start"], resNames = ["out0", "end"]} {
// CHECK:           %[[VAL_2:.*]] = extsi %[[VAL_0]] {handshake.bb = 0 : ui32} : <i1> to <i8>
// CHECK:           %[[VAL_3:.*]] = source {handshake.bb = 0 : ui32} : <>
// CHECK:           %[[VAL_4:.*]] = constant %[[VAL_3]] {handshake.bb = 0 : ui32, value = 71 : i8} : <>, <i8>
// CHECK:           %[[VAL_5:.*]] = andi %[[VAL_2]], %[[VAL_4]] {handshake.bb = 0 : ui32} : <i8>
// CHECK:           %[[VAL_6:.*]] = extsi %[[VAL_5]] : <i8> to <i32>
// CHECK:           end {handshake.bb = 0 : ui32} %[[VAL_6]], %[[VAL_1]] : <i32>, <>
// CHECK:         }
handshake.func @test_and_sext_sext(%arg0: !handshake.channel<i1>, %arg2: !handshake.control<>, ...) -> (!handshake.channel<i32>, !handshake.control<>) attributes {argNames = ["var2", "start"], resNames = ["out0", "end"]} {
  %2 = source {handshake.bb = 0 : ui32, handshake.name = "source1"} : <>
  %3 = constant %2 {handshake.bb = 0 : ui32, handshake.name = "constant1", value = 71 : i8} : <>, <i8>
  %4 = extsi %3 : <i8> to <i32>
  %7 = extsi %arg0 {handshake.bb = 0 : ui32, handshake.name = "extsi0"} : <i1> to <i32>
  %9 = andi %7, %4 {handshake.bb = 0 : ui32, handshake.name = "andi0"} : <i32>
  end {handshake.bb = 0 : ui32, handshake.name = "end0"} %9, %arg2 : <i32>, <>
}
