// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py
// RUN: dynamatic-opt --handshake-optimize-bitwidths --remove-operation-names %s --split-input-file | FileCheck %s

// CHECK-LABEL:   handshake.func @test_and_sext_sext(
// CHECK-SAME:                                       %[[VAL_0:.*]]: !handshake.channel<i1>,
// CHECK-SAME:                                       %[[VAL_1:.*]]: !handshake.channel<i16>,
// CHECK-SAME:                                       %[[VAL_2:.*]]: !handshake.control<>, ...) -> (!handshake.channel<i32>, !handshake.control<>) attributes {argNames = ["arg0", "arg1", "start"], resNames = ["out0", "end"]} {
// CHECK:           %[[VAL_3:.*]] = extsi %[[VAL_0]] {handshake.bb = 0 : ui32} : <i1> to <i16>
// CHECK:           %[[VAL_4:.*]] = ori %[[VAL_3]], %[[VAL_1]] {handshake.bb = 0 : ui32} : <i16>
// CHECK:           %[[VAL_5:.*]] = extsi %[[VAL_4]] : <i16> to <i32>
// CHECK:           end {handshake.bb = 0 : ui32} %[[VAL_5]], %[[VAL_2]] : <i32>, <>
// CHECK:         }
handshake.func @test_and_sext_sext(%arg0: !handshake.channel<i1>, %arg1: !handshake.channel<i16>, %arg2: !handshake.control<>, ...) -> (!handshake.channel<i32>, !handshake.control<>) attributes {argNames = ["arg0", "arg1", "start"], resNames = ["out0", "end"]} {
  %0 = extsi %arg0 {handshake.bb = 0 : ui32, handshake.name = "extsi0"} : <i1> to <i32>
  %1 = extsi %arg1 {handshake.bb = 0 : ui32, handshake.name = "extsi1"} : <i16> to <i32>
  %2 = ori %0, %1 {handshake.bb = 0 : ui32, handshake.name = "andi0"} : <i32>
  end {handshake.bb = 0 : ui32, handshake.name = "end0"} %2, %arg2 : <i32>, <>
}

// -----

// CHECK-LABEL:   handshake.func @test_and_sext_zext(
// CHECK-SAME:                                       %[[VAL_0:.*]]: !handshake.channel<i1>,
// CHECK-SAME:                                       %[[VAL_1:.*]]: !handshake.channel<i16>,
// CHECK-SAME:                                       %[[VAL_2:.*]]: !handshake.control<>, ...) -> (!handshake.channel<i32>, !handshake.control<>) attributes {argNames = ["arg0", "arg1", "start"], resNames = ["out0", "end"]} {
// CHECK:           %[[VAL_3:.*]] = extui %[[VAL_1]] {handshake.bb = 0 : ui32} : <i16> to <i17>
// CHECK:           %[[VAL_4:.*]] = extsi %[[VAL_0]] {handshake.bb = 0 : ui32} : <i1> to <i17>
// CHECK:           %[[VAL_5:.*]] = ori %[[VAL_4]], %[[VAL_3]] {handshake.bb = 0 : ui32} : <i17>
// CHECK:           %[[VAL_6:.*]] = extsi %[[VAL_5]] : <i17> to <i32>
// CHECK:           end {handshake.bb = 0 : ui32} %[[VAL_6]], %[[VAL_2]] : <i32>, <>
// CHECK:         }
handshake.func @test_and_sext_zext(%arg0: !handshake.channel<i1>, %arg1: !handshake.channel<i16>, %arg2: !handshake.control<>, ...) -> (!handshake.channel<i32>, !handshake.control<>) attributes {argNames = ["arg0", "arg1", "start"], resNames = ["out0", "end"]} {
  %0 = extsi %arg0 {handshake.bb = 0 : ui32, handshake.name = "extsi0"} : <i1> to <i32>
  %1 = extui %arg1 {handshake.bb = 0 : ui32, handshake.name = "extsi1"} : <i16> to <i32>
  %2 = ori %0, %1 {handshake.bb = 0 : ui32, handshake.name = "andi0"} : <i32>
  end {handshake.bb = 0 : ui32, handshake.name = "end0"} %2, %arg2 : <i32>, <>
}


// -----

// CHECK-LABEL:   handshake.func @test_and_zext_sext(
// CHECK-SAME:                                       %[[VAL_0:.*]]: !handshake.channel<i1>,
// CHECK-SAME:                                       %[[VAL_1:.*]]: !handshake.channel<i16>,
// CHECK-SAME:                                       %[[VAL_2:.*]]: !handshake.control<>, ...) -> (!handshake.channel<i32>, !handshake.control<>) attributes {argNames = ["arg0", "arg1", "start"], resNames = ["out0", "end"]} {
// CHECK:           %[[VAL_3:.*]] = extui %[[VAL_0]] {handshake.bb = 0 : ui32} : <i1> to <i16>
// CHECK:           %[[VAL_4:.*]] = ori %[[VAL_3]], %[[VAL_1]] {handshake.bb = 0 : ui32} : <i16>
// CHECK:           %[[VAL_5:.*]] = extsi %[[VAL_4]] : <i16> to <i32>
// CHECK:           end {handshake.bb = 0 : ui32} %[[VAL_5]], %[[VAL_2]] : <i32>, <>
// CHECK:         }
handshake.func @test_and_zext_sext(%arg0: !handshake.channel<i1>, %arg1: !handshake.channel<i16>, %arg2: !handshake.control<>, ...) -> (!handshake.channel<i32>, !handshake.control<>) attributes {argNames = ["arg0", "arg1", "start"], resNames = ["out0", "end"]} {
  %0 = extui %arg0 {handshake.bb = 0 : ui32, handshake.name = "extsi0"} : <i1> to <i32>
  %1 = extsi %arg1 {handshake.bb = 0 : ui32, handshake.name = "extsi1"} : <i16> to <i32>
  %2 = ori %0, %1 {handshake.bb = 0 : ui32, handshake.name = "andi0"} : <i32>
  end {handshake.bb = 0 : ui32, handshake.name = "end0"} %2, %arg2 : <i32>, <>
}
