name: Build docker image

on:
  # Make sure that settings are set to require permission
  # to run workflows by external contributors!
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened, ready_for_review]
  
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t dynamatic-image .
