name: Build on Ubuntu 22.04

on:
  # Make sure that settings are set to require permission
  # to run workflows by external contributors!
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened, ready_for_review]

  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jiahui17/dynamatic:latest

    steps:
      - name: Set PR env
        if: github.event_name == 'pull_request'
        env:
          GIT_REF: ${{ github.event.pull_request.head.ref }}
          GIT_REPO: ${{ github.event.pull_request.head.repo.clone_url }}
        run: echo "PR branch is $GIT_REF, from repo $GIT_REPO"

      - name: Set push env
        if: github.event_name == 'push'
        env:
          GIT_REF: ${{ github.ref_name }}
          GIT_REPO: https://github.com/${{ github.repository }}.git
        run: echo "Push branch is $GIT_REF"

      - name: Build Dynamatic
        # NOTE: here we cannot use "actions/checkout@v4", because it always
        # operate on the mounted volume instead of the pre-built Dynamatic
        # directory in the container.
        run: |
          # Github runner always overrides HOME to "/github/home/". Here we need
          # to make sure that we only write to writable locations
          export CCACHE_DIR=/home/dynamatic/dynamatic/.ccache
          cd /home/dynamatic/dynamatic
          # Replaces the origin the repo of the PR (it might be a fork)
          echo "Checking branch $GIT_REF, from repo $GIT_REPO"
          git remote remove origin 2>/dev/null || true
          git remote add origin "$GIT_REPO"
          # Fetch the PR branch
          git fetch origin "$GIT_REF"
          # Checkout and reset to the PR branch
          git checkout -B pr-branch FETCH_HEAD
          echo "Test Dynamatic build on commit: $GIT_REF repo: $GIT_REPO"
          # Update submodules if needed
          git submodule update --init --recursive
          ./build.sh -f --release
