name: Build on Ubuntu 22.04

on:
  # Make sure that settings are set to require permission
  # to run workflows by external contributors!
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened, ready_for_review]

  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jiahui17/dynamatic:latest

    steps:
      - name: Build Dynamatic
        # Github runner always overrides HOME to "/github/home/"
        # Here we need to make sure that we only write to writable locations
        run: |
          export CCACHE_DIR=/home/dynamatic/dynamatic/.ccache
          cd /home/dynamatic/dynamatic
          ./build.sh -f --release
