name: check-format

on:
  # Make sure that settings are set to require permission
  # to run workflows by external contributors!
  pull_request:
    branches: ["main"]

jobs:
  integration:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: check-format-cpp
        run: |
          sudo apt-get -y update
          sudo apt-get -y install clang-format-19
          git fetch origin main --no-recurse-submodules
          git clang-format --diff FETCH_HEAD --extensions c,h,m,mm,cc,cp,cpp,c++,cxx,hh,hpp,hxx,inc

      - name: check-format-python
        if: success() || failure()
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install autopep8==2.3.2
          echo "Running autopep8..."
          git fetch origin main --no-recurse-submodules
          git reset FETCH_HEAD
          FILES=$(comm -23 <(git ls-files '*.py' --modified | sort) <(git ls-files '*.py' --deleted | sort))
          STATUS=$?
          if [[ $FILES ]]; then
            exec 3>&1
            OUTPUT=$(autopep8 --max-line-length 200 --diff $FILES 3>&- | tee /dev/fd/3)
            exec 3>&-
            if [[ $OUTPUT ]]; then
              STATUS=1
            else
              STATUS=0
            fi
          else
            STATUS=0
          fi
          echo "autopep8 exited with $STATUS"
          deactivate
          exit $STATUS

