name: unittests

on:
  # Make sure that settings are set to require permission
  # to run workflows by external contributors!
  pull_request:
    paths-ignore:
      - 'docs/**'
    branches: ["main"]
    types: [opened, synchronize, reopened, ready_for_review]
  
  push:
    paths-ignore:
      - 'docs/**'
    branches: ["main"]

# Cancel previous CI builds when a new push occurs to the same PR.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  unittests:
    runs-on: ubuntu-latest

    steps:
      - name: cleanup
        run: |
          echo "Emptying folder"
          rm -rf -- * .*
          echo "Folder contents"
          ls -la

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Update apt and install prerequisites
        run: |
          sudo apt-get -y update
          sudo apt-get -y install software-properties-common
          sudo add-apt-repository ppa:deadsnakes/ppa

      - name: Install system dependencies
        run: |
          sudo apt-get install -y \
            --option APT::Immediate-Configure=false \
            sudo vim clang lld ccache cmake wget \
            ninja-build python3 graphviz git curl \
            gzip libreadline-dev \
            libboost-all-dev pkg-config python3.12 \
            python3.12-venv python3.12-dev \
            ghdl verilator \
            flex bison tcl-dev

      - name: Verify Python 3.12
        run: python3.12 --version

      - name: build
        run: ./build.sh --release --use-prebuilt-llvm --enable-abc --enable-cbc --enable-yosys --force

      - name: check-dynamatic
        if: steps.build.outputs.exit_code == 0
        run: ninja check-dynamatic
        working-directory: build

