module {
  hw.module @if_convert(in %a_loadData : i32, in %b_loadData : i32, in %a_start : !handshake.control<>, in %b_start : !handshake.control<>, in %start : !handshake.control<>, in %clk : i1, in %rst : i1, out a_end : !handshake.control<>, out b_end : !handshake.control<>, out end : !handshake.control<>, out a_loadEn : i1, out a_loadAddr : i8, out a_storeEn : i1, out a_storeAddr : i8, out a_storeData : i32, out b_loadEn : i1, out b_loadAddr : i8, out b_storeEn : i1, out b_storeAddr : i8, out b_storeData : i32) {
    %fork0.outs_0, %fork0.outs_1, %fork0.outs_2 = hw.instance "fork0" @handshake_fork_0(ins: %start: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.control<>, outs_1: !handshake.control<>, outs_2: !handshake.control<>)
    %mem_controller2.memEnd, %mem_controller2.loadEn, %mem_controller2.loadAddr, %mem_controller2.storeEn, %mem_controller2.storeAddr, %mem_controller2.storeData = hw.instance "mem_controller2" @handshake_mem_controller_0(loadData: %b_loadData: i32, memStart: %b_start: !handshake.control<>, ctrl_0: %passer9.result: !handshake.channel<i32>, stAddr_0: %store1.addrOut: !handshake.channel<i8>, stData_0: %store1.dataToMem: !handshake.channel<i32>, ctrlEnd: %fork16.outs_1: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (memEnd: !handshake.control<>, loadEn: i1, loadAddr: i8, storeEn: i1, storeAddr: i8, storeData: i32)
    %mem_controller3.ldData_0, %mem_controller3.memEnd, %mem_controller3.loadEn, %mem_controller3.loadAddr, %mem_controller3.storeEn, %mem_controller3.storeAddr, %mem_controller3.storeData = hw.instance "mem_controller3" @handshake_mem_controller_1(loadData: %a_loadData: i32, memStart: %a_start: !handshake.control<>, ldAddr_0: %load1.addrOut: !handshake.channel<i8>, ctrlEnd: %fork16.outs_0: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (ldData_0: !handshake.channel<i32>, memEnd: !handshake.control<>, loadEn: i1, loadAddr: i8, storeEn: i1, storeAddr: i8, storeData: i32)
    %constant2.outs = hw.instance "constant2" @handshake_constant_0(ctrl: %fork0.outs_0: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i2>)
    %extsi7.outs = hw.instance "extsi7" @handshake_extsi_0(ins: %constant2.outs: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %fork1.outs_0, %fork1.outs_1 = hw.instance "fork1" @handshake_fork_1(ins: %extsi7.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>)
    %mux0.outs = hw.instance "mux0" @handshake_mux_0(index: %fork2.outs_0: !handshake.channel<i1>, ins_0: %fork1.outs_0: !handshake.channel<i32>, ins_1: %fork15.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %mux1.outs = hw.instance "mux1" @handshake_mux_0(index: %fork2.outs_1: !handshake.channel<i1>, ins_0: %fork1.outs_1: !handshake.channel<i32>, ins_1: %fork15.outs_1: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %control_merge0.outs, %control_merge0.index = hw.instance "control_merge0" @handshake_control_merge_0(ins_0: %fork0.outs_2: !handshake.control<>, ins_1: %cond_br6.trueOut: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>, index: !handshake.channel<i1>)
    %fork2.outs_0, %fork2.outs_1 = hw.instance "fork2" @handshake_fork_2(ins: %control_merge0.index: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>)
    %buffer1.outs = hw.instance "buffer1" @handshake_buffer_0(ins: %mux0.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %mux2.outs = hw.instance "mux2" @handshake_mux_0(index: %fork25.outs_2: !handshake.channel<i1>, ins_0: %buffer1.outs: !handshake.channel<i32>, ins_1: %passer2.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer3.outs = hw.instance "buffer3" @handshake_buffer_0(ins: %mux2.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %fork23.outs_0, %fork23.outs_1, %fork23.outs_2, %fork23.outs_3 = hw.instance "fork23" @handshake_fork_3(ins: %buffer3.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>, outs_2: !handshake.channel<i32>, outs_3: !handshake.channel<i32>)
    %buffer2.outs = hw.instance "buffer2" @handshake_buffer_0(ins: %mux1.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %mux3.outs = hw.instance "mux3" @handshake_mux_0(index: %fork25.outs_1: !handshake.channel<i1>, ins_0: %buffer2.outs: !handshake.channel<i32>, ins_1: %passer12.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer7.outs = hw.instance "buffer7" @handshake_buffer_1(ins: %mux3.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %buffer8.outs = hw.instance "buffer8" @handshake_buffer_0(ins: %buffer7.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %fork24.outs_0, %fork24.outs_1, %fork24.outs_2, %fork24.outs_3, %fork24.outs_4 = hw.instance "fork24" @handshake_fork_4(ins: %buffer8.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>, outs_2: !handshake.channel<i32>, outs_3: !handshake.channel<i32>, outs_4: !handshake.channel<i32>)
    %mux4.outs = hw.instance "mux4" @handshake_mux_1(index: %fork25.outs_0: !handshake.channel<i1>, ins_0: %control_merge0.outs: !handshake.control<>, ins_1: %passer13.result: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %source0.outs = hw.instance "source0" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant9.outs = hw.instance "constant9" @handshake_constant_1(ctrl: %source0.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i9>)
    %extsi1.outs = hw.instance "extsi1" @handshake_extsi_1(ins: %constant9.outs: !handshake.channel<i9>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %cmpi0.result = hw.instance "cmpi0" @handshake_cmpi_0(lhs: %fork24.outs_1: !handshake.channel<i32>, rhs: %extsi1.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %buffer4.outs = hw.instance "buffer4" @handshake_buffer_1(ins: %fork23.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %cmpi1.result = hw.instance "cmpi1" @handshake_cmpi_1(lhs: %fork24.outs_0: !handshake.channel<i32>, rhs: %buffer4.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %andi0.result = hw.instance "andi0" @handshake_andi_0(lhs: %cmpi0.result: !handshake.channel<i1>, rhs: %cmpi1.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %buffer13.outs = hw.instance "buffer13" @handshake_buffer_2(ins: %fork26.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %init0.outs = hw.instance "init0" @handshake_init_0(ins: %buffer13.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %fork25.outs_0, %fork25.outs_1, %fork25.outs_2 = hw.instance "fork25" @handshake_fork_5(ins: %init0.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>)
    %source4.outs = hw.instance "source4" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant0.outs = hw.instance "constant0" @handshake_constant_2(ctrl: %source4.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer0.outs = hw.instance "buffer0" @handshake_buffer_3(ins: %passer0.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %merge0.outs = hw.instance "merge0" @handshake_merge_0(ins_0: %buffer0.outs: !handshake.channel<i1>, ins_1: %constant0.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer11.outs = hw.instance "buffer11" @handshake_buffer_4(ins: %merge0.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer12.outs = hw.instance "buffer12" @handshake_buffer_3(ins: %buffer11.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %fork26.outs_0, %fork26.outs_1, %fork26.outs_2, %fork26.outs_3, %fork26.outs_4 = hw.instance "fork26" @handshake_fork_6(ins: %buffer12.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>, outs_3: !handshake.channel<i1>, outs_4: !handshake.channel<i1>)
    %andi1.result = hw.instance "andi1" @handshake_andi_0(lhs: %not0.outs: !handshake.channel<i1>, rhs: %fork28.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %fork27.outs_0, %fork27.outs_1, %fork27.outs_2 = hw.instance "fork27" @handshake_fork_5(ins: %andi1.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>)
    %spec_v2_resolver0.confirmSpec = hw.instance "spec_v2_resolver0" @handshake_spec_v2_resolver_0(actualCondition: %fork29.outs_4: !handshake.channel<i1>, generatedCondition: %fork26.outs_4: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (confirmSpec: !handshake.channel<i1>)
    %fork28.outs_0, %fork28.outs_1, %fork28.outs_2, %fork28.outs_3, %fork28.outs_4, %fork28.outs_5, %fork28.outs_6 = hw.instance "fork28" @handshake_fork_7(ins: %spec_v2_resolver0.confirmSpec: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>, outs_3: !handshake.channel<i1>, outs_4: !handshake.channel<i1>, outs_5: !handshake.channel<i1>, outs_6: !handshake.channel<i1>)
    %passer0.result = hw.instance "passer0" @handshake_passer_0(data: %fork29.outs_5: !handshake.channel<i1>, ctrl: %fork27.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %fork29.outs_0, %fork29.outs_1, %fork29.outs_2, %fork29.outs_3, %fork29.outs_4, %fork29.outs_5 = hw.instance "fork29" @handshake_fork_8(ins: %andi0.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>, outs_2: !handshake.channel<i1>, outs_3: !handshake.channel<i1>, outs_4: !handshake.channel<i1>, outs_5: !handshake.channel<i1>)
    %not0.outs = hw.instance "not0" @handshake_not_0(ins: %fork29.outs_0: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %buffer5.outs = hw.instance "buffer5" @handshake_buffer_1(ins: %fork23.outs_1: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %passer1.result = hw.instance "passer1" @handshake_passer_1(data: %buffer5.outs: !handshake.channel<i32>, ctrl: %fork27.outs_2: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %buffer14.outs = hw.instance "buffer14" @handshake_buffer_5(ins: %fork26.outs_3: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %passer2.result = hw.instance "passer2" @handshake_passer_1(data: %fork12.outs_1: !handshake.channel<i32>, ctrl: %buffer14.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %buffer15.outs = hw.instance "buffer15" @handshake_buffer_5(ins: %fork28.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %passer3.result = hw.instance "passer3" @handshake_passer_2(data: %trunci1.outs: !handshake.channel<i8>, ctrl: %buffer15.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i8>)
    %buffer16.outs = hw.instance "buffer16" @handshake_buffer_5(ins: %passer7.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i1>)
    %passer4.result = hw.instance "passer4" @handshake_passer_2(data: %passer3.result: !handshake.channel<i8>, ctrl: %buffer16.outs: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i8>)
    %passer5.result = hw.instance "passer5" @handshake_passer_0(data: %fork29.outs_1: !handshake.channel<i1>, ctrl: %fork28.outs_4: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %passer6.result = hw.instance "passer6" @handshake_passer_0(data: %fork29.outs_2: !handshake.channel<i1>, ctrl: %fork28.outs_3: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %passer7.result = hw.instance "passer7" @handshake_passer_0(data: %fork29.outs_3: !handshake.channel<i1>, ctrl: %fork28.outs_2: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %passer8.result = hw.instance "passer8" @handshake_passer_1(data: %passer10.result: !handshake.channel<i32>, ctrl: %passer6.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %passer9.result = hw.instance "passer9" @handshake_passer_1(data: %passer11.result: !handshake.channel<i32>, ctrl: %passer5.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %buffer9.outs = hw.instance "buffer9" @handshake_buffer_6(ins: %mux4.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %buffer10.outs = hw.instance "buffer10" @handshake_buffer_7(ins: %buffer9.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %fork22.outs_0, %fork22.outs_1, %fork22.outs_2 = hw.instance "fork22" @handshake_fork_0(ins: %buffer10.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.control<>, outs_1: !handshake.control<>, outs_2: !handshake.control<>)
    %passer10.result = hw.instance "passer10" @handshake_passer_1(data: %fork11.outs_0: !handshake.channel<i32>, ctrl: %fork28.outs_5: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %passer11.result = hw.instance "passer11" @handshake_passer_1(data: %extsi3.outs: !handshake.channel<i32>, ctrl: %fork28.outs_6: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %passer12.result = hw.instance "passer12" @handshake_passer_1(data: %addi2.result: !handshake.channel<i32>, ctrl: %fork26.outs_2: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %passer13.result = hw.instance "passer13" @handshake_passer_3(data: %fork22.outs_2: !handshake.control<>, ctrl: %fork26.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.control<>)
    %passer14.result = hw.instance "passer14" @handshake_passer_3(data: %fork22.outs_0: !handshake.control<>, ctrl: %fork27.outs_1: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.control<>)
    %trunci0.outs = hw.instance "trunci0" @handshake_trunci_0(ins: %fork23.outs_2: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8>)
    %constant10.outs = hw.instance "constant10" @handshake_constant_0(ctrl: %fork22.outs_1: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i2>)
    %fork10.outs_0, %fork10.outs_1 = hw.instance "fork10" @handshake_fork_9(ins: %constant10.outs: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i2>, outs_1: !handshake.channel<i2>)
    %extsi2.outs = hw.instance "extsi2" @handshake_extsi_0(ins: %fork10.outs_0: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %fork11.outs_0, %fork11.outs_1, %fork11.outs_2 = hw.instance "fork11" @handshake_fork_10(ins: %extsi2.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>, outs_2: !handshake.channel<i32>)
    %extsi3.outs = hw.instance "extsi3" @handshake_extsi_0(ins: %fork10.outs_1: !handshake.channel<i2>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %source1.outs = hw.instance "source1" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant11.outs = hw.instance "constant11" @handshake_constant_3(ctrl: %source1.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i15>)
    %extsi4.outs = hw.instance "extsi4" @handshake_extsi_2(ins: %constant11.outs: !handshake.channel<i15>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %source2.outs = hw.instance "source2" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant12.outs = hw.instance "constant12" @handshake_constant_4(ctrl: %source2.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i3>)
    %extsi5.outs = hw.instance "extsi5" @handshake_extsi_3(ins: %constant12.outs: !handshake.channel<i3>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %load1.addrOut, %load1.dataOut = hw.instance "load1" @handshake_load_0(addrIn: %trunci0.outs: !handshake.channel<i8>, dataFromMem: %mem_controller3.ldData_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (addrOut: !handshake.channel<i8>, dataOut: !handshake.channel<i32>)
    %buffer6.outs = hw.instance "buffer6" @handshake_buffer_8(ins: %fork23.outs_3: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %muli0.result = hw.instance "muli0" @handshake_muli_0(lhs: %buffer6.outs: !handshake.channel<i32>, rhs: %load1.dataOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %cmpi2.result = hw.instance "cmpi2" @handshake_cmpi_0(lhs: %muli0.result: !handshake.channel<i32>, rhs: %extsi4.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %addi0.result = hw.instance "addi0" @handshake_addi_0(lhs: %fork24.outs_4: !handshake.channel<i32>, rhs: %extsi5.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %addi1.result = hw.instance "addi1" @handshake_addi_0(lhs: %fork24.outs_3: !handshake.channel<i32>, rhs: %fork11.outs_1: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %buffer18.outs = hw.instance "buffer18" @handshake_buffer_9(ins: %addi1.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %select1.result = hw.instance "select1" @handshake_select_0(condition: %cmpi2.result: !handshake.channel<i1>, trueValue: %addi0.result: !handshake.channel<i32>, falseValue: %buffer18.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %fork12.outs_0, %fork12.outs_1 = hw.instance "fork12" @handshake_fork_1(ins: %select1.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>)
    %trunci1.outs = hw.instance "trunci1" @handshake_trunci_0(ins: %fork12.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i8>)
    %buffer17.outs = hw.instance "buffer17" @handshake_buffer_9(ins: %passer8.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %store1.addrOut, %store1.dataToMem = hw.instance "store1" @handshake_store_0(addrIn: %passer4.result: !handshake.channel<i8>, dataIn: %buffer17.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (addrOut: !handshake.channel<i8>, dataToMem: !handshake.channel<i32>)
    %addi2.result = hw.instance "addi2" @handshake_addi_0(lhs: %fork24.outs_2: !handshake.channel<i32>, rhs: %fork11.outs_2: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i32>)
    %fork13.outs_0, %fork13.outs_1 = hw.instance "fork13" @handshake_fork_1(ins: %passer1.result: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>)
    %source3.outs = hw.instance "source3" @handshake_source_0(clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.control<>)
    %constant13.outs = hw.instance "constant13" @handshake_constant_1(ctrl: %source3.outs: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i9>)
    %extsi6.outs = hw.instance "extsi6" @handshake_extsi_1(ins: %constant13.outs: !handshake.channel<i9>, clk: %clk: i1, rst: %rst: i1) -> (outs: !handshake.channel<i32>)
    %cmpi3.result = hw.instance "cmpi3" @handshake_cmpi_0(lhs: %fork13.outs_1: !handshake.channel<i32>, rhs: %extsi6.outs: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (result: !handshake.channel<i1>)
    %fork14.outs_0, %fork14.outs_1 = hw.instance "fork14" @handshake_fork_2(ins: %cmpi3.result: !handshake.channel<i1>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i1>, outs_1: !handshake.channel<i1>)
    %cond_br5.trueOut, %cond_br5.falseOut = hw.instance "cond_br5" @handshake_cond_br_0(condition: %fork14.outs_1: !handshake.channel<i1>, data: %fork13.outs_0: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.channel<i32>, falseOut: !handshake.channel<i32>)
    hw.instance "sink3" @handshake_sink_0(ins: %cond_br5.falseOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> ()
    %fork15.outs_0, %fork15.outs_1 = hw.instance "fork15" @handshake_fork_1(ins: %cond_br5.trueOut: !handshake.channel<i32>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.channel<i32>, outs_1: !handshake.channel<i32>)
    %cond_br6.trueOut, %cond_br6.falseOut = hw.instance "cond_br6" @handshake_cond_br_1(condition: %fork14.outs_0: !handshake.channel<i1>, data: %passer14.result: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (trueOut: !handshake.control<>, falseOut: !handshake.control<>)
    %fork16.outs_0, %fork16.outs_1 = hw.instance "fork16" @handshake_fork_11(ins: %cond_br6.falseOut: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (outs_0: !handshake.control<>, outs_1: !handshake.control<>)
    hw.output %mem_controller3.memEnd, %mem_controller2.memEnd, %fork0.outs_1, %mem_controller3.loadEn, %mem_controller3.loadAddr, %mem_controller3.storeEn, %mem_controller3.storeAddr, %mem_controller3.storeData, %mem_controller2.loadEn, %mem_controller2.loadAddr, %mem_controller2.storeEn, %mem_controller2.storeAddr, %mem_controller2.storeData : !handshake.control<>, !handshake.control<>, !handshake.control<>, i1, i8, i1, i8, i32, i1, i8, i1, i8, i32
  }
  hw.module.extern @handshake_fork_0(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.control<>, out outs_1 : !handshake.control<>, out outs_2 : !handshake.control<>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.control<>, SIZE = 3 : ui32}}
  hw.module.extern @handshake_mem_controller_0(in %loadData : i32, in %memStart : !handshake.control<>, in %ctrl_0 : !handshake.channel<i32>, in %stAddr_0 : !handshake.channel<i8>, in %stData_0 : !handshake.channel<i32>, in %ctrlEnd : !handshake.control<>, in %clk : i1, in %rst : i1, out memEnd : !handshake.control<>, out loadEn : i1, out loadAddr : i8, out storeEn : i1, out storeAddr : i8, out storeData : i32) attributes {hw.name = "handshake.mem_controller", hw.parameters = {ADDR_TYPE = !handshake.channel<i8>, DATA_TYPE = !handshake.channel<i32>, NUM_CONTROLS = 1 : ui32, NUM_LOADS = 0 : ui32, NUM_STORES = 1 : ui32}}
  hw.module.extern @handshake_mem_controller_1(in %loadData : i32, in %memStart : !handshake.control<>, in %ldAddr_0 : !handshake.channel<i8>, in %ctrlEnd : !handshake.control<>, in %clk : i1, in %rst : i1, out ldData_0 : !handshake.channel<i32>, out memEnd : !handshake.control<>, out loadEn : i1, out loadAddr : i8, out storeEn : i1, out storeAddr : i8, out storeData : i32) attributes {hw.name = "handshake.mem_controller", hw.parameters = {ADDR_TYPE = !handshake.channel<i8>, DATA_TYPE = !handshake.channel<i32>, NUM_CONTROLS = 0 : ui32, NUM_LOADS = 1 : ui32, NUM_STORES = 0 : ui32}}
  hw.module.extern @handshake_constant_0(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i2>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 2 : ui32, INTERNAL_DELAY = "0.0", VALUE = "01"}}
  hw.module.extern @handshake_extsi_0(in %ins : !handshake.channel<i2>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i2>, INTERNAL_DELAY = "0.0", OUTPUT_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_fork_1(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_mux_0(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.channel<i32>, in %ins_1 : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_control_merge_0(in %ins_0 : !handshake.control<>, in %ins_1 : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.control<>, out index : !handshake.channel<i1>) attributes {hw.name = "handshake.control_merge", hw.parameters = {DATA_TYPE = !handshake.control<>, INDEX_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_fork_2(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_0(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.channel<i32>, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_fork_3(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>, out outs_2 : !handshake.channel<i32>, out outs_3 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, SIZE = 4 : ui32}}
  hw.module.extern @handshake_buffer_1(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.channel<i32>, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_fork_4(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>, out outs_2 : !handshake.channel<i32>, out outs_3 : !handshake.channel<i32>, out outs_4 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, SIZE = 5 : ui32}}
  hw.module.extern @handshake_mux_1(in %index : !handshake.channel<i1>, in %ins_0 : !handshake.control<>, in %ins_1 : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.control<>) attributes {hw.name = "handshake.mux", hw.parameters = {DATA_TYPE = !handshake.control<>, SELECT_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_source_0(in %clk : i1, in %rst : i1, out outs : !handshake.control<>) attributes {hw.name = "handshake.source", hw.parameters = {}}
  hw.module.extern @handshake_constant_1(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i9>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 9 : ui32, INTERNAL_DELAY = "0.0", VALUE = "011000111"}}
  hw.module.extern @handshake_extsi_1(in %ins : !handshake.channel<i9>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i9>, INTERNAL_DELAY = "0.0", OUTPUT_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_cmpi_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.cmpi", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, INTERNAL_DELAY = "0_000000", PREDICATE = "slt"}}
  hw.module.extern @handshake_cmpi_1(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.cmpi", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, INTERNAL_DELAY = "0_000000", PREDICATE = "eq"}}
  hw.module.extern @handshake_andi_0(in %lhs : !handshake.channel<i1>, in %rhs : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.andi", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, INTERNAL_DELAY = "0_000000"}}
  hw.module.extern @handshake_buffer_2(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i1>, NUM_SLOTS = 2 : ui32}}
  hw.module.extern @handshake_init_0(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.init", hw.parameters = {INIT_TOKEN = 0 : ui32}}
  hw.module.extern @handshake_fork_5(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>, out outs_2 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 3 : ui32}}
  hw.module.extern @handshake_constant_2(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 1 : ui32, INTERNAL_DELAY = "0.0", VALUE = "1"}}
  hw.module.extern @handshake_buffer_3(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.channel<i1>, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_merge_0(in %ins_0 : !handshake.channel<i1>, in %ins_1 : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.merge", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_buffer_4(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i1>, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_fork_6(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>, out outs_2 : !handshake.channel<i1>, out outs_3 : !handshake.channel<i1>, out outs_4 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 5 : ui32}}
  hw.module.extern @handshake_spec_v2_resolver_0(in %actualCondition : !handshake.channel<i1>, in %generatedCondition : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out confirmSpec : !handshake.channel<i1>) attributes {hw.name = "handshake.spec_v2_resolver", hw.parameters = {}}
  hw.module.extern @handshake_fork_7(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>, out outs_2 : !handshake.channel<i1>, out outs_3 : !handshake.channel<i1>, out outs_4 : !handshake.channel<i1>, out outs_5 : !handshake.channel<i1>, out outs_6 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 7 : ui32}}
  hw.module.extern @handshake_passer_0(in %data : !handshake.channel<i1>, in %ctrl : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i1>) attributes {hw.name = "handshake.passer", hw.parameters = {}}
  hw.module.extern @handshake_fork_8(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i1>, out outs_1 : !handshake.channel<i1>, out outs_2 : !handshake.channel<i1>, out outs_3 : !handshake.channel<i1>, out outs_4 : !handshake.channel<i1>, out outs_5 : !handshake.channel<i1>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i1>, SIZE = 6 : ui32}}
  hw.module.extern @handshake_not_0(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.not", hw.parameters = {DATA_TYPE = !handshake.channel<i1>}}
  hw.module.extern @handshake_passer_1(in %data : !handshake.channel<i32>, in %ctrl : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.passer", hw.parameters = {}}
  hw.module.extern @handshake_buffer_5(in %ins : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i1>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i1>, NUM_SLOTS = 4 : ui32}}
  hw.module.extern @handshake_passer_2(in %data : !handshake.channel<i8>, in %ctrl : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i8>) attributes {hw.name = "handshake.passer", hw.parameters = {}}
  hw.module.extern @handshake_buffer_6(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.control<>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_DV", DATA_TYPE = !handshake.control<>, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_buffer_7(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.control<>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "ONE_SLOT_BREAK_R", DATA_TYPE = !handshake.control<>, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_passer_3(in %data : !handshake.control<>, in %ctrl : !handshake.channel<i1>, in %clk : i1, in %rst : i1, out result : !handshake.control<>) attributes {hw.name = "handshake.passer", hw.parameters = {}}
  hw.module.extern @handshake_trunci_0(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i8>) attributes {hw.name = "handshake.trunci", hw.parameters = {INPUT_TYPE = !handshake.channel<i32>, INTERNAL_DELAY = "0.0", OUTPUT_TYPE = !handshake.channel<i8>}}
  hw.module.extern @handshake_fork_9(in %ins : !handshake.channel<i2>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i2>, out outs_1 : !handshake.channel<i2>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i2>, SIZE = 2 : ui32}}
  hw.module.extern @handshake_fork_10(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.channel<i32>, out outs_1 : !handshake.channel<i32>, out outs_2 : !handshake.channel<i32>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, SIZE = 3 : ui32}}
  hw.module.extern @handshake_constant_3(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i15>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 15 : ui32, INTERNAL_DELAY = "0.0", VALUE = "010011100010000"}}
  hw.module.extern @handshake_extsi_2(in %ins : !handshake.channel<i15>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i15>, INTERNAL_DELAY = "0.0", OUTPUT_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_constant_4(in %ctrl : !handshake.control<>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i3>) attributes {hw.name = "handshake.constant", hw.parameters = {DATA_WIDTH = 3 : ui32, INTERNAL_DELAY = "0.0", VALUE = "010"}}
  hw.module.extern @handshake_extsi_3(in %ins : !handshake.channel<i3>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.extsi", hw.parameters = {INPUT_TYPE = !handshake.channel<i3>, INTERNAL_DELAY = "0.0", OUTPUT_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_load_0(in %addrIn : !handshake.channel<i8>, in %dataFromMem : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out addrOut : !handshake.channel<i8>, out dataOut : !handshake.channel<i32>) attributes {hw.name = "handshake.load", hw.parameters = {ADDR_TYPE = !handshake.channel<i8>, DATA_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_buffer_8(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i32>, NUM_SLOTS = 1 : ui32}}
  hw.module.extern @handshake_muli_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.muli", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, INTERNAL_DELAY = "1_000000"}}
  hw.module.extern @handshake_addi_0(in %lhs : !handshake.channel<i32>, in %rhs : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.addi", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, INTERNAL_DELAY = "0_000000"}}
  hw.module.extern @handshake_buffer_9(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out outs : !handshake.channel<i32>) attributes {hw.name = "handshake.buffer", hw.parameters = {BUFFER_TYPE = "FIFO_BREAK_NONE", DATA_TYPE = !handshake.channel<i32>, NUM_SLOTS = 4 : ui32}}
  hw.module.extern @handshake_select_0(in %condition : !handshake.channel<i1>, in %trueValue : !handshake.channel<i32>, in %falseValue : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out result : !handshake.channel<i32>) attributes {hw.name = "handshake.select", hw.parameters = {DATA_TYPE = !handshake.channel<i32>, INTERNAL_DELAY = "0_000000"}}
  hw.module.extern @handshake_store_0(in %addrIn : !handshake.channel<i8>, in %dataIn : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out addrOut : !handshake.channel<i8>, out dataToMem : !handshake.channel<i32>) attributes {hw.name = "handshake.store", hw.parameters = {ADDR_TYPE = !handshake.channel<i8>, DATA_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_cond_br_0(in %condition : !handshake.channel<i1>, in %data : !handshake.channel<i32>, in %clk : i1, in %rst : i1, out trueOut : !handshake.channel<i32>, out falseOut : !handshake.channel<i32>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_sink_0(in %ins : !handshake.channel<i32>, in %clk : i1, in %rst : i1) attributes {hw.name = "handshake.sink", hw.parameters = {DATA_TYPE = !handshake.channel<i32>}}
  hw.module.extern @handshake_cond_br_1(in %condition : !handshake.channel<i1>, in %data : !handshake.control<>, in %clk : i1, in %rst : i1, out trueOut : !handshake.control<>, out falseOut : !handshake.control<>) attributes {hw.name = "handshake.cond_br", hw.parameters = {DATA_TYPE = !handshake.control<>}}
  hw.module.extern @handshake_fork_11(in %ins : !handshake.control<>, in %clk : i1, in %rst : i1, out outs_0 : !handshake.control<>, out outs_1 : !handshake.control<>) attributes {hw.name = "handshake.fork", hw.parameters = {DATA_TYPE = !handshake.control<>, SIZE = 2 : ui32}}
  hw.module.extern @mem_to_bram_32_8(in %loadEn : i1, in %loadAddr : i8, in %storeEn : i1, in %storeAddr : i8, in %storeData : i32, in %din0 : i32, in %din1 : i32, out ce0 : i1, out we0 : i1, out address0 : i8, out dout0 : i32, out ce1 : i1, out we1 : i1, out address1 : i8, out dout1 : i32, out loadData : i32) attributes {hw.name = "mem_to_bram", hw.parameters = {ADDR_WIDTH = 8 : ui32, DATA_WIDTH = 32 : ui32}}
  hw.module @if_convert_wrapper(in %a_din0 : i32, in %a_din1 : i32, in %b_din0 : i32, in %b_din1 : i32, in %a_start : !handshake.control<>, in %b_start : !handshake.control<>, in %start : !handshake.control<>, in %clk : i1, in %rst : i1, out a_end : !handshake.control<>, out b_end : !handshake.control<>, out end : !handshake.control<>, out a_ce0 : i1, out a_we0 : i1, out a_address0 : i8, out a_dout0 : i32, out a_ce1 : i1, out a_we1 : i1, out a_address1 : i8, out a_dout1 : i32, out b_ce0 : i1, out b_we0 : i1, out b_address0 : i8, out b_dout0 : i32, out b_ce1 : i1, out b_we1 : i1, out b_address1 : i8, out b_dout1 : i32) {
    %mem_to_bram_converter_b.ce0, %mem_to_bram_converter_b.we0, %mem_to_bram_converter_b.address0, %mem_to_bram_converter_b.dout0, %mem_to_bram_converter_b.ce1, %mem_to_bram_converter_b.we1, %mem_to_bram_converter_b.address1, %mem_to_bram_converter_b.dout1, %mem_to_bram_converter_b.loadData = hw.instance "mem_to_bram_converter_b" @mem_to_bram_32_8(loadEn: %if_convert_wrapped.b_loadEn: i1, loadAddr: %if_convert_wrapped.b_loadAddr: i8, storeEn: %if_convert_wrapped.b_storeEn: i1, storeAddr: %if_convert_wrapped.b_storeAddr: i8, storeData: %if_convert_wrapped.b_storeData: i32, din0: %b_din0: i32, din1: %b_din1: i32) -> (ce0: i1, we0: i1, address0: i8, dout0: i32, ce1: i1, we1: i1, address1: i8, dout1: i32, loadData: i32)
    %mem_to_bram_converter_a.ce0, %mem_to_bram_converter_a.we0, %mem_to_bram_converter_a.address0, %mem_to_bram_converter_a.dout0, %mem_to_bram_converter_a.ce1, %mem_to_bram_converter_a.we1, %mem_to_bram_converter_a.address1, %mem_to_bram_converter_a.dout1, %mem_to_bram_converter_a.loadData = hw.instance "mem_to_bram_converter_a" @mem_to_bram_32_8(loadEn: %if_convert_wrapped.a_loadEn: i1, loadAddr: %if_convert_wrapped.a_loadAddr: i8, storeEn: %if_convert_wrapped.a_storeEn: i1, storeAddr: %if_convert_wrapped.a_storeAddr: i8, storeData: %if_convert_wrapped.a_storeData: i32, din0: %a_din0: i32, din1: %a_din1: i32) -> (ce0: i1, we0: i1, address0: i8, dout0: i32, ce1: i1, we1: i1, address1: i8, dout1: i32, loadData: i32)
    %if_convert_wrapped.a_end, %if_convert_wrapped.b_end, %if_convert_wrapped.end, %if_convert_wrapped.a_loadEn, %if_convert_wrapped.a_loadAddr, %if_convert_wrapped.a_storeEn, %if_convert_wrapped.a_storeAddr, %if_convert_wrapped.a_storeData, %if_convert_wrapped.b_loadEn, %if_convert_wrapped.b_loadAddr, %if_convert_wrapped.b_storeEn, %if_convert_wrapped.b_storeAddr, %if_convert_wrapped.b_storeData = hw.instance "if_convert_wrapped" @if_convert(a_loadData: %mem_to_bram_converter_a.loadData: i32, b_loadData: %mem_to_bram_converter_b.loadData: i32, a_start: %a_start: !handshake.control<>, b_start: %b_start: !handshake.control<>, start: %start: !handshake.control<>, clk: %clk: i1, rst: %rst: i1) -> (a_end: !handshake.control<>, b_end: !handshake.control<>, end: !handshake.control<>, a_loadEn: i1, a_loadAddr: i8, a_storeEn: i1, a_storeAddr: i8, a_storeData: i32, b_loadEn: i1, b_loadAddr: i8, b_storeEn: i1, b_storeAddr: i8, b_storeData: i32)
    hw.output %if_convert_wrapped.a_end, %if_convert_wrapped.b_end, %if_convert_wrapped.end, %mem_to_bram_converter_a.ce0, %mem_to_bram_converter_a.we0, %mem_to_bram_converter_a.address0, %mem_to_bram_converter_a.dout0, %mem_to_bram_converter_a.ce1, %mem_to_bram_converter_a.we1, %mem_to_bram_converter_a.address1, %mem_to_bram_converter_a.dout1, %mem_to_bram_converter_b.ce0, %mem_to_bram_converter_b.we0, %mem_to_bram_converter_b.address0, %mem_to_bram_converter_b.dout0, %mem_to_bram_converter_b.ce1, %mem_to_bram_converter_b.we1, %mem_to_bram_converter_b.address1, %mem_to_bram_converter_b.dout1 : !handshake.control<>, !handshake.control<>, !handshake.control<>, i1, i1, i8, i32, i1, i1, i8, i32, i1, i1, i8, i32, i1, i1, i8, i32
  }
}

